### PR TITLE
Effects: allow clearing chains with empty '---' preset

### LINKED ISSUE #10777: add 'no effect' to (quick) effect chain selector
Reported by: **[ronso0](https://github.com/ronso0)**
Date: 2022-07-05T15:22:04Z
Status: In Progress
Importance: Wishlist
Launchpad Issue: [lp1980755](https://bugs.launchpad.net/bugs/1980755)
Tags: effects, gui, preferences

---

It would be helpful to have an empty (quick effect) chain available by default.
Furthermore, I think a 'clear effect unit' action in the effect chain settings menu would be a welcome shortcut to clear a unit.

I want to disable all stuff in the audio chain I don't use, both because it's one more thing I'd need to check if something goes wrong (yes, that happens) and because I want to get rid of visual clutter (in the mixer).

Before the effects refactoring there was a '---' Quick Effect item in the EQ preferences which did exactly that. After the refactoring, the quick effect selector was restored in the prefs, though the 'empty' item is just a blank item, not recognized by / retrieved from the effects engine, and thus not valid or available in the quick effect selector.

My current workaround is store an empty chain, go to prefs, drag (copy) it to Quick Effect chains, then select it in the prefs (or mixer).

Would a fix be as easy as having a built-in empty chain?
(named '---' like other [empty] selectors)

### PR DESCRIPTION
**Pull request by ronso0**
Alternative to #4892 
This implementation works ~~without hacks~~ only minor adjustments in the GUI counterparts (EQ / effects preferences, skins).

An empty preset named  `---` is created by `EffectChainPresetManager` on each start.
* it is added at the top of the common chain preset list and the QuickEffect preset list
* it is shown in the chain preset selectors in Preferences > EQ & `WEffectChainPresetSelector`
* it is **hidden** from the preset lists in Preferences > Effects to avoid manipulation
when those lists are changed they are pushed back to `EffectChainPrestManager` to update the lists in effect widgets, `---` is missing and needs to be re-added to the standard and QuickEffect preset lists
* it is **not** saved to `[settings_dir]/effects/chains`
* `---` is not accepted as preset name when saving or importing chain presets to avoid conflicts
* `---` can be selected with `[fx chain], chain_preset_selector` and `.., next/prev_chain_preset`
* `loaded_chain_preset` called with `0` will now clear the chain

**Update:**
`---` is only added to the QuickEffect chain presets list to avoid a few incosistencies with standard chains.

~~When picked in **standard chains**' preset selectors, [EffectChain::loadChainPreset](https://github.com/mixxxdj/mixxx/pull/10859/files#diff-fa28becfc988b55ba9c54ec2aee6524f22af4a27efb9a4d18a2a9fe121ddab35R219-R230) will clear the name (more details in https://github.com/mixxxdj/mixxx/pull/10859#discussion_r962314889), so~~
* ~~`chainPresetChanged()` signal will clear the selector combobox (index = -1) and the selection in the chain preset menu~~
* ~~the empty preset can not be overwritten via 'Update Preset' in the `WEffectChainPresetButton` menu~~
* ~~it is **not** stored as preset name for standard effect chains in `effects.xml`~~

When picked in **QuickEffect chains**' preset selectors or in Preferences > Equalizer, the name `---` persists
* `---` remains selected in preset selectors to signal the current chain is empty (and will remain empty because there's no (skin) interface to load effects into chain slots)
* it is used as preset identifier for QuickEffect chains in `effects.xml`:
    ```
     <QuickEffectChains>
      <ChainPresetName group="[Channel1]">Echo</ChainPresetName>
      <ChainPresetName group="[Channel2]">---</ChainPresetName>
      <ChainPresetName group="[Channel3]">Filter</ChainPresetName>
      <ChainPresetName group="[Channel4]">Filter</ChainPresetName>
     </QuickEffectChains>
    ```
    which is valid to restore the empty preset when Mixxx is started

### CODE REVIEW

File: src/effects/presets/effectchainpresetmanager.cpp [hunk 1]
```diff
@@ -668,10 +695,27 @@ EffectsXmlData EffectChainPresetManager::readEffectsXml(
...
+    // It will not be saved to effects/chains nor written to effects.xml
+    // except as identifier for QuickEffects.chains.
+    // It will not be visible in the effects preferences.
+    EffectManifestPointer pEmptyChainManifest(new EffectManifest());
+    pEmptyChainManifest->setName(kNoEffectString);
+    pEmptyChainManifest->setShortName(kNoEffectString);
+
+    auto pEmptyChainPreset =
+            EffectChainPresetPointer(new EffectChainPreset(pEmptyChainManifest));
+    pEmptyChainPreset->setName(pEmptyChainManifest->name());
```
Comment (ronso0) [inline src/effects/presets/effectchainpresetmanager.cpp:709]: I can also imagine to create a new `class EmptyStaticEffectChainPreset : public EffectChainPreset` to outsource this setup.

If all those `preset->name() == kNoEffectString` tests are not considered safe or "nice" that might also allow to use `static EmptyStaticEffectChainPreset::name` instead, or try to cast to `EmptyStaticEffectChainPreset` where applicable.

Comment (ronso0) [reply src/effects/presets/effectchainpresetmanager.cpp:709]: `EmptyStaticEffectChainPreset` is overkill, I'll try to add `setReadOnly`/`isReadOnly` to `EffectChainPreset`.

**Comment by Swiftb0y** [comment]
sorry I'm a bit short on time atm. I'll try to get back to this PR and #4892 next week. Thanks for understanding

**Comment by ronso0** [comment]
I don't have any expectations this will get merged soonish, so no need to excuse and no need to hurry. I just gave this another shot while I'm still into the details of the preset management.

File: src/effects/presets/effectchainpreset.h [hunk 2]
```diff
@@ -40,6 +40,12 @@ class EffectChainPreset {
     double superKnob() const {
         return m_dSuper;
     }
+    void setReadOnly(bool readOnly) {
```
Comment (daschuer) [inline src/effects/presets/effectchainpreset.h:43]: Is this ever used for the false case? If not we may consider to remove the parameter.

File: src/preferences/dialog/dlgprefeq.cpp [hunk 3]
```diff
@@ -492,8 +489,8 @@ void DlgPrefEQ::slotQuickEffectChangedOnDeck(int effectIndex) {
     EffectChainPointer pChain = m_pEffectsManager->getEffectChain(unitGroup);
     QList<EffectChainPresetPointer> presetList =
             m_pChainPresetManager->getQuickEffectPresetsSorted();
-    if (pChain && effectIndex > 0 && effectIndex <= presetList.size()) {
-        pChain->loadChainPreset(presetList[effectIndex - 1]);
+    if (pChain && effectIndex > -1 && effectIndex <= presetList.size()) {
```
Comment (daschuer) [inline src/preferences/dialog/dlgprefeq.cpp:492]:
```suggestion
    if (pChain && effectIndex >= 0 && effectIndex < presetList.size()) {
```
looks more pleasant IMHO

**Review by daschuer — CHANGES_REQUESTED** [review]
Thank you. This looks like a good solution. 
Can we close https://github.com/mixxxdj/mixxx/pull/4892 then?

**Comment by daschuer** [comment]
I experience a segfault: 
```
Thread 1 "mixxx" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffeb677140 (LWP 57663)]
0x0000555555be0ed6 in WEffectChainPresetButton::populateMenu (
    this=0x555568927870) at ../../src/effects/presets/effectchainpreset.h:47
47	        return m_readOnly;
(gdb) bt
#0  0x0000555555be0ed6 in WEffectChainPresetButton::populateMenu()
    (this=0x555568927870) at ../../src/effects/presets/effectchainpreset.h:47
#1  0x00007ffff3b42328 in QtPrivate::QSlotObjectBase::call(QObject*, void**)
    (a=0x7fffffffcab0, r=0x555568927870, this=0x555568498640)
    at ../../include/QtCore/../../src/corelib/kernel/qobjectdefs_impl.h:394
#2  QMetaObject::activate(QObject*, int, int, void**)
    (sender=0x55555b61ad10, signalOffset=<optimized out>, local_signal_index=<optimized out>, argv=<optimized out>) at kernel/qobject.cpp:3784
#3  0x0000555555903d67 in EffectSlot::effectChanged() (this=0x55555b61ad10)
    at mixxx-lib_autogen/include/moc_effectslot.cpp:194
#4  EffectSlot::loadEffectInner(QSharedPointer<EffectManifest>, QSharedPointer<EffectPreset>, bool)
    (this=0x55555b61ad10, pManifest=..., pEffectPreset=..., adoptMetaknobFromPreset=<optimized out>) at ../../src/effects/effectslot.cpp:368
#5  0x0000555555904356 in EffectSlot::loadEffectWithDefaults(QSharedPointer<EffectManifest>) (this=0x55555b61ad10, pManifest=...)
    at /usr/include/c++/9/bits/atomic_base.h:318
#6  0x0000555555e9a16a in WEffectSelector::slotEffectSelected(int)
    (this=0x555569488980, newIndex=1)
    at /usr/include/c++/9/bits/atomic_base.h:318
#7  0x00007ffff3b42328 in QtPrivate::QSlotObjectBase::call(QObject*, void**)
    (a=0x7fffffffce20, r=0x555569488980, this=0x555569a4c1b0)
    at ../../include/QtCore/../../src/corelib/kernel/qobjectdefs_impl.h:394
--Type <RET> for more, q to quit, c to continue without paging--
#8  QMetaObject::activate(QObject*, int, int, void**)
    (sender=0x555569488980, signalOffset=<optimized out>, local_signal_index=<optimized out>, argv=<optimized out>) at kernel/qobject.cpp:3784
#9  0x00007ffff6cf30c5 in QComboBox::activated(int)
    (this=this@entry=0x555569488980, _t1=<optimized out>)
    at .moc/moc_qcombobox.cpp:481
#10 0x00007ffff6cf54d2 in QComboBoxPrivate::emitActivated(QModelIndex const&)
    (this=this@entry=0x5555686a7d10, index=...)
    at ../../include/QtCore/../../src/corelib/itemmodels/qabstractitemmodel.h:62
#11 0x00007ffff6cf7fa0 in QComboBoxPrivate::_q_itemSelected(QModelIndex const&)
    (this=0x5555686a7d10, item=...) at widgets/qcombobox.cpp:1346
#12 0x00007ffff6cfdaf5 in QComboBox::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)
    (_o=<optimized out>, _c=<optimized out>, _id=<optimized out>, _a=0x7fffffffd000) at widgets/qcombobox.h:252
#13 0x00007ffff3b421d0 in QMetaObject::activate(QObject*, int, int, void**)
    (sender=0x555567956ab0, signalOffset=<optimized out>, local_signal_index=<optimized out>, argv=<optimized out>) at kernel/qobject.cpp:3804
#14 0x00007ffff6cf33b6 in QComboBoxPrivateContainer::itemSelected(QModelIndex const&) (this=this@entry=0x555567956ab0, _t1=...) at .moc/moc_qcombobox_p.cpp:347
#15 0x00007ffff6cf3aca in QComboBoxPrivateContainer::eventFilter(QObject*, QEvent*) (this=0x555567956ab0, o=0x5555699fd2b0, e=0x7fffffffd570)
--Type <RET> for more, q to quit, c to continue without paging--
    at widgets/qcombobox.cpp:758
#16 0x00007ffff3b1651b in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) (event=<optimized out>, receiver=<optimized out>)
    at kernel/qcoreapplication.cpp:1214
#17 QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*)
    (receiver=receiver@entry=0x5555699fd2b0, event=event@entry=0x7fffffffd570)
    at kernel/qcoreapplication.cpp:1203
#18 0x00007ffff6beca55 in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    (this=this@entry=0x55555663e270, receiver=receiver@entry=0x5555699fd2b0, e=e@entry=0x7fffffffd570) at kernel/qapplication.cpp:3694
#19 0x00007ffff6bf6343 in QApplication::notify(QObject*, QEvent*)
    (this=<optimized out>, receiver=0x5555699fd2b0, e=0x7fffffffd570)
    at kernel/qapplication.cpp:3160
#20 0x00007ffff3b1680a in QCoreApplication::notifyInternal2(QObject*, QEvent*)
    (receiver=0x5555699fd2b0, event=0x7fffffffd570)
    at ../../include/QtCore/../../src/corelib/kernel/qobject.h:142
#21 0x00007ffff6bf5457 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool)
    (receiver=0x5555699fd2b0, event=event@entry=
    0x7fffffffd570, alienWidget=0x5555699fd2b0, nativeWidget=0x555567956ab0, buttonDown=buttonDown@entry=0x7ffff711c8d0 <qt_button_down>, lastMouseReceiver=..., spontaneous=true, onlyDispatchEnterLeave=false)
    at kernel/qapplication.cpp:2646
--Type <RET> for more, q to quit, c to continue without paging--
#22 0x00007ffff6c4bce4 in QWidgetWindow::handleMouseEvent(QMouseEvent*)
    (this=0x55556ffa62a0, event=0x7fffffffd9f0)
    at /usr/include/c++/9/bits/atomic_base.h:413
#23 0x00007ffff6c4e1ec in QWidgetWindow::event(QEvent*)
    (event=0x7fffffffd9f0, this=0x55556ffa62a0) at kernel/qwidgetwindow.cpp:289
#24 QWidgetWindow::event(QEvent*) (this=0x55556ffa62a0, event=0x7fffffffd9f0)
    at kernel/qwidgetwindow.cpp:232
#25 0x00007ffff6beca66 in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    (this=this@entry=0x55555663e270, receiver=receiver@entry=0x55556ffa62a0, e=e@entry=0x7fffffffd9f0) at kernel/qapplication.cpp:3700
#26 0x00007ffff6bf60f0 in QApplication::notify(QObject*, QEvent*)
    (this=0x7fffffffde60, receiver=0x55556ffa62a0, e=0x7fffffffd9f0)
    at kernel/qapplication.cpp:3446
#27 0x00007ffff3b1680a in QCoreApplication::notifyInternal2(QObject*, QEvent*)
    (receiver=0x55556ffa62a0, event=0x7fffffffd9f0)
    at ../../include/QtCore/../../src/corelib/kernel/qobject.h:142
#28 0x00007ffff65727d3 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) (e=e@entry=0x55556ffdfb20)
    at kernel/qguiapplication.cpp:2107
#29 0x00007ffff657410b in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) (e=e@entry=0x55556ffdfb20)
    at kernel/qguiapplication.cpp:1842
#30 0x00007ffff654e35b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<--Type <RET> for more, q to quit, c to continue without paging--
QEventLoop::ProcessEventsFlag>) (flags=flags@entry=...)
    at kernel/qwindowsysteminterface.cpp:1151
#31 0x00007fffeaf2532e in xcbSourceDispatch(GSource*, GSourceFunc, gpointer)
    (source=<optimized out>) at qxcbeventdispatcher.cpp:105
#32 0x00007ffff274d17d in g_main_context_dispatch ()
    at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#33 0x00007ffff274d400 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#34 0x00007ffff274d4a3 in g_main_context_iteration ()
    at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#35 0x00007ffff3b6e435 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (this=0x5555566faec0, flags=...)
    at kernel/qeventdispatcher_glib.cpp:422
#36 0x00007ffff3b153ab in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) (this=this@entry=0x7fffffffdd90, flags=..., flags@entry=...)
    at ../../include/QtCore/../../src/corelib/global/qflags.h:140
#37 0x00007ffff3b1d116 in QCoreApplication::exec() ()
    at ../../include/QtCore/../../src/corelib/global/qflags.h:120
#38 0x000055555573908d in (anonymous namespace)::runMixxx
    (args=..., pApp=0x7fffffffde60) at ../../src/main.cpp:70
#39 main(int, char**) (argc=<optimized out>, argv=<optimized out>)
    at ../../src/main.cpp:198
```

File: src/effects/presets/effectchainpreset.h (hunk 2 above)
Comment (ronso0) [reply src/effects/presets/effectchainpreset.h:43]: good point, will remove it.
If someone intends to toggle this state in a later implementation the argument may be added again.

File: src/effects/effectchain.cpp [hunk 4]
```diff
@@ -216,7 +216,20 @@ void EffectChain::loadChainPreset(EffectChainPresetPointer pPreset) {
...
+    //   empty '---' preset is not going to be stored either)
+    // With QuickEffect chains this doesn't matter because only the name will be
+    // stored for each deck.
+    // For details check EffectsManager::saveEffectsXml()
+    if (pPreset->name() == kNoEffectString &&
+            !m_pEffectsManager->chainIsQuickEffectChain(this)) {
+        m_presetName = QString();
+    } else {
+        m_presetName = pPreset->name();
+    }
```
[the remark this answers is not in the document]
Comment (ronso0) [reply src/effects/effectchain.cpp:232]: No, we can't.
This is required to deal with how QuickEffect vs. regular chain presets are stored.
It is the least invasive solution, and it works perfectly for both chain types.

I try to explain it once more, this is best understood if you look at your effects.xml.

* **QuickEffect chains** are not editable, only super knob and enable switch are exposed¹
* for Quick Effect chains only the preset name is stored in effects.xml
* on next start, this name is looked up in the comon preset list
* if this field is empty or preset not found, the default preset is loaded (Filter)
* = `---` will accomplish that the empty chain is restored correctly

__
* for **regular chains** (e.g. EffectRack1) the entire chains state is stored
* this maybe an unchanged default preset, or some custom chain that wasn't even saved or exported, yet, so the preset name is optional
* the empty `---` preset itself _must not be edited_, it is just a shortcut to clear the entire chain and allow the user to start over
= eject preset = clear slots & preset name = the user can immediatley start to create a new chain
* thus, if the chain would adopt the `---` as preset name, that would be incorrect as soon as an effect slot is populated
* the only way to save/overwrite any effect chain preset is via WEffectChainPresetButton:
when `effectChainPresetListUpdated` or `chainPresetChanged` are received [the menu will be populated](https://github.com/mixxxdj/mixxx/pull/10859/files#diff-be1dd872669ac0a1d01711568bbb7890d5288f7c198e80f44dfd7bb4362a264fR50), and since (empty name) will not be found in the common preset list, the preset is considered null and "Update Preset" is not shown (same applies to [`WEffectChainPresetSelector`](https://github.com/mixxxdj/mixxx/pull/10859/files#diff-2ac3fea593519ba78388b958c24246fd446bd7fb86f4c2c1d067699790c34d53R101)

¹ note that this is only true with official skins. IIUC it's not prohibited in any way to create WEffectChainPresetButton and WEffectSeletor widgets for a QuickEffect chain, so with those one could alter the `---` preset, though that state would not be saved automatically and thus not be restored on next start.
Idk if we need to add a guard to not allow this in the first place to avoid disaapointment with custom skins that implemet those widgets.

**Comment by ronso0** [comment]
> I experience a segfault: This happens after selecting a new effect before it was "---"

Yep, already fixed. incorrect usage of `isReadOnly()`

**Comment by ronso0** [comment]
Note that I need to rebase anyway to remove the skin debug commit.
I'll make fixup commits for all proposed changes and squash on final rebase.
Alright?

File: src/effects/effectchain.cpp (hunk 4 above)
[the remark this answers is not in the document]
Comment (ronso0) [reply src/effects/effectchain.cpp:232]: I updated the above description. Hopefully it's comprehensible ths time.

**Comment by ronso0** [comment]
For debugging / stress-testing I added a complete QuickEffect rack above the decks in LateNight.

File: src/preferences/dialog/dlgprefeq.cpp [hunk 5]
```diff
@@ -492,8 +489,8 @@ void DlgPrefEQ::slotQuickEffectChangedOnDeck(int effectIndex) {
     EffectChainPointer pChain = m_pEffectsManager->getEffectChain(unitGroup);
     QList<EffectChainPresetPointer> presetList =
             m_pChainPresetManager->getQuickEffectPresetsSorted();
-    if (pChain && effectIndex > 0 && effectIndex <= presetList.size()) {
-        pChain->loadChainPreset(presetList[effectIndex - 1]);
+    if (pChain && effectIndex >= 0 && effectIndex <= presetList.size()) {
```
Comment (daschuer) [inline src/preferences/dialog/dlgprefeq.cpp:492]:
```suggestion
    if (pChain && effectIndex >= 0 && effectIndex < presetList.size()) {
```

**Review by Be-ing — CHANGES_REQUESTED** [review]
~~Exposing all the effects and parameters within QuickEffect chains makes them no longer any different from regular effect chains, which therefore makes them pointless.~~

Sorry, I didn't see that was just for debugging. Disregard this comment.

**Comment by ronso0** [comment]
> ~Exposing all the effects and parameters within QuickEffect chains makes them no longer any different from regular effect chains, which therefore makes them pointless.~
> 
> Sorry, I didn't see that was just for debugging. Disregard this comment.

And even more for doing things that are possible, though not available in official skins (by concept).

@Be-ing Besides that, do you have any idea how to improve this solution, especially the `---` string comparison?

**Comment by ronso0** [comment]
`[fxChain],chain_preset_selector` is broken now: it get's stuck due preset (empty string) not being found in the presetlist (presetIndex() returns -1) [here](https://github.com/mixxxdj/mixxx/blob/a8440945ae8aef3f629768b6f0836b0edc145745/src/effects/effectchain.cpp#L329-L340).
Here, this happens because the preset name was changed to (empty string) intentionally, though if it happens due to other inconsistencies the index should be reset to `0` to jump to a working index again.

**Comment by ronso0** [comment]
I doubt this is the appropriate fix for the issue.

FWIW in dev tools I see `chain_preset-selector` twice for each unit/chain

File: src/effects/presets/effectchainpresetmanager.cpp [hunk 6]
```diff
@@ -227,10 +233,22 @@ void EffectChainPresetManager::renamePreset(const QString& oldName) {
...
+    if (m_effectChainPresets.value(oldName)->isReadOnly()) {
+        QMessageBox msgBox;
+        msgBox.setText(tr("Effect chain preset can not be renamed"));
+        msgBox.setInformativeText(
+                tr("Effect chain preset \"%1\" is read-only and can not be renamed.")
+                        .arg(oldName));
+        msgBox.setIcon(QMessageBox::Warning);
+        msgBox.exec();
+        return;
+    }
```
Comment (ronso0) [inline src/effects/presets/effectchainpresetmanager.cpp:245]: currently only `---` is read-only and this is not shown in the preset lists in the effect preferences, so (currently) this shouldn't be called anyway.

**Comment by ronso0** [comment]
Recent changes, besides fixups:
* `---` is re-added to standard and QuickEffect preset lists when changed lists are pushed back from effect preferences to EffectChainPresetManager (which updates the preset lists in effect widgets), selected index persists
* fixed the issue with `chain_preset_selector` (https://github.com/mixxxdj/mixxx/pull/10859#issuecomment-1237508937)

I tried hard to deal with `---` only in EffectChainPresetManager and EffectChain, I hope this implementation is safe and comprehensible.
I think I'm done here, the concept works well and during extensive manual test I did not discover regressions.
I'll post some manual test soon.

There's one inconsistency though:
if `loaded_chain_preset` is set to `0` for a standard chain, the chain is cleared as expected, though the controls is reset (preset index not found returns -1 and `setControlLoadedPresetIndex` requires uint arg)

**Comment by ronso0** [comment]
- [ ] remove skin commit

File: src/effects/effectchain.cpp (hunk 4 above)
[the remark this answers is not in the document]
Comment (daschuer) [reply src/effects/effectchain.cpp:233]: I have tested the LatNight effect chain selector and label and I have noticed that WEffectChain is cleared instead of dashed out. Is this desired, or only a side effect of the this code here? 
For my understanding it should be "---" instead and the code above needs to be removed. 

The solution with 
m_pEffectsManager->chainIsQuickEffectChain(this)
is also a bit unusual because now we have QuickEffectChain code in the base class even though QuickEffectChain has already an implementation of loadChainPreset() 

I have just did a test with replacing the code above with 
`m_presetName = pPreset->name();`
And it works IMHO flawlessly after deleting the assertion in EffectChainPresetManager::saveEffectsXml() which is IMHO wrong, because it saves the current state, independent from which chain was loaded. 

This way the preset name is "---" but the changes after selecting "---" are still recorded, which is valid and happens with any other chain. 

If you want to reflect that the chain is no longer empty, we may rename it in "New Chain". This however happens with any other chain you pick and than change the effect. For instance if you Pick the Reverb preset and replace the Reverb effect with a bit-chusher you have the same inconsistent state. 

> the empty --- preset itself must not be edited,

Why not, like any other preset. It must not be stored as preset though, but that is already disabled elsewhere. 

> thus, if the chain would adopt the --- as preset name,

This is not a problem of this PR, because it happens with any other preset in the same way. 
If we want to fix that, it is a topic of another PR. 

> = selecting another preset, then going back to --- would not clear the chain!

This works in my test. 

Maybe I am still missing something?

File: src/effects/presets/effectchainpresetmanager.cpp [hunk 7]
```diff
@@ -699,13 +783,22 @@ void EffectChainPresetManager::saveEffectsXml(QDomDocument* pDoc, const EffectsX
     QDomElement chainsElement = pDoc->createElement(EffectXml::kChainsRoot);
     rackElement.appendChild(chainsElement);
     for (const auto& pPreset : std::as_const(data.standardEffectChainPresets)) {
+        // '---' should already be cleared (empty string) for standard chains
+        // when loading it
+        VERIFY_OR_DEBUG_ASSERT(pPreset->name() != kNoEffectString) {
+            return;
+        }
```
Comment (daschuer) [inline src/effects/presets/effectchainpresetmanager.cpp:790]: This assertion is IMHO not required.

**Comment by daschuer** [comment]
Apart form the "---" to "" renaming everything works and looks good. Thank you.

@Be-ing Is it correct that your change request is outdated?

File: src/effects/effectchain.cpp (hunk 4 above)
[the remark this answers is not in the document]
Comment (ronso0) [reply src/effects/effectchain.cpp:233]: > The solution with
m_pEffectsManager->chainIsQuickEffectChain(this)
is also a bit unusual because now we have QuickEffectChain code in the base class even though QuickEffectChain has already an implementation of loadChainPreset()

If chosen this path to avoid code duplication. If you think this needs to be resolved I can move it the quickeffectchain.cpp

[the remark this answers is not in the document]
Comment (ronso0) [reply src/effects/effectchain.cpp:233]: The basic rule I want to adhere to is that `---` _always_ means "empty" in any other selector in skins and preferences.
I built everything on this to find a way to clear the QuickEffect chains.

It gets tricky only with standart effect chains, because IMO for those the `---` item should be an **action** not a **state**, it should allow the user to restore the initial state (empty chain) like after starting Mixxx the first time.
Yes, the inconsistency of keeping `---` (or any other preset name) after changing an effect applies to all preset, though IMO it is hard to distinguish if a user alters _EchoVerbHP_ by selecting a different filter or adds a entirely different effect. But we should accept this inconsistency for the very special `---` item.

Btw I just notice a somewhat big mistake: actually the chain preset selectors are not part of official skins (and neither are WEffectChain labels) so `---` should be in the menu of WEffectChainPresetButton (and not be marked selected after selecting it). Or we add a separate "Clear chain" item. I think `---` would be more intuitive, though I have no strong preference.

[the remark this answers is not in the document]
Comment (ronso0) [reply src/effects/effectchain.cpp:233]: > > = selecting another preset, then going back to --- would not clear the chain!

> This works in my test.

True, it works, even when `---` is already selected. But  definitely expereinced that, probably with an early state of this branch, maybe in the preset menu, idk.

[the remark this answers is not in the document]
Comment (daschuer) [reply src/effects/effectchain.cpp:233]: > But we should not accept this inconsistency for the very special --- item.

Accepting it would make the behavior consistent that the chain label only displays the last **action**. Special case the "---" case and replace it with "" does not solve the underlying issue, that you expectation is to display the **state**. 
"" is also shown in case the chain is still "---" which feels wrong as well. 

This can be solved by removing the label once the user has re-added an effect, or in case of other preset once they have changes any effect. For this PR I would prefer to keep the last **action** display feature working for all.

**Comment by ronso0** [comment]
> "" is also shown in case the chain is still "---" which feels wrong as well.

True, but the blank label is also the initial state after first start (and we should show `---` then IMO) so it makes more sense to me to have this blank label than `---` for the same (blank) state.

Considering my actual goal was to have a way to clear the **QuickEffect chains** I now think I'd be better to add `---` only to QuickEffect chain preset selectors for consistency with WEffectSelector
and **not** add it to selectors of standard chains in the first place to avoid all this.
We may simply add a "Clear chain" action to chain preset menu to restore the initial Mixxx effects state. I don't mind if that happens here or in another PR.

At this point this means reverting a few commits, so my way would be to rebase and pick only what is required for the QuickEffect chains. As usual, give me :+1: if this is okay for you.

**Comment by daschuer** [comment]
> True, but the blank label is also the initial state after first start (and we should show --- then IMO) so it makes more sense to me to have this blank label than --- for the same (blank) state.

Yes, that makes sense.

I would rather change that, instead of undoing, half of this good working PR. Apart from these few renaming lines, the PR is well designed and I like that we treat all chains the same.

But I have not a strong opinion here.

**Comment by daschuer** [comment]
Is it just the  default of ` m_presetName(""),`  ?

File: src/effects/effectchain.cpp (hunk 4 above)
[the remark this answers is not in the document]
Comment (ronso0) [reply src/effects/effectchain.cpp:233]: > I would rather change that, instead of undoing, half of this good working PR.

Oh, it's little work actually. Just not adding it to the standard chains makes the special treatment obsolete in a few places, and I can remove `chainIsQuickeffectChain`.

> Apart from these few renaming lines, the PR is well designed and I like that we treat all chains the same.

Hmm, as our discussion unveils that's exactly the issue, because there GUI representation is not the same. QuickEffect chains have a stripped GUI and their preset selectors look like the single effec slot selectors now, and that's fine. Standard chains have the full GUI and maybe even don't necessarily need `---` or "Clear chain". Thus I'm fine with making a few steps backwards.

**Comment by ronso0** [comment]
> I would rather change that, instead of undoing, half of this good working PR.

Oh, it's little work actually. Just not adding it to the standard chains makes the special treatment obsolete in a few places, and I can remove `chainIsQuickeffectChain`.

> Apart from these few renaming lines, the PR is well designed and I like that we treat all chains the same.

Hmm, as our discussion unveils that's exactly the issue, because there GUI representation is not the same. QuickEffect chains have a stripped GUI and their preset selectors look like the single effec slot selectors now, and that's fine. Standard chains have the full GUI and maybe even don't necessarily need `---` or "Clear chain". Thus I'm fine with making a few steps backwards.

**Comment by daschuer** [comment]
Ok, go ahead. Thank you.

File: src/effects/effectsmanager.cpp [hunk 8]
```diff
@@ -177,6 +177,8 @@ void EffectsManager::readEffectsXml() {
     }
     file.close();
 
+    // QuickEffect chains are created only for existing main decks, so read
+    // the configured presets only for those
```
Comment (daschuer) [inline src/effects/effectsmanager.cpp:181]:
```suggestion
    // Note: QuickEffect chains are created only for existing main decks
```

The second half sound as if we need to special case something here, but that is not the case. The comment only explains the surprising file name, right?

Comment (ronso0) [reply src/effects/effectsmanager.cpp:181]: > The comment only explains the surprising file name, right?

Hm?

I think the imperative is misleading here.
```suggestion
    // Note: QuickEffect chains are created only for existing main decks
    // thus only for those the configured presets are requested
```
Better?

File: src/widget/weffectchainpresetbutton.cpp [hunk 9]
```diff
@@ -46,20 +46,23 @@ void WEffectChainPresetButton::populateMenu() {
     m_pMenu->clear();
 
     // Chain preset items
-    bool chainIsPreset = false;
+    bool allowUpdatingPreset = false;
```
Comment (daschuer) [inline src/widget/weffectchainpresetbutton.cpp:49]: Can we invert the logic her to match the function call?

File: src/effects/effectsmanager.cpp (hunk 8 above)
Comment (daschuer) [reply src/effects/effectsmanager.cpp:181]: Yes, Thank you.

File: src/widget/weffectchainpresetbutton.cpp (hunk 9 above)
Comment (ronso0) [reply src/widget/weffectchainpresetbutton.cpp:49]: Like this?
```
bool isReadOnly = true;
...
isReadOnly = pChainPreset->isReadOnly();
...
if (!isReadOnly) {
   // show Update button
```

Comment (daschuer) [reply src/widget/weffectchainpresetbutton.cpp:49]: Yes

Comment (ronso0) [reply src/widget/weffectchainpresetbutton.cpp:49]: alright, done.

**Comment by ronso0** [comment]
**ping*

**Comment by daschuer** [comment]
Is the draft state still correct?

**Comment by ronso0** [comment]
It seems we agreed on the essential implememntation now : ) so yeah I can remove the draft state

File: src/effects/presets/effectchainpreset.h [hunk 10]
```diff
@@ -50,4 +56,5 @@ class EffectChainPreset {
     EffectChainMixMode::Type m_mixMode;
     double m_dSuper;
     QList<EffectPresetPointer> m_effectPresets;
+    bool m_readOnly = false;
```
Comment (daschuer) [inline src/effects/presets/effectchainpreset.h:59]: We normally don't use initialization in a header.  Please move that to the constructor.

File: src/effects/presets/effectchainpresetmanager.cpp [hunk 11]
```diff
@@ -123,6 +123,12 @@ void EffectChainPresetManager::importPreset() {
         EffectChainPresetPointer pPreset(
                 new EffectChainPreset(doc.documentElement()));
         if (!pPreset->isEmpty() && !pPreset->name().isEmpty()) {
+            // Don't allow '---' because that's the name of the internal empty preset
+            if (pPreset->name() == kNoEffectString) {
+                pPreset->setName(pPreset->name() +
+                        QLatin1String(" (") + tr("imported") + QLatin1String(")"));
```
Comment (daschuer) [inline src/effects/presets/effectchainpresetmanager.cpp:129]: Since + calls QStringBuilder converting Laitn1 to utf16, it is more effective to use QStringLiteral here.

Comment (daschuer) [reply src/effects/presets/effectchainpresetmanager.cpp:129]: You may also fix the code below.

File: src/effects/presets/effectchainpresetmanager.cpp [hunk 12]
```diff
@@ -359,10 +389,26 @@ void EffectChainPresetManager::setQuickEffectPresetOrder(
         m_quickEffectChainPresetsSorted.append(
                 m_effectChainPresets.value(chainPresetName));
     }
+    prependEmptyPreset(m_quickEffectChainPresetsSorted);
 
     emit quickEffectChainPresetListUpdated();
 }
 
+void EffectChainPresetManager::prependEmptyPreset(
+        QList<EffectChainPresetPointer>& pPresetList) const {
```
Comment (daschuer) [inline src/effects/presets/effectchainpresetmanager.cpp:398]: We try to avoid non const references. 
```suggestion
        QList<EffectChainPresetPointer>* pPresetList) const {
```

In this case you may also consider to use m_quickEffectChainPresetsSorted directly.

**Review by daschuer — CHANGES_REQUESTED** [review]

File: src/effects/presets/effectchainpresetmanager.cpp (hunk 11 above)
Comment (ronso0) [reply src/effects/presets/effectchainpresetmanager.cpp:129]: done

File: src/effects/presets/effectchainpreset.h (hunk 10 above)
Comment (ronso0) [reply src/effects/presets/effectchainpreset.h:59]: okido

File: src/effects/presets/effectchainpresetmanager.cpp (hunk 12 above)
Comment (ronso0) [reply src/effects/presets/effectchainpresetmanager.cpp:398]: oh, okay.
I just merged it into `setQuickEffectPresetOrder` because it's only called from there anyway.

File: src/effects/presets/effectchainpresetmanager.cpp (hunk 11 above)
Comment (ronso0) [reply src/effects/presets/effectchainpresetmanager.cpp:129]: > Since + calls QStringBuilder converting Laitn1 to utf16, it is more effective to use QStringLiteral here.

Could you please share the page where you got that from? Didn't find it (explicitly) in the QString doc

**Comment by ronso0** [comment]
@daschuer I addressed all comments, this is ready

**Review by daschuer — APPROVED** [review]
Works and looks good. Thank you.

You can trick yourself by calling effect chains "--" or "----" but I rgink this is a corner case not worth a fix. is it? 

@Be-ing You review is still not approved. Is there anything else to do?

**Comment by ronso0** [comment]
> You can trick yourself by calling effect chains "--" or "----" but I rgink this is a corner case not worth a fix. is it?

Sure we could have a helper function that disallows multipple =, but if users prefer ultra-descriptive chain names like that or ++#-- it's up to them I'd say

**Comment by ronso0** [comment]
_*ding dong_

@Be-ing's only comment was about the debugging interface for QuickEffects, https://github.com/mixxxdj/mixxx/pull/10859#pullrequestreview-1096668276

**Comment by daschuer** [comment]
OK, It should be safe to merge now. Thank you.

**Comment by ronso0** [comment]
:tada: since the various attempts to get this done have caused me quite some headaches : )

**Comment by ronso0** [comment]
Thanks @daschuer and  @Swiftb0y for your patience!
