### PR TITLE
Preferences waveforms: recall correct waveform type when selecting an overview type

### LINKED ISSUE #12226: Changing the waveform overview type after changing the main waveform type resets the main waveform type
### Bug Description

I set the main waveform type to "Simple (GLSL)" and Ok the preferences.

Then I go back in, and select "Filtered (GLSL)" for the main waveform type, and it changes to the newer non-semitransparent stacked RGB style. (I know "stacked" and "RGB" relate to other waveform styles, but I really don't know how else to simply describe the new style!)

But I then change the waveform overview type, and the main waveform type changes style from "Filtered (GLSL)" to something else.

I Ok the preferences, then I reopen the preferences and the option main waveform type has changed to "RBG (GLSL)"

This happened regardless of what the initial main waveform type is.

Arguably related to #9745 in some way

### Version

2.5-alpha-137-gc2f2f64891 (main)

### OS

Arch btw

### PR DESCRIPTION
**Pull request by ronso0**
Closes #12226 

The waveform type was written to config but the local variable `m_configType` holding this type for updating the widgets after skin (re)load was not updated accordingly.

Note that I consider this just a quick fix.

IMO we should not store the value in `m_configType` but read it from the config in `setWidgetTypeFromConfig` (move the logic from `setConfig()`. AFAICT this is required only in the constructor and in `slotSkinLoaded()`.
A commit that should do th trick is 80bb79c012, though I'm not motivated to verify this actually works under all conditions / on all OS. If someone wants to check that and do the testing, please go ahead.
Maybe also call `DlgPrefWaveforms::slotUpdate` when `MixxxMainWindow::rebootMixxxView` succeeded.

### CODE REVIEW

File: src/waveform/waveformwidgetfactory.cpp [hunk 1]
```diff
@@ -1163,6 +1174,16 @@ int WaveformWidgetFactory::findHandleIndexFromType(WaveformWidgetType::Type type
     return index;
 }
 
+QString WaveformWidgetFactory::getDisplayNameFromType(WaveformWidgetType::Type type) {
+    for (int i = 0; i < m_waveformWidgetHandles.size(); i++) {
```
Comment (daschuer) [inline src/waveform/waveformwidgetfactory.cpp:1178]: This can become a range based loop.

Comment (ronso0) [reply src/waveform/waveformwidgetfactory.cpp]: done.

File: src/waveform/waveformwidgetfactory.cpp [hunk 2]
```diff
@@ -537,6 +538,8 @@ bool WaveformWidgetFactory::setWidgetType(
         WaveformWidgetType::Type type,
         WaveformWidgetType::Type* pCurrentType) {
     if (type == *pCurrentType) {
+        qDebug() << "WaveformWidgetFactory::setWidgetType - type"
```
Comment (ywwg) [inline src/waveform/waveformwidgetfactory.cpp:541]: this does not seem like a debug statement we need -- ok to delete it?

File: src/waveform/waveformwidgetfactory.cpp [hunk 3]
```diff
@@ -564,25 +569,33 @@ bool WaveformWidgetFactory::setWidgetType(
 }
 
 bool WaveformWidgetFactory::setWidgetTypeFromConfig() {
+    // qDebug() << "WaveformWidgetFactory::setWidgetTypeFromConfig";
     int empty = findHandleIndexFromType(WaveformWidgetType::EmptyWaveform);
     int desired = findHandleIndexFromType(m_configType);
     if (desired == -1) {
+        qDebug() << "WaveformWidgetFactory::setWidgetTypeFromConfig"
```
Comment (ywwg) [inline src/waveform/waveformwidgetfactory.cpp:576]: (whereas, this one seems useful)

File: src/waveform/waveformwidgetfactory.cpp [hunk 4]
```diff
@@ -1153,14 +1166,23 @@ WaveformWidgetType::Type WaveformWidgetFactory::findTypeFromHandleIndex(int inde
 }
 
 int WaveformWidgetFactory::findHandleIndexFromType(WaveformWidgetType::Type type) {
-    int index = -1;
-    for (int i = 0; i < m_waveformWidgetHandles.size(); i++) {
-        WaveformWidgetAbstractHandle& handle = m_waveformWidgetHandles[i];
+    int index = 0;
+    for (const auto& handle : std::as_const(m_waveformWidgetHandles)) {
```
Comment (ywwg) [inline src/waveform/waveformwidgetfactory.cpp:1170]: if you're going to maintain an index like this, you might as well keep the original style of loop (and use .get() to get a const ref instead of mutable)

**Review by ywwg — COMMENTED** [review]
I made some style notes, but the basic code looks good! thanks for this fix

**Comment by ronso0** [comment]
Thanks for your review. Feel free to edit this branch, I'm ill and probably won't fix it this year.

**Comment by ywwg** [comment]
> Thanks for your review. Feel free to edit this branch, I'm ill and probably won't fix it this year.

<3 hope you feel better and happy new year

**Comment by ronso0** [comment]
Thanks, doing better already.
Either you edit this as you desire, or I find time to do this, whatever happens earlier. After all I need some distraction from the usual xmas madness..

File: src/waveform/waveformwidgetfactory.cpp (hunk 4 above)
Comment (ronso0) [reply src/waveform/waveformwidgetfactory.cpp:1170]: Good point, I reverted this.
Though this is a QVector, not sure what you mean by `get()`.

**Comment by ronso0** [comment]
I addressed your comments with !fixups. Please check and give :+1: if it's okay, then I'll squash and force-push.

**Review by ywwg — APPROVED** [review]

**Comment by ronso0** [comment]
Draft again to avoid merging the separate fixups.

**Comment by ywwg** [comment]
Let me know how you want to treat this PR, not quite clear how you wanted to treat the fixups?

**Comment by ronso0** [comment]
I want to squash them but give @daschuer a chance to review them separately.

**Comment by ywwg** [comment]
Can you mark this as ready for review, and then add a note that it needs to be squashed before merge?  that way it gets on his radar

**Comment by ronso0** [comment]
@daschuer I pushed to fixups and left them separate for now so you can easily review those.
Please give me a hint when you consider this okay, then I'll squash and force-push.
Thanks!

**Review by daschuer — APPROVED** [review]
I can confirm the issue is fixed and the Code looks good. Thank you. 
Please give a hint once I can press merge.

**Comment by ronso0** [comment]
Ready!

**Comment by daschuer** [comment]
Thank you.
