### PR TITLE
Add global analysis progress percentage & fix UI jitter

### LINKED ISSUE #14796: analysis: display percentage of total number on tracks done?
### Feature Description

there is a percentage displayed for each track, but that just whizzes by

the addition of a percentage denoting the total number of tracks completed in the total number in the analysis queue/batch would be cool

### PR DESCRIPTION
**Pull request by xARSENICx**
Added a global progress percentage (X%)to the analysis status label. This gives users immediate feedback on the overall completion of the selected batch of tracks.

**Edge Case Handling:**
- The global percentage calculation is explicitly clamped at 100% to prevent display errors in edge cases where the finished count might momentarily exceed calculations.
- Safe division handling ensures no divide-by-zero errors if totalCount is zero.
- Removed individual track analysis progress

Fixes #14796

### CODE REVIEW

**Comment by ronso0** [comment]
Thank you for this PR!
As a first-time contributor we need you to sign the [Mixxx Contributor Agreement](https://docs.google.com/forms/d/e/1FAIpQLScC9QG327sjLL0eWftmfGUasxFFLxg6LCXJ2xHDYRzFIRqyiw/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ) and comment here when you have done so. It gives us permission to distribute your contribution under the GPL v2 or later license and the Apple Mac App Store. It is also helpful for us to have contact information for contributors in case we may need it in the future.

**Comment by xARSENICx** [comment]
Done.
Quite excited for the first PR in this repository. 😅

File: src/library/analysis/dlganalysis.cpp [hunk 1]
```diff
@@ -41,7 +41,8 @@ DlgAnalysis::DlgAnalysis(WLibrary* parent,
 
     QBoxLayout* box = qobject_cast<QBoxLayout*>(layout());
     VERIFY_OR_DEBUG_ASSERT(box) { // Assumes the form layout is a QVBox/QHBoxLayout!
-    } else {
+    }
+    else {
```
Comment (ronso0) [inline src/library/analysis/dlganalysis.cpp]: Please revert that. Overall the formatting looks good, though I suggest you take a look at https://github.com/mixxxdj/mixxx/wiki/Coding-Guidelines (braces are mentioned [here](https://github.com/mixxxdj/mixxx/wiki/Coding-Guidelines#braces)

File: src/library/analysis/dlganalysis.cpp [hunk 2]
```diff
@@ -130,14 +131,14 @@ void DlgAnalysis::selectAll() {
...
-    //qDebug() << this << "analyze()";
+    // qDebug() << this << "analyze()";
     if (m_bAnalysisActive) {
         emit stopAnalysis();
     } else {
         QList<AnalyzerScheduledTrack> tracks;
 
         QModelIndexList selectedIndexes = m_pAnalysisLibraryTableView->selectionModel()->selectedRows();
-        foreach(QModelIndex selectedIndex, selectedIndexes) {
+        foreach (QModelIndex selectedIndex, selectedIndexes) {
```
Comment (ronso0) [inline src/library/analysis/dlganalysis.cpp]: if you're touching this you may as well switch to a for loop, and make use of const and auto (here and in the surrounding code)
```suggestion
        for (const auto& selectedIndex : std::as_const(selectedIndexes)) {
```

File: src/library/analysis/dlganalysis.cpp [hunk 3]
```diff
@@ -166,21 +167,29 @@ void DlgAnalysis::slotAnalysisActive(bool bActive) {
...
-            QString progressPercent = QString::number(
-                    analyzerProgressPercent(analyzerProgress));
-            progressText = tr("Analyzing %1% %2/%3").arg(
-                    progressPercent,
-                    QString::number(finishedCount),
-                    QString::number(totalCount));
+            QString progressPercent = QString("%1").arg(
+                    analyzerProgressPercent(analyzerProgress), 3);
+            progressText =
+                    tr("Analyzing %1%  %2/%3 (%4%)")
```
Comment (ronso0) [inline src/library/analysis/dlganalysis.cpp]: I didn't build this yet, but how does this fixed whitespace avoid jitter when the track % changes?

Comment (ronso0) [reply src/library/analysis/dlganalysis.cpp]: Personally, I don't see the benefit of the single track percentage and would removeit, so just have the done/total (nn%). Wdyt?

Comment (xARSENICx) [reply src/library/analysis/dlganalysis.cpp]: > Personally, I don't see the benefit of the single track percentage and would removeit, so just have the done/total (nn%). Wdyt?

Yes, I agree. done/total should be enough.

> I didn't build this yet, but how does this fixed whitespace avoid jitter when the track % changes?

Well, it was somewhat better imo. But, when the percentage became nn% from n%, there was some jitter. Yes. But, if we get rid of the track percentage altogether, then there is no jitter to deal with. I am committing the change as per your reviews, please go through.

Comment (ronso0) [reply src/library/analysis/dlganalysis.cpp]: Okay, thank you.
Please don't close review conversations yourself, it's better if the reviewer does this, mostly for checking whether all issues have been resolved.
(I know they're auto-closed if you commit code proposals)

Comment (xARSENICx) [reply src/library/analysis/dlganalysis.cpp]: I will make a note. Let me know if anymore changes are expected or is it good to proceed with.

File: src/library/analysis/dlganalysis.cpp (hunk 1 above)
Comment (ronso0) [reply src/library/analysis/dlganalysis.cpp]: _ping_

Comment (xARSENICx) [reply src/library/analysis/dlganalysis.cpp]: The clang format just doesn't let me do this for some reason. (It is prolly due to `VERIFY_OR_DEBUG_ASSERT` which doesn't treat it like a conditional block.) 
Stuck with this formatting issue, help will be appreciated.

Comment (xARSENICx) [reply src/library/analysis/dlganalysis.cpp]: Well, I went ahead and made a fix in the latest commit which seems to restore the original way of things. But, am highly unsure if this is how it should be done. 
@ronso0 pinging for support.

**Review by ronso0 — CHANGES_REQUESTED** [review]
Just this one is left, code-wise.
Will test this week.

File: src/library/analysis/dlganalysis.cpp [hunk 4]
```diff
@@ -165,24 +165,22 @@ void DlgAnalysis::slotAnalysisActive(bool bActive) {
...
+            if (totalProgressPercent > 100) {
+                totalProgressPercent = 100;
+            }
         }
-        labelProgress->setText(progressText);
+
+        labelProgress->setText(tr("Analyzing %1/%2 (%3%)")
+                        .arg(QString::number(finishedCount),
+                                QString::number(totalCount),
+                                QString::number(totalProgressPercent)));
```
Comment (acolombier) [inline src/library/analysis/dlganalysis.cpp]: Changing the content of `tr` will invalidate the existing translation for it. Since the appended value is a number, perhaps we could keep the content as it was line 181 and append the new arg like so

```suggestion
        labelProgress->setText(tr("Analyzing %1/%2")
                        .arg(QString::number(finishedCount),
                                QString::number(totalCount)) + QStringLiteral(" (%3%)").arg(QString::number(totalProgressPercent)));
```

File: src/library/analysis/dlganalysis.cpp [hunk 5]
```diff
@@ -40,12 +40,14 @@ DlgAnalysis::DlgAnalysis(WLibrary* parent,
...
 
     QBoxLayout* box = qobject_cast<QBoxLayout*>(layout());
+    // clang-format off
     VERIFY_OR_DEBUG_ASSERT(box) { // Assumes the form layout is a QVBox/QHBoxLayout!
     } else {
         box->removeWidget(m_pTrackTablePlaceholder);
         m_pTrackTablePlaceholder->hide();
         box->insertWidget(1, m_pAnalysisLibraryTableView);
     }
+    // clang-format on
```
Comment (ronso0) [inline src/library/analysis/dlganalysis.cpp]: Oh sorry, your previous the formatting fix was correct as macros are apparently handled differently that if/else lines. Turning clang-format off is probably no big deal for this compact else branch, but I think it's better to keep it enabled so this patterns doesn't get adopted by other contributors.
Please revert to your initial commit.

Nad sorry for the noise, should have checked better initially.

Comment (ronso0) [reply src/library/analysis/dlganalysis.cpp]: Btw feel free to squash commits and force-push.

Comment (xARSENICx) [reply src/library/analysis/dlganalysis.cpp]: For future reference, can I go ahead and squash commit for similar smaller or progressively insignificant commits?

**Comment by xARSENICx** [comment]
All requests have been looked into. Request for review and potential merge.

File: src/library/analysis/dlganalysis.cpp (hunk 5 above)
Comment (ronso0) [reply src/library/analysis/dlganalysis.cpp]: In general it is best to ask before yo do so if there is already a review in progress. That is because force-push/rebase may remove review comments, depending on the rebase changes, of course.

File: src/library/analysis/dlganalysis.cpp [hunk 6]
```diff
@@ -165,24 +164,23 @@ void DlgAnalysis::slotAnalysisActive(bool bActive) {
...
-            // Omit to display any percentage
-            progressText = tr("Analyzing %1/%2").arg(
-                    QString::number(finishedCount),
-                    QString::number(totalCount));
+        int totalProgressPercent = 0;
+        if (totalCount > 0) {
+            totalProgressPercent = (finishedCount * 100) / totalCount;
+            if (totalProgressPercent > 100) {
+                totalProgressPercent = 100;
+            }
```
Comment (ronso0) [inline src/library/analysis/dlganalysis.cpp:176]: I wonder if we ever need to show 100 %, as that means "done."
Can the analysis get stuck at 100% when it's processing the last track? If yes, should we clamp to 99% for better UX?
Just a question, not a change request.

**Review by ronso0 — APPROVED** [review]
LGTM, thank you!

File: src/library/analysis/dlganalysis.cpp (hunk 6 above)
Comment (xARSENICx) [reply src/library/analysis/dlganalysis.cpp:176]: The clamping logic was written keeping situations like race conditions in mind- `finishedCount` updates from a thread while `totalCount` decreases. I know it is highly unlikely but I think the defensive approach is still quite realistic. WDYT?

99% wouldn't really make much sense here. Still, open to deliberation.

**Comment by acolombier** [comment]
@ronso0 is this ready to merge or did you want further testing here?

File: src/library/analysis/dlganalysis.cpp (hunk 6 above)
Comment (ronso0) [reply src/library/analysis/dlganalysis.cpp:176]: Okay, let's go then.
