### PR TITLE
Beats: Fix unsafe overflow checks and debug asserts

### LINKED ISSUE #12071: DEBUG ASSERT: "m_value < origValue" in function mixxx::Beats::ConstIterator
### Bug Description

Just encountered this. When I run the tests again, everything passes.

```
 91/808 Test #387: HotcueControlTest.SavedLoopActivate ........................................................***Exception: Interrupt  0.35 sec
QML debugging is enabled. Only use this in a safe environment.
info [0x55f4d12c7180] Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Note: Google Test filter = HotcueControlTest.SavedLoopActivate
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from HotcueControlTest
[ RUN      ] HotcueControlTest.SavedLoopActivate
info [0x55f4d12c7180] SoundSourceFFmpeg - Disabling untested input formats: aa, aax, ac3, ace, acm, act, adf, adp, ads, adx, aea, afc, aix, alp, amr, amrnb, amrwb, anm, apac, apc, ape, apm, apng, aptx, aptx_hd, aqtitle, argo_asf, argo_brp, argo_cvg, asf, asf_o, ass, ast, au, av1, avi, avisynth, avr, avs, avs2, avs3, bethsoftvid, bfi, bin, bink, binka, bit, bitpacked, bmv, bfstm, brstm, boa, bonk, c93, caf, cavsvideo, cdg, cdxl, cine, codec2, codec2raw, concat, dash, data, daud, dcstr, derf, dfa, dfpwm, dhav, dirac, dnxhd, dsf, dsicin, dss, dts, dtshd, dv, dvbsub, dvbtxt, dxa, ea, ea_cdata, eac3, epaf, ffmetadata, filmstrip, fits, flac, flic, flv, live_flv, 4xm, frm, fsb, fwse, g722, g723_1, g726, g726le, g729, gdv, genh, gif, gsm, gxf, h261, h263, h264, hca, hcom, hevc, hls, hnm, ico, idcin, idf, iff, ifv, ilbc, image2, image2pipe, alias_pix, brender_pix, imf, ingenient, ipmovie, ipu, ircam, iss, iv8, ivf, ivr, jacosub, jv, kux, kvag, laf, lmlm4, loas, luodat, lrc, lvf, lxf, mca, mcc, matroska,webm, mgsts, microdvd, mjpeg, mjpeg_2000, mlp, mlv, mm, mmf, mods, moflex, mpc, mpc8, mpeg, mpegts, mpegtsraw, mpegvideo, mpjpeg, mpl2, mpsub, msf, msnwctcp, msp, mtaf, mtv, musx, mv, mvi, mxf, mxg, nc, nistsphere, nsp, nsv, nut, nuv, obu, ogg, oma, paf, alaw, mulaw, vidc, f64be, f64le, f32be, f32le, s32be, s32le, s24be, s24le, s16be, s16le, s8, u32be, u32le, u24be, u24le, u16be, u16le, u8, pjs, pmp, pp_bnk, pva, pvf, qcp, r3d, rawvideo, realtext, redspark, rka, rl2, rm, roq, rpl, rsd, rso, rtp, rtsp, s337m, sami, sap, sbc, sbg, scc, scd, sdns, sdp, sdr2, sds, sdx, film_cpk, ser, sga, shn, siff, simbiosis_imx, sln, smk, smjpeg, smush, sol, sox, spdif, srt, psxstr, stl, subviewer1, subviewer, sup, svag, svs, swf, tak, tedcaptions, thp, 3dostr, tiertexseq, tmv, truehd, tta, txd, tty, ty, v210, v210x, vag, vc1, vc1test, vividas, vivo, vmd, vobsub, voc, vpk, vplayer, vqf, w64, wady, wavarc, wc3movie, webm_dash_manifest, webvtt, wsaud, wsd, wsvqa, wtv, wve, xa, xbin, xmd, xmv, xvag, xwma, yop, yuv4mpegpipe, bmp_pipe, cri_pipe, dds_pipe, dpx_pipe, exr_pipe, gem_pipe, gif_pipe, hdr_pipe, j2k_pipe, jpeg_pipe, jpegls_pipe, jpegxl_pipe, pam_pipe, pbm_pipe, pcx_pipe, pfm_pipe, pgmyuv_pipe, pgm_pipe, pgx_pipe, phm_pipe, photocd_pipe, pictor_pipe, png_pipe, ppm_pipe, psd_pipe, qdraw_pipe, qoi_pipe, sgi_pipe, svg_pipe, sunrast_pipe, tiff_pipe, vbn_pipe, webp_pipe, xbm_pipe, xpm_pipe, xwd_pipe, libmodplug, libopenmpt
info [0x55f4d12c7180] faad2::LibLoader - Successfully loaded FAAD2 library "libfaad.so.2" version 2.10.1
info [0x55f4d12c7180] SoundSourceSndFile - Disabling OGG decoding for "libsndfile-1.2.2"
info [0x55f4d12c7180] SoundSourceProxy - SoundSource providers for file type "3g2"
info [0x55f4d12c7180] SoundSourceProxy - 1 (lowest) : "FFmpeg n6.0"
info [0x55f4d12c7180] SoundSourceProxy - SoundSource providers for file type "3gp"
info [0x55f4d12c7180] SoundSourceProxy - 1 (lowest) : "FFmpeg n6.0"
info [0x55f4d12c7180] SoundSourceProxy - SoundSource providers for file type "aac"
info [0x55f4d12c7180] SoundSourceProxy - 1 (lowest) : "FFmpeg n6.0"
info [0x55f4d12c7180] SoundSourceProxy - SoundSource providers for file type "aiff"
info [0x55f4d12c7180] SoundSourceProxy - 3 (default) : "libsndfile"
info [0x55f4d12c7180] SoundSourceProxy - 1 (lowest) : "FFmpeg n6.0"
info [0x55f4d12c7180] SoundSourceProxy - SoundSource providers for file type "caf"
info [0x55f4d12c7180] SoundSourceProxy - 2 (lower) : "libsndfile"
info [0x55f4d12c7180] SoundSourceProxy - SoundSource providers for file type "flac"
info [0x55f4d12c7180] SoundSourceProxy - 4 (higher) : "Xiph.org libFLAC"
info [0x55f4d12c7180] SoundSourceProxy - 2 (lower) : "libsndfile"
info [0x55f4d12c7180] SoundSourceProxy - SoundSource providers for file type "it"
info [0x55f4d12c7180] SoundSourceProxy - 3 (default) : "MODPlug"
info [0x55f4d12c7180] SoundSourceProxy - SoundSource providers for file type "m4a"
info [0x55f4d12c7180] SoundSourceProxy - 3 (default) : "Nero FAAD2"
info [0x55f4d12c7180] SoundSourceProxy - 1 (lowest) : "FFmpeg n6.0"
info [0x55f4d12c7180] SoundSourceProxy - SoundSource providers for file type "mj2"
info [0x55f4d12c7180] SoundSourceProxy - 1 (lowest) : "FFmpeg n6.0"
info [0x55f4d12c7180] SoundSourceProxy - SoundSource providers for file type "mod"
info [0x55f4d12c7180] SoundSourceProxy - 3 (default) : "MODPlug"
info [0x55f4d12c7180] SoundSourceProxy - SoundSource providers for file type "mov"
info [0x55f4d12c7180] SoundSourceProxy - 1 (lowest) : "FFmpeg n6.0"
info [0x55f4d12c7180] SoundSourceProxy - SoundSource providers for file type "mp3"
info [0x55f4d12c7180] SoundSourceProxy - 3 (default) : "MAD: MPEG Audio Decoder 0.15.1 (beta) FPM_64BIT"
info [0x55f4d12c7180] SoundSourceProxy - 1 (lowest) : "FFmpeg n6.0"
info [0x55f4d12c7180] SoundSourceProxy - SoundSource providers for file type "mp4"
info [0x55f4d12c7180] SoundSourceProxy - 3 (default) : "Nero FAAD2"
info [0x55f4d12c7180] SoundSourceProxy - 1 (lowest) : "FFmpeg n6.0"
info [0x55f4d12c7180] SoundSourceProxy - 1 (lowest) : "FFmpeg n6.0"
info [0x55f4d12c7180] SoundSourceProxy - SoundSource providers for file type "ogg"
info [0x55f4d12c7180] SoundSourceProxy - 4 (higher) : "Xiph.org OggVorbis"
info [0x55f4d12c7180] SoundSourceProxy - SoundSource providers for file type "okt"
info [0x55f4d12c7180] SoundSourceProxy - 3 (default) : "MODPlug"
info [0x55f4d12c7180] SoundSourceProxy - SoundSource providers for file type "opus"
info [0x55f4d12c7180] SoundSourceProxy - 4 (higher) : "Xiph.org libopusfile"
info [0x55f4d12c7180] SoundSourceProxy - SoundSource providers for file type "s3m"
info [0x55f4d12c7180] SoundSourceProxy - 3 (default) : "MODPlug"
info [0x55f4d12c7180] SoundSourceProxy - SoundSource providers for file type "stm"
info [0x55f4d12c7180] SoundSourceProxy - 3 (default) : "MODPlug"
info [0x55f4d12c7180] SoundSourceProxy - SoundSource providers for file type "wav"
info [0x55f4d12c7180] SoundSourceProxy - 3 (default) : "libsndfile"
info [0x55f4d12c7180] SoundSourceProxy - 1 (lowest) : "FFmpeg n6.0"
info [0x55f4d12c7180] SoundSourceProxy - SoundSource providers for file type "wv"
info [0x55f4d12c7180] SoundSourceProxy - 4 (higher) : "WavPack"
info [0x55f4d12c7180] SoundSourceProxy - 1 (lowest) : "FFmpeg n6.0"
info [0x55f4d12c7180] SoundSourceProxy - SoundSource providers for file type "xm"
info [0x55f4d12c7180] SoundSourceProxy - 3 (default) : "MODPlug"
warning [0x55f4d12c7180] ControlObject accessed via deprecated key "[Channel1]" "hotcue_1_enabled" - use "[Channel1]" "hotcue_1_status" instead
warning [Engine] Beats: Iterator would go out of possible range, capping at earliest possible position.
critical [Engine] DEBUG ASSERT: "m_value < origValue" in function mixxx::Beats::ConstIterator mixxx::Beats::ConstIterator::operator-=(difference_type) at /home/jan/Projects/mixxx/src/track/beats.cpp:123
```

### Version

2.4

### OS

Arch Linux

### PR DESCRIPTION
**Pull request by fwcd**
### Fixes #12071 (for me, testing would be appreciated!)

With this patch Mixxx no longer crashes after loading variable BPM tracks with debug assertions enabled.

As noted in https://github.com/mixxxdj/mixxx/issues/12071#issuecomment-1825743901, the overflow checks in `Beats::ConstIterator` were rather unsafe and probably even undefined behavior, therefore this patch replaces them with a safe check.

Additionally, I have updated the `DEBUG_ASSERT`s to accept equality too. This should make sense, since we can't move the iterator further once we're at the limit, as the warning should indicate:

```
warning [CachingReaderWorker 1] Beats: Iterator would go out of possible range, capping at earliest possible position.
```

It should be noted, however, that I still think there's an issue somewhere in the (de)serialization machinery of `BeatMap-1.0`, since this feels like an edge case we shouldn't be hitting, even for variable BPM maps. Some more debugging would probably be helpful, but for now this should hopefully at least fix the assertion.

### CODE REVIEW

**Review by m0dB — APPROVED** [review]

**Comment by daschuer** [comment]
I see now: 
warning [CachingReaderWorker 1] Beats: Iterator would go out of possible range, capping at earliest possible position.
With one effected file. The other critical one loads without any warning now. 
I will investigate.

**Comment by fwcd** [comment]
My theory is that this overflow check didn't really work before, because the compiler might have optimized it out, so we might not hit this warning in all cases and that we should have always gotten it for variable BPM tracks (due to some other issue with the beatmaps).

File: src/track/beats.cpp [hunk 1]
```diff
@@ -60,23 +60,23 @@ Beats::ConstIterator Beats::ConstIterator::operator+=(Beats::ConstIterator::diff
...
     DEBUG_ASSERT(n > 0);
-    const int beatOffset = m_beatOffset + n;
 #ifdef MIXXX_DEBUG_ASSERTIONS_ENABLED
     const auto origValue = m_value;
 #endif
 
-    // Detect integer overflow
-    if (beatOffset < m_beatOffset) {
+    // Detect integer overflow in `m_beatOffset + n`
+    const int maxBeatOffset = std::numeric_limits<Beats::ConstIterator::difference_type>::max();
```
Comment (daschuer) [inline src/track/beats.cpp:68]: So this is 2,147,483,647. My track as a ~150 BPM track with 2:21. 
No clue how that can be triggered.

Comment (fwcd) [reply src/track/beats.cpp:68]: I was a bit confused about this too, but apparently the max/min integers are used as a form of marker values to indicate the first/last possible beat (outside of a track):

https://github.com/mixxxdj/mixxx/blob/2c2e706b4419794e1b29f23f124ce65f49b88bc7/src/track/beats.h#L199-L210

Haven't dug too much into the code to find out where that actually is useful, but for now I think coding defensively in the iterator is probably a good idea.

File: src/track/beats.cpp [hunk 2]
```diff
@@ -60,23 +60,23 @@ Beats::ConstIterator Beats::ConstIterator::operator+=(Beats::ConstIterator::diff
...
+    if (m_beatOffset > maxBeatOffset - n) {
         qWarning() << "Beats: Iterator would go out of possible range, capping "
```
Comment (m0dB) [inline src/track/beats.cpp:70]: I am trying to find an explanation why the original overflow condition wouldn't work. At a first glance, the result should be the same. That said, this is certainly less obscure and more readable. Still, it would be nice to understand the difference, and I don't see that yet.

Comment (fwcd) [reply src/track/beats.cpp:70]: (My understanding, might be wrong) is that the compiler is allowed to assume that signed overflow never happens and may optimize away the entire if-statement to a noop. In any case, we shouldn't rely on it.

**Review by daschuer — APPROVED** [review]
LGTM, This is a good first step. I think we should take care that the warning never happens. 
I am in the progress of a follow up. Thank you for finding this hard bit.
