### PR TITLE
Work around an Ubuntu, Ibus or Qt issue regarding detecting the current keyboard layout.

### LINKED ISSUE #14797: Current locale is not taken into account for setting the keyboard mapping (fr-CH), Mixxx assumes a US layout
### Bug Description

I run Mixxx 2.5.1 on my Ubuntu 24.04 machine.

As I live in western, the French-speaking part of Switzerland, the OS is configured in fr_CH locale and the keyboard mapping is the Swiss French one. FIY it is nearly the same as the Swiss German except that a couple accent keys like é/ö, à/ä have their Shift behaviour reversed.

When I start Mixxx using developer mode, I seee that Mixxx decides to load the default US layout.

`debug [Main] Found and will use default keyboard mapping "/usr/share/mixxx/keyboard/en_US.kbd.cfg"`

Some shortcuts are impractical due to this, for example cue on deck 2.

Is there a missing config on my side?

Output of `localectl status`:

```
System Locale: LANG=fr_FR.UTF-8
               LC_NUMERIC=fr_CH.UTF-8
               LC_TIME=fr_CH.UTF-8
               LC_MONETARY=fr_CH.UTF-8
               LC_PAPER=fr_CH.UTF-8
               LC_NAME=fr_CH.UTF-8
               LC_ADDRESS=fr_CH.UTF-8
               LC_TELEPHONE=fr_CH.UTF-8
               LC_MEASUREMENT=fr_CH.UTF-8
               LC_IDENTIFICATION=fr_CH.UTF-8
    VC Keymap: (unset)                      
   X11 Layout: ch
    X11 Model: pc105
  X11 Variant: fr
```

### Version

2.5.1

### OS

Ubuntu 24.04

### PR DESCRIPTION
**Pull request by daschuer**
Since we can't wait for an upstream solution this is a workaround. 
#14838 #14797

### CODE REVIEW

**Comment by ronso0** [comment]
Looks like the Xfce pendant is
`xfconf-query -c keyboard-layout -p /Default/XkbLayout`
It will return a comma-separated list with the first item being the current layout.

I'll check if this works.

**Comment by ronso0** [comment]
Yep, this works for xfce
88fe19fd27

**Comment by ronso0** [comment]
IIUC parsing the output of `localectl status` should also work.

**Comment by daschuer** [comment]
localectl status does not follow the gnome settings. Mixxx does. 

```
$ localectl status
   System Locale: LANG=de_DE.UTF-8
       VC Keymap: n/a
      X11 Layout: de
       X11 Model: pc105
$ dconf read /org/gnome/desktop/input-sources/mru-sources 
[('xkb', 'us'), ('xkb', 'de')]
```

**Comment by ronso0** [comment]
So GNOME settings override `localectl` which is still considered the default source, even on Wayland. Interesting..

**Comment by ronso0** [comment]
Did you notice my Xfce fixup?

> Yep, this works for xfce [88fe19f](https://github.com/mixxxdj/mixxx/commit/88fe19fd270175dde147a5fc50ed5c48f527afc8)

**Comment by daschuer** [comment]
Now :-)

File: src/coreservices.cpp [hunk 1]
```diff
@@ -98,11 +100,80 @@ Bool __xErrorHandler(Display* display, XErrorEvent* event, xError* error) {
...
+#if defined(Q_OS_LINUX)
+    if (isGnomeSession()) {
+        // In a Gnome session QGuiApplication::inputMethod() is not necessarily correct
+        // https://github.com/mixxxdj/mixxx/issues/14838
+        // If this auto detection still fails the user may use a Custom.kb.cfg
+        QProcess sourcesProc;
+        sourcesProc.start("dconf",
+                QStringList()
+                        << "read"
+                        << "/org/gnome/desktop/input-sources/mru-sources");
```
Comment (ronso0) [inline src/coreservices.cpp]:
```suggestion
                        << "/org/gnome/desktop/input-sources/sources");
```

**Review by ronso0 — CHANGES_REQUESTED** [review]

**Comment by ronso0** [comment]
and the 1st item reurned by `xfconf-query -c keyboard-layout -p /Default/XkbLayout` is the actual layout only if the layout is switched with `xfce-keyboard-settings` (default kbd settings page, preferred layout moved to top).

It's not when the layout switched with
* `xfce4-xkb-plugin` (which is an optional tool IIUC)
* custom hotkey
* `setxkbmap -layout [layout]`

For my feeling, it's all pretty messed up in xfce, at least in 4.14

Since that woul donly affect users who a) switch layouts with b) the tools mentioned above, I'd say merge (with the `dconf` fixup) and wait for more reports.
Since Ubuntu Studio 24.04 now uses KDE Plasma, the number of users with Xfce is probably low.
Or we try [`xkblayout-state`](https://github.com/nonpop/xkblayout-state) first (optional tool, recommended [here](https://gitlab.xfce.org/xfce/xfconf/-/issues/32#note_55682)), then use `xfconf`. But this is really too much of an edge case, so let's go.

**Comment by daschuer** [comment]
Now it shall cover the "only one" keyboard case. Of #14797 we have however no fr_CH keyboard yet. 

The whole issue is a real mess. At one point we need to revive the keyboard controller idea, using the key codes, not what is printed when pressing the key.

**Comment by ronso0** [comment]
Haha, you wrote the commit message with en_US?
> [read kezboard lazout form /org/gnome/desktop/input-sources/sources if…](https://github.com/mixxxdj/mixxx/pull/14883/commits/3998605ef4bd9e8b903509dcc1bb6c367dff7387)

Please rewrite so it's easier to find 'keyboard' commits.

Will test again in my VM soonish.

**Comment by daschuer** [comment]
Done

File: src/coreservices.cpp [hunk 2]
```diff
@@ -98,11 +100,116 @@ Bool __xErrorHandler(Display* display, XErrorEvent* event, xError* error) {
...
+                return localeFromXkbLayout(layout);
+            } else {
+                // mru-sources (most recently used source) is empty when user
+                // has only one keyboard layout enabled. Use it from sources.
+                sourcesProc.start("dconf",
+                        {"read", "/org/gnome/desktop/input-sources/sources"});
+                if (sourcesProc.waitForFinished(100)) {
+                    const QString sourcesStr = sourcesProc.readAllStandardOutput().trimmed();
+                    // Expecting something like this: [('xkb', 'de')]
+                    static const QRegularExpression re(QStringLiteral("\\('xkb',\\s*'([^']+)'\\)"));
```
Comment (ronso0) [inline src/coreservices.cpp]: reuse `re` from above?

**Comment by daschuer** [comment]
I have tested xkblayout-state and it works like a charm. It seems to have really the truth. I can imagine to put the related x11 calls into Mixxx. Unfortunatly it requires to link agains `-lX11` (Which we already do conditionally https://github.com/mixxxdj/mixxx/blob/837f0ab69904c3f4a086fab5323029fb0d0f0c5d/CMakeLists.txt#L3905) and it does not work with Wayland. 

The solution here works for X11 and Wayland, is however somwhat fragile.

**Comment by ronso0** [comment]
Good news!
So, having `xkblayout-state` always available would be great. Can you add that to the ppa?

**Comment by daschuer** [comment]
I prefere the idea to do the X11 API calls directly. 
Likely easier to maintain.

**Comment by ronso0** [comment]
> It seems to have really the truth. I can imagine to put the related x11 calls into Mixxx

Ah okay, sorry I overlooked / misunderstood that earlier (on mobile, in a hurry).
Yeah, sure, if you think that's feasible go ahead.

Btw I wonder why these issues are noticed just now, or is it that only recent Ubuntu(-ish) distros expose this issue?

**Comment by daschuer** [comment]
That's an interesting question. I am sure it worked with older Ubuntu version and QT5, but I have no interest to track that down.

**Comment by ronso0** [comment]
Alright, #14838 seems fixed (and #14797 for de_DE).
Guess I don't need to do a test in the VM then.
Confirmation from @davthedev would be good.

I added the Qt6 label.

**Comment by daschuer** [comment]
Works now. First it ties to via X11 XWayland. That works even if Mixxx itself is running with Wayland. If XWayland is not installed it falls back to 
dconf/Xfc and than ibus. 
If there is still an issue user can use a custom keyboard.

**Comment by ronso0** [comment]
Great, thanks!
Idk when I have time for a proper test in the 24.04 VM, probably on sunday evening.

File: src/coreservices.cpp [hunk 3]
```diff
@@ -45,8 +47,17 @@
...
 
-#if defined(Q_OS_LINUX) && QT_VERSION < QT_VERSION_CHECK(6, 0, 0)
+#ifdef Q_OS_LINUX
+#include <X11/XKBlib.h>
 #include <X11/Xlib.h>
+#include <X11/extensions/XKBrules.h>
+
+// #include <X11/Xresource.h>
+// #include <X11/extensions/XKBrules.h>
+// #include "X11Exception.h"
```
Comment (ronso0) [inline src/coreservices.cpp]: Can be removed, right?

**Review by ronso0 — CHANGES_REQUESTED** [review]
nothing special. will try to review the Xkb function soon.

**Comment by ronso0** [comment]
> First it ties to via X11 XWayland. That works even if Mixxx itself is running with Wayland. If XWayland is not installed it falls back to dconf/Xfc and than ibus. If there is still an issue user can use a custom keyboard.

Can you add that as comments to `inputLocale()`? Some info is already there, but I think it would be good to document the issue and the entire approach.

**Comment by daschuer** [comment]
Comment added.

**Comment by daschuer** [comment]
Can we now merge this? This should be really part of 2.5.2

**Comment by ronso0** [comment]
If you're confident, go ahead.

Else, I'd like to do one more test, and take a look at the Xkb calls. Which I can do tomorrow night finally.

File: src/coreservices.cpp [hunk 4]
```diff
@@ -98,11 +102,229 @@ Bool __xErrorHandler(Display* display, XErrorEvent* event, xError* error) {
...
+    }
+    char* pGroupName = XGetAtomName(pDisplay, pDesc->names->groups[state.group]);
+    if (!pGroupName) {
+        qWarning() << "XGetAtomName failed";
+        XkbFreeNames(pDesc, XkbGroupNamesMask, True);
+        return {};
+    }
+    QString layoutName = QString(pGroupName);
+    XkbFreeNames(pDesc, XkbKeyNamesMask, True);
+    XFree(pGroupName);
```
Comment (ronso0) [inline src/coreservices.cpp:240]: it seems we should also `XCloseDisplay(pDisplay)`?

**Comment by ronso0** [comment]
I can't test the 2.5 build in the 24.04 VM, so I created https://github.com/ronso0/mixxx/pull/94 against 2.6 to get a build.
Will report asap.

**Comment by ronso0** [comment]
Works nicely in 24.04 :+1:

**Comment by daschuer** [comment]
XCloseDisplay(pDisplay) is in place. Thank you for testing.

**Comment by daschuer** [comment]
/softfix

I am curious to see if this now actualy did an autosquash

**Comment by ronso0** [comment]
It worked, but CI wasn't triggered.

**Comment by daschuer** [comment]
Edited the initial description. 
I need to have a look how we can trigger the CI automatically

**Comment by daschuer** [comment]
All green finally.

**Comment by ronso0** [comment]
Great, thank you!
