### PR TITLE
Fix loading the wrong track via drag and drop and fix wrong DEBUG_ASSERT

### LINKED ISSUE #13706: DEBUG ASSERT with two symlinked tracks
### Bug Description

```
critical [Main] DEBUG ASSERT: "!trackId.isValid() || trackId == cacheResolver.getTrackRef().getId()" in function TrackPointer TrackDAO::getTrackById(TrackId) const at ./src/library/dao/trackdao.cpp:1440
```

ASSERTS are for conditions that can never happen. However this can easily happen if you have for instance a symlink to the file. 

The track cache takes care that only one track per physical file exists, to avoid concurrent writes that may corrupt the file. 
So if we have the file in cache, the second instance cannot be used. 

Since https://github.com/mixxxdj/mixxx/pull/13685 see an empty track properties menu. Better than nothing but informing the user about the situation would be better. 

### Version

2.4.1

### OS

Ubuntu Focal

### PR DESCRIPTION
**Pull request by daschuer**
This fixes handling with duplicated tracks https://github.com/mixxxdj/mixxx/issues/13706. Now an attempt for caching two tracks with different locations referencing the same file are reliably detected and rejected the situation is reported as warning, and does no longer violates assertions. 

This has been tested on Ubuntu focal using a symlink 
`ln -s track.mp3 symlink.mp3`

The related issues showing the empty property page and overwriting thee symlink https://github.com/mixxxdj/mixxx/issues/13707 are still pending, work is in progress.

### CODE REVIEW

File: src/library/dao/trackdao.cpp [hunk 1]
```diff
@@ -828,34 +828,47 @@ TrackPointer TrackDAO::addTracksAddFile(
...
+        break;
+    }
+    case GlobalTrackCacheLookupResult::Miss:
+        // An (almost) empty track object
+        DEBUG_ASSERT(pTrack);
+        DEBUG_ASSERT(!pTrack->getId().isValid());
+        // Continue and populate the (almost) empty track object
+        break;
+    case GlobalTrackCacheLookupResult::ConflictCanonicalLocation:
+        // Reject requests that would otherwise cause a caching caching conflict
```
Comment (ronso0) [inline src/library/dao/trackdao.cpp:852]:
```suggestion
        // Reject requests that would otherwise cause a caching conflict
```

File: src/library/dao/trackdao.cpp [hunk 2]
```diff
@@ -828,34 +828,47 @@ TrackPointer TrackDAO::addTracksAddFile(
...
+        // by accessing the same, physical file from multiple tracks concurrently.
+        DEBUG_ASSERT(!pTrack);
+        DEBUG_ASSERT(cacheResolver.getTrackRef().hasCanonicalLocation());
+        DEBUG_ASSERT(cacheResolver.getTrackRef().getCanonicalLocation() ==
+                fileAccess.info().canonicalLocation());
+        kLogger.warning()
+                << "Failed to add track"
+                << fileAccess.info().location()
+                << "because tack"
```
Comment (ronso0) [inline src/library/dao/trackdao.cpp:861]:
```suggestion
                << "because track"
```

**Comment by ronso0** [comment]
Looks like this fixes #13540 (and #13140)

**Comment by ronso0** [comment]
Just an idea how to allow users fixing the situation in Mixxx:
* in case we manage to display an error dialog, we could allow showing both tracks in the tracks view via an OR search for both track ids (or more, maybe a file has already been added a third or forth time) with `Library::searchTracksInCollection(QStringLiteral("id:trackId1 | id:trackId2"));`
* users can now merge metadata and purge the obsolete track
* maybe allow replacing the obsolete track with the original in playlists and crates, incl. history

**Comment by daschuer** [comment]
Sounds good. Can we merge this now since this is IMHO a 2.4.2 bug fix.

**Comment by daschuer** [comment]
I consider this ready for merge.

**Comment by JoergAtGithub** [comment]
@ronso0 How do you rate the risk here? Should we postpone this to 2.5.1 ?

**Review by acolombier — APPROVED** [review]
LGTM - haven't had a chance to run manual testing tho

Edit: Do we want this in `2.4` or shall it go in `2.5`?

**Comment by ronso0** [comment]
> @ronso0 How do you rate the risk here? Should we postpone this to 2.5.1 ?

Oh sorry, I missed that!
I'm still having a hard time understanding some of the Track/Trackrecord/db relations, I don't feel competent to judge the changes.

If the manual tests¹ succeed this is good for 2.5 IMO. Question is how to easily (easy for reviewers) get this into 2.5 since 2.4 is frozen IIUC.

Tests:
* all new tracks must be discovered, of course
* all new tracks must be discovered after moving a base music directory via preferences
* what about old/new symlinked tracks @daschuer ?

File: src/library/dao/trackdao.cpp [hunk 3]
```diff
@@ -828,34 +828,47 @@ TrackPointer TrackDAO::addTracksAddFile(
...
-                    << fileAccess.info().location()
-                    << "and an existing track at"
-                    << trackLocation
-                    << "are referencing the same file"
-                    << fileAccess.info().canonicalLocation();
-            return nullptr;
+    switch (cacheResolver.getLookupResult()) {
+    case GlobalTrackCacheLookupResult::Hit: {
+        DEBUG_ASSERT(pTrack);
+        const TrackId oldTrackId = pTrack->getId();
```
[the remark this answers is not in the document]
Comment (ronso0) [reply src/library/dao/trackdao.cpp:834]: _ping_ @daschuer ?

**Comment by ronso0** [comment]
@daschuer can you please rebase onto 2.5? (or just chnage the target branch, idk)

**Comment by ronso0** [comment]
Will do a manual test soon!

File: src/library/dao/trackdao.cpp [hunk 4]
```diff
@@ -1422,42 +1438,47 @@ TrackPointer TrackDAO::getTrackById(TrackId trackId) const {
...
             DEBUG_ASSERT(cacheResolver.getTrackRef().getCanonicalLocation() ==
                     fileInfo.canonicalLocation());
             kLogger.warning()
-                    << "Failed to load track with id"
+                    << "Failed to load track"
+                    << trackLocation
+                    << "with id"
                     << trackId
-                    << "that is referencing the same file"
+                    << "because tack"
```
Comment (cr7pt0gr4ph7) [inline src/library/dao/trackdao.cpp:1465]:
```suggestion
                    << "because track"
```

File: src/track/globaltrackcache.cpp [hunk 5]
```diff
@@ -464,25 +437,27 @@ TrackPointer GlobalTrackCache::lookupById(
...
                 return trackPtr;
             }
+            kLogger.warning()
+                    << "Found a different track for the same canonical location:"
+                    << "requested =" << trackRef
+                    << "cached =" << cachedTrackRef;
         }
     }
-    return trackPtr;
+    return {};
```
Comment (cr7pt0gr4ph7) [inline src/track/globaltrackcache.cpp:460]:
```suggestion
    // Lookup failed, either because the TrackRef did not specify an id or canonical location,
    // or because the database contains multiple tracks with that canonical location.
    return {};
```

File: src/library/dao/trackdao.cpp (hunk 3 above)
[the remark this answers is not in the document]
Comment (cr7pt0gr4ph7) [reply src/library/dao/trackdao.cpp:834]: Just for context, does the `"File not found"` message previously present here mean `"File not found in the database"` or `"File not found on the filesystem"`?

**Review by cr7pt0gr4ph7 — CHANGES_REQUESTED** [review]

File: src/library/dao/trackdao.cpp (hunk 3 above)
[the remark this answers is not in the document]
Comment (daschuer) [reply src/library/dao/trackdao.cpp:836]: Kind of file not found on the file system. If the file is not in the database it is anyhow added to the cache to prevent writing the file metadata while playing. The cache uses the canonical location of the file which requires file system access. The file is however later opened which still may fail. 

Null check is now back.

**Comment by daschuer** [comment]
Done

**Comment by daschuer** [comment]
Can one take a final look an merge?

**Review by cr7pt0gr4ph7 — APPROVED** [review]
LGTM

**Comment by JoergAtGithub** [comment]
> Will do a manual test soon!

It seems this code is reviewed, but no one tested it yet. Can someone test with Unix symbolic links?

**Comment by ronso0** [comment]
So, finally, here are my test results with this branch.
Strangely I can not make it hit the assert mentioned in #13706 with 2.5
(track paths are truncated)

* I created one symlink of a track which is already in the db
track1.mp3 + symlink.mp3
* track1.mp3 has been added to the library
* do a Library rescan

```
debug [LibraryScanner 1] LibraryScanner - slotStartScan()
... (scanner info)
debug [Thread (pooled)] Importing track "/music/symlink.mp3"
debug [LibraryScanner 1] isFileSupported "mp3"
debug [LibraryScanner 1] GlobalTrackCache - Resolving track by canonical location "/music/track1.mp3"
debug [LibraryScanner 1] GlobalTrackCache - Cache miss - allocating track  TrackRef {"/music/symlink.mp3","/music/track1.mp3",-1}
debug [LibraryScanner 1] GlobalTrackCache - Cache miss - inserting new track into cache  TrackRef {"/music/symlink.mp3","/music/track1.mp3",-1} QObject(0x0)
... (SoundSource, Serato, TagLib)
debug [LibraryScanner 1] TrackDAO - TrackDAO: Adding track "/music/symlink.mp3"
debug [Main] GlobalTrackCache - Evicting track  TrackRef {"/music/symlink.mp3","/music/track1.mp3",2} Track(0x7fa7a80b2f40)
debug [LibraryScanner 1] LibraryScanner - slotFinishHashedScan
debug [LibraryScanner 1] LibraryScanner - slotFinishUnhashedScan
debug [Main] GlobalTrackCache - Deleting Track(0x7fa7a80b2f40)
... (scanner info)
debug [LibraryScanner 1] LibraryScanner - Scan finished cleanly
debug [LibraryScanner 1] Scan took: 83671775 ns. 0 unchanged directories. 1 changed/added directories. 1 tracks verified from changed/added directories. 1 new tracks.
```

* get this info once when I press Down in the Tracks to select symlink.mp3.
* get this 5 times more when I press Ctrl+Enter to open Track Info (then hit the dbg assert in dlgtrackinfo.cpp)
```
debug [Main] GlobalTrackCache - Resolving track by id 2
debug [Main] GlobalTrackCache - Resolving track by canonical location "/music/track1.mp3"
debug [Main] GlobalTrackCache - Cache Conflict - found a different track for the same canonical location: requested =  TrackRef {"/music/symlink.mp3","/music/track1.mp3",2} cached =  TrackRef {"/music/track1.mp3","/music/track1.mp3",1}
warning [Main] TrackDAO - Failed to load track "/music/symlink.mp3" with id 2 because track "/music/track1.mp3" with id 1 referencing the same file at "/music/track1.mp3" is already loaded.
```

**Comment by ronso0** [comment]
Had to merge this branch into 2.5 for testing.
Please rebase.

**Comment by daschuer** [comment]
Done

**Comment by ronso0** [comment]
Looks like the rebase went wrong, now the only change is the new comment?

**Comment by daschuer** [comment]
The major part of this PR has been merged via: 
https://github.com/mixxxdj/mixxx/pul.githubl/13719
Now we have only the comment, which was not part in that.

**Comment by ronso0** [comment]
LGTM :man_shrugging:
