### PR TITLE
BaseSqlTableModel: Fix bounds check

### LINKED ISSUE #11491: Some columns in external playlists (iTunes, Traktor, ...) cannot be sorted (initially)
### Bug Description

To reproduce:

- Open Mixxx
- Open a playlist in an iTunes or Traktor library
- Sort by BPM
- The table will not sort correctly and the log will emit

```
warning [Main] BaseSqlTableModel::setSort invalid column: 14
```

Now, interestingly, once the user sorts by artist or title, the sort by BPM will work correctly and the issue seems to be 'fixed' for the rest of the session. So there's probably something strange in the way the table is initialized.

This issue also seems to be rather old, it occurs on recent 2.4 and `main` builds all the way back to at least f67460db13 (probably longer).

### Version

2.4-alpha-1426-g45eb0bbddf

### OS

macOS 13.3.1

### PR DESCRIPTION
**Pull request by fwcd**
This fixes #11491, i.e. fixes the sorting for certain columns (e.g. BPM).

I hope this solution is also semantically correct, since I don't have a super deep understanding of the different indexing schemes (sort columns vs column indices etc.).

From what I understand, the issue was that the table columns  (`track_id`, `position`, `preview`) weren't considered and then caused the bound check to fail. This was particularly an issue for columns such as BPM and rating since they have a rather high index and thus fell outside the range of the 3 track table columns that weren't considered:

Screenshot 2023-04-19 at 17 08 59

Once `m_sortColumns` was populated (which happens on the first sort), the bound check 'accidentally' passed since the previously out-of-bounds column indices were suddenly in bounds. This is also why sorting by a key such as title or artist would 'fix' the BPM sorting issue.

This should hopefully resolve the issue both for iTunes and Traktor (and perhaps other external) playlists.

### CODE REVIEW

**Comment by fwcd** [comment]
Since this fixes a pretty central bug while being a rather isolated change, perhaps it would even be worth targeting 2.3? Or are there no more 2.3 releases planned?

**Comment by daschuer** [comment]
We have planned a 2.3.5 see the milestone. 
It sounds that this suits to it.

**Comment by fwcd** [comment]
I've rebased it on to 2.3

File: src/library/basesqltablemodel.cpp [hunk 1]
```diff
@@ -423,7 +423,7 @@ void BaseSqlTableModel::setSort(int column, Qt::SortOrder order) {
     int trackSourceColumnCount = m_trackSource ? m_trackSource->columnCount() : 0;
 
     if (column < 0 ||
-            column >= trackSourceColumnCount + m_sortColumns.size() - 1) {
+            column >= trackSourceColumnCount + m_tableColumns.size() + m_sortColumns.size() - 1) {
```
Comment (daschuer) [inline src/library/basesqltablemodel.cpp:426]: I think you have found a popy/paste issue. m_sortColumns.size() is the sort history kept for the secondary sort. 
```suggestion
            column >= trackSourceColumnCount + m_tableColumns.size() - 1) {
```

**Comment by fwcd** [comment]
Thanks for clarifying, I've updated the branch with your suggested fix. Would be awesome if this could be included in 2.3.5

**Comment by daschuer** [comment]
Thank you.
