### PR TITLE
Fix pitch issue (only) with dynamic tracks and sync

### LINKED ISSUE #10550: Changing tempo when using instant double and sync
Reported by: **[daschuer](https://github.com/daschuer)**
Date: 2021-10-07T17:58:08Z
Status: New
Importance: Undecided
Launchpad Issue: [lp1946385](https://bugs.launchpad.net/bugs/1946385)

---

When using instant double and sync is enabled on the source and target deck, the tempo changes every time you repeat the instant double action.
The issue has been recorded here https://github.com/mixxxdj/mixxx/pull/3944#issuecomment-917712679

### PR DESCRIPTION
**Pull request by daschuer**
This PR fixes https://github.com/mixxxdj/mixxx/issues/10550 Via a couple of single fixes regarding using the right data at the right time.

This is a split from https://github.com/mixxxdj/mixxx/pull/12435 which also fixes gain issues happens during track cloning

### CODE REVIEW

**Review by ywwg — APPROVED** [review]
lgtm. Added some notes for comments to better explain what we are doing

File: src/engine/enginebuffer.h [hunk 1]
```diff
@@ -71,6 +71,8 @@ class EngineBuffer : public EngineObject {
         /// This is an artificial state that happens if a standard seek and a
         /// phase seek are scheduled at the same time.
         SEEK_STANDARD_PHASE = SEEK_STANDARD | SEEK_PHASE,
+        /// #SEEK_EXACT to the other deck position
+        SEEK_CLONE = 8u,
```
[the remark this answers is not in the document]
Comment (daschuer) [reply src/engine/enginebuffer.h:75]: just the next enum value. I will use the bit shift notation to make this obvious.

**Comment by daschuer** [comment]
Done

File: src/engine/channels/enginedeck.h [hunk 2]
```diff
@@ -25,7 +25,16 @@ class EngineDeck : public EngineChannel, public AudioDestination {
 
     void process(CSAMPLE* pOutput, const int iBufferSize) override;
     void collectFeatures(GroupFeatureState* pGroupFeatures) const override;
+
+    // postProcessLocalBpm() is called on all decks to update the localBpm after
+    // process() is done. Updated localBpm for all decks are required for the
+    // postPrecess() step, to not deal with the order they are processed.
+    // It cannot be done during process() because it relies that the localBpm
+    // of all decks are on their old values.
```
Comment (ywwg) [inline src/engine/channels/enginedeck.h:33]: slight language tweak

```suggestion
    // postProcessLocalBpm() is called on all decks to update the localBpm after
    // process() is done. Updated localBpms for all decks are required for the
    // postProcess() step, to avoid issues with the order they are processed.
    // It cannot be done during process() because it relies that the localBpm
    // of all decks are on their old values.
```

File: src/engine/enginebuffer.h [hunk 3]
```diff
@@ -58,21 +58,21 @@ class EngineBuffer : public EngineObject {
...
         SEEK_EXACT_PHASE = SEEK_PHASE | SEEK_EXACT,
         /// #SEEK_PHASE if Quantize enables, otherwise SEEK_EXACT
-        SEEK_STANDARD = 4u,
+        SEEK_STANDARD = 1 << 2,
         /// This is an artificial state that happens if a standard seek and a
         /// phase seek are scheduled at the same time.
         SEEK_STANDARD_PHASE = SEEK_STANDARD | SEEK_PHASE,
         /// #SEEK_EXACT to the other deck position
-        SEEK_CLONE = 8u,
+        SEEK_CLONE = 1 << 3
```
Comment (ywwg) [inline src/engine/enginebuffer.h:75]: thanks :)

**Review by ywwg — APPROVED** [review]
looks great, thank you!

**Comment by daschuer** [comment]
Done

**Comment by daschuer** [comment]
@ywwg Can you merge this?

**Review by ywwg — APPROVED** [review]

**Comment by ywwg** [comment]
success! thanks for the direct ping I know it's an annoying extra step
