### PR TITLE
(fix UX) Library: add feedback to directory operations (add, remove, relink)

### LINKED ISSUE #10481: improve UX when encountering missing/invalid library directory
Reported by: **[ronso0](https://github.com/ronso0)**
Date: 2021-07-23T16:45:10Z
Status: New
Importance: Undecided
Launchpad Issue: [lp1937851](https://bugs.launchpad.net/bugs/1937851)
Tags: library, usability

---

Amongst others, my library contains a folder on an external drive.
That drive was not mounted when I wanted to add a subfolder of my home directory. Adding was refused, message says it's already in the library or the library is being scanned. Neither was true.
That was driving me crazy so I removed all watched folders to finally  figur it's failing due to the unmounted drive :\

the message
https://github.com/mixxxdj/mixxx/blob/3546054e299956a952c1fb1b7855e95e5f2be200/src/library/library.cpp#L504-L509

caused by
https://github.com/mixxxdj/mixxx/blob/3546054e299956a952c1fb1b7855e95e5f2be200/src/library/dao/directorydao.cpp#L68

Though the logged line is clear about the cause:
> Aborting to add QFileInfo(/home/abc/Music/mmumu) : Loaded directory QFileInfo(/mnt/yxo/audio) does not exist or is inaccessible

After closing the dialog and hitting Apply in the preferences Mixxx says "one or more directories were added... Rescan / Cancel"
Also wrong.

1) can `DirectoryDAO::AddResult` be passed through to the requester so that we can have explicit error messages?

2) Why is a missing directory hindering the addition of others in the first place? I'm aware the dir is missing, that was the reason to add another track source ;)

### PR DESCRIPTION
**Pull request by ronso0**
This improves user feedback for library directory action in Library preferences (add, relink, remove) and when adding a directory in the Computer feature by showing appropriate message popups.

Fixes #10481

### CODE REVIEW

File: src/library/dao/directorydao.h [hunk 1]
```diff
@@ -28,8 +29,14 @@ class DirectoryDAO : public DAO {
     };
     RemoveResult removeDirectory(const mixxx::FileInfo& oldDir) const;
 
+    enum class RelocateResult {
+        Ok,
+        InvalidOrMissingDirectory,
+        UnreadableDirectory,
+        SqlError,
+    };
```
Comment (ronso0) [inline src/library/dao/directorydao.h:37]: To reduce tr strings for the dialogs we could merge all `~Result` types and forward them to a dialog function in Library.

File: src/library/dao/directorydao.h [hunk 2]
```diff
@@ -28,8 +29,14 @@ class DirectoryDAO : public DAO {
...
     // TODO: Move this function out of the DAO
-    QList<RelocatedTrack> relocateDirectory(
+    std::pair<RelocateResult, QList<RelocatedTrack>> relocateDirectory(
```
Comment (ronso0) [inline src/library/dao/directorydao.h:39]: This could also be a struct to make it more compact, but that appearantly that requires some extras to make it work with `std::tie` in TrackCollection.
Didn't test it.
```c++
struct RelocateResult {
    Result result;
    QList<RelocatedTrack> trackList;
    template<typename T, typename U>
    operator std::tuple<T, U>();
};
```

**Review by acolombier — APPROVED** [review]
Tested and working as expected on PopOS 22.04/Wayland!

**Comment by ronso0** [comment]
I rebased onto main to resolve the conflicts (should have merged main instead : | ).
@acolombier If you have I'd appreciate if you'd test again.

**Comment by ronso0** [comment]
argh, missed some comments.

I'll revert to last good state and merge main.

**Comment by ronso0** [comment]
Done.

**Comment by daschuer** [comment]
Oh sorry, a conflict has developed after @acolombier review.
