### PR TITLE
Crates: only store or activate sibling crate if it's valid

### LINKED ISSUE #11769: Debug Assert if I delete the last existing Crate
### Bug Description

grafik

<details>
<summary>Stacktrace</summary>
```
mixxx.exe!mixxx::`anonymous namespace'::handleMessage(QtMsgType type=QtCriticalMsg, const QMessageLogContext & context={...}, const QString & input={...}) Line 355
	at C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\util\logging.cpp(355)
[External Code]
mixxx.exe!mixxx_debug_assert(const char * assertion=0x00007ff681dec0d8, const char * file=0x00007ff681dec060, int line=320, const char * function=0x00007ff681debf98) Line 10
	at C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\util\assert.h(10)
mixxx.exe!mixxx_debug_assert_return_true(const char * assertion=0x00007ff681dec0d8, const char * file=0x00007ff681dec060, int line=320, const char * function=0x00007ff681debf98) Line 19
	at C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\util\assert.h(19)
mixxx.exe!CrateFeature::activateCrate(CrateId crateId={...}) Line 320
	at C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\library\trackset\crate\cratefeature.cpp(320)
mixxx.exe!CrateFeature::slotCrateTableChanged(CrateId crateId={...}) Line 882
	at C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\library\trackset\crate\cratefeature.cpp(882)
mixxx.exe!QtPrivate::FunctorCall<QtPrivate::IndexesList<0>,QtPrivate::List<CrateId>,void,void (__cdecl CrateFeature::*)(CrateId)>::call(void(CrateFeature::*)(CrateId) f=0x00007ff68093528e, CrateFeature * o=0x000001a54e0295d0, void * * arg=0x0000002a75d5f738) Line 152
	at C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-61b0d50\installed\x64-windows\include\qt5\QtCore\qobjectdefs_impl.h(152)
mixxx.exe!QtPrivate::FunctionPointer<void (__cdecl CrateFeature::*)(CrateId)>::call<QtPrivate::List<CrateId>,void>(void(CrateFeature::*)(CrateId) f=0x00007ff68093528e, CrateFeature * o=0x000001a54e0295d0, void * * arg=0x0000002a75d5f738) Line 186
	at C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-61b0d50\installed\x64-windows\include\qt5\QtCore\qobjectdefs_impl.h(186)
mixxx.exe!QtPrivate::QSlotObject<void (__cdecl CrateFeature::*)(CrateId),QtPrivate::List<CrateId>,void>::impl(int which=1, QtPrivate::QSlotObjectBase * this_=0x000001a55b12b220, QObject * r=0x000001a54e0295d0, void * * a=0x0000002a75d5f738, bool * ret=0x0000000000000000) Line 419
	at C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-61b0d50\installed\x64-windows\include\qt5\QtCore\qobjectdefs_impl.h(419)
[External Code]
mixxx.exe!TrackCollection::crateDeleted(CrateId _t1={...}) Line 423
	at C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\build\x64__off\mixxx-lib_autogen\include\moc_trackcollection.cpp(423)
mixxx.exe!TrackCollection::deleteCrate(CrateId crateId={...}) Line 470
	at C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\library\trackcollection.cpp(470)
mixxx.exe!CrateFeature::slotDeleteCrate() Line 456
	at C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\library\trackset\crate\cratefeature.cpp(456)
mixxx.exe!QtPrivate::FunctorCall<QtPrivate::IndexesList<>,QtPrivate::List<>,void,void (__cdecl CrateFeature::*)(void)>::call(void(CrateFeature::*)() f=0x00007ff68093304c, CrateFeature * o=0x000001a54e0295d0, void * * arg=0x0000002a75d5fe88) Line 152
	at C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-61b0d50\installed\x64-windows\include\qt5\QtCore\qobjectdefs_impl.h(152)
mixxx.exe!QtPrivate::FunctionPointer<void (__cdecl CrateFeature::*)(void)>::call<QtPrivate::List<>,void>(void(CrateFeature::*)() f=0x00007ff68093304c, CrateFeature * o=0x000001a54e0295d0, void * * arg=0x0000002a75d5fe88) Line 186
	at C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-61b0d50\installed\x64-windows\include\qt5\QtCore\qobjectdefs_impl.h(186)
mixxx.exe!QtPrivate::QSlotObject<void (__cdecl CrateFeature::*)(void),QtPrivate::List<>,void>::impl(int which=1, QtPrivate::QSlotObjectBase * this_=0x000001a55b12b4c0, QObject * r=0x000001a54e0295d0, void * * a=0x0000002a75d5fe88, bool * ret=0x0000000000000000) Line 419
	at C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-61b0d50\installed\x64-windows\include\qt5\QtCore\qobjectdefs_impl.h(419)
[External Code]
mixxx.exe!MixxxApplication::notify(QObject * target=0x0000002a75d67718, QEvent * event=0x0000002a75d61e30) Line 170
	at C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\mixxxapplication.cpp(170)
[External Code]
mixxx.exe!MixxxApplication::notify(QObject * target=0x000001a52b2905a0, QEvent * event=0x0000002a75d63bc0) Line 170
	at C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\mixxxapplication.cpp(170)
[External Code]
mixxx.exe!CrateFeature::onRightClickChild(const QPoint & globalPos={...}, const QModelIndex & index={...}) Line 416
	at C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\library\trackset\crate\cratefeature.cpp(416)
mixxx.exe!SidebarModel::rightClicked(const QPoint & globalPos={...}, const QModelIndex & index={...}) Line 363
	at C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\library\sidebarmodel.cpp(363)
mixxx.exe!QtPrivate::FunctorCall<QtPrivate::IndexesList<0,1>,QtPrivate::List<QPoint const &,QModelIndex const &>,void,void (__cdecl SidebarModel::*)(QPoint const &,QModelIndex const &)>::call(void(SidebarModel::*)(const QPoint &, const QModelIndex &) f=0x00007ff68094198f, SidebarModel * o=0x000001a55a3bb410, void * * arg=0x0000002a75d67cb8) Line 152
	at C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-61b0d50\installed\x64-windows\include\qt5\QtCore\qobjectdefs_impl.h(152)
mixxx.exe!QtPrivate::FunctionPointer<void (__cdecl SidebarModel::*)(QPoint const &,QModelIndex const &)>::call<QtPrivate::List<QPoint const &,QModelIndex const &>,void>(void(SidebarModel::*)(const QPoint &, const QModelIndex &) f=0x00007ff68094198f, SidebarModel * o=0x000001a55a3bb410, void * * arg=0x0000002a75d67cb8) Line 186
	at C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-61b0d50\installed\x64-windows\include\qt5\QtCore\qobjectdefs_impl.h(186)
mixxx.exe!QtPrivate::QSlotObject<void (__cdecl SidebarModel::*)(QPoint const &,QModelIndex const &),QtPrivate::List<QPoint const &,QModelIndex const &>,void>::impl(int which=1, QtPrivate::QSlotObjectBase * this_=0x000001a51946c1a0, QObject * r=0x000001a55a3bb410, void * * a=0x0000002a75d67cb8, bool * ret=0x0000000000000000) Line 419
	at C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-61b0d50\installed\x64-windows\include\qt5\QtCore\qobjectdefs_impl.h(419)
[External Code]
mixxx.exe!WLibrarySidebar::rightClicked(const QPoint & _t1={...}, const QModelIndex & _t2={...}) Line 196
	at C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\build\x64__off\mixxx-lib_autogen\include\moc_wlibrarysidebar.cpp(196)
mixxx.exe!WLibrarySidebar::contextMenuEvent(QContextMenuEvent * event=0x0000002a75d69e98) Line 46
	at C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\widget\wlibrarysidebar.cpp(46)
[External Code]
mixxx.exe!MixxxApplication::notify(QObject * target=0x000001a5193dd660, QEvent * event=0x0000002a75d69e98) Line 170
	at C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\mixxxapplication.cpp(170)
[External Code]
mixxx.exe!MixxxApplication::notify(QObject * target=0x000001a546ba5480, QEvent * event=0x0000002a75d6ba30) Line 170
	at C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\mixxxapplication.cpp(170)
[External Code]
mixxx.exe!`anonymous namespace'::runMixxx(MixxxApplication * pApp=0x0000002a75d6f998, const CmdlineArgs & args={...}) Line 82
	at C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\main.cpp(82)
mixxx.exe!main(int argc=1, char * * argv=0x000001a53af90db0) Line 213
	at C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\main.cpp(213)
[External Code]
```
</details>

### Version

2.4.0 Beta

### OS

Windows 11

### PR DESCRIPTION
**Pull request by ronso0**
Close #11769

### CODE REVIEW

File: src/library/trackset/crate/cratefeature.cpp [hunk 1]
```diff
@@ -877,7 +880,9 @@ void CrateFeature::slotCrateTableChanged(CrateId crateId) {
         if (!activateCrate(m_crateTableModel.selectedCrate())) {
             // probably last clicked crate was deleted, try to
             // select the stored sibling
-            activateCrate(m_prevSiblingCrate);
+            if (m_prevSiblingCrate.isValid()) {
+                activateCrate(m_prevSiblingCrate);
```
Comment (daschuer) [inline src/library/trackset/crate/cratefeature.cpp:884]: This seems to be the fix, right?

File: src/library/trackset/crate/cratefeature.cpp [hunk 2]
```diff
@@ -862,7 +862,10 @@ void CrateFeature::storePrevSiblingCrateId(CrateId crateId) {
             TreeItem* pTreeItem = m_pSidebarModel->getItem(newIndex);
             DEBUG_ASSERT(pTreeItem != nullptr);
             if (!pTreeItem->hasChildren()) {
-                m_prevSiblingCrate = crateIdFromIndex(newIndex);
+                CrateId prevCrateId = crateIdFromIndex(newIndex);
+                if (prevCrateId.isValid()) {
```
Comment (daschuer) [inline src/library/trackset/crate/cratefeature.cpp:866]: I did a look around and I have not yet understand in which cases it can be invalid at all? Does this case source from another bug deeper in the code? Can we have children with invalid crates? Please add a comment to the code.

Idea: The loop can be reversed and exited early with break. That would make the "search for one sibling" nature more clear.

**Review by daschuer — CHANGES_REQUESTED** [review]
Thank you fort the fix and the fast responds. 
I have not tested it yet, just some comments.

File: src/library/trackset/crate/cratefeature.cpp (hunk 1 above)
Comment (daschuer) [reply src/library/trackset/crate/cratefeature.cpp:884]: This code is also in place at 2.3. 
Does this crash happen in 2.3 as well?

File: src/library/trackset/crate/cratefeature.cpp (hunk 2 above)
Comment (ronso0) [reply src/library/trackset/crate/cratefeature.cpp:866]: True, this is excessive. The check in `activateCrate()` is sufficient.
I'll revert this.

**Comment by daschuer** [comment]
Thank you. Is this a 2.3 PR then? 
@JoergAtGithub does thit fix you issue?

**Comment by daschuer** [comment]
Oh nevermind, just read you commend at the bug report.

**Review by daschuer — APPROVED** [review]
LGTM
