### PR TITLE
(fix) adjust Gain after adopting it as ReplayGain only in requesting player

### LINKED ISSUE #14806: Issue with samples when change replaygain
### Bug Description

I think I have found an issue with samples when you change the replaygain:

Load track as a sample
Load track into deck.
Change deck gain, and apply “Update Replaygain from Deck Gain”.
Track shows updated replaygain value in properties – this is the case whether look at properties of the track via right click and properties on the deck, in the library or from the sample.
Track plays at correct new volume in decks. This includes if eject and add back in to initial deck, or if add to a different deck.
Track does not play at correct new volume if selected from sample.
If replace sample with the same (updated) track from library does not play at new volume, still at old volume before adjust.
If eject track from sample and then replace with same track still does not play at correct new volume.
If shut down and restart Mixxx the track plays at correct new volume from sample.
If place track in a different sample position, either within same bank of samples or a different bank of samples it plays at the correct new volume. So it seems to be tied to that particular sample position and only until Mixxx is restarted.

### Version

2.6 Beta

### OS

Windows 11

### PR DESCRIPTION
**Pull request by ronso0**
Fixes #14806

### The issue:
if a track's ReplayGain is adjusted, all players that have it loaded adjust the Gain knob so that the effective gain remains unchanged. I guess this is supposed to prevent sudden volume changes in case that track is being played in other decks, besides the one where the ReplayGain was adjusted. While this seems okay for main decks where the Gain knob is _usually_ visible, it has unpleasant side effects (samplers, preview deck, see #14806) and users have little chance to fix it.

I think we should drop this.
If users decide to adjust the ReplayGain while playing a track, they need to be aware of the effect.
And I guess this lesson is learned quickly ; )

### The fix:
Adjust gain only the requesting player.
The requesting player group string is passed around so that only the requester adjusts the Gain knob.

When invoked via CO, BaseTrackPlayer(Impl) could as well send a pointer to itself, but ReplayGain can also be adjusted via WTrackMenu which acts on the Track directly (and has and should have no knowledge about the actual player) I decided to use the group string.

### CODE REVIEW

File: src/mixer/basetrackplayer.cpp [hunk 1]
```diff
@@ -798,19 +798,26 @@ void BaseTrackPlayerImpl::slotSetReplayGain(mixxx::ReplayGain replayGain) {
     }
 }
 
-void BaseTrackPlayerImpl::slotAdjustReplayGain(mixxx::ReplayGain replayGain) {
+void BaseTrackPlayerImpl::slotAdjustReplayGain(
+        mixxx::ReplayGain replayGain, const QString& requetingPlayerGroup) {
```
Comment (daschuer) [inline src/mixer/basetrackplayer.cpp:802]:
```suggestion
        mixxx::ReplayGain replayGain, const QString& requestingPlayerGroup) {
```

File: src/test/replaygaintest.cpp [hunk 2]
```diff
@@ -179,13 +179,12 @@ TEST_F(AdjustReplayGainTest, AdjustReplayGainUpdatesPregain) {
     ControlObject::getControl(ConfigKey(m_sGroup1, "pregain"))->set(1.2);
     ControlObject::getControl(ConfigKey(m_sGroup1, "update_replaygain_from_pregain"))->set(1.0);
 
-    // The pregain value is folded into the replaygain value, and all pregains for all decks that
-    // have the same track loaded are adjusted so that the audible volume of the track does not
-    // change.
+    // The pregain value is folded into the replaygain value, and pregains is reset
+    // for the deck where the adjust control was triggered so that the audible volume
+    // of the track does not change.
+    // Pregain should not change o other decks with this track loaded.
```
Comment (daschuer) [inline src/test/replaygaintest.cpp:185]:
```suggestion
    // Pregain should not change other decks with this track loaded.
```

**Review by daschuer — APPROVED** [review]
LGTM, Thank you.
