### PR TITLE
Fix crash when hiding waveforms in Deere

### LINKED ISSUE #14157: Crash when minimising waveforms section
### Bug Description

**Steps to reproduce**
1. Load any track(s) in any deck(s). **edit(@ronso0)**: a marker must be visible in the waveform (eg. a hotcue, with Cue alone it won't  crash)
2. Grab the bottom edge of parallel waveforms section with mouse click, drag to top to minimise it.
3. Mixxx instantly hang and then crash. Every time

I can enlarge the section and then make it smaller back with no issue. But dragging the edge up to the point it would disappear cause the bug.

This was first spotted on **2.4.1.** Updated to **2.4.2** to still get the bug. Updated to **2.5.0** and the bug is still there.

**Related settings:**
Skin: Deere, 4 decks, Waveform type: Filtered (GLSL)

### Version

2.5.0

### OS

Windows 10 Pro 22H2

### PR DESCRIPTION
**Pull request by daschuer**
This fixes #14157

### CODE REVIEW

File: src/waveform/renderers/waveformmark.cpp [hunk 1]
```diff
@@ -335,7 +335,7 @@ class MarkerGeometry {
 };
 
 QImage WaveformMark::generateImage(float devicePixelRatio) {
-    assert(needsImageUpdate());
+    DEBUG_ASSERT(needsImageUpdate());
```
Comment (ronso0) [inline src/waveform/renderers/waveformmark.cpp:338]: VERIFY_OR_DEBUG_ASSERT ?
IIUC all below would be a no-op otherwise, right?

File: src/waveform/renderers/allshader/waveformrendermark.cpp [hunk 2]
```diff
@@ -383,20 +388,22 @@ void allshader::WaveformRenderMark::drawUntilMark(const QMatrix4x4& matrix, floa
 // Note that in the legacy waveform widgets this is drawn directly
 // in the WaveformWidgetRenderer itself. Doing it here is cleaner.
 void allshader::WaveformRenderMark::updatePlayPosMarkTexture() {
-    float imgwidth;
-    float imgheight;
+    const float imgheight = m_waveformRenderer->getBreadth();
+    const float imgwidth = 11.f;
```
Comment (ronso0) [inline src/waveform/renderers/allshader/waveformrendermark.cpp:392]:
```suggestion
    const float imgHeight = m_waveformRenderer->getBreadth();
    const float imgWidth = 11.f;
```
and where used, of course.

File: src/waveform/renderers/allshader/waveformrendermark.cpp [hunk 3]
```diff
@@ -383,20 +388,22 @@ void allshader::WaveformRenderMark::drawUntilMark(const QMatrix4x4& matrix, floa
...
 
-    imgwidth = 11.f;
-    imgheight = height;
-
     QImage image(static_cast<int>(imgwidth * devicePixelRatio),
             static_cast<int>(imgheight * devicePixelRatio),
             QImage::Format_ARGB32_Premultiplied);
+    if (image.isNull()) {
+        return;
+    }
```
Comment (ronso0) [inline src/waveform/renderers/allshader/waveformrendermark.cpp:406]: imgWidth is < 0 and there is already a check for `imgHeight != 0` above, so this can only be NULL if devicePixelRatio is 0.
Can this ever happen?

File: src/waveform/renderers/waveformmark.cpp [hunk 4]
```diff
@@ -355,11 +377,14 @@ QImage WaveformMark::generateImage(float devicePixelRatio) {
...
 
-    m_label.setAreaRect(markerGeometry.m_labelRect);
+    m_label.setAreaRect(markerGeometry.labelRect());
 
     // Create the image
     QImage image{markerGeometry.getImageSize(devicePixelRatio),
             QImage::Format_ARGB32_Premultiplied};
+    if (image.isNull()) {
+        return image;
+    }
```
Comment (ronso0) [inline src/waveform/renderers/waveformmark.cpp:387]: how can that happen?
There is already the `m_breadth == 0.0f` above.

**Review by ronso0 — CHANGES_REQUESTED** [review]

File: src/waveform/renderers/allshader/waveformrendermark.cpp (hunk 3 above)
Comment (daschuer) [reply src/waveform/renderers/allshader/waveformrendermark.cpp:406]: When looking at the Qt source, there are other reasons like out of memory or such. All can't probably not happen but this saves Mixxx from crash if it happen anyway. I think a 
VERIFY_OR_DEBUG_ASSERT is a good choice.

**Comment by ronso0** [comment]
FWIW since this happens only with Deere (which is the only skin that uses waveform Singletons), I assume this is an issue with WSplitter/QSplitter and Singleton, like when the waveform part of the splitter is collapsed the waveform is not hidden or something?

File: src/waveform/renderers/waveformmark.cpp (hunk 1 above)
Comment (daschuer) [reply src/waveform/renderers/waveformmark.cpp:338]: Yes, but we assert that it never happens and when it happens, it does no harm.

**Comment by daschuer** [comment]
> like when the waveform part of the splitter is collapsed the waveform is not hidden or something?

Yes, the widget is sized to 1 before it is hidden due to the border the images have 0 height, which has caused the crash.

**Comment by daschuer** [comment]
Done

**Comment by ronso0** [comment]
Ah, now I could reproduce the crash: you need to have one or more hotcue markers visible in waveform.

Can confirm the fix :+1:

**Review by ronso0 — APPROVED** [review]
LGTM, thanks for this fix!
