### PR TITLE
Reintroduce QML on 2.7 alpha

### LINKED ISSUE #15437: Remove the `--qml` flag
### Bug Description

I am not able to start Mixxx 2.6 with experimental QML GUI. 

This is the log: 
```
Cannot connect to server socket err = Datei oder Verzeichnis nicht gefunden
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
critical [Main] Error setting up sound devices: 2
```

### Version

2.6-beta

### OS

_No response_

### PR DESCRIPTION
**Pull request by acolombier**
~This addresses #15437 and~ honour the [agreed plan](https://github.com/mixxxdj/mixxx/pull/14772#issuecomment-2891273221) regarding QML feature on `main`

### CODE REVIEW

File: src/util/cmdlineargs.cpp [hunk 1]
```diff
@@ -280,10 +281,20 @@ bool CmdlineArgs::parse(const QStringList& arguments, CmdlineArgs::ParseMode mod
     parser.addOption(developer);
 
 #ifdef MIXXX_USE_QML
-    const QCommandLineOption qml(QStringLiteral("qml"),
-            forUserFeedback ? QCoreApplication::translate("CmdlineArgs",
-                                      "Loads experimental QML GUI instead of legacy QWidget skin")
-                            : QString());
+    const QCommandLineOption qml(QStringLiteral("next"),
```
Comment (Holzhaus) [inline src/util/cmdlineargs.cpp]: I was not involved in the discussion, but isn't `--next` even more cryptic? Could basically mean everything (e.g., "play next track").

If you think it's too technical, maybe consider `--new-user-interface` or something like that?

Also, keep in mind that contributors will likely still use the term "QML" to refer to the new UI, so I am wondering if it's really that cryptic after all.

I'm happy with whatever name you think fits, I just wanted to point this out.

Comment (acolombier) [reply src/util/cmdlineargs.cpp]: Yeah, that's a good shout, I didn't think of the "Next" in the context of a player which is very relevant to Mixxx. I think `--new-user-interface` is a good shout!
> Also, keep in mind that contributors will likely still use the term "QML" to refer to the new UI, so I am wondering if it's really that cryptic after all.

Note that `--qml` will continue working, at least for some time! But technically, this remains implementation details; the fact that contributors or technical-aware people continue referencing it is this way is fine tho - I surely will continue calling it QML :) 

However, for less technical user, this feels unnecessary confusing, especially now that QML is also used in the legacy UI (for controller offscreen rendering)

**Comment by JoergAtGithub** [comment]
Could you please split this PR, that we can re-enable QML independend of the renaming discussion.

**Comment by acolombier** [comment]
Sure, will do asap.

Edit: done!

File: src/util/cmdlineargs.cpp (hunk 1 above)
Comment (acolombier) [reply src/util/cmdlineargs.cpp]: Moving to #15596

**Review by JoergAtGithub — APPROVED** [review]
LGTM! Thank you!
