### PR TITLE
Fix cue points being assigned invalid value of -1.0

### LINKED ISSUE #10993: Cue positions at ~-1.0 are "invalid"
### Bug Description

I noticed that in two of my tracks, the main cue point was not working.  After some debugging, I discovered this is because the cue position rounds to -1.0, and in frame.h, -1.0 is the "kLegacyInvalidEnginePosition".  Therefore the cue is considered invalid and ignored.  It's not even possible to set a new cue position without using Reset / Cue Point.  With some tracks, because of beat grid adjustments it is plausible that the main cue point is actually in the silence before the start.  (I have some where it is an entire beat or two before the start.)  In this case, it is very very close to 1 frame before the start, at position -1.049180327871.

Do we still need this invalid position value check?  The comments mention backwards compatibility but it's not clear what situations this is needed.  Could NaN or -INF be used instead?

In the meantime I can tweak the beatgrid of these tracks to avoid the problem.

### Version

main branch

### OS

Ubuntu 22.04

### PR DESCRIPTION
**Pull request by ywwg**
Fixes two issues in cue point creation:
* cue point positions are stored as doubles, not ints, so they should be loaded that way from the db.
* in the conversion to engine sample position, avoid creating invalid -1.0 values.

Fixes https://github.com/mixxxdj/mixxx/issues/10993

### CODE REVIEW

**Comment by ywwg** [comment]
Sister fix of https://github.com/mixxxdj/mixxx/pull/10998

**Comment by ywwg** [comment]
verified this fixes the issue with my problem tracks.  In very very very rare cases a user might have a cue point set at exactly -1.0 frame, in which case they should right click the track and select Reset / Cue Point and when they create it it will work correctly.

**Review by daschuer — APPROVED** [review]
Great, that looks like a good minimum impact fix.  

I have just tested to create a Cue point at a fractional position but without success. 
Even though I have such fractional Cue points already in my library. Did we re-add rounding to a full frame when storing cue points at one point?

**Comment by daschuer** [comment]
Got it: The column is set to int and it is read back as int
https://github.com/mixxxdj/mixxx/blob/074c938834643b5edcea66c09482e90e1d5204fc/src/library/dao/cuedao.cpp#L46

The maincue is written and read as double: 
https://github.com/mixxxdj/mixxx/blob/074c938834643b5edcea66c09482e90e1d5204fc/src/library/dao/trackdao.cpp#L1170
https://github.com/mixxxdj/mixxx/blob/074c938834643b5edcea66c09482e90e1d5204fc/src/library/dao/trackdao.cpp#L563

We need to check how a shifted cue is handled in a database round-trip.

**Comment by Holzhaus** [comment]
> In very very very rare cases a user might have a cue point set at exactly -1.0 frame

You mean at -0.5 frame = -1.0 sample, right?

**Review by daschuer — CHANGES_REQUESTED** [review]
The near -1 cue must not become -1 after reading back from the library.

File: src/audio/frame.h [hunk 1]
```diff
@@ -44,7 +44,15 @@ class FramePos final {
...
     double toEngineSamplePos() const {
         DEBUG_ASSERT(isValid());
-        return value() * mixxx::kEngineChannelCount;
+        double engineSamplePos = value() * mixxx::kEngineChannelCount;
+        // In the rare but possible instance that the position is valid but
+        // the engine sample position is exactly -1.0, we nudge the position
+        // because otherwise fromEngineSamplePosMaybeInvalid() will think
+        // the position is invalid.
+        if (engineSamplePos == kLegacyInvalidEnginePosition) {
+            return kLegacyInvalidEnginePosition - .0001;
```
Comment (Holzhaus) [inline src/audio/frame.h:53]: This is eeaser to read IMHO:

```suggestion
            return kLegacyInvalidEnginePosition - 0.0001;
```

**Review by Holzhaus — APPROVED** [review]
Code looks good, did not have time to test though.

**Comment by ywwg** [comment]
Cue points are currently written as double and read as int.  This PR fixes that so they are read back as doubles.

https://github.com/mixxxdj/mixxx/blob/main/src/library/dao/cuedao.cpp#L172

**Comment by ywwg** [comment]
> The near -1 cue must not become -1 after reading back from the library.

The toInt was causing this.  By changing it to doubles, this is fixed

**Comment by Holzhaus** [comment]
> Cue points are currently written as double and read as int.  This PR fixes that so they are read back as doubles.
> 
> https://github.com/mixxxdj/mixxx/blob/b071d6ecf67afd8353430f1df51844d54510b5cd/src/library/dao/cuedao.cpp#L172

The DB schema says the column is an int. If we really want to store fractional cue positions in the DB, we need a schema migration IMHO. I know it works without it, because SQLite does not enforce column types by default, but marking the column as int and then storing a different type is really confusing IMHO.

**Comment by ywwg** [comment]
yeah I'm ok adding a db schema migration.  I think that's out of scope for 2.3 though... I'd prefer to let the schema be broken in that version since it works fine, rather than surprise users with a schema difference in a "stable" version.  Is that ok?

**Review by daschuer — APPROVED** [review]
LGTM. The question of the schema migration is orthogonal to this PR, because we already store frictional cues in the in column. Here we only read and fix the wrong int rounding.
@Holzhaus: merge?

**Comment by daschuer** [comment]
We have also the question whether a default is appropriated, moved from:
https://github.com/mixxxdj/mixxx/pull/10998#issuecomment-1290378253
https://github.com/mixxxdj/mixxx/pull/10998#issuecomment-1301585279

```sql
      CREATE TABLE IF NOT EXISTS cues (
        ...
        position INTEGER DEFAULT -1 NOT NULL,
        length INTEGER DEFAULT 0 NOT NULL,
        ...
```

I think no, because we will never add a cue with an invalid position, or do I miss something?

**Comment by daschuer** [comment]
Reading the sqlite docs: https://www.sqlite.org/flextypegood.html 
We may argue that the Type "INTEGER" is just correct, because we want to store the "INTEGER" -1 and the "REAL" double position. So we may ditch the schema migration completely.
Since this is still a source of confusion we should place a big warning at here explaining our decision, with a reference to the sqlite manual, here: https://github.com/mixxxdj/mixxx/blob/main/res/schema.xml#L83 
@ywwg can you do this in in this PR? 

The other issue that should also be fixed in this PR that the "length" column should be also read as double.
This can be also done in this PR.

**Review by daschuer — CHANGES_REQUESTED** [review]
Please add a comment at schema.xml and apply the fix to "length" as well.

**Comment by daschuer** [comment]
A good reason for the column migration would be the move from our stereo sample based format to an frame based format. Introducing another lstalkec egacy column for that would be  odd. We have also discussed to use sample rate independent format ... Not sure about that though.

**Comment by ywwg** [comment]
sqlite does not support changing column type:
https://sqlite.org/lang_altertable.html
https://stackoverflow.com/questions/2083543/modify-a-columns-type-in-sqlite3

so this migration would require:
1. Create a new clean table with the correct types
2. Copy all of the data from the old track table to the new one
3. delete the old track table
4. (hope we don't crash here)
5. rename the new track table to the proper track table name.

Is that really worth the trouble?  I think I would prefer to add annotations to the code.  Since SQLite is well known for not having strict types, it doesn't seem like a big deal that this is wrong.

File: src/library/dao/cuedao.cpp [hunk 2]
```diff
@@ -43,7 +43,7 @@ CuePointer cueFromRow(const QSqlRecord& row) {
     int type = row.value(row.indexOf("type")).toInt();
     const auto position =
             mixxx::audio::FramePos::fromEngineSamplePosMaybeInvalid(
-                    row.value(row.indexOf("position")).toInt());
+                    row.value(row.indexOf("position")).toDouble());
     int lengthFrames = row.value(row.indexOf("length")).toInt() / mixxx::kEngineChannelCount;
```
Comment (daschuer) [inline src/library/dao/cuedao.cpp:47]:
```suggestion
    FrameDiff_t lengthFrames = row.value(row.indexOf("length")).toDouble() / mixxx::kEngineChannelCount;
```

**Review by daschuer — CHANGES_REQUESTED** [review]

File: src/library/dao/cuedao.cpp [hunk 3]
```diff
@@ -44,7 +44,7 @@ CuePointer cueFromRow(const QSqlRecord& row) {
     const auto position =
             mixxx::audio::FramePos::fromEngineSamplePosMaybeInvalid(
                     row.value(row.indexOf("position")).toDouble());
-    int lengthFrames = row.value(row.indexOf("length")).toInt() / mixxx::kEngineChannelCount;
+    FrameDiff_t lengthFrames = row.value(row.indexOf("length")).toDouble() / mixxx::kEngineChannelCount;
```
Comment (Holzhaus) [inline src/library/dao/cuedao.cpp:47]: `‘FrameDiff_t’ was not declared in this scope; did you mean ‘mixxx::audio::FrameDiff_t’?`

Comment (ywwg) [reply src/library/dao/cuedao.cpp]: fixed

**Comment by ywwg** [comment]
With the update from 2.3 this now just includes the comment in the schema about double values, and the check to ensure cuepoints are not created at exactly -1.0

**Review by daschuer — APPROVED** [review]
LGTM, Thank you. 
 
Since you have debased anyway, can you rebase this to main and get rid of the not working commit?

**Comment by daschuer** [comment]
Thank you.
