### PR TITLE
Sandbox: Fix regression that caused `Sandbox::canAccess` to fail

### LINKED ISSUE #12137: Mixxx seeking access permission form iTunes Media folder on every launch
### Bug Description

Each time I launch Mixxx 2.4 beta it is seeking access permission to the iTunes Media folder.It's not retaining permissions.

### Version

2.4

### OS

Mac OS 10.14.6

### PR DESCRIPTION
**Pull request by fwcd**
### Fixes #12137 (and #11552)

This fixes a regression with macOS sandboxing introduced in #3761 that caused `Sandbox::canAccess` to always fail and to wrongly present this dialog on every launch:

image

The issue was that the token is not assigned to a variable and thus immediately deinitialized (and invalidated):

```cpp
bool Sandbox::canAccess(mixxx::FileInfo* pFileInfo) {
    ...
    openSecurityToken(pFileInfo, true); // Token is invalidated immediately
    return pFileInfo->isReadable();     // therefore this may wrongly return false!
}
```

See https://github.com/mixxxdj/mixxx/pull/3761#issuecomment-1867131495 for details. To avoid regressing on this in the future, I have added a `[[nodiscard]]` to the `openSecurityToken` methods, which will generate a warning if used like this again.

### CODE REVIEW

**Comment by JoergAtGithub** [comment]
Doesn't the compiler optimize this unused variable away?

**Comment by Holzhaus** [comment]
> Doesn't the compiler optimize this unused variable away?

I think not. We also use RAII and there the unused variable is not optimized away either. But in any case we should probably mark the token with `Q_UNUSED` or something?

File: src/util/sandbox.h [hunk 1]
```diff
@@ -53,8 +53,14 @@ class Sandbox {
...
-    static SecurityTokenPointer openSecurityToken(mixxx::FileInfo* pFileInfo, bool create);
-    static SecurityTokenPointer openSecurityTokenForDir(const QDir& dir, bool create);
+    [[nodiscard(
+            "A new security token should be assigned to a variable, otherwise "
+            "it will be invalidated immediately.")]] static SecurityTokenPointer
+    openSecurityToken(mixxx::FileInfo* pFileInfo, bool create);
+    [[nodiscard(
+            "A new security token should be assigned to a variable, otherwise "
+            "it will be invalidated immediately.")]] static SecurityTokenPointer
+    openSecurityTokenForDir(const QDir& dir, bool create);
```
Comment (daschuer) [inline src/util/sandbox.h:63]: This fails unfortunately on Ubuntu Focal  
```
src/util/sandbox.h:59:62: error: wrong number of arguments specified for ‘nodiscard’ attribute
   59 |     openSecurityToken(mixxx::FileInfo* pFileInfo, bool create);
      |   
```

This works: 

```suggestion
#if defined(__GNUC__) && __cplusplus < 201907L
#define RATIONAL
#else
#define RATIONAL                                                            \
    ("A new security token should be assigned to a variable, otherwise it " \
     "will be invalidated immediately.")
#endif

    [[nodiscard RATIONAL]] static SecurityTokenPointer openSecurityToken(
            mixxx::FileInfo* pFileInfo, bool create);
    [[nodiscard RATIONAL]] static SecurityTokenPointer openSecurityTokenForDir(
            const QDir& dir, bool create);
```

**Review by daschuer — CHANGES_REQUESTED** [review]

**Comment by daschuer** [comment]
I think we have no issue with the variable being unused. It is a QSharedPointer<SandboxSecurityToken> which has a scope until the end of the function.

File: src/util/sandbox.h (hunk 1 above)
Comment (JoergAtGithub) [reply src/util/sandbox.h:63]: I don't think we should add workarounds for such old C++ language versions.
This is in line with our [Minimum requirements policy](https://github.com/mixxxdj/mixxx/wiki/Minimum-requirements-policy). The oldest supported Ubuntu version is currently 22.04.

Comment (daschuer) [reply src/util/sandbox.h:63]: This is no reason to drop Ubuntu Focal support on the last minute before the 2.4 release. 
The alternative would be to make the rational a comment. It will anyway never appear, because the bug is now fixed.

Comment (JoergAtGithub) [reply src/util/sandbox.h:63]: Than we should at least ensure, that this workaround get not merged into Main.

Comment (daschuer) [reply src/util/sandbox.h:63]: I will take care.

Comment (fwcd) [reply src/util/sandbox.h:63]: Nit: It should be "rationale"

Comment (fwcd) [reply src/util/sandbox.h:63]: > Than we should at least ensure, that this workaround get not merged into Main.

We could simply add a commit on `main` removing this workaround after the next 2.4 -> `main` merge. That should make sure that everything not touching those lines would merge cleanly in the future.

Comment (daschuer) [reply src/util/sandbox.h:63]: I have updated the suggestion.

**Review by Swiftb0y — APPROVED** [review]

File: src/util/sandbox.h [hunk 2]
```diff
@@ -53,17 +53,27 @@ class Sandbox {
         return createSecurityToken(dir.canonicalPath(), true);
     }
 
-    static SecurityTokenPointer openSecurityToken(mixxx::FileInfo* pFileInfo, bool create);
-    static SecurityTokenPointer openSecurityTokenForDir(const QDir& dir, bool create);
+#if defined(__GNUC__) && __cplusplus < 201907L
+#define RATIONALE
```
Comment (uklotzde) [inline src/util/sandbox.h:57]: Introducing a define with a generic name in a widely used header file is probably not a good idea.

Comment (fwcd) [reply src/util/sandbox.h]: I agree, I forgot this was the header and not the implementation file when I saw this. I've renamed it to `SECURITY_TOKEN_NODISCARD_RATIONALE`.

**Review by daschuer — APPROVED** [review]
Thank you. 2.4 is coming into sight!
