### PR TITLE
Fix iterator adjustment in Beats::iteratorFrom() (#13262)

### LINKED ISSUE #13262: DEBUG ASSERT: "it == cbegin() || it == cend() || *it >= position" in function class mixxx::Beats::ConstIterator __cdecl mixxx::Beats::iteratorFrom(class mixxx::audio::FramePos) const at src\track\beats.cpp:470
### Bug Description

Today I go with main and some other PR based on it the following assert, after very short time of playing with 4 synced decks:

```
 	[Inline Frame] mixxx.exe!mixxx_debug_assert(const char *) Line 9	C++
 	mixxx.exe!mixxx::Beats::iteratorFrom(mixxx::audio::FramePos position) Line 471	C++
 	mixxx.exe!mixxx::Beats::findNBeatsFromPosition(mixxx::audio::FramePos position, double beats) Line 501	C++
 	mixxx.exe!LoopingControl::hintReader(gsl::not_null<QVarLengthArray<Hint,512> *> pHintList) Line 591	C++
 	[Inline Frame] mixxx.exe!EngineBuffer::hintReader(const double) Line 1510	C++
 	mixxx.exe!EngineBuffer::processTrackLocked(float * pOutput=0xc0a53125b32dee8a, const int iBufferSize, mixxx::audio::SampleRate sampleRate) Line 1146	C++
 	mixxx.exe!EngineBuffer::process(float * pOutput=0x000002121549a0b0, const int iBufferSize) Line 1180	C++
 	mixxx.exe!EngineDeck::process(float * pOut=0x000002121549a0b0, const int iBufferSize) Line 65	C++
 	mixxx.exe!EngineMixer::processChannels(int iBufferSize) Line 370	C++
 	mixxx.exe!EngineMixer::process(const int iBufferSize) Line 430	C++
 	mixxx.exe!SoundDevicePortAudio::callbackProcessClkRef(const __int64 framesPerBuffer=1024, float * out=0x0000021232932160, const float * in=0x0000000000000000, const PaStreamCallbackTimeInfo * timeInfo=0x0000002b309ff7a8, unsigned long statusFlags=0) Line 998	C++
 	mixxx.exe!`anonymous namespace'::paV19CallbackClkRef(const void * inputBuffer, void * outputBuffer, unsigned long framesPerBuffer, const PaStreamCallbackTimeInfo * timeInfo, unsigned long statusFlags=0, void * soundDevice=0x00000212114788f0) Line 72	C++
 	portaudio.dll!NonAdaptingProcess(PaUtilBufferProcessor * bp=0x0000021236b764b8, int * streamCallbackResult=0x0000002b309ff7a4, PaUtilChannelDescriptor * hostInputChannels=0x0000000000000000, PaUtilChannelDescriptor * hostOutputChannels=0x00000212373f59b0, unsigned long framesToProcess=1024) Line 879	C
 	portaudio.dll!PaUtil_EndBufferProcessing(PaUtilBufferProcessor * bp=0x0000021236b764b8, int * streamCallbackResult=0x0000002b309ff7a4) Line 1591	C
 	portaudio.dll!WaspiHostProcessingLoop(void * inputBuffer=0x0000000000000000, long inputFrames=0, void * outputBuffer=0x0000021232932160, long outputFrames=1024, void * userData=0x0000021236b76450) Line 5168	C
 	portaudio.dll!ProcessOutputBuffer(PaWasapiStream * stream=0x0000021236b76450, PaWasapiHostProcessor * processor=0x0000002b309ff8b8, unsigned int frames=1024) Line 5771	C
 	portaudio.dll!ProcThreadPoll(void * param=0x0000021236b76450) Line 6397	C
 	ucrtbase.dll!thread_start<unsigned int (__cdecl*)(void *),1>()	Unknown
 	kernel32.dll!BaseThreadInitThunk()	Unknown
 	ntdll.dll!RtlUserThreadStart()	Unknown

```

<!DOCTYPE html>
<HTML>
<head>
<body>

  | Name | Value | Type
-- | -- | -- | --
◢ | this | 0x000002121a74fa50 {m_markers={ size=0 } m_lastMarkerPosition={m_framePosition=18107.000000000000 } ...} | const mixxx::Beats *
  | ▶ std::enable_shared_from_this<mixxx::Beats> | {_Wptr=empty } | std::enable_shared_from_this<mixxx::Beats>
  | ▶ m_markers | { size=0 } | std::vector<mixxx::BeatMarker,std::allocator<mixxx::BeatMarker>>
  | ▶ m_lastMarkerPosition | {m_framePosition=18107.000000000000 } | mixxx::audio::FramePos
  | ▶ m_lastMarkerBpm | {m_value=141.83333333333331 } | mixxx::Bpm
  | ▶ m_sampleRate | {m_value=44100 } | mixxx::audio::SampleRate
  | ▶ m_subVersion | "rounding=V4\|vamp_plugin_id=qm-tempotracker:0" | const QString
◢ | it | {m_value={m_framePosition=-548.69917743830956 } m_beats=0x000002121a74fa50 {m_markers={ size=0 } m_lastMarkerPosition=...} ...} | mixxx::Beats::ConstIterator
  | ◢ m_value | {m_framePosition=-548.69917743830956 } | mixxx::audio::FramePos
  | m_framePosition | -548.69917743830956 | double
  | ◢ m_beats | 0x000002121a74fa50 {m_markers={ size=0 } m_lastMarkerPosition={m_framePosition=18107.000000000000 } ...} | const mixxx::Beats *
  | ▶ std::enable_shared_from_this<mixxx::Beats> | {_Wptr=empty } | std::enable_shared_from_this<mixxx::Beats>
  | ▶ m_markers | { size=0 } | std::vector<mixxx::BeatMarker,std::allocator<mixxx::BeatMarker>>
  | ▶ m_lastMarkerPosition | {m_framePosition=18107.000000000000 } | mixxx::audio::FramePos
  | ▶ m_lastMarkerBpm | {m_value=141.83333333333331 } | mixxx::Bpm
  | ▶ m_sampleRate | {m_value=44100 } | mixxx::audio::SampleRate
  | ▶ m_subVersion | "rounding=V4\|vamp_plugin_id=qm-tempotracker:0" | const QString
  | ◢ m_it | <NULL> | std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<mixxx::BeatMarker>>>
  | ▶ [ptr] | 0x0000000000000000 <NULL> | mixxx::BeatMarker *
  | ▶ [Raw View] | {_Ptr=0x0000000000000000 <NULL> } | std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<mixxx::BeatMarker>>>
  | m_beatOffset | -1 | int

</body>
</HTML>

<!DOCTYPE html>
<HTML>
<head>
<body>

  | Name | Value | Type
-- | -- | -- | --
◢ | this | 0x00000212119d44c0 {m_pCOBeatLoopActivate=0x0000021214f3ccc0 {m_buttonMode=PUSH (0) m_iNoStates=2 } ...} | LoopingControl *
  | ▶ EngineControl | {m_group="[Channel4]" m_pConfig=strong reference to shared pointer of type "ConfigObject<ConfigValue>" ...} | EngineControl
  | ▶ m_pCOBeatLoopActivate | 0x0000021214f3ccc0 {m_buttonMode=PUSH (0) m_iNoStates=2 } | ControlPushButton *
  | ▶ m_pCOBeatLoopRollActivate | 0x0000021214f3c9c0 {m_buttonMode=PUSH (0) m_iNoStates=2 } | ControlPushButton *
  | ▶ m_pCOLoopStartPosition | 0x0000021214f3d4a0 {m_key={group="[Channel4]" item="loop_start_position" } m_pControl=strong reference to shared pointer of type "ControlDoublePrivate" } | ControlObject *
  | ▶ m_pCOLoopEndPosition | 0x0000021214f3db00 {m_key={group="[Channel4]" item="loop_end_position" } m_pControl=strong reference to shared pointer of type "ControlDoublePrivate" } | ControlObject *
  | ▶ m_pCOLoopEnabled | 0x0000021214f3cde0 {m_key={group="[Channel4]" item="loop_enabled" } m_pControl=strong reference to shared pointer of type "ControlDoublePrivate" } | ControlObject *
  | ▶ m_pCOLoopAnchor | 0x0000021214f3dbc0 {m_buttonMode=TOGGLE (1) m_iNoStates=2 } | ControlPushButton *
  | ▶ m_pLoopInButton | 0x0000021214f3b6a0 {m_buttonMode=PUSH (0) m_iNoStates=2 } | ControlPushButton *
  | ▶ m_pLoopInGotoButton | 0x0000021214f3b700 {m_buttonMode=PUSH (0) m_iNoStates=2 } | ControlPushButton *
  | ▶ m_pLoopOutButton | 0x0000021214f3b820 {m_buttonMode=PUSH (0) m_iNoStates=2 } | ControlPushButton *
  | ▶ m_pLoopOutGotoButton | 0x0000021214f3ba60 {m_buttonMode=PUSH (0) m_iNoStates=2 } | ControlPushButton *
  | ▶ m_pLoopExitButton | 0x0000021214f3bb80 {m_buttonMode=PUSH (0) m_iNoStates=2 } | ControlPushButton *
  | ▶ m_pReloopToggleButton | 0x0000021214f3bbe0 {m_buttonMode=PUSH (0) m_iNoStates=2 } | ControlPushButton *
  | ▶ m_pReloopAndStopButton | 0x0000021214f3bc40 {m_buttonMode=PUSH (0) m_iNoStates=2 } | ControlPushButton *
  | ▶ m_pCOLoopScale | 0x0000021214f41880 {m_key={group="[Channel4]" item="loop_scale" } m_pControl=strong reference to shared pointer of type "ControlDoublePrivate" } | ControlObject *
  | ▶ m_pLoopHalveButton | 0x0000021214f418e0 {m_buttonMode=PUSH (0) m_iNoStates=2 } | ControlPushButton *
  | ▶ m_pLoopDoubleButton | 0x0000021214f42780 {m_buttonMode=PUSH (0) m_iNoStates=2 } | ControlPushButton *
  | ▶ m_pLoopRemoveButton | 0x0000021214f421e0 {m_buttonMode=TRIGGER (4) m_iNoStates=2 } | ControlPushButton *
  | ▶ m_pSlipEnabled | 0x0000021214f3c600 {m_buttonMode=TOGGLE (1) m_iNoStates=2 } | ControlObject * {ControlPushButton}
  | ▶ m_pRateControl | 0x000002120df776f0 {m_pButtonRateTempDown=0x0000021214f41520 {m_buttonMode=PUSH (0) m_iNoStates=2 } ...} | RateControl *
  | ▶ m_pPlayButton | 0x0000021214f3b4c0 {m_buttonMode=TOGGLE (1) m_iNoStates=2 } | ControlObject * {ControlPushButton}
  | ▶ m_pRepeatButton | 0x0000021214f3c660 {m_buttonMode=TOGGLE (1) m_iNoStates=2 } | ControlObject * {ControlPushButton}
  | m_bLoopingEnabled | false | bool
  | m_bLoopRollActive | false | bool
  | m_bLoopWasEnabledBeforeSlipEnable | false | bool
  | m_bAdjustingLoopIn | false | bool
  | m_bAdjustingLoopOut | false | bool
  | m_bAdjustingLoopInOld | false | bool
  | m_bAdjustingLoopOutOld | false | bool
  | m_bLoopOutPressedWhileLoopDisabled | false | bool
  | ▶ m_activeLoopRolls | { size=0 } | QStack<double>
  | ▶ m_loopInfo | {...} | ControlValueAtomic<LoopingControl::LoopInfo,8>
  | ▶ m_prevLoopInfo | {...} | ControlValueAtomic<LoopingControl::LoopInfo,8>
  | m_prevLoopSize | -1.0000000000000000 | double
  | ▶ m_oldLoopInfo | {startPosition={m_framePosition=nan } endPosition={m_framePosition=nan } seekMode=None (2) } | LoopingControl::LoopInfo
  | ▶ m_currentPosition | {...} | ControlValueAtomic<mixxx::audio::FramePos,8>
  | ▶ m_pQuantizeEnabled | 0x0000021214f3c6c0 {m_buttonMode=TOGGLE (1) m_iNoStates=2 } | ControlObject * {ControlPushButton}
  | ▶ m_pActiveBeatLoop | 0x0000021215038d20 {m_dBeatLoopSize=0.25000000000000000 m_bActive=false m_pLegacy=unique_ptr {m_buttonMode=TOGGLE (1) m_iNoStates=2 } ...} | QAtomicPointer<BeatLoopingControl>
  | ▶ m_pCOBeatLoop | 0x0000021214f3db60 {m_key={group="[Channel4]" item="beatloop" } m_pControl=strong reference to shared pointer of type "ControlDoublePrivate" } | ControlObject *
  | ▶ m_pCOBeatLoopSize | 0x0000021214f3d2c0 {m_key={group="[Channel4]" item="beatloop_size" } m_pControl=strong reference to shared pointer of type "ControlDoublePrivate" } | ControlObject *
  | ▶ m_beatLoops | { size=15 } | QList<BeatLoopingControl *>
  | ▶ m_pCOBeatJump | 0x0000021214f400e0 {m_key={group="[Channel4]" item="beatjump" } m_pControl=strong reference to shared pointer of type "ControlDoublePrivate" } | ControlObject *
  | ▶ m_pCOBeatJumpSize | 0x0000021214f40c20 {m_key={group="[Channel4]" item="beatjump_size" } m_pControl=strong reference to shared pointer of type "ControlDoublePrivate" } | ControlObject *
  | ▶ m_pCOBeatJumpSizeHalve | 0x0000021214f3fba0 {m_buttonMode=PUSH (0) m_iNoStates=2 } | ControlPushButton *
  | ▶ m_pCOBeatJumpSizeDouble | 0x0000021214f40e60 {m_buttonMode=PUSH (0) m_iNoStates=2 } | ControlPushButton *
  | ▶ m_pCOBeatJumpForward | 0x0000021214f40140 {m_buttonMode=PUSH (0) m_iNoStates=2 } | ControlPushButton *
  | ▶ m_pCOBeatJumpBackward | 0x0000021214f407a0 {m_buttonMode=PUSH (0) m_iNoStates=2 } | ControlPushButton *
  | ▶ m_beatJumps | { size=15 } | QList<BeatJumpControl *>
  | ▶ m_pCOLoopMove | 0x0000021214f40b60 {m_key={group="[Channel4]" item="loop_move" } m_pControl=strong reference to shared pointer of type "ControlDoublePrivate" } | ControlObject *
  | ▶ m_loopMoves | { size=15 } | QList<LoopMoveControl *>
  | ▶ m_pTrack | shared_ptr {m_qMutex={owner={...} count=0 mutex={...} } m_fileAccess={m_fileInfo={m_fileInfo={d_ptr=pointer to implicit shared object of type "QFileInfoPrivate" } } ...} ...} [28 strong refs, 1 weak ref] [{_Uses=28 _Weaks=2 }] | std::shared_ptr<Track>
  | ▶ m_pBeats | shared_ptr {m_markers={ size=0 } m_lastMarkerPosition={m_framePosition=18107.000000000000 } m_lastMarkerBpm={m_value=...} ...} [7 strong refs] [default] | std::shared_ptr<mixxx::Beats const>
◢ | pBeats | shared_ptr {m_markers={ size=0 } m_lastMarkerPosition={m_framePosition=18107.000000000000 } m_lastMarkerBpm={m_value=...} ...} [7 strong refs] [default] | std::shared_ptr<mixxx::Beats const>
  | ◢ [ptr] | 0x000002121a74fa50 {m_markers={ size=0 } m_lastMarkerPosition={m_framePosition=18107.000000000000 } ...} | const mixxx::Beats *
  | ▶ std::enable_shared_from_this<mixxx::Beats> | {_Wptr=empty } | std::enable_shared_from_this<mixxx::Beats>
  | ▶ m_markers | { size=0 } | std::vector<mixxx::BeatMarker,std::allocator<mixxx::BeatMarker>>
  | ▶ m_lastMarkerPosition | {m_framePosition=18107.000000000000 } | mixxx::audio::FramePos
  | ▶ m_lastMarkerBpm | {m_value=141.83333333333331 } | mixxx::Bpm
  | ▶ m_sampleRate | {m_value=44100 } | mixxx::audio::SampleRate
  | ▶ m_subVersion | "rounding=V4\|vamp_plugin_id=qm-tempotracker:0" | const QString
  | ◢ [control block] | default | std::_Ref_count_base {std::_Ref_count<mixxx::Beats>}
  | ◢ [original ptr] | 0x000002121a74fa50 {m_markers={ size=0 } m_lastMarkerPosition={m_framePosition=18107.000000000000 } ...} | mixxx::Beats *
  | ▶ std::enable_shared_from_this<mixxx::Beats> | {_Wptr=empty } | std::enable_shared_from_this<mixxx::Beats>
  | ▶ m_markers | { size=0 } | std::vector<mixxx::BeatMarker,std::allocator<mixxx::BeatMarker>>
  | ▶ m_lastMarkerPosition | {m_framePosition=18107.000000000000 } | mixxx::audio::FramePos
  | ▶ m_lastMarkerBpm | {m_value=141.83333333333331 } | mixxx::Bpm
  | ▶ m_sampleRate | {m_value=44100 } | mixxx::audio::SampleRate
  | ▶ m_subVersion | "rounding=V4\|vamp_plugin_id=qm-tempotracker:0" | const QString
  | ▶ [Raw View] | {_Ptr=0x000002121a74fa50 {m_markers={ size=0 } m_lastMarkerPosition={m_framePosition=18107.000000000000 } ...} } | std::_Ref_count_base {std::_Ref_count<mixxx::Beats>}
  | ◢ [Raw View] | {...} | std::shared_ptr<mixxx::Beats const>
  | ◢ std::_Ptr_base<mixxx::Beats const > | {_Ptr=0x000002121a74fa50 {m_markers={ size=0 } m_lastMarkerPosition={m_framePosition=18107.000000000000 } ...} ...} | std::_Ptr_base<mixxx::Beats const>
  | ◢ _Ptr | 0x000002121a74fa50 {m_markers={ size=0 } m_lastMarkerPosition={m_framePosition=18107.000000000000 } ...} | const mixxx::Beats *
  | ▶ std::enable_shared_from_this<mixxx::Beats> | {_Wptr=empty } | std::enable_shared_from_this<mixxx::Beats>
  | ▶ m_markers | { size=0 } | std::vector<mixxx::BeatMarker,std::allocator<mixxx::BeatMarker>>
  | ▶ m_lastMarkerPosition | {m_framePosition=18107.000000000000 } | mixxx::audio::FramePos
  | ▶ m_lastMarkerBpm | {m_value=141.83333333333331 } | mixxx::Bpm
  | ▶ m_sampleRate | {m_value=44100 } | mixxx::audio::SampleRate
  | ▶ m_subVersion | "rounding=V4\|vamp_plugin_id=qm-tempotracker:0" | const QString
  | ▶ _Rep | 0x000002121af71be0 default | std::_Ref_count_base * {std::_Ref_count<mixxx::Beats>}

</body>
</HTML>

### Version

main

### OS

Windows 11

### PR DESCRIPTION
**Pull request by alajovic**
Fixes #13262

### CODE REVIEW

File: src/track/beats.cpp [hunk 1]
```diff
@@ -455,20 +464,20 @@ Beats::ConstIterator Beats::iteratorFrom(audio::FramePos position) const {
...
         }
         it -= static_cast<int>(n);
-        it = previousIfNeeded(it, position);
+        it = adjustIfNeeded(it, position);
     } else {
         it = std::lower_bound(cfirstmarker(), clastmarker() + 1, position);
     }
     DEBUG_ASSERT(it == cbegin() || it == cend() || *it >= position);
-    DEBUG_ASSERT(it == cbegin() || it == cend() || *it > *std::prev(it));
+    DEBUG_ASSERT(it == cbegin() || it == cend() || *std::prev(it) < position);
```
Comment (acolombier) [inline src/track/beats.cpp:480]: Why changing the assert here? No issue in adding a new assert, but I though making sure that `it > std::prev(it)` was valuable, isn’t it?

Comment (ywwg) [reply src/track/beats.cpp:480]: see discussion in the original issue

Comment (acolombier) [reply src/track/beats.cpp:480]: I cannot see any explanation in the original issue.

Comment (alajovic) [reply src/track/beats.cpp:480]: [This question](https://github.com/mixxxdj/mixxx/issues/13262#issuecomment-3985157492) and [this reply](https://github.com/mixxxdj/mixxx/issues/13262#issuecomment-3985174893). Previous version of this assertion basically checked that "this beat comes after the beat before it". Which is a tautology. What it was _supposed_ to check is that "the previous beat is not a closer match for `position` than this one". That's what I'm checking in the newly added tests, and that's what the modified assertion is also checking.

Comment (alajovic) [reply src/track/beats.cpp:480]: I see only two ways to have `*it > *std::prev(it)`:
1. `it == cbegin()`, consequently `std::prev` underflows (at least I _think_ that's what would happen). However, the assertion short-circuits on `it == cbegin()`, so this cannot trigger it anyway.
2. Flaw in iterator implementation. If this is a concern, such an assertion should be in the iterator logic, not in a caller.

Comment (acolombier) [reply src/track/beats.cpp:480]: Thanks for the explaination.

> This question and this reply. 

Yeah I saw those, but "yes" isn't quite much of an explanation :sweat_smile:

Comment (alajovic) [reply src/track/beats.cpp:480]: Haha, true that!

Comment (daschuer) [reply src/track/beats.cpp:480]: The original assertion checks that the beats around the position are in consecutive order. 
The new assertion is still only true when they are in consecutive order, but also verified that the position is in a consecutive oder between them
So I consider this a good improvement.
Did I miss something?

File: src/test/beatstest.cpp [hunk 2]
```diff
@@ -569,4 +571,68 @@ TEST(BeatsTest, roundBpm) {
...
+    const auto sampleRate = audio::SampleRate(48000);
+    const auto markerPos = audio::FramePos(1000);
+    const auto bpm = Bpm(127.0);
+    constexpr int kBeatOffset = 11;
+
+    const auto beats = Beats(markerPos, bpm, sampleRate, QString());
+    const auto beatPos = *(beats.cfirstmarker() + kBeatOffset);
+    const auto position = audio::FramePos(
+            std::nextafter(beatPos.value(),
+                    std::numeric_limits<double>::infinity()));
```
Comment (daschuer) [inline src/test/beatstest.cpp]: You can use here `util_double_infinity();` from util/fpclassify.h if you really need infinity. However the code is allowed to ignore  it at any following call.

**Review by daschuer — CHANGES_REQUESTED** [review]
The code looks good. Thank you. We just need to fix the fastmath issue.

File: src/test/beatstest.cpp (hunk 2 above)
Comment (daschuer) [reply src/test/beatstest.cpp]: util/fpclassify.h is compiled without the -Wnan-infinity-disabled flag. This causes that the CPU at least has the hex code of infinity in its registers.

Comment (alajovic) [reply src/test/beatstest.cpp]: Thanks. I wasn't aware that `-ffast-math` was enabled. Not a problem: infinity is not really needed here, it's just an idiomatic pattern. I think the most elegant solution is to use `std::numeric_limits<double>::max()` instead.

File: src/track/beats.cpp (hunk 1 above)
Comment (alajovic) [reply src/track/beats.cpp:480]: Correct. Combined, the two assertions verify that `*std::prev(it) < position <= *it` (mathematical notation, not C++ code). This implies `*std::prev(it) < *it`, so the check has become strictly tighter.

File: src/test/beatstest.cpp (hunk 2 above)
Comment (daschuer) [reply src/test/beatstest.cpp]: Yes that's even better.

**Review by daschuer — APPROVED** [review]
LGTM, thank you.

**Comment by daschuer** [comment]
Oh I have just notices that we have missed to ask you for permission to distribute you changes with Mixxx.  
If that's OK, please sign the [Mixxx Contributor Agreement](https://docs.google.com/forms/d/e/1FAIpQLScC9QG327sjLL0eWftmfGUasxFFLxg6LCXJ2xHDYRzFIRqyiw/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ) and comment here when you have done so. It gives us the permission to distribute your work under the GPL v2 or later license and the Apple Mac App Store. It is also helpful for us to have contact information for contributors in case we may need it in the future.

**Comment by alajovic** [comment]
Oh, yes, obviously! Signed just now.

**Comment by daschuer** [comment]
Thanks
