### PR TITLE
Fix reading the Spinny cover on Windows 

### LINKED ISSUE #11131: Deck/Spinny Coverart is randomly not read
### Bug Description

If I load a track into a deck, the CoveArt is sometimes displayed, and sometimes not. This doesn't depend on the track, it can be reproduced for any track after some retries.
This doesn't happen with 2.3, only with Main.

In the --developer output I see in cases without loaded coverart:
```
info [Thread (pooled)] MetadataSourceTagLib - No track metadata or cover art found in file "C:/Users/Joerg.WORLDWARTWEB/Music/Der Dritte Raum - Hale Bopp (original mix).mp3" with type 3
debug [Thread (pooled)] SoundSourceProxy - SoundSourceProvider "MAD: MPEG Audio Decoder" created a SoundSource for file "file:///C:/Users/Joerg.WORLDWARTWEB/Music/Der Dritte Raum - Hale Bopp (original mix).mp3" of type "mp3"
debug [AnalyzerThread 0 #1] AnalyzerThread - Dequeued next track 140
debug [Thread (pooled)] SoundSourceProxy - SoundSourceProvider "MAD: MPEG Audio Decoder" created a SoundSource for file "file:///C:/Users/Joerg.WORLDWARTWEB/Music/Der Dritte Raum - Hale Bopp (original mix).mp3" of type "mp3"
warning [Thread (pooled)] TagLib - Cannot read audio properties from inaccessible/unreadable/invalid file:
debug [AnalyzerThread 0 #1] AnalyzerThread - Analyzing QFileInfo(C:\Users\Joerg.WORLDWARTWEB\Music\Der Dritte Raum - Hale Bopp (original mix).mp3)
info [Thread (pooled)] MetadataSourceTagLib - No track metadata or cover art found in file "C:/Users/Joerg.WORLDWARTWEB/Music/Der Dritte Raum - Hale Bopp (original mix).mp3" with type 3
warning [Thread (pooled)] TagLib - Cannot read audio properties from inaccessible/unreadable/invalid file:
info [Thread (pooled)] MetadataSourceTagLib - No track metadata or cover art found in file "C:/Users/Joerg.WORLDWARTWEB/Music/Der Dritte Raum - Hale Bopp (original mix).mp3" with type 3
```

### Version

2.4

### OS

Windows7 & Windows11

### PR DESCRIPTION
**Pull request by daschuer**
This finally fixes https://github.com/mixxxdj/mixxx/issues/11131

This patch awoid to access the same file simultaneously form two threads. 
Instead it used the same thread to redponds to both requests. 

@JoergAtGithub Please confirm if this fixes your issue. 

This PR is on top of #12087 which is on top of #12009

### CODE REVIEW

**Comment by m0dB** [comment]
Great work, @daschuer ! 

> This patch avoids to access the same file simultaneously from two threads.

Isn't that something that could have been solved with a simple mutex? Not saying that that would have been a better solution (I am all for reducing needless threading complexity), just trying to understand the changes so I can do the review.

> Instead it used the same thread to respond to both requests.

Can you point out the where in the code this change is implemented?

**Comment by daschuer** [comment]
> Isn't that something that could have been solved with a simple mutex? 

Yes, a quick hack solution with a mutex would have been possible. The downside would be that only one thread would be have file excess and that multiple access of the same file would have been chained. 

Now we still use a new concurrent thread for every new file. Simultaneous accesses to the same file, that happens when loadingva track, are performed by a single thread.

File: src/library/coverartcache.cpp [hunk 1]
```diff
@@ -158,10 +158,12 @@ void CoverArtCache::tryLoadCover(
     }
 
     const auto requestedCacheKey = coverInfo.cacheKey();
-    // keep a list of trackIds for which a future is currently running
+    QString cacheKey = pixmapCacheKey(requestedCacheKey, desiredWidth);
+    // keep a list of cacheKeys for which a future is currently running
     // to avoid loading the same picture again while we are loading it
-    QPair<const QObject*, mixxx::cache_key_t> requestId = qMakePair(pRequester, requestedCacheKey);
-    if (m_runningRequests.contains(requestId)) {
+    bool requestPending = m_runningRequests.contains(cacheKey);
```
Comment (daschuer) [inline src/library/coverartcache.cpp]: Here we collect requests to a same file. 
Whe the first look up is done m_runningRequests is used to signall all requesters.

Comment (m0dB) [reply src/library/coverartcache.cpp]: Got it! Thanks, this helps!

File: src/library/basetracktablemodel.cpp [hunk 2]
```diff
@@ -546,17 +553,21 @@ QVariant BaseTrackTableModel::composeCoverArtToolTipHtml(
...
+            absoluteHeightOfCoverartToolTip);
     if (pixmap.isNull()) {
-        // Cache miss -> Don't show a tooltip
-        return QVariant();
+        // Cache miss -> Request Cover via coverFound signal
+        CoverArtCache::requestUncachedCover(
+                this,
+                coverInfo,
+                absoluteHeightOfCoverartToolTip);
+        return tr("Fetching image ...");
```
Comment (m0dB) [inline src/library/basetracktablemodel.cpp:570]: What is the string used for? Can you add a comment?

File: src/library/basetracktablemodel.cpp [hunk 3]
```diff
@@ -1105,3 +1116,15 @@ bool BaseTrackTableModel::updateTrackMood(
...
+void BaseTrackTableModel::slotCoverFound(
+        const QObject* pRequester,
+        const CoverInfo& coverInfo,
+        const QPixmap& pixmap) {
+    Q_UNUSED(pixmap);
+    if (pRequester != this ||
+            getTrackLocation(m_toolTipIndex) != coverInfo.trackLocation) {
+        return;
+    }
+    emit dataChanged(m_toolTipIndex, m_toolTipIndex, {Qt::ToolTipRole});
```
Comment (m0dB) [inline src/library/basetracktablemodel.cpp:1129]: What has the tooltip to do with the cover?

File: src/library/coverart.h [hunk 4]
```diff
@@ -70,20 +70,25 @@ class CoverInfoRelative {
...
         m_legacyHash = legacyHash;
     }
 
+    bool hasCacheKey() const {
+        return !m_imageDigest.isEmpty() || m_legacyHash != defaultLegacyHash();
+    }
+
     bool hasImage() const {
-        return cacheKey() != CoverImageUtils::defaultCacheKey();
+        return type != NONE;
```
Comment (m0dB) [inline src/library/coverart.h:88]: might be a good moment to prefix this m_type?

**Comment by JoergAtGithub** [comment]
The deck spinnies are now loaded, but there is a new issue:

If I start with initial library table column size everything works:
grafik
But if I change the column width of the library, the loading of coverart stops(in the screenshot you see how it looks after column width change an loading the same track into deck1):
grafik

File: src/library/basetracktablemodel.cpp (hunk 3 above)
Comment (JoergAtGithub) [reply src/library/basetracktablemodel.cpp:1129]: If library tooltips are enabled and you move the mouse over a library cover, than the tooltip shows a bigger picture of this cover (mouse pointer is not captured by screenshot-tool):
grafik

File: src/library/basetracktablemodel.cpp (hunk 2 above)
Comment (daschuer) [reply src/library/basetracktablemodel.cpp:570]: This text is shown as tooltip for the spit of a second before the actual cover is shown. I will add a comment.

**Comment by daschuer** [comment]
Can you allso have a look to that mature https://github.com/mixxxdj/mixxx/pull/12009
This needs to be merged first and would make the review here more easy.

File: src/library/basetracktablemodel.cpp (hunk 3 above)
Comment (m0dB) [reply src/library/basetracktablemodel.cpp:1129]: Got it!t Thanks! Still discovering mixxx features I never use :-)

File: src/library/basetracktablemodel.cpp (hunk 2 above)
Comment (daschuer) [reply src/library/basetracktablemodel.cpp:571]: Done

**Comment by daschuer** [comment]
I was able to reproduce the column size issue. I have amended the last commit with a fix.

**Comment by JoergAtGithub** [comment]
This doesn't compile:
```
  [222/686] Building CXX object CMakeFiles\mixxx-lib.dir\src\library\coverartcache.cpp.obj
  FAILED: CMakeFiles/mixxx-lib.dir/src/library/coverartcache.cpp.obj 
  C:\PROGRA~1\MICROS~1\2022\COMMUN~1\VC\Tools\MSVC\1437~1.328\bin\Hostx64\x64\cl.exe  /nologo /TP -DAMD64 -DDJINTEROP_SOURCE -DHAVE_WINSOCK2_H -DMIXXX_BUILD_RELEASE -DMIXXX_DEBUG_ASSERTIONS_ENABLED -DMIXXX_DEBUG_ASSERTIONS_FATAL -DMIXXX_USE_QOPENGL -DNOMINMAX -DPROTOBUF_USE_DLLS -DQT_CONCURRENT_LIB -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_PRINTSUPPORT_LIB -DQT_QMLMODELS_LIB -DQT_QML_LIB -DQT_QUICKWIDGETS_LIB -DQT_QUICK_LIB -DQT_SQL_LIB -DQT_SVG_LIB -DQT_TABLET_SUPPORT -DQT_TESTCASE_BUILDDIR=\"C:/Users/Joerg.WORLDWARTWEB/source/repos/JoergAtGithub/mixxx/build/x64__legacy\" -DQT_TESTLIB_LIB -DQT_USE_QSTRINGBUILDER -DQT_WIDGETS_LIB -DQT_XML_LIB -DSFC_SUPPORTS_SET_COMPRESSION_LEVEL -DUNICODE -DWIN32 -DWINVER=0x0601 -D_ATL_MIN_CRT -D_CRT_SECURE_NO_WARNINGS -D_SILENCE_CXX17_ITERATOR_BASE_CLASS_DEPRECATION_WARNING -D_USE_MATH_DEFINES -D_WIN32_WINNT=0x0601 -D_WINSOCK_DEPRECATED_NO_WARNINGS -D__BATTERY__ -D__BROADCAST__ -D__ENGINEPRIME__ -D__HID__ -D__HSS1394__ -D__LILV__ -D__MAD__ -D__MEDIAFOUNDATION__ -D__MODPLUG__ -D__OPUS__ -D__QTKEYCHAIN__ -D__SNDFILE__ -D__SQLITE3__ -D__SSE2__ -D__SSE__ -D__VINYLCONTROL__ -D__WINDOWS__ -D__WV__ -IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\build\x64__legacy\mixxx-lib_autogen\include -IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src -IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\build\x64__legacy\src -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\lib\fidlib -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\lib\portaudio -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-0309294\installed\x64-windows\include -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\lib\rigtorp\SPSCQueue\include -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\lib\replaygain -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\lib\reverb -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\lib\libshout-idjc\include -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-0309294\installed\x64-windows\include\djinterop -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\lib\kaitai -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\lib\mp3guessenc-0.27.4 -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-0309294\installed\x64-windows\include\qt5 -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-0309294\installed\x64-windows\include\qt5\QtConcurrent -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-0309294\installed\x64-windows\include\qt5\QtCore -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-0309294\installed\x64-windows\tools\qt5\mkspecs\win32-msvc -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-0309294\installed\x64-windows\include\qt5\QtGui -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-0309294\installed\x64-windows\include\qt5\QtNetwork -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-0309294\installed\x64-windows\include\qt5\QtOpenGL -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-0309294\installed\x64-windows\include\qt5\QtWidgets -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-0309294\installed\x64-windows\include\qt5\QtPrintSupport -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-0309294\installed\x64-windows\include\qt5\QtQml -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-0309294\installed\x64-windows\include\qt5\QtQuickWidgets -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-0309294\installed\x64-windows\include\qt5\QtQuick -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-0309294\installed\x64-windows\include\qt5\QtQmlModels -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-0309294\installed\x64-windows\include\qt5\QtSql -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-0309294\installed\x64-windows\include\qt5\QtSvg -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-0309294\installed\x64-windows\include\qt5\QtTest -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-0309294\installed\x64-windows\include\qt5\QtXml -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\lib\qm-dsp -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\lib\qm-dsp\include -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-0309294\installed\x64-windows\include\taglib -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-0309294\installed\x64-windows\include\opus -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-0309294\installed\x64-windows\include\hidapi -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\lib\xwax -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-0309294\installed\x64-windows\include\wavpack -external:W0 /DWIN32 /D_WINDOWS /GR /EHsc /Zc:__cplusplus /Zc:inline /Z7 /O2  /DNDEBUG -std:c++20 -MD /UTF8 /fp:fast /Gy /W3 -DPA_USE_JACK=1 -DPA_USE_ASIO=1 -DPA_USE_DS=1 -DPA_USE_WMME=1 -DPA_USE_WASAPI=1 -DPA_USE_WDMKS=1 /showIncludes /FoCMakeFiles\mixxx-lib.dir\src\library\coverartcache.cpp.obj /FdCMakeFiles\mixxx-lib.dir\mixxx-lib.pdb /FS -c C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\library\coverartcache.cpp
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\library\coverartcache.cpp(301): error C2653: 'm_runningRequests': is not a class or namespace name
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\library\coverartcache.cpp(301): error C2664: 'int remove(const char *)': cannot convert argument 1 from 'mixxx::cache_key_t' to 'const char *'
  C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\library\coverartcache.cpp(301): note: Conversion from integral type to pointer type requires reinterpret_cast, C-style cast or parenthesized function-style cast
  C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt\stdio.h(369): note: see declaration of 'remove'
  C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\library\coverartcache.cpp(301): note: while trying to match the argument list '(mixxx::cache_key_t)'
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\library\coverartcache.cpp(303): error C2144: syntax error: 'auto' should be preceded by ';'
```

**Comment by daschuer** [comment]
Now it builds again.

File: src/library/basetracktablemodel.cpp (hunk 2 above)
Comment (JoergAtGithub) [reply src/library/basetracktablemodel.cpp:571]: > This text is shown as tooltip for the spit of a second before the actual cover is shown.

Than it doesn't work, I see the text, but it's no replaced by the cover art. If I don't move the mouse, it remains there for some seconds, and than the tooltip disappears.

**Comment by daschuer** [comment]
Strange, I am not able to confirm it natively on Ubuntu, but on my windows 10 virtual machine.

**Comment by daschuer** [comment]
Fixed here by rebasing on https://github.com/mixxxdj/mixxx/pull/12087

**Review by JoergAtGithub — APPROVED** [review]
Now the CoverArt tooltip always appears, but I couldn't see the string "Fetching image ..." anymore. Not sure, if it does not appear, or the loading is too fast. Anyway, it is what the user expect. Great work! Thank you!

**Comment by daschuer** [comment]
Rebased on top of the branches this one is based on.

**Comment by JoergAtGithub** [comment]
I think this needs to be rebased to latest 2.4, before we can be merge this - or can Git handle this merge without rebase?

**Comment by daschuer** [comment]
Rebased.

**Comment by JoergAtGithub** [comment]
Thank you! Still LGTM!
