### PR TITLE
Excluding ELAN touch screen

### LINKED ISSUE #11323: ELAN touchscreen detecetd as a controller
### Bug Description

The touch screen that fits [Dell XPS](https://ubuntu.com/certified/202104-28892/20.04%20LTS) is detected as an available controller:

image

### Version

2.4.0

### OS

PopOs (Ubuntu) 22.04

### PR DESCRIPTION
**Pull request by acolombier**
Excluding ELAN touch screen, which fits XPS 15 laptops.

This should also exclude other touch screens, but unfortunately, the ELAN device exposes other HID usages through vendor specific and reserved usage pages (`01ff`, `ff00` and `ff01`) so it cannot be excluded using the global rule. 

This fixes #11323.

### CODE REVIEW

**Comment by JoergAtGithub** [comment]
Is this an USB HID device? If it's an I2C HID or SPI HID device, we could also filter by bus type. Than all internal laptop devices would be hidden.
The bus type information is new in hidapi 0.13.0 https://github.com/libusb/hidapi/releases/tag/hidapi-0.13.0 and would require an update of hidapi in the ./lib folder first.

**Comment by acolombier** [comment]
This particular device doesn't seem to be an USB HID, so this would work too.
Happy to give the update a spin and see how much work it would need to work if you think we should go this way instead.

**Comment by JoergAtGithub** [comment]
This would be additional, because your change covers also the case of an HID touchpads on USB keyboards etc.

File: src/controllers/hid/hidenumerator.cpp [hunk 1]
```diff
@@ -34,12 +34,12 @@ bool recognizeDevice(const hid_device_info& device_info) {
...
-        // If vendor ids do not match, skip.
-        if (device_info.vendor_id != denylisted.vendor_id) {
+        // If vendor ids are specified and do not match, skip.
+        if (denylisted.vendor_id && device_info.vendor_id != denylisted.vendor_id) {
             continue;
         }
-        // If product IDs do not match, skip.
-        if (device_info.product_id != denylisted.product_id) {
+        // If product IDs are specified and do not match, skip.
+        if (device_info.product_id && device_info.product_id != denylisted.product_id) {
```
Comment (JoergAtGithub) [inline src/controllers/hid/hidenumerator.cpp:42]:
```suggestion
        if (denylisted.product_id && device_info.product_id != denylisted.product_id) {
```

**Review by JoergAtGithub — CHANGES_REQUESTED** [review]

**Comment by JoergAtGithub** [comment]
An HID touchpad/screen could be mapped for effects control like here: https://youtu.be/vVfmMevmxxs?t=99
But maybe this is not of practical relevance.

**Comment by acolombier** [comment]
I have added an other exclusion for Logitech G Pro mouse which also appears to be detected as a valid controller unfortunately. The reason behind this is that this mouse expose bunch of other HID interface which can be use to tweak the mouse setting (colors, DPIs) as well as accessing status (battery level)

2 cents thought as this issue likely impact many other devices - could we have a whitelist instead of a blacklist? This whitelist could be a little bit more flexible (e.g no devices are shown by default if not present on distributed whitelist -> user is able to to bypass the whitelist and select their device from the list of all HID device -> whitelist gets updated so next user find their device right away)

**Comment by JoergAtGithub** [comment]
I head a second thought about it. When we have a controller with touch input, it should most likely mapped to a future QML instance which renders the screen content and not to the normal HID mapping. Therefore it fits to ignore the usage touch here.

**Comment by JoergAtGithub** [comment]
Thank you!
