### PR TITLE
WStarRating: don't update track directly, use signals/slots

### LINKED ISSUE #11540: Updating Star rating in track properties clears other unsaved properties
### Bug Description

Clicking on any of 5 stars in file/track properties inside Mixxx, will revert unsaved changes in all other fields.
I think this bug lasted for long, but never reported it since.

To reproduce:
In library right mouse click on any track > properties >  type anything in any input field/s > click on star class. (doesn't matter the initial star value) > unsaved changes reverted.

Let me know if backtrace log is needed

### Version

2.4-alpha-1467-g425ad1e47a

### OS

Windows 10 Pro 21H2

### PR DESCRIPTION
**Pull request by ronso0**
fixes #11540 

changes to the star rating are now handled via change signals, like with the QLineEdits

**edit:** instead of working around the symptom, as per @uklotzde's suggestion, this PR now adds slots and signals for track rating. Now it's consistent with other track properties and WStarRating  now much smaller.

**Note:** updating the rating (or any other track property) elsewhere emits the `trackCganged` signal and will therefore still wipe pending changes in the properties dialog. This is not a bug.

### CODE REVIEW

File: src/widget/wstarrating.cpp [hunk 1]
```diff
@@ -166,7 +174,11 @@ void WStarRating::mouseReleaseEvent(QMouseEvent* /*unused*/) {
         return;
     }
 
-    m_pCurrentTrack->setRating(m_starRating.starCount());
+    m_currRating = m_starRating.starCount();
+    if (m_updateTrack) {
```
Comment (uklotzde) [inline src/widget/wstarrating.cpp:178]: Thanks for addressing these issues. QML will hopefully help to prevent those mistakes in the (far away) future.

The widget should never directly update the track state on its own. Instead the receiver of the signal could do that if desired or otherwise reject the proposed new value by resetting the widget -> unidirectional data flow.

Offering both options is confusing and not maintainable. But I am afraid that trying to avoid this mixed behavior could open another _Pandora's Box_.

Comment (uklotzde) [reply src/widget/wstarrating.cpp:178]: Ideally the widget would only offer a slot for setting the rating (input, write-only) and emit a signal when the rating changed (output, read-only). Maybe a getter for reading the current rating on demand. No track pointer, no implicit context management.

Comment (ronso0) [reply src/widget/wstarrating.cpp:178]: I understand what you're saying, and I agree that WStarRating becomes more complex and bit harder to maintain. Looks like this can be changed without too much hazzle, with a few changes to Track and BaseTrackPlayer(Impl) (and mediators like LegacySkinParser, and DlgTrackinfo, of course), and WStarRating would be quite clean then.

I think I'll take a stab at this for 2.4 beta, though it's out of scope for this quick bug fix.

**Comment by ronso0** [comment]
@uklotzde That was easier than I thought, though tedious.
I went back to square one and reverted the previous commit.
Please take a look.

File: src/widget/wstarrating.h [hunk 2]
```diff
@@ -22,16 +22,13 @@ class WStarRating : public WWidget {
...
-    ///
-    /// The value must be consistent with the current track if connected.
-    void setRating(int rating);
-
   public slots:
-    void slotTrackLoaded(TrackPointer pTrack = TrackPointer());
+    void slotSetRating(int rating);
+
+  signals:
+    void ratingChangeRequest(int rating);
```
Comment (uklotzde) [inline src/widget/wstarrating.h:29]: Events are named using past tense, i.e. `ratingChanged()`. For requests (method or command) you use an imperative verb.

File: src/mixer/basetrackplayer.h [hunk 3]
```diff
@@ -44,13 +44,15 @@ class BaseTrackPlayer : public BasePlayer {
     virtual void slotCloneFromGroup(const QString& group) = 0;
     virtual void slotCloneDeck() = 0;
     virtual void slotEjectTrack(double) = 0;
+    virtual void slotRatingChangeRequest(int rating) = 0;
```
Comment (uklotzde) [inline src/mixer/basetrackplayer.h:47]: `slotSetTrackRating()`

File: src/widget/wstarrating.cpp [hunk 4]
```diff
@@ -118,32 +82,24 @@ void WStarRating::mouseMoveEvent(QMouseEvent *event) {
...
 void WStarRating::slotStarsDown(double v) {
-    if (!m_pCurrentTrack) {
-        return;
-    }
     if (v > 0 && m_starRating.starCount() > 0) {
         int star = m_starRating.starCount() - 1;
-        m_starRating.setStarCount(star);
-        update();
-        m_pCurrentTrack->setRating(star);
+        emit ratingChangeRequest(star);
```
Comment (uklotzde) [inline src/widget/wstarrating.cpp:94]: The signal should only be emitted if the value has actually changed to prevent cycles.

File: src/widget/wstarrating.cpp [hunk 5]
```diff
@@ -162,22 +118,16 @@ int WStarRating::starAtPosition(int x) {
...
-    m_pCurrentTrack->setRating(m_starRating.starCount());
+    emit ratingChangeRequest(m_starRating.starCount());
 }
 
 void WStarRating::fillDebugTooltip(QStringList* debug) {
     WWidget::fillDebugTooltip(debug);
 
-    QString currentRating = "-";
+    QString currentRating;
+    currentRating.setNum(m_currRating);
```
Comment (uklotzde) [inline src/widget/wstarrating.cpp:128]: What's the difference between m_currRating and m_starRating? The widget should not store any redundant state that could get inconsistent.

File: src/track/track.h [hunk 6]
```diff
@@ -436,6 +436,7 @@ class Track : public QObject {
     // adjusted in the opposite direction to compensate (no audible change).
     void replayGainAdjusted(const mixxx::ReplayGain&);
     void colorUpdated(const mixxx::RgbColor::optional_t& color);
+    void ratingUpdated(int rating);
```
Comment (uklotzde) [inline src/track/track.h:439]: I would prefer the neutral and agnostic _changed_ terminology. That would be inconsistent with the existing signals, but we could add a TODO to those later.

**Review by uklotzde — CHANGES_REQUESTED** [review]
Glad to hear that this was easier than expected. The refactoring avoids to pile up more legacy code.

File: src/widget/wstarrating.cpp (hunk 5 above)
Comment (ronso0) [reply src/widget/wstarrating.cpp:128]: `m_starRating.starCount()` is the current value of StarRating, i.e. what you see (for example while hovering).
`m_currRating` is the confirmed value of the track / pending track record value in DlgTrackInfo, after LeaveEvent.

File: src/mixer/basetrackplayer.h (hunk 3 above)
Comment (ronso0) [reply src/mixer/basetrackplayer.h:47]: :+1:

File: src/widget/wstarrating.h (hunk 2 above)
Comment (ronso0) [reply src/widget/wstarrating.h:29]: :+1:

File: src/widget/wstarrating.cpp (hunk 5 above)
Comment (uklotzde) [reply src/widget/wstarrating.cpp:128]: Then `m_currRating` is redundant. The widget should maintain only a single value and don't care what it's clients or subscribers are assuming.

File: src/widget/wstarrating.cpp (hunk 4 above)
Comment (ronso0) [reply src/widget/wstarrating.cpp:94]: Sure. This just handles the `group,stars_up` CO and changes the current value. The cycle prevention is in [`Track::setRating`](https://github.com/mixxxdj/mixxx/blob/2.4/src/track/track.cpp#L1363-L1368).

However, I changed this method to work with `m_currRating`, i.e. the stored value delivered by `Track::ratingUpdated`, not the visual state (which avoids confusion in the unlikely case a user hovers the rating **and** uses the CO).

**Comment by ronso0** [comment]
pushed some fixups which I'd like to squash if they're okay.

File: src/widget/wstarrating.cpp [hunk 7]
```diff
@@ -162,22 +118,16 @@ int WStarRating::starAtPosition(int x) {
...
     QString maximumRating = QString::number(m_starRating.maxStarCount());
 
-    if (m_pCurrentTrack) {
-        currentRating.setNum(m_pCurrentTrack->getRating());
-    }
```
Comment (ronso0) [inline src/widget/wstarrating.cpp:180]: showing `- / 5` in the debug tooltip with no track would be the only reason to track the "track loaded" state. not worth the effort IMO

File: src/widget/wstarrating.cpp (hunk 5 above)
Comment (ronso0) [reply src/widget/wstarrating.cpp:128]: > Then `m_currRating` is redundant.

Redundant with what?
The current value of `StarRating` (starCount()) just reflects the count of currently painted stars, be it final (clicked, not necessarily accepted by Track or DlgTrackInfo) or temporary (hovering, mouse moving).

Only `m_currRating` is storing the applied / real value and we need that for the COs and to restore the real value when leaving the widget (after mouse move, not clicked).

**Comment by ronso0** [comment]
> pushed some fixups which I'd like to squash if they're okay.

setting this to draft just to avoid accidental merge.

**Comment by uklotzde** [comment]
> pushed some fixups which I'd like to squash if they're okay.

Sure. I will take a final look when done.

File: src/widget/wstarrating.cpp (hunk 5 above)
Comment (uklotzde) [reply src/widget/wstarrating.cpp:128]: I'll check it later. Only viewed the diff, not the whole code.

Comment (uklotzde) [reply src/widget/wstarrating.cpp:128]: Nevertheless my comments reveal that meaning and purpose of those member variables is unclear on first sight.

**Comment by ronso0** [comment]
Go ahead, I'm done, I just addressed your review comments and packed the changes in small chunks for easy review.
Added a missing setrating to DlgTrackInof. All performs as expected.

**Comment by uklotzde** [comment]
Stopping my review here. I wasn't able to fully understand what the code is supposed to do, already wasted too much time. If it works, then feel free to merge it. This has to be rewritten for QML anyway.

**Comment by ronso0** [comment]
@uklotzde Thanks for your time and https://github.com/ronso0/mixxx/pull/43.
Your renaming and cleanup commits are valuable so I'll pick them, I'll just revert (ammend) that one small thing I spotted.

It's working fine now: rating is synced if updated anywhere (library, decks, DlgTrackInfo), as it's not possible to set the rating in an empty deck (or empty DlgTrackInfo, if that could be displayed).

**Comment by daschuer** [comment]
@ronso0 do you still plan to rebase this or does it put to much work on us?

**Comment by daschuer** [comment]
@ronso0 do you still plan to rebase this or does it put to much work on us?

**Comment by ronso0** [comment]
Thanks for the reminder!
Yes, I can rebase onto 2.3

**Review by daschuer — APPROVED** [review]
LGTM and works good, Thank you.

**Comment by ronso0** [comment]
Thanks for reviewing!

File: src/widget/wstarrating.cpp [hunk 8]
```diff
@@ -37,55 +36,27 @@ void WStarRating::setup(const QDomNode& node, const SkinContext& context) {
...
+        // Unchanged
+        return;
     }
-}
-
-void WStarRating::slotTrackChanged(TrackId trackId) {
-    Q_UNUSED(trackId);
-    updateRatingFromTrack();
+    m_starCount = starCount;
+    updateVisualRating(starCount);
```
Comment (ronso0) [inline src/widget/wstarrating.cpp:59]: had to add `emit ratingChanged(m_starCount)` in order to make the _up/_down controls to also update the track value
pushed a fix 0550e07eddcb7d45256038c67fac13f40d52328d
