### PR TITLE
Fix UI freeze when analyzing many tracks. 

### LINKED ISSUE #14563: Batch Anaylsis: UI freezes and becomes completely unresponsive
### Bug Description

Mixxx freezes completely when running a batch analysis on multiple tracks after analyzing a few tracks. You have to kill the process.

Last debug log messages are from the analyzer thread. ~~The stacktrace of the UI thread doesn't provide helpful insights.~~ See the attached stacktrace (main + patches): 

[mixxx_main_patched.txt](https://github.com/user-attachments/files/19512859/mixxx_main_patched.txt)

I have export of metadata enabled.

### Version

main

### OS

Fedora

### PR DESCRIPTION
**Pull request by daschuer**
This fixes #14563 a regression introduced in https://github.com/mixxxdj/mixxx/pull/13719 caused by an underlying issue with recursive calls to the track cache. 

I did some testing and backtrack analysis and can confirm the issue is now fixed.

### CODE REVIEW

**Comment by uklotzde** [comment]
Thanks for the fix 🙏 I didn't notice any issues so far after some quick testing.

My recommendation is not to release a new version right after merging this PR. The major changes on the caching need more time for thorough and broad testing on the different platforms.

I wonder how no one else complained about and reported such a serious issue before me? Suspicious. Seems like hardly anyone is actually using beta/development snapshots.

The decision to merge the major changes from #13719 into 2.5 was wrong. This is **_not_** an accusation! Just a post-mortem analysis for future fixes.

**Comment by ronso0** [comment]
> I wonder how no one else complained about and reported such a serious issue before me? Suspicious. Seems like hardly anyone is actually using beta/development snapshots.

Hmm, I _think_ there are quite a few `main` users, but maybe none of them is using batch analysis?

**Comment by uklotzde** [comment]
> > I wonder how no one else complained about and reported such a serious issue before me? Suspicious. Seems like hardly anyone is actually using beta/development snapshots.
> 
> Hmm, I _think_ there are quite a few `main` users, but maybe none of them is using batch analysis?

Also occurred multiple times when exiting Mixxx after editing track properties.

**Comment by ronso0** [comment]
> Also occurred multiple times when exiting Mixxx after editing track properties.

I do that a lot in pretty much every session and didn't experience the issue :shrug: 
One of the few benefits that I'm still with Qt6.2.3? :grimacing:

**Comment by daschuer** [comment]
@uklotzde thank you for testing and confirming the fix. 

When looking to all these 2.5.1 bugs, it is obviously that the testing coverage in the beta branch is too low. We really need to work on a better quality during beta. 

Here we have two options, revert #13719 or merge this an release the long overdue 2.5.1 version. The first would be a mayor annoyance for me because the stuttering library scrolling is really bad in case of a spinning HDD. The later means there getting after 2.5.1 tag and waiting for more testing. 

I vote for merging because the issue could be clearly reproduced and identified in a backtrace and the fix has been confirmed now by @uklotzde. #13719 itself  has already received a good portion of testing and code review.

**Comment by ywwg** [comment]
Unfortunately I am on vacation without my personal laptop so I cannot test. I think we need to consider which risk is greater:
1. The current state, where mixxx can freeze during analysis
2. Some possible bug with this new version -- could it introduce something even worse?

I would say unless there is a fear that this fix causes larger problems, like data corruption or freezes during performance, it is worth taking that risk to prevent the known bug in the current state.  Maybe let's have @acolombier look at it as the person who has also worked on this code recently?

File: src/library/trackcollection.cpp [hunk 1]
```diff
@@ -23,11 +23,6 @@ TrackCollection::TrackCollection(
           m_trackDao(m_cueDao, m_playlistDao,
                      m_analysisDao, m_libraryHashDao, pConfig) {
     // Forward signals from TrackDAO
-    connect(&m_trackDao,
-            &TrackDAO::trackClean,
-            this,
-            &TrackCollection::trackClean,
-            /*signal-to-signal*/ Qt::DirectConnection);
```
Comment (acolombier) [inline src/library/trackcollection.cpp:30]: Was that the root cause of the UI freeze?

**Comment by acolombier** [comment]
> I vote for merging

I think the risk is worth the reward here. 

I've only briefly checked the code so far, and it looks good. I'll try to have a deeper look sometime today.

File: src/library/trackcollection.cpp (hunk 1 above)
Comment (daschuer) [reply src/library/trackcollection.cpp:30]: No, that was just unused code. I comment inline.

File: src/library/basetrackcache.cpp [hunk 2]
```diff
@@ -228,10 +191,6 @@ bool BaseTrackCache::updateIndexWithQuery(const QString& queryString) {
         qDebug() << "updateIndexWithQuery issuing query:" << queryString;
     }
 
-    if (m_bIsCaching) {
-        resetRecentTrack();
```
Comment (daschuer) [inline src/library/basetrackcache.cpp:232]: This was the root cause of the deadlock. This gets called in responds of another track that is evicted form cache. 
Here another track is evicted form cache leading to a recursive call.

**Comment by daschuer** [comment]
@acolombier merge?

**Review by acolombier — APPROVED** [review]
LGTM

**Comment by acolombier** [comment]
Thank you!

**Comment by daschuer** [comment]
Juchu! Thank you.
