### PR TITLE
Playlists & crates: restore previous search

### LINKED ISSUE #11015: Search query is cleared when clicking another playlist or crate
### Bug Description

* select a playlist, type a search query
* select another playlist (no query)
* reselect 1st playlist: query is cleared

Solutions
1. remember query per feature (one query for all items)
2. store query per item

### Version

2.3 + 2.4-alpha

### OS

_No response_

### PR DESCRIPTION
**Pull request by ronso0**
Previous search queries are restored when selecting a playlist or crate.

To make users aware of this new feature we should finally highlight the searchbar when it's active #7922

Closes #11015 (see also #9522)

### CODE REVIEW

File: src/library/playlisttablemodel.h [hunk 1]
```diff
@@ -40,4 +40,5 @@ class PlaylistTableModel final : public TrackSetTableModel {
 
     int m_iPlaylistId;
     bool m_keepDeletedTracks;
+    QHash<int, QString> m_searchTexts;
```
Comment (ronso0) [inline src/library/playlisttablemodel.h:43]: I guess this could be moved to [TrackSetmodel](**https://github.com/mixxxdj/mixxx/blob/main/src/library/trackset/tracksettablemodel.h**) but I didn't dare to touch that minimal class..

File: src/library/playlisttablemodel.cpp [hunk 2]
```diff
@@ -170,7 +175,16 @@ void PlaylistTableModel::setTableModel(int playlistId) {
             LIBRARYTABLE_ID,
             columns,
             m_pTrackCollectionManager->internalCollection()->getTrackSource());
-    setSearch("");
+
+    // Restore search text
+    QString prevSearch("");
```
Comment (daschuer) [inline src/library/playlisttablemodel.cpp:180]: QString is empty by default. 
```suggestion
    QString prevSearch;
```

File: src/library/playlisttablemodel.cpp [hunk 3]
```diff
@@ -170,7 +175,16 @@ void PlaylistTableModel::setTableModel(int playlistId) {
...
+    if (m_iPlaylistId != -1) {
+        auto it = m_searchTexts.constFind(m_iPlaylistId);
+        if (it != m_searchTexts.constEnd()) {
+            prevSearch = it.value();
+        }
+    }
+    setSearch(prevSearch);
```
Comment (daschuer) [inline src/library/playlisttablemodel.cpp:187]: I think we can simplify this even more, because m_iPlaylistId will never be -1 and even if, the QHash will return an empty QString: 
```suggestion
    setSearch(m_searchTexts.value(m_iPlaylistId));
```

**Review by daschuer — CHANGES_REQUESTED** [review]
Some ideas for improvement

**Comment by daschuer** [comment]
Is this a 2.3 fix?

File: src/library/playlisttablemodel.cpp (hunk 3 above)
Comment (ronso0) [reply src/library/playlisttablemodel.cpp:187]: I tried that first but it's not working because in the called code the string is tested for `isNull` (not `isEmty`).
I can check whether `isEmpty` can be used down the line.

Comment (ronso0) [reply src/library/playlisttablemodel.cpp:187]: QString() didn't work because of
https://github.com/mixxxdj/mixxx/blob/3aa2318e34f306808420a6707857dabd37d0bea2/src/widget/wsearchlineedit.cpp#L456-L464

oh, this was you, eight years ago : ) 
https://github.com/mixxxdj/mixxx/commit/54f71ea7b8e5d6e87ad9132bcf7fdfe2a7c8372a#diff-5112567721f7d2345d3df3bdf1e73badf29f2feb7796f069777b54b949c910feL120

I'll remove the isNull branch. It is not required anymore since `disableSearch` is called explicitly where required.

Comment (ronso0) [reply src/library/playlisttablemodel.cpp]: done.

**Review by daschuer — APPROVED** [review]
LGTM, Thank you.
