### PR TITLE
Fix update of play count after removing tracks from history playlist

### LINKED ISSUE #12046: `library.timesplayed` lost for entire database after upgrade
### Bug Description

I'm not sure in what commit exactly (I don't have the time to bisect right now), but somewhere the `timesplayed` for all tracks in my 6K track library have been nuked. Not a huge issue for me as I have backups as well, but not something that can stay in 2.4 in the release. I have confirmed that the issue affects the DB and not the hardware (as `SELECT COUNT(*) FROM library where timesplayed > 0` is only the dozen or so played recently. I'm not sure what action caused, nor do I think I have the log from when this happened as I only realized it after the fact.
Can anybody reproduce?
I'll tag this as critical for now as this counts as data loss imo.

### Version

2.4-beta-163-g420b678c5e-modified (fix/gh11923)

### OS

Fedora Linux 38

### PR DESCRIPTION
**Pull request by uklotzde**
@Swiftb0y: Fixes #12046 and #12256.

### CODE REVIEW

File: tools/mixxxdb_cleanup.sql [hunk 1]
```diff
@@ -47,6 +47,26 @@ DELETE FROM PlaylistTracks WHERE track_id NOT IN (SELECT id FROM library);
...
+SET timesplayed=q.timesplayed,last_played_at=q.last_played_at
+FROM (
+    SELECT
+    PlaylistTracks.track_id as id,
+    COUNT(PlaylistTracks.track_id) as timesplayed,
+    MAX(PlaylistTracks.pl_datetime_added) as last_played_at
+    FROM PlaylistTracks
+    JOIN Playlists
+    ON PlaylistTracks.playlist_id=Playlists.id
+    WHERE Playlists.hidden=2
```
Comment (Swiftb0y) [inline tools/mixxxdb_cleanup.sql:65]:
```suggestion
    -- PlaylistDAO::PLHT_SET_LOG=2
    WHERE Playlists.hidden=2 
```

**Review by Swiftb0y — COMMENTED** [review]
I'm not well versed in SQL so I would've never spotted this issue during code review. Looking very carefully at your changes, I see how the previous code was buggy and this is fixing it. Thank you. Almost LGTM

**Review by Swiftb0y — APPROVED** [review]
Thank you very much for this fix. I doubt this would've gotten fixed by anyone else. LGTM

**Comment by Swiftb0y** [comment]
Waiting for CI, just to be sure.
