### PR TITLE
DlgPrefSound: Fix fetching of sample rate

### LINKED ISSUE #11949: Regression: Audio buffer size UI shows `inf ms` on macOS
### Bug Description

Mixxx reports bogus audio latencies with the Core Audio backend (though it still seems to work fine):

image

According to my regression finder, this was introduced between 8d0ded74be (good) and e4f2e050db (bad), see [this diff](https://github.com/mixxxdj/mixxx/compare/8d0ded74be240f1249500b8b9484c00031e22f3e...e4f2e050dbf793fb195902328413ced50d1a46aa). Looking at the commits it seems as if it was introduced by
- #11904

cc @Holzhaus 

### Version

2.5-alpha-98-gf4692aa5ea (Qt 6.5.2)

### OS

macOS 13.5

### PR DESCRIPTION
**Pull request by fwcd**
Fixes #11949, i.e. causes audio buffer sizes to be displayed correctly again:

image

The issue was that the sample rate combo box was still queried for a double, while underlying data already used the `SampleRate` type, causing it to presumably default to 0 and thus result in divisions by zero. This was likely an oversight in #11904.

### CODE REVIEW

File: src/preferences/dialog/dlgprefsound.cpp [hunk 1]
```diff
@@ -608,7 +608,8 @@ void DlgPrefSound::updateAudioBufferSizes(int sampleRateIndex) {
                 static_cast<unsigned int>(SoundManagerConfig::
                                 JackAudioBufferSizeIndex::Size4096fpp));
     } else {
-        double sampleRate = sampleRateComboBox->itemData(sampleRateIndex).toDouble();
+        double sampleRate = sampleRateComboBox->itemData(sampleRateIndex)
+                                    .value<mixxx::audio::SampleRate>();
```
Comment (Swiftb0y) [inline src/preferences/dialog/dlgprefsound.cpp:612]: lets add a debug assert to avoid the issue with the default construction in the future.
```suggestion
        DEBUG_ASSERT(sampleRateComboBox->itemData(sampleRateIndex).canConvert<mixxx::audio::SampleRate>());
        double sampleRate = sampleRateComboBox->itemData(sampleRateIndex)
                                    .value<mixxx::audio::SampleRate>().toDouble();
```

**Review by Swiftb0y — CHANGES_REQUESTED** [review]

**Comment by Swiftb0y** [comment]
thank you, please run pre-commit and squash.

**Review by Holzhaus — APPROVED** [review]
LGTM, thank you!

**Review by Swiftb0y — APPROVED** [review]
LGTM thank you
