### PR TITLE
Musicbrainz: Improved messages in case of empty results 

### LINKED ISSUE #13666: "Could not find this track in the MusicBrainz database." in case the lokal track file is not accessible
### Bug Description

This is a misleading message, leading the user in the wrong direction. 

### Version

2.4.1

### OS

Ubuntu Focal

### PR DESCRIPTION
**Pull request by daschuer**
Allow to use different messages in case Musikbrainz lookup ends without results.
This fixes #13666

Since this PR moves a translatable text form on object to another we need an Transifex cycle to not loose the translation in the stable 2.4 branch.

### CODE REVIEW

File: src/musicbrainz/tagfetcher.cpp [hunk 1]
```diff
@@ -165,7 +166,8 @@ void TagFetcher::slotAcoustIdTaskSucceeded(
 
         emit resultAvailable(
                 std::move(pTrack),
-                QList<mixxx::musicbrainz::TrackRelease>());
+                {},
+                tr("Could not identify track through Acoustid."));
```
Comment (acolombier) [inline src/musicbrainz/tagfetcher.cpp:170]: Nit: casing of `AcoustID`

**Review by acolombier — APPROVED** [review]
LGTM

Just a small optional nit

File: src/musicbrainz/tagfetcher.cpp [hunk 2]
```diff
@@ -299,9 +301,15 @@ void TagFetcher::slotMusicBrainzTaskSucceeded(
...
+    QString whyEmptyMessage;
+    if (guessedTrackReleases.empty()) {
+        whyEmptyMessage = tr("Could not find this track in the MusicBrainz database.");
+    }
+
     emit resultAvailable(
             std::move(pTrack),
-            std::move(guessedTrackReleases));
+            std::move(guessedTrackReleases),
+            whyEmptyMessage);
```
Comment (Swiftb0y) [inline src/musicbrainz/tagfetcher.cpp:312]: the check is clunky and unnecessary from what I can tell. Can you just inline like you did with the other calls?

Comment (Swiftb0y) [reply src/musicbrainz/tagfetcher.cpp:312]: so just
```suggestion
    emit resultAvailable(
            std::move(pTrack),
            std::move(guessedTrackReleases),
            tr("Could not find this track in the MusicBrainz database.");
```

Comment (Swiftb0y) [reply src/musicbrainz/tagfetcher.cpp:312]: if unconditionally looking up the translated string presents too much overhead, we can also introduce an enum and switch on it only in the failure case (in `DlgTagFetcher::fetchTagFinished`).

Comment (daschuer) [reply src/musicbrainz/tagfetcher.cpp:312]: This way we add the text even if we have a list of tracks. I think it is clearer to have to dedicated emmit calls.

Comment (Swiftb0y) [reply src/musicbrainz/tagfetcher.cpp:312]: yes, one in case of success and a different one in case of error would also be better.

File: src/musicbrainz/tagfetcher.cpp (hunk 1 above)
Comment (daschuer) [reply src/musicbrainz/tagfetcher.cpp]: I have also fixed another occourenc, and will also fix Translations after merge.

File: src/musicbrainz/tagfetcher.cpp (hunk 2 above)
Comment (Swiftb0y) [reply src/musicbrainz/tagfetcher.cpp]: I rather thought of two different signals (with differing parameters), but the current solution works too ig. not widening the scope too much.

**Review by Swiftb0y — APPROVED** [review]
LGTM. Thanks you. Waiting for CI.

**Comment by daschuer** [comment]
clazy fixed

**Comment by ronso0** [comment]
Thank you!
