### PR TITLE
Fix reading metadata for some file extensions

### LINKED ISSUE #13205: Metadata is not read from files with the wrong extension
### Bug Description

Mixxx uses already the mime type when encoding the file. This does however not work for metadata extraction and should be fixed. 

### Version

_No response_

### OS

_No response_

### PR DESCRIPTION
**Pull request by daschuer**
This replaces all file type guessing code form the file extension, by using the normalized file type stored in the Track object. 
This makes sure all parts are using the same file type, even if the extension is wrong. 

This fixes #13205

### CODE REVIEW

File: src/track/taglib/trackmetadata_file.cpp [hunk 1]
```diff
@@ -45,36 +45,70 @@ void readAudioProperties(
...
+            TypePair{"module"_L1, FileType::Mod},
+            TypePair{"nst"_L1, FileType::Mod},
+            TypePair{"wow"_L1, FileType::Mod},
+            TypePair{"s3m"_L1, FileType::S3M},
+            TypePair{"xm"_L1, FileType::XM},
+            TypePair{"dsf"_L1, FileType::DSF},
+            TypePair{"dff"_L1, FileType::DSDIFF},
+            TypePair{"dsdiff"_L1, FileType::DSDIFF}};
+
+    auto it = std::find_if(lookupTable.cbegin(),
```
Comment (acolombier) [inline src/track/taglib/trackmetadata_file.cpp:108]: Looks like this could be more specific
```suggestion
    const auto *it = std::find_if(lookupTable.cbegin(),
```

**Review by acolombier — COMMENTED** [review]
Could it be worth adding one or few test case to ensure the behaviour and prevent potential regression?

File: src/test/soundproxy_test.cpp [hunk 2]
```diff
@@ -1086,3 +1087,14 @@ TEST_F(SoundSourceProxyTest, freeModeGarbage) {
         break;
     }
 }
+
+TEST_F(SoundSourceProxyTest, taglibStringToEnumFileType) {
+    for (const auto& fileType : SoundSourceProxy::getSupportedFileTypes()) {
```
Comment (acolombier) [inline src/test/soundproxy_test.cpp:1092]: clazy here

File: src/track/taglib/trackmetadata_file.cpp [hunk 3]
```diff
@@ -45,36 +45,70 @@ void readAudioProperties(
...
+    DEBUG_ASSERT(!fileType.isEmpty());
+
+    struct TypePair {
+        QLatin1String strType;
+        FileType eType;
+    };
+
+    // This table is aligned with detectByExtension() in fileref.cpp
+    constexpr std::array lookupTable = {
+            TypePair{"mp3"_L1, FileType::MPEG},
```
Comment (Swiftb0y) [inline src/track/taglib/trackmetadata_file.cpp:68]: one day we should think about introducing a "minimal perfect hash function"-based approach for LUTs like these.

Comment (Swiftb0y) [reply src/track/taglib/trackmetadata_file.cpp:68]: you'll also need to make it static, otherwise the compiler is more likely to choose to create it at runtime. 
```suggestion
    // This table is aligned with detectByExtension() in fileref.cpp
    constexpr static std::array lookupTable = {
            TypePair{"mp3"_L1, FileType::MPEG},
```

File: src/sources/metadatasourcetaglib.h [hunk 4]
```diff
@@ -7,16 +7,11 @@ namespace mixxx {
...
-            : m_fileName(fileName),
-              m_fileType(taglib::getFileTypeFromFileName(fileName)) {
-    }
     MetadataSourceTagLib(
             const QString& fileName,
-            taglib::FileType fileType)
+            const QString& fileType)
             : m_fileName(fileName),
-              m_fileType(fileType) {
+              m_fileType(taglib::stringToEnumFileType(fileType)) {
```
Comment (Swiftb0y) [inline src/sources/metadatasourcetaglib.h:14]: whats the advantage of taking a string here instead of shifting the conversion duty to the caller? This smells [stringly-typed](https://wiki.c2.com/?StringlyTyped)

Comment (Swiftb0y) [reply src/sources/metadatasourcetaglib.h:14]: fyi, two of the other three comments were redundant if this would avoid strings better.

File: src/track/serato/tags.cpp [hunk 5]
```diff
@@ -82,7 +83,7 @@ double SeratoTags::guessTimingOffsetMillis(
     // PR for more detailed information:
     // https://github.com/mixxxdj/mixxx/pull/2119
     double timingOffset = 0;
-    if (taglib::getFileTypeFromFileName(filePath) == taglib::FileType::MP3) {
+    if (fileType == "mp3") {
```
[the remark this answers is not in the document]
Comment (daschuer) [reply src/track/serato/tags.cpp:86]: Qt has explicit an operator for it and it is faster than using a QStringLiteral:
https://github.com/qt/qtbase/blob/5686af295c98a5ed4b0793ad0098cef76f39a2d7/src/corelib/text/qstring.h#L1376

File: src/sources/metadatasourcetaglib.h (hunk 4 above)
Comment (daschuer) [reply src/sources/metadatasourcetaglib.h:14]: We have the duality of a string typed fileType used in Soundsource classes outside of Taglib and the enum inside Taglib. We still need the "fileType" as string, because it holds the file extension in case the type has not been normalized.  This is a left over from the legacy when Mixxx uses just the file extension.

I have moved the conversion here, to hide all implementation details of MetadataSourceTagLib and keep the taglib includes in its cpp file. 
Else it would be here: 
https://github.com/mixxxdj/mixxx/blob/d1c09b5c5006ef674cb4ab8eaa4fb617200c79d7/src/sources/soundsource.cpp#L84-L88

**Comment by daschuer** [comment]
Done

File: src/track/taglib/trackmetadata_file.cpp [hunk 6]
```diff
@@ -45,36 +45,70 @@ void readAudioProperties(
...
+            TypePair{"module"_L1, FileType::Mod},
+            TypePair{"nst"_L1, FileType::Mod},
+            TypePair{"wow"_L1, FileType::Mod},
+            TypePair{"s3m"_L1, FileType::S3M},
+            TypePair{"xm"_L1, FileType::XM},
+            TypePair{"dsf"_L1, FileType::DSF},
+            TypePair{"dff"_L1, FileType::DSDIFF},
+            TypePair{"dsdiff"_L1, FileType::DSDIFF}};
+
+    const auto it = std::find_if(lookupTable.cbegin(),
```
Comment (acolombier) [inline src/track/taglib/trackmetadata_file.cpp:108]: clang-tidy

```suggestion
    const auto *const it = std::find_if(lookupTable.cbegin(),
```

File: src/track/serato/tags.cpp (hunk 5 above)
[the remark this answers is not in the document]
Comment (Swiftb0y) [reply src/track/serato/tags.cpp:86]: good catch

File: src/track/taglib/trackmetadata_file.cpp (hunk 6 above)
Comment (daschuer) [reply src/track/taglib/trackmetadata_file.cpp]: This seems to be a false positive. I will try the explicit type.

Comment (daschuer) [reply src/track/taglib/trackmetadata_file.cpp]: I give up, following clang-tidy with the pointer "cast"

**Comment by daschuer** [comment]
Done

**Comment by daschuer** [comment]
Did not work with MSVC so I have now decided to just silence clang_tidy

**Comment by daschuer** [comment]
@acolombier Is this now ready to merge?

**Review by acolombier — APPROVED** [review]
LGTM!
