### PR TITLE
(fix) avoid crash after removing Quick Link

### LINKED ISSUE #8270: 1.12 removing a quick link can lead to crash
Reported by: **[daschuer](https://github.com/daschuer)**
Date: 2015-10-26T12:31:28Z
Status: Fix Released
Importance: Critical
Launchpad Issue: [lp1510068](https://bugs.launchpad.net/bugs/1510068)

---

This was reported here: 
http://www.mixxx.org/forums/viewtopic.php?f=3&t=7593

### PR DESCRIPTION
**Pull request by ronso0**
workaround for #8270, happening with Qt 6.2.3

(... and other minor fixes for BrowseFeature, please see individual commits)

Apparently, the checks for `item != nullptr` and `item->getData().isValid()` don't suffice.
The crash happens afterwards with `qDebug() << item->getLabel() << item->getData().toString()`, so apparently the item has been removed in the meantime.

Simply don't call `onLazyChildExpandation()` after the context menu was closed and a Quick Link might have been removed.
Tbh I don't understand reasoning to expand the item after the menu closed in the first place. Regardless if the menu is used or closed right away, this is basically expand on right-click.

I removed those calls entirely, simply to avoid any further surprises.
___
Another bug I noticed while working on #14514 is that "Refresh directory tree" doesn't work for items other than first-level child items (and probably never did :grimacing: since #12908).
Fixed by using the last right-clicked index, too, as we do in other library features.

### CODE REVIEW

**Comment by ronso0** [comment]
I can split the commit into the actual workaround and other tweaks if desired.

File: src/library/browse/browsefeature.cpp [hunk 1]
```diff
@@ -411,27 +426,29 @@ void BrowseFeature::onLazyChildExpandation(const QModelIndex& index) {
...
+    // NOTE(ronso0) Still relevant with 2.5.0 and Qt6. These checks don't seem
+    // to suffice, it would crash after removing a quick link.
+    // Just don't call this after right-clicking a quick link.
     if (!index.isValid()) {
         return;
     }
-    TreeItem *item = static_cast<TreeItem*>(index.internalPointer());
-    if (!(item && item->getData().isValid())) {
+    TreeItem* pItem = static_cast<TreeItem*>(index.internalPointer());
+    if (!(pItem && pItem->getData().isValid())) {
```
Comment (ronso0) [inline src/library/browse/browsefeature.cpp:436]: Interestingly, if I add various qDebug() calls (log item data and label etc.), the item pointer seems to remain intact and the existing qDebug() call below doesn't crash anymore :shrug:

Would the delete management of `std::shared_ptr`/`unique_ptr` instead of plain * keep the item intact?

Comment (daschuer) [reply src/library/browse/browsefeature.cpp:436]: I have no clue what could be the reason. The internalPointer() is however a void* only without smart pointer capabilities. You get here only the address where the object has been when stored. There is no smart grantee, that the object TreeItem is still there. The pointer is only "borrowed", someone else need to take care that the object is kept valid.

Comment (ronso0) [reply src/library/browse/browsefeature.cpp:436]: Okay.
I removed the call as it was unnecessary in the first place, so I think this is ready.
We just need to make sure not to call it after/while modifying the tree.

**Comment by daschuer** [comment]
I have already a review in progress.

**Review by daschuer — CHANGES_REQUESTED** [review]
For my understanding is that the root cause if the crash is the borrowed InternalPointer() in QModelIndex.

All later checks are pointless, because they succeed either (the pointer will never be null) or are also crashing because of call to the internal printer hidden behind the QT API. 

The solution presented here to clear the stored value after using works only if it is actually used. 
But there is no guarantee that such an action happens. 

It would be better, if we effectively clear the pointer whenever the side bar tree structure is edited and there's a chance for a dangling pointer. 

This seems to be more safe than all other not working checks. 

I have not looked into a possible implementation but if you like, I can do a PR to your branch. 

1. Use only m_lastRightClickIndex 
2. Listen to a model changes we signal or such and reset the value
3. Temove misleading checks (make them asserts) 

What do you think?

**Comment by ronso0** [comment]
Thanks for taking a look!

> I have not looked into a possible implementation but if you like, I can do a PR to your branch.

Yes, please. I think I get the idea, but I'm not sure about the QModelIndex <--> TreeItem relation.

IIUC the issue would be fixed if we'd listen to the tree model's signals `rowsAboutToBe[Removed|Inserted|Moved]` and clear the lastRightClickedItem/Index. Only if it is affected? (it is not if rows are added below, but that's currently cumbersome to figure out (it's a bit easier with [`TreeItem::childLevel()` from #14508](https://github.com/mixxxdj/mixxx/pull/14508/files#diff-d00fac3236871c8296e4a07c7824ff97eb43d2395e0892b583bca8291f52002d) but still..)

**Comment by daschuer** [comment]
Here it is: 
https://github.com/ronso0/mixxx/pull/92

**Review by daschuer — APPROVED** [review]
LGTM, Thank you.

File: src/library/browse/browsefeature.cpp [hunk 2]
```diff
@@ -52,6 +52,18 @@ BrowseFeature::BrowseFeature(
...
+            this,
+            &BrowseFeature::invalidateRightClickIndex);
+    connect(m_pSidebarModel,
+            &QAbstractItemModel::rowsAboutToBeInserted,
+            this,
+            &BrowseFeature::invalidateRightClickIndex);
+    connect(m_pSidebarModel,
+            &QAbstractItemModel::modelAboutToBeReset,
+            this,
+            &BrowseFeature::invalidateRightClickIndex);
```
Comment (ronso0) [inline src/library/browse/browsefeature.cpp:66]: This breaks [`slotRefreshDirectoryTree()`](https://github.com/mixxxdj/mixxx/blob/f356d49b0638abd3807c465eab6202236d3307b0/src/library/browse/browsefeature.cpp#L249) where we call
`onLazyChildExpandation(m_lastRightClickedIndex);`
[`TreeItemModel::insertTreeItemRows()`](https://github.com/mixxxdj/mixxx/blob/f356d49b0638abd3807c465eab6202236d3307b0/src/library/treeitemmodel.cpp#L170) has now an invalid index (invalid parent TreeItem) and inserts the new rows at row 0.

Apparently it's not required to reset the QModelIndex in that case since `onLazyChildExpandation(index)` works flawlessly even tough this also alters the model (below the index).

Possible fixes:
1. revert this commit -- and test all cases that caused crashes earlier
(see #8270 / #12817)
2. in `slotRefreshDirectoryTree()`, copy `m_lastRightClickedIndex` and call `onLazyChildExpandation(copy)` -- works, no crash

@daschuer What do you think?
