### PR TITLE
AutoDJ: handle "enabled" CO change requests like clicks on the GUI button

### LINKED ISSUE #11494: AutoDJ shortcut (SHIFT+F12) and "symbol" turns on, but feature doesn't turn on due to "two decks playing at the same time."
### Bug Description

I'm using the LateNight PaleMoon skin.

Prerequisites to replicating the problem:
1. Have two decks play music
2. Enter the "AutoDJ" section from the library tree
3. Have a keyboard that can enable/disable the AutoDJ feature by pressing SHIFT+F12

Procedure:
When two decks are both playing music, AutoDJ cannot be enabled from the on-screen gui "AutoDJ button."
However, pressing SHIFT+F12 while two decks are playing songs will allow the AutoDJ symbol to turn on, but the AutoDJ feature will remain off despite the symbol staying on (as if the feature was on and working).

Recommendation:
If the AutoDJ feature cannot turn on due to two songs playing, the AutoDJ symbol should not turn on until the feature parameters are met.

The video below demonstrates the bug. The cursor will demonstrate and highlight these concerns.
[Screencast from 2023-04-17 18-25-17 (converted).webm](https://user-images.githubusercontent.com/57690587/232711557-31900ccf-d419-47f6-8931-f124db60438e.webm)

### Version

2.3.4

### OS

Fedora Linux

### PR DESCRIPTION
**Pull request by ronso0**
otherwise, if AutoDJ refuses to start because of unmet conditions, no error messages are shown and the CO remains in 'enabled' state.

Fixes #11494

### CODE REVIEW

**Comment by daschuer** [comment]
I experience a stack overflow during due a recursive loop during testing: 
```
#57 AutoDJProcessor::toggleAutoDJ(bool) (this=0x0, enable=<optimized out>)
    at ../../src/library/autodj/autodjprocessor.cpp:432
#58 0x0000555555dfed91 in DlgAutoDJ::toggleAutoDJButton(bool)
    (this=0x55556a42c4a0, enable=<optimized out>)
    at ../../src/library/autodj/dlgautodj.cpp:279
#59 0x00007ffff3cbf328 in QtPrivate::QSlotObjectBase::call(QObject*, void**)
    (a=0x7fffff801a70, r=0x55556a42c4a0, this=0x55556a4ba1e0)
    at ../../include/QtCore/../../src/corelib/kernel/qobjectdefs_impl.h:394
#60 QMetaObject::activate(QObject*, int, int, void**)
    (sender=0x55555b644550, signalOffset=<optimized out>, local_signal_index=<optimized out>, argv=<optimized out>) at kernel/qobject.cpp:3784
#61 0x0000555555df2086 in AutoDJProcessor::autoDJStateChangeRequest(bool)
    (this=<optimized out>, _t1=<optimized out>)
    at mixxx-lib_autogen/include/moc_autodjprocessor.cpp:805
#62 0x00007ffff3cbf328 in QtPrivate::QSlotObjectBase::call(QObject*, void**)
    (a=0x7fffff801ba0, r=0x55555b644550, this=0x55555b63e950)
    at ../../include/QtCore/../../src/corelib/kernel/qobjectdefs_impl.h:394
#63 QMetaObject::activate(QObject*, int, int, void**)
    (sender=0x55555b6682d0, signalOffset=<optimized out>, local_signal_index=<optimized out>, argv=<optimized out>) at kernel/qobject.cpp:3784
#64 0x00005555559a5d67 in ControlDoublePrivate::valueChangeRequest(double)
    (this=this@entry=0x55555b6682d0, _t1=<optimized out>)
--Type <RET> for more, q to quit, c to continue without paging--
    at mixxx-lib_autogen/include/moc_control.cpp:151
#65 0x00005555559a6658 in ControlDoublePrivate::set(double, QObject*)
    (this=0x55555b6682d0, value=<optimized out>, pSender=0x55555b63f4c0)
    at ../../src/control/control.cpp:208
#66 0x0000555555df6b73 in ControlObject::set(double)
    (value=1, this=<optimized out>) at ../../src/control/controlobject.h:83
#67 AutoDJProcessor::toggleAutoDJ(bool) (this=0x0, enable=<optimized out>)
    at ../../src/library/autodj/autodjprocessor.cpp:432
```

**Comment by daschuer** [comment]
The loop can be broken by m_pEnabledAutoDJ->setAndConfirm() inside AutoDJProcessor::toggleAutoDJ() maybe we also need to adjust the checks of the m_pEnabledAutoDJ->get(), because it returns now the confirmed value and not like before unconfirmed value.

**Review by daschuer — CHANGES_REQUESTED** [review]
.

**Comment by ronso0** [comment]
Yep, I agree. I simply forgot to change `set` to `setAndConfirm`.

**Comment by ronso0** [comment]
The previous fix / hack with the signal sent to DlgAutoDJ and back to AutoDJPrcessor felt too much like a ahck so I tried to fix the root cause by _emitting_ an error code signal (instead of return values).

File: src/library/autodj/autodjprocessor.cpp [hunk 1]
```diff
@@ -419,18 +424,15 @@ AutoDJProcessor::AutoDJError AutoDJProcessor::toggleAutoDJ(bool enable) {
 
         TrackPointer nextTrack = getNextTrackFromQueue();
         if (!nextTrack) {
-            qDebug() << "Queue is empty now";
-            if (m_pEnabledAutoDJ->get() != 0.0) {
-                m_pEnabledAutoDJ->set(0.0);
-            }
+            qDebug() << "Queue is empty now, disable Auto DJ";
+            m_pEnabledAutoDJ->setAndConfirm(0.0);
```
Comment (ronso0) [inline src/library/autodj/autodjprocessor.cpp:428]: I think we don't need these in the `enable` anymore.
Didn't look close enough, yet, to be sure.

File: src/library/autodj/autodjprocessor.cpp [hunk 2]
```diff
@@ -419,18 +424,15 @@ AutoDJProcessor::AutoDJError AutoDJProcessor::toggleAutoDJ(bool enable) {
...
             emitAutoDJStateChanged(m_eState);
-            return ADJ_QUEUE_EMPTY;
+            emit autoDJError(ADJ_QUEUE_EMPTY);
```
Comment (ronso0) [inline src/library/autodj/autodjprocessor.cpp:430]: this and `ADJ_OK` are not handled (as before) but I kept them.

File: src/library/autodj/dlgautodj.cpp [hunk 3]
```diff
@@ -270,29 +275,30 @@ void DlgAutoDJ::fadeNowButton(bool) {
 }
 
 void DlgAutoDJ::toggleAutoDJButton(bool enable) {
-    AutoDJProcessor::AutoDJError error = m_pAutoDJProcessor->toggleAutoDJ(enable);
+    m_pAutoDJProcessor->toggleAutoDJ(enable);
+}
+
+// TODO If there's a way to migrate the translations move this
+// to AutoDJProcessor in order to keep this class minimal
+void DlgAutoDJ::autoDJError(AutoDJProcessor::AutoDJError error) {
```
Comment (ronso0) [inline src/library/autodj/dlgautodj.cpp:283]: I have no experience with Transifex: is it smart enough to keep the existing translations?

File: src/library/autodj/dlgautodj.cpp [hunk 4]
```diff
@@ -270,29 +275,30 @@ void DlgAutoDJ::fadeNowButton(bool) {
...
     switch (error) {
     case AutoDJProcessor::ADJ_NOT_TWO_DECKS:
         QMessageBox::warning(nullptr,
                 tr("Auto DJ"),
                 tr("Auto DJ requires two decks assigned to opposite sides of the crossfader."),
                 QMessageBox::Ok);
-        // Make sure the button becomes unpushed.
-        pushButtonAutoDJ->setChecked(false);
```
Comment (ronso0) [inline src/library/autodj/dlgautodj.cpp:281]: here and below: obsolete, since `AutoDJProcessor::autoDJStateChanged` signal >> `DlgAutoDJ::autoDJStateChanged` updates the GUI

File: src/library/autodj/dlgautodj.cpp (hunk 3 above)
Comment (daschuer) [reply src/library/autodj/dlgautodj.cpp:283]: Yes, as long as the original string and the name of the surrounding QObject is not changed.

**Comment by ronso0** [comment]
In the first run I didn't build the tests and didn't notice they require the return value.

This is now unchanged and the error codes are emitted additionally _after_ the new/unchanged AutoDJ state is emitted to update the GUI. The separate error handling also allows to show error messages in some yet uncovered situations.

File: src/library/autodj/autodjprocessor.cpp [hunk 5]
```diff
@@ -625,7 +629,11 @@ void AutoDJProcessor::crossfaderChanged(double value) {
                     }
                     pToDeck->play();
                 } else {
+                    // TODO Is this also only possible if the user changed the
+                    // deck orientation?
```
Comment (daschuer) [inline src/library/autodj/autodjprocessor.cpp:633]: This happens if the track in the To Deck has been ejected or shorter than 200 ms.

**Review by daschuer — CHANGES_REQUESTED** [review]
LGTM and works good. 
Can you please remove the question in the comment, once it is clarified?

File: src/library/autodj/autodjprocessor.cpp (hunk 5 above)
Comment (ronso0) [reply src/library/autodj/autodjprocessor.cpp:633]: Okay, I understood the above condition, and it seems 'eject' and a manually loaded, very short track could be the only cause, since IIUC tracks shorter than `kMinimumTrackDurationSec` are skipped https://github.com/mixxxdj/mixxx/blob/0d5b4a79388afdb74cabc4eb19340844fb148b1c/src/library/autodj/autodjprocessor.cpp#L1223-L1228

If  AutoDJ stops unexpectedly a popup would be helpful to notify users.
But if that happens after user interaction (eject) we don't need it IMO
