### PR TITLE
glwaveformrenderbackground

### LINKED ISSUE #11164: Deck Waveform: Green background and flickering
### Bug Description

The deck waveform changes from a black to a green background after hitting play:

Screenshot from 2022-12-29 15-09-04

Eventually it switches back to black or even starts to flicker. The flickering occurs when moving the mouse over skin controls.

Mesa Intel® HD Graphics 530 (SKL GT2) on Fedora 37 / Mesa 22.3

### Version

2.4.0

### OS

Fedora 37

### PR DESCRIPTION
**Pull request by m0dB**
glwaveformrenderbackground  is a replacement for waveformrenderbackground, which uses glClear to clear the waveform widget. this is a potential fix for https://github.com/mixxxdj/mixxx/issues/11164

### CODE REVIEW

**Comment by Swiftb0y** [comment]
Thank you. I can confirm that this fixes #11164.

**Comment by Swiftb0y** [comment]
@uklotzde can you spare a couple minutes to confirm this fixes #11164 for you as well?

**Comment by uklotzde** [comment]
https://imgflip.com/i/7k4cx5

Maintaining 3 differing major branches is a PITA for everyone involved and waste of scarce resources. The project should be aware of the consequences of its decisions. Last time that I build 2.3.

**Review by uklotzde — APPROVED** [review]
@Swiftb0y Works for me.

**Comment by Swiftb0y** [comment]
Thank you. 2.3 will be retired soon. 2.3.5 will likely be our last 2.3 release before 2.4

File: src/waveform/renderers/glwaveformrenderbackground.cpp [hunk 1]
```diff
@@ -0,0 +1,25 @@
+#include "waveform/renderers/glwaveformrenderbackground.h"
+
+GLWaveformRenderBackground::GLWaveformRenderBackground(
+        WaveformWidgetRenderer* waveformWidgetRenderer)
+        : WaveformRenderBackground(waveformWidgetRenderer) {
+}
+
+GLWaveformRenderBackground::~GLWaveformRenderBackground() {
+}
```
Comment (Swiftb0y) [inline src/waveform/renderers/glwaveformrenderbackground.cpp:9]: empty virtual destructor. Just out of curiosity, is there ever a need for one? If not, why is it here?

File: src/waveform/renderers/glwaveformrenderbackground.cpp [hunk 2]
```diff
@@ -0,0 +1,25 @@
...
+
+    painter->beginNativePainting();
+    glClearColor(static_cast<float>(m_backgroundColor.redF()),
+            static_cast<float>(m_backgroundColor.greenF()),
+            static_cast<float>(m_backgroundColor.blueF()),
+            1.f);
+    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
+    painter->endNativePainting();
+
+    drawImage(painter);
```
Comment (Swiftb0y) [inline src/waveform/renderers/glwaveformrenderbackground.cpp:23]: why the drawImage?

File: src/waveform/renderers/glwaveformrenderbackground.cpp (hunk 1 above)
Comment (m0dB) [reply src/waveform/renderers/glwaveformrenderbackground.cpp:9]: because I copied waveformrenderbackground.cpp and it's there because I couldn't be bothered cleaning up code that isn't mine ;-) These empty destructors are all over the place. But I'll remove this one.

File: src/waveform/renderers/glwaveformrenderbackground.cpp (hunk 2 above)
Comment (Swiftb0y) [reply src/waveform/renderers/glwaveformrenderbackground.cpp:23]: Yeah, I'd prefer if the control flow was a little more visible here. I think it would be best if split into `drawImage` and `drawFlatColor` and a `shouldDrawImage`. Then plain `draw` would just be `if(shouldDrawImage()) {drawImage();} else {drawFlatColor()}; IMO thats pretty legible while still having clearly separated concerns.

Comment (m0dB) [reply src/waveform/renderers/glwaveformrenderbackground.cpp:23]: only that in the case of gl the glclear should always be done. but i'll add the conditional.

**Comment by daschuer** [comment]
I can confirm that the waveforms are still working @60 Hz on Ubuntu Focal and
openGL 4.3 (Mesa Intel(R) UHD Graphics (CML GT2))
Thank you for the fats fix.

File: src/waveform/renderers/glwaveformrenderbackground.cpp (hunk 2 above)
Comment (m0dB) [reply src/waveform/renderers/glwaveformrenderbackground.cpp]: done

**Comment by m0dB** [comment]
I have made a minor change based on @Swiftb0y review (aesthetic only, code execution should be identical).

File: src/waveform/renderers/glwaveformrenderbackground.cpp (hunk 1 above)
Comment (m0dB) [reply src/waveform/renderers/glwaveformrenderbackground.cpp]: done

**Review by Swiftb0y — APPROVED** [review]
LGTM. I highly thank you for helping us fix the issue. I highly doubt anyone else would've identified and contributed a potential fix as fast as you did in this PR.

**Comment by uklotzde** [comment]
@m0dB You contributions are greatly appreciated and needed to keep Mixxx alive.

**Comment by m0dB** [comment]
Thanks guys :-)

It sure helped that I have been deep down the waveform renderer rabbit hole!
