### PR TITLE
Fix regression Numark-Mixtrack-Platinum from #12021

### LINKED ISSUE #14571: [Main],vu_meter_left/right and peak_indicador_left/right not working on 2.6
### Bug Description

Hello.

I first reported this on zulip at https://mixxx.zulipchat.com/#narrow/channel/109171-development/topic/controller.20vumeters.2C.20new.20name.20not.20working

I believe there is a bug (or some merge issue) on main, because I've tested a few Mixxx 2.6 alphas, and the controls mentioned in the title are not working.

To put them in perspective, the original control names (And the names still documented in the Mixxx Controls manual entry) are VuMeterL/R VuMeter and PeakIndicatorL/R and PeakIndicator.

At some point, i think during 2.5 development, new names were added and a warning is printed in the logs about deprecated control names.

Now, if one tries to use the old names, they work, but the new names for Main do not. ( the new names work for ChannelN controls).

So first is to know what happened to those controls, and the second will be a need to update the manual accordingly.

### Version

2.6 alpha

### OS

Windows 10

### PR DESCRIPTION
**Pull request by JosepMaJAZ**
This fixes a small regression from PR #12021 that updated the vumeter COs to a new naming schema.

### CODE REVIEW

**Comment by ronso0** [comment]
Thank you! Please check why pre-commit is complaining.

File: res/controllers/Numark-Mixtrack-Platinum-scripts.js [hunk 1]
```diff
@@ -1413,13 +1413,13 @@ MixtrackPlatinum.vuCallback = function(value, group, control) {
             midi.sendShortMsg(0xBF, 0x45, level);
         }
     }
-    else if (group == '[Master]' && control == 'VuMeterL') {
+    else if (group == '[Main]' && control == 'vu_meter_left') {
```
Comment (Swiftb0y) [inline res/controllers/Numark-Mixtrack-Platinum-scripts.js:1416]: yeah, please fix the indent style while ur touching this line

Comment (JosepMaJAZ) [reply res/controllers/Numark-Mixtrack-Platinum-scripts.js:1416]: Actually, it is not the indent what it is complaining about.
It is complaining that the Script uses single quotes ' for strings rather than double quotes " .

**Comment by ronso0** [comment]
LGTM Squash & merge?

**Review by ronso0 — APPROVED** [review]
Looks good & has been confirmed working.
Thanks!

**Comment by ronso0** [comment]
Oh, the issue is already in 2.5.
Please rebase onto 2.5

**Comment by JosepMaJAZ** [comment]
It will need to wait for a week since i am not at home.
Of course, I will not mind if anyone creates a new PR.

**Comment by ronso0** [comment]
I rebased onto 2.5 and force-pushed to your fork.
2-line changeset is safe so I will not wait for CI

Thanks!

**Comment by ronso0** [comment]
FWIW I'm checking #12021 again and already found another issue:
aliases are only created for either the old group (`[Master]`) or for the same group + old keys (`VuMeter`), but not for
`[Master],vu_meter_l` etc., so this is broken, too:
https://github.com/mixxxdj/mixxx/pull/12021/files#diff-44744e6ca93321e904726ff6fab7d21287fda2463d0ee9b9c952442e92af7601

Will open a PR soon.

**Comment by Swiftb0y** [comment]
still have the MM1 (though the ch3/4 faders broke off). I can give it a quick test. make sure to ping me.

**Comment by ronso0** [comment]
Ha, I already fixed that en-passant in #12769
