### PR TITLE
Fix gain issue with cloned tracks

### LINKED ISSUE #10550: Changing tempo when using instant double and sync
Reported by: **[daschuer](https://github.com/daschuer)**
Date: 2021-10-07T17:58:08Z
Status: New
Importance: Undecided
Launchpad Issue: [lp1946385](https://bugs.launchpad.net/bugs/1946385)

---

When using instant double and sync is enabled on the source and target deck, the tempo changes every time you repeat the instant double action.
The issue has been recorded here https://github.com/mixxxdj/mixxx/pull/3944#issuecomment-917712679

### PR DESCRIPTION
**Pull request by daschuer**
This PR fixes #10550 Via a couple of single fixes regarding using the right data at the right time. 

This finally allows to play two cloned tracks with changing tempo without that the leader applies future or outdated tempo changes to the follower.

### CODE REVIEW

**Comment by JoergAtGithub** [comment]
Does this also fix #11788 ?

**Comment by daschuer** [comment]
No, @ywwg has a fix in https://github.com/mixxxdj/mixxx/pull/12431

**Review by ywwg — APPROVED** [review]

File: src/test/enginesynctest.cpp [hunk 1]
```diff
@@ -1937,29 +1964,18 @@ TEST_F(EngineSyncTest, HalfDoubleThenPlay) {
...
-    ProcessBuffer();
-
     EXPECT_DOUBLE_EQ(87.5,
             ControlObject::getControl(ConfigKey(m_sGroup1, "bpm"))->get());
 
     EXPECT_NEAR(
             m_pChannel1->getEngineBuffer()->m_pSyncControl->getBeatDistance(),
             m_pChannel2->getEngineBuffer()->m_pSyncControl->getBeatDistance(),
             kMaxFloatingPointErrorHighPrecision);
-
```
Comment (ywwg) [inline src/test/enginesynctest.cpp:1958]: by removing these ProcessBuffers the two checks at the bottom are identical -- does it fail if play advances?

Comment (daschuer) [reply src/test/enginesynctest.cpp:1958]: Ah Ok, I did not realize that this was a test. I will revert it.

**Comment by daschuer** [comment]
Done.

**Comment by ronso0** [comment]
I confirm this fixes #10550 

But it seems there is a difference in how clones are aligned (without Sync) in 2.4 compared to 2.3.6, there seems to be some tiny offset / flanger.
This zip contains some Flac files for comparison: -solo, -clone_2.3.6 and -clone_2.4-beta
[zeitgeist-clone.tar.gz](https://github.com/mixxxdj/mixxx/files/13728838/zeitgeist-clone.tar.gz)

**Comment by daschuer** [comment]
Let's focus on https://github.com/mixxxdj/mixxx/issues/10550 which aims to fix all flanger effects, independent of sync and quantize. 

There is no need for a recording. If you are able to create a flanger, please describe the steps and you may also share the file. Than I can hunt down the issue.

**Comment by daschuer** [comment]
There was a similar ssue, that is fixed in https://github.com/mixxxdj/mixxx/issues/10550 does that fix the issue for you?

**Comment by ronso0** [comment]
We're in the PR that fixes #10550 ;)

I noticed the effect with this PR, then I tested with 2.4 (identical) and with 2.3 from the ppa (issue not present).

**Comment by daschuer** [comment]
Ah ok. Is it a fixed bpm track?

**Comment by ronso0** [comment]
Nope, variable BPM. Approx. 105-145
I'll write that report and send you the file via email.

**Comment by daschuer** [comment]
I have discovered and fixed a ramping issue with ReplayGain that is now fixed. 

I can reproduce the Flanger issue with Soundtouch + Keylock enabled. My guess is that the fresh initialized filters behave different compared to the established filters of the playing deck. Rubberband does not show the issue. Not sure if we can fix it from the Mixxx code. This is out of scope of this PR. 

@ronso0 can you confirm this?

**Comment by daschuer** [comment]
This should also fix the flipping test HotcueControlTest.CueGotoAndPlay on Launchpad, because the result original depends on thread timing.

**Comment by daschuer** [comment]
@ronso0 can we merge this now?

**Comment by ronso0** [comment]
I don't understand the EnginePregain changes, sorry.
Diving into that will take time.

What about moving those commits to another PR?
Then we can merge the Sync fix right away.

**Comment by daschuer** [comment]
You can find the first part of this PR here: https://github.com/mixxxdj/mixxx/pull/12515

**Comment by ronso0** [comment]
Okay, #12515 targets main, so please remove the pregain commits here.

**Comment by daschuer** [comment]
https://github.com/mixxxdj/mixxx/pull/12515 is now for 2.4 with removed gain commits. 
This one can be merged in a second step.

**Comment by daschuer** [comment]
@ronso0 Will you find time to repeat you original tests with this branch soon? If not, let's remove this form the 2.4 milestone, since the gain issue is not a 2.4 regression. The sync part also contains in https://github.com/mixxxdj/mixxx/pull/12515 is the 2.4 part.

**Comment by ywwg** [comment]
@daschuer now that #12515 is merged, can you update this PR? it's still showing all the diffs instead of the ones unique to this branch

**Comment by daschuer** [comment]
Done.

File: src/engine/enginepregain.cpp [hunk 2]
```diff
@@ -88,17 +88,17 @@ void EnginePregain::process(CSAMPLE* pInOut, const int iBufferSize) {
...
         // This means that a ReplayGain value has been calculated after the
         // track has been loaded
-        constexpr float kFadeSeconds = 1.0;
+        constexpr float kFadeSeconds = 1.0f;
 
         if (m_bSmoothFade) {
             float seconds = static_cast<float>(m_timer.elapsed().toDoubleSeconds());
-            if (seconds < kFadeSeconds) {
-                // Fade smoothly
+            if (seconds < kFadeSeconds && m_dSpeed != 0.0 && m_dOldSpeed != 0.0) {
```
Comment (ywwg) [inline src/engine/enginepregain.cpp:100]: does this mean that once the replaygain is calculated, mixxx will now change the gain while the track is playing back?

File: src/test/reference_buffers/CueGotoAndStopTest [hunk 3]
```diff
@@ -1,512 +1,512 @@
...
-0.00943226,0.00943226
-0.00894785,0.00894785
-0.00829291,0.00829291
-0.00747693,0.00747693
-0.00651449,0.00651449
-0.00541663,0.00541663
-0.00420177,0.00420177
-0.00288188,0.00288188
-0.00147617,0.00147617
+0,0
```
Comment (ywwg) [inline src/test/reference_buffers/CueGotoAndStopTest:1]: why are these all zeros now?

File: src/test/reference_buffers/BasicProcessingTestPause [hunk 4]
```diff
@@ -1,512 +1,512 @@
...
-0.0119712,0.0119712
-0.0102581,0.0102581
-0.00857037,0.00857037
-0.00692855,0.00692855
-0.00535108,0.00535108
-0.00385238,0.00385238
-0.00245179,0.00245179
-0.00116233,0.00116233
+0,0
+0,0
```
Comment (ywwg) [inline src/test/reference_buffers/BasicProcessingTestPause:2]: why are these all zeroes now?

File: src/mixer/basetrackplayer.cpp [hunk 5]
```diff
@@ -527,7 +527,6 @@ void BaseTrackPlayerImpl::slotTrackLoaded(TrackPointer pNewTrack,
         m_pDuration->set(0);
         m_pFileBPM->set(0);
         m_pKey->set(0);
-        setReplayGain(0);
```
Comment (ywwg) [inline src/mixer/basetrackplayer.cpp:530]: why was this the wrong place to put the replaygain setting?

File: src/engine/enginepregain.cpp (hunk 2 above)
Comment (daschuer) [reply src/engine/enginepregain.cpp:100]: These condition applies the replay gain instantly without fading if the track is or was stopped. If it plays, fading is done. 
The logic that a analyzer replay gain is not applied when playing is handled here: https://github.com/mixxxdj/mixxx/blob/59ca3a25b768c44ac0934ed4cb4504cac52bde54/src/mixer/basetrackplayer.cpp#L711

File: src/mixer/basetrackplayer.cpp (hunk 5 above)
Comment (daschuer) [reply src/mixer/basetrackplayer.cpp:530]: Because it was too late, the first engine call uses the replay gain of the previous loaded track.

File: src/test/reference_buffers/CueGotoAndStopTest (hunk 3 above)
Comment (daschuer) [reply src/test/reference_buffers/CueGotoAndStopTest:1]: That seems to be wrong. I will have a look.

**Comment by daschuer** [comment]
@ywwg thank you for your good review. The test changes where wrong. 
I have added a fixup commit. If this works for you I will rebase it.

**Comment by daschuer** [comment]
@Swiftb0y @ronso0 I think this new fixup! checker suites good to prevent merging preliminary PRs. 
What do you think?

File: src/test/reference_buffers/ScratchTestStart [hunk 6]
```diff
@@ -1,6 +1,6 @@
 -0.000926289,-0.000926289
 -0.00185258,-0.00185258
--0.00277897,-0.00277897
+-0.00277896,-0.00277896
```
Comment (daschuer) [inline src/test/reference_buffers/ScratchTestStart:3]: I will revert this rounding artefact during fixup

**Comment by Swiftb0y** [comment]
> @Swiftb0y @ronso0 I think this new fixup! checker suites good to prevent merging preliminary PRs.

Yup, I agree. Is there already PR for that I missed?

**Comment by daschuer** [comment]
No, I will create one.

**Review by ywwg — APPROVED** [review]
thank you!

**Comment by daschuer** [comment]
All green after debase and an approval from @ywwg. So it is ready to go.
