### PR TITLE
Fix/initial waveform crash

### LINKED ISSUE #15737: Sporadic crash on track loading with vinyl control
### Bug Description

I am experiencing sporadic crashes. I can't always reproduce this. The steps that mostly work are

1. Start Mixxx with vinyl control layout
2. Without clicking anything scratch a bit
3. Enable vinyl control and scratch a bit again
4. Wait until the record stops
5. Load a track
6. Scratch again

Here is the backtrace: 

https://0x0.st/KCq8.log

### Version

master

### OS

Arch Linux

### PR DESCRIPTION
**Pull request by jclsn**
Tested it a few times and it seems to indeed fix the issue.

Fixes https://github.com/mixxxdj/mixxx/issues/15737

### CODE REVIEW

File: src/waveform/renderers/allshader/waveformrendererrgb.cpp [hunk 1]
```diff
@@ -89,6 +89,10 @@ bool WaveformRendererRGB::preprocessInner() {
     const double visualIncrementPerPixel =
             (lastVisualFrame - firstVisualFrame) / static_cast<double>(pixelLength);
 
+    // Fixes a sporadic crash caused by a division by zero on waveform initialization
+    if (!visualIncrementPerPixel)
+        return false;
```
Comment (Swiftb0y) [inline src/waveform/renderers/allshader/waveformrendererrgb.cpp:72]: I know this just a four line change, but this is awfully C in terms of logic and formatting...

```suggestion
    // Fixes a sporadic crash caused by a division by zero on waveform initialization
    if (visualIncrementPerPixel == 0.0) {
        return false;
    }
```

**Review by Swiftb0y — COMMENTED** [review]
is `main` the right target or does this apply to earlier branches too?

File: src/waveform/renderers/allshader/waveformrendererrgb.cpp (hunk 1 above)
Comment (jclsn) [reply src/waveform/renderers/allshader/waveformrendererrgb.cpp:72]: Changed

**Comment by jclsn** [comment]
> is `main` the right target or does this apply to earlier branches too?

Not sure. I have only discovered this recently. The main from 2-3 months ago didn't have this issue afaik.

**Review by Swiftb0y — APPROVED** [review]
LGTM. Thank you.

**Comment by daschuer** [comment]
This also applies to the 2.5 branch. Maybe it does not happen there because of a different control flow. But It can't hurt. 
I pushed it through so that we can release 2.5.4 tomorrow as planed. 
Thank you for the fix!

**Comment by jclsn** [comment]
Can you also merge into main please?

**Comment by daschuer** [comment]
Yes

File: src/waveform/renderers/allshader/waveformrendererrgb.cpp [hunk 2]
```diff
@@ -67,6 +67,11 @@ void WaveformRendererRGB::paintGL() {
     const double visualIncrementPerPixel =
             (lastVisualFrame - firstVisualFrame) / static_cast<double>(length);
 
+    // Fixes a sporadic crash caused by a division by zero on waveform initialization
+    if (visualIncrementPerPixel == 0.0) {
+        return false;
```
Comment (acolombier) [inline src/waveform/renderers/allshader/waveformrendererrgb.cpp:72]: Looks like this was merge with some clazy warning 
> return-statement with a value, in function returning ‘void’ [-fpermissive]

Could you please is a PR to fix this?

Comment (daschuer) [reply src/waveform/renderers/allshader/waveformrendererrgb.cpp:72]: I notices the issue immediately after merge and fixed it here:  
https://github.com/mixxxdj/mixxx/commit/62b291055fe38e76da9f7298c31a1a9ef8782654
