### PR TITLE
Traktor S4mk2: fix script error in pointlessLightShow()

### LINKED ISSUE #14103: Script error in Mixxx 2.5 when using Traktor Kontrol S4 MK2
### Bug Description

Hello dear community,

I received Mixxx 2.5 today via Ubuntu update and when I started it I received the following message.
Bildschirmfoto vom 2025-01-02 09-46-08

The error message contained gives me the following information.

> Uncaught exception: file:///usr/share/mixxx/controllers/Traktor-Kontrol-S4-MK2-hid-scripts.js:696:
> TypeError: Passing incompatible arguments to C++ functions from JavaScript is not allowed.
> 
> Backtrace: @file:///usr/share/mixxx/controllers/Traktor-Kontrol-S4-MK2-hid-scripts.js:696
> @file:///usr/share/mixxx/controllers/Traktor-Kontrol-S4-MK2-hid-scripts.js:714

I hope this bug will be fixed as soon as possible.

The current version is attached in the following screenshot.
Bildschirmfoto vom 2025-01-02 09-57-11

### Version

2.5

### OS

Ubuntu 22.04.5 LTS

### PR DESCRIPTION
**Pull request by ronso0**
Fixes #14103 

Reported to work here
https://mixxx.discourse.group/t/traktor-kontrol-s4-mk2-2-5-bug-fix-script-error/31267/6

### CODE REVIEW

File: res/controllers/Traktor-Kontrol-S4-MK2-hid-scripts.js [hunk 1]
```diff
@@ -679,7 +679,7 @@ TraktorS4MK2.lightDeck = function(group) {
 };
 
 TraktorS4MK2.pointlessLightShow = function() {
-    var packets = [Object(), Object(), Object()];
+    const packets = [[], [], []];
```
Comment (ronso0) [inline res/controllers/Traktor-Kontrol-S4-MK2-hid-scripts.js:682]: eslint insisted on `const` here.
So const is only the number of items in the array? Not the size/content of the items?

Comment (Swiftb0y) [reply res/controllers/Traktor-Kontrol-S4-MK2-hid-scripts.js:682]: yup. `const` in JS only applies to the binding. Meaning a variable assigned with `const` can not be reassigned. For primitive values (numbers, bools, etc) that means they're effectively const. For complex types (Objects, arrays, strings, etc) you can never reassign the value, but you can mutate it. So yeah, `const` is correct in this case.

**Review by Swiftb0y — APPROVED** [review]
LGTM. Thank you.

File: res/controllers/Traktor-Kontrol-S4-MK2-hid-scripts.js (hunk 1 above)
Comment (Swiftb0y) [reply res/controllers/Traktor-Kontrol-S4-MK2-hid-scripts.js:682]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/const

Comment (ronso0) [reply res/controllers/Traktor-Kontrol-S4-MK2-hid-scripts.js:682]: Thanks!
