### PR TITLE
(fix) FX units not working on all samplers

### LINKED ISSUE #15799: FX units not working on all samplers
Name        : mixxx
Version     : 2.5.4
Release     : 1.fc42
Architecture: x86_64
Install Date: Do 25 Dez 2025 10:01:07 CET

As illustrated in this screenshot:

Image

The sampler on the right side do not work with at least Units 3 and 4, but the one on the left side does work.

the samplers on the right will start working after an event i did not figured out yet.

telling the master channel to use FX3, does work as expected, it's just the sample units on the right.

A few releases back, they all worked flawless.

### PR DESCRIPTION
**Pull request by ronso0**
Fixes #15799

* new profile (or just no effects.xml and effects dir)
* load a track into sampler 5, play
* assign FX1, load Echo etc., turn all on and turn Meta so there's some good feedback/filter effect
* close, restart
* enable Echo, press Play on sampler 5
-> this PR: enjoy the noise : )
-> 2.5: no echo. toggle Fx1 Off and On before engaging Echo & Co, then it works.

The root cause:
short: the fx I/O routing table is not updated instantly when additional samplers are added to the engine (or any inputs actually).

long:
* CoreServices adds the default inputs (4 decks, 4 samplers, mics, aux etc.) and upon creation they are registered in `EffectsManager`
* CoreServices then calls `m_pEffectsManager->setup()` which initializes all EngineEffectChains with the registred inputs/outputs
* then samplers.xml is parsed and maybe more samplers are created -- same when a sampler bank is loaded manually or when we switch to a skin with more samplers
* new inputs are registered in `EffectsManager`, then [in each (standard) effect chain](https://github.com/mixxxdj/mixxx/blob/1bd3c4306269c79cafc62f90a824a5ce10fdbe04/src/engine/effects/engineeffectchain.cpp#L143) and the Fx routing CO states are also restored correctly (see GUI, FX1 on sampler 5)
-> BUT the I/O maps used by `EngineEffectChain`s are not updated, hence engaging an effect has no ..effect for those new inputs
-> the I/O maps _are_ extended for the new key, but `ChannelHandleMap::maybeExpand` abviously can't initialize the outputs map

The fix:
* store the outputs map when creating EngineEffectChain(it won't change as no new outputs are added after `EffectsManager::setup()`-- afaict)
* when registering and [enabling a new input](https://github.com/mixxxdj/mixxx/blob/1bd3c4306269c79cafc62f90a824a5ce10fdbe04/src/engine/effects/engineeffectchain.cpp#L143), use `ChannelHandleMap[input]` as before but then assign the stored output map

____
Maybe alternatively we could add a method `EngineEffectChain::registerInputChannel` and use a new `EffectsRequest::MessageType` to send the request via the message pipe.
But I doubt it has any benefits over the current fix. Does it?

### CODE REVIEW

File: src/engine/effects/engineeffectchain.cpp [hunk 1]
```diff
@@ -145,6 +147,16 @@ bool EngineEffectChain::enableForInputChannel(ChannelHandle inputHandle) {
...
     auto& outputMap = m_chainStatusForChannelMatrix[inputHandle];
+
+    if (outputMap.isEmpty()) {
+        // Apparently a request to enable an unregistered input.
+        // ChannelHandleMap's operator[] does maybeExpand(), so we now have an
+        // inputHandle key and we can assign our outputmap to it.
+        // Now request the map reference again and we're ready to roll...
+        m_chainStatusForChannelMatrix[inputHandle] = m_outputChannelMap;
+        outputMap = m_chainStatusForChannelMatrix[inputHandle];
+    }
```
Comment (ywwg) [inline src/engine/effects/engineeffectchain.cpp]: I prefer to avoid this pattern where we create a new variable, and then check to see ok, and then fix it if not.  This creates an in-between state where the variable is invalid, and later down the line someone may accidentally put code in between.

By reordering this a little, we can do the assignment once and outputMap is always valid.  It does technically do two lookups, but this map lookup is extremely fast, the map is small, and this function is not in a hot path. 

```suggestion
    if (m_chainStatusForChannelMatrix[inputHandle].isEmpty()) {
        // Apparently a request to enable an unregistered input.
        // ChannelHandleMap's operator[] does maybeExpand(), so we now have an
        // inputHandle key and we can assign our outputmap to it.
        // Now request the map reference again and we're ready to roll...
        m_chainStatusForChannelMatrix[inputHandle] = m_outputChannelMap;
    }
    auto& outputMap = m_chainStatusForChannelMatrix[inputHandle];
```

**Review by ywwg — CHANGES_REQUESTED** [review]

File: src/engine/effects/engineeffectchain.cpp (hunk 1 above)
Comment (ronso0) [reply src/engine/effects/engineeffectchain.cpp]: Thanks, makes sense

**Comment by tuulikauri** [comment]
I tested [the build artifact on Windows 11 x64](https://github.com/mixxxdj/mixxx/actions/runs/22141274665/job/64005905338). I confirmed these steps work. However I will note that when I first reloaded Mixxx, FX1 was not enabled on sampler 5. I believe that I had enabled it and left it enabled before quitting but I'm not 100% sure.
* **installed Windows x64 build artifact**
* new profile (or just no effects.xml and effects dir) -> **Ran Mixxx from the Start Menu without changing any profile; I'm not sure how to make a new profile or check to have no effects dir? If this is important I can retest. Is it the same as creating a backup of the [user settings directory](https://manual.mixxx.org/2.5/en/chapters/appendix/settings_directory) (hmm.. manual is still down for me), ie rename the settings folder so Mixxx creates a new fresh directory?**
* load a track into sampler 5, play -> **yup**
* assign FX1, load Echo etc., turn all on and turn Meta so there's some good feedback/filter effect -> **yup**
* close, restart -> **yup. When mixxx is restarted (after the first time? or user error maybe?) FX1 is enabled on deck 5 but the effects rack itself has everything turned off on restart**
* enable Echo, press Play on sampler 5
-> this PR: enjoy the noise : ) -> **yup**
-> 2.5: no echo. toggle Fx1 Off and On before engaging Echo & Co, then it works. -> **didnt test**

I didnt confirm the pre-fix (bugged) case.
Cheers!

**Review by ywwg — APPROVED** [review]

**Comment by ronso0** [comment]
Thanks for testing!

> FX1 is enabled on deck 5 but the effects rack itself has everything turned off on restart

That is on purpose so you can start playback whitout any potentially hidden effects being enabled.

**Comment by ronso0** [comment]
@ywwg You approved, let's merge?
