### PR TITLE
Fix crash when no GL context is available

### LINKED ISSUE #11929: Mixxx 2.4-beta crash on Windows 10 with No GL
### Bug Description

Tested on Virtual Box 7. 

EXCEPTION_ACCESS_VIOATION 

At the beginning ther is a popup about missing OpenGL 

### Version

2.4-beta

### OS

Windows 10

### PR DESCRIPTION
**Pull request by daschuer**
This fixes #11929

A next iteration would be to get rid of the initial GL widget. Maybe we can already use the context without the widget. 
I am just afraid that this requires a lot of testing. Nothing suitable just before a release.

### CODE REVIEW

**Comment by JoergAtGithub** [comment]
I guess this should be targeted to 2.4?

File: src/mixxxmainwindow.cpp [hunk 1]
```diff
@@ -149,22 +152,36 @@ MixxxMainWindow::MixxxMainWindow(std::shared_ptr<mixxx::CoreServices> pCoreServi
...
+            // but allows us to take advantage of the existing classes.
+            WInitialGLWidget* widget = new WInitialGLWidget(this);
+            widget->setGeometry(QRect(0, 0, 3, 3));
+            SharedGLContext::setWidget(widget);
+            // When the widget's QOpenGLWindow has been initialized, we continue
+            // with the actual initialization
+            connect(widget, &WInitialGLWidget::onInitialized, this, &MixxxMainWindow::initialize);
+            widget->show();
+            // note: the format is set in the WGLWidget's OpenGLWindow constructor
+            return;
```
Comment (Swiftb0y) [inline src/mixxxmainwindow.cpp:180]: this comment no longer applies since the context has been created earlier in the function

File: src/mixxxmainwindow.cpp [hunk 2]
```diff
@@ -149,22 +152,36 @@ MixxxMainWindow::MixxxMainWindow(std::shared_ptr<mixxx::CoreServices> pCoreServi
...
-        // When the widget's QOpenGLWindow has been initialized, we continue
-        // with the actual initialization
-        connect(widget, &WInitialGLWidget::onInitialized, this, &MixxxMainWindow::initialize);
-        widget->show();
-        // note: the format is set in the WGLWidget's OpenGLWindow constructor
-    } else {
-        initialize();
+#endif
+        QSurfaceFormat format;
+        format.setVersion(2, 1);
```
Comment (m0dB) [inline src/mixxxmainwindow.cpp:163]: Without this, we had a single place where QSurfaceFormat was set (in OpenGLWindow constructor). Also, I liked going through an actual QOpenGLWindow creation to do the check. But I am okay with this change, especially because I agree with the eventual removal of SharedGLContext.

Comment (daschuer) [reply src/mixxxmainwindow.cpp:163]: We may consider to set the default format in a single place instead. But I was not sure about the implications.

Comment (Swiftb0y) [reply src/mixxxmainwindow.cpp:163]: should be easy enough to solve by just putting the QSurfaceFormat creation into a function that is called from both places, right?

**Review by Swiftb0y — COMMENTED** [review]
LGTM. please fix pre-commit before merge

**Comment by daschuer** [comment]
Done.

**Review by Swiftb0y — APPROVED** [review]
