### PR TITLE
(fix) avoid empty waveform with invalid config - refactor waveform factory/preferences

### LINKED ISSUE #15338: Simple waveform is empty when selected after an unaccelerated type.
### Bug Description

To reproduce: 
* load a track 
* Select Filtered waveform in the scrolling waveform preference
* Waveform appears 
* Unselect accelerated 
* Waveform changes 
* Select simple waveform 
* Waveform disappears, accelerated is checked and grayed out. 

This state remains across restarts. 

### Version

2.6-beta 

### OS

Ubuntu Jammy

### PR DESCRIPTION
**Pull request by ronso0**
Fixes #15338

**Update:** 
This is now just the fix for #15338 and for disabling Stem options when Stems are not supported by waveform type.
I moved the refactoring to another branch, PR will follow asap
_________
DlgPreferencesWaveform was a bit more complicated than necessary. I took the opportunity to clean it up and make it a frontend for WaveformWidgetFactory. I hope commits are isolated enough to ease review.

--> next step is refactoring the overview settings as well, so that all waveform/overview settings are managed by WaveformWidgetFactory. Should allow to drop some COs/proxies
**edit:** not possible, or if it would be quite elaborate to forward the factory signal to OverviewDelegate

### CODE REVIEW

File: src/waveform/waveformwidgetfactory.cpp [hunk 1]
```diff
@@ -604,15 +606,67 @@ bool WaveformWidgetFactory::widgetTypeSupportsUntilMark() const {
...
+    case WaveformWidgetType::RGB:
+        return true;
+    case WaveformWidgetType::Filtered:
+        return true;
+    case WaveformWidgetType::Simple:
+        return true;
+    case WaveformWidgetType::HSV:
+        return true;
+    case WaveformWidgetType::Stacked:
+        return true;
```
Comment (Swiftb0y) [inline src/waveform/waveformwidgetfactory.cpp:610]: NIT: perfectly valid and idiomatic and less noisy
```suggestion
    case WaveformWidgetType::RGB:
    case WaveformWidgetType::Filtered:
    case WaveformWidgetType::Simple:
    case WaveformWidgetType::HSV:
    case WaveformWidgetType::Stacked:
        return true;
```

**Review by Swiftb0y — COMMENTED** [review]
code looks fine, though I'm a little concerned about this introducing last-minute regressions considering the 2.6 milestone is overdue by two days.

File: src/waveform/waveformwidgetfactory.cpp (hunk 1 above)
Comment (ronso0) [reply src/waveform/waveformwidgetfactory.cpp:610]: Yeah, noticed that, too, but didn't touch it (1:1 c/p from widgetTypeSupportsUntilMark) because I assumed it's structured like this to allow adding exceptions in case renderer changes require so.
But of course that's easy to do and I'll make it more compact.

**Comment by ronso0** [comment]
> though I'm a little concerned about this introducing last-minute regressions considering the 2.6 milestone is overdue by two days.

Sure. I can try to isolate the fixes and move the refactoring to 2.7

**Comment by ronso0** [comment]
Or would it help if I break the commits into smaller chunks?

**Comment by Swiftb0y** [comment]
I would prefer to minimize the stuff that goes into 2.6 and target cleanups at 2.7...

**Comment by ronso0** [comment]
Okay, done.
It's now only some helpers and the two fixes.

**Review by Swiftb0y — APPROVED** [review]
LGTM, thank you.
