### PR TITLE
(fix) Waveform scratching: fix seeking to hotcue (reduced, alt. for #14059)

### LINKED ISSUE #13981: pressing hotcue while holding waveform or spinny should seek to hotcue (and stay there)
### Bug Description

* play a track
* click and hold waveform or spinny, playback stops
* press hotcue (keyboard or controller)

**Current behaviour:**
* play pos seeks to hotcue and 'scratches' back to previous play position (where the waveform/spinny stopped)

**Expected behaviour:**
* seek to hotcue and stay there (or rather: continue the scratch move as if nothing happened)

### Version

2.5

### OS

_No response_

### PR DESCRIPTION
**Pull request by ronso0**
This is #14059 without the member/slot refactoring, i.e. just the fixes + switch to parented_ptr etc.
I hope this lowers the barrier to get the fix into 2.5.1

Original description:
___
This is a first (still dirty) fix for #13981 

**TL;DR**
it's now possible to seek to hotcues while doing wave scratches.
Scratching at/across  loop boundaries (active) still works.

Recently I [compared the available methods for scratching with controllers](https://github.com/mixxxdj/mixxx/pull/14004), and while PositionScratchController (developed for waveform scratching) turned out to be the best (for me, no drift, smooth at low rates, nice spinback) I couldn't really use it as I want to because seeking to hotcues while scratching (holding the wheel, or turning very slowly) produced insanely high rates, and didn't stop at the cue pos.

Even though the bug is fixed I still consider this 'dirty' because I don't fully understand what was going wrong with the filters after seeking.

### CODE REVIEW

File: src/engine/positionscratchcontroller.cpp [hunk 1]
```diff
@@ -187,7 +203,7 @@ void PositionScratchController::process(double currentSamplePos,
                 bool reverse = triggerPos < targetPos;
                 double loopLength = reverse ? -1 * (targetPos - triggerPos)
                                             : triggerPos - targetPos;
-                if (wrappedAround > 2) {
+                if (wrappedAround > 1) {
```
Comment (daschuer) [inline src/engine/positionscratchcontroller.cpp:206]: I think I can confirm that this fixes an issue, however I think it still does not behave right in case of reverse. 
This is because the reverse case is considered loopLength but not for `sampleDelta +=` below. 
It can become via math: 
`sampleDelta +=  (triggerPos - targetPos ) + (currentSamplePos - m_prevSamplePos);` 

Can we refactor the whole block into a forward and a backward branch? 

Something like (untested): 

```
            double sampleDelta = currentSamplePos - m_prevSamplePos;
            if (wrappedAround > 0) {
                // If we wrapped around, add  loop length for each wrap-aound 
                // (necessary if the buffer is longer than the loop, e.g. when looping 
                // at high rates / with short loops. 
                double triggerPos = trigger.toEngineSamplePos();
                double targetPos = target.toEngineSamplePos();
                double loopLength = triggerPos - targetPos;
                if (loopLength < 0.0) {
                    // reverse 
                    loopLength *= -1; 
                }
                sampleDelta += wrappedAround * loopLength;
            }
``

File: src/engine/positionscratchcontroller.cpp [hunk 2]
```diff
@@ -129,6 +132,15 @@ void PositionScratchController::process(double currentSamplePos,
     m_pVelocityController->setPD(p, d);
     m_pRateIIFilter->setFactor(f);
 
+    bool adoptSeekPos = false;
+    if (!util_isnan(m_seekSamplePos)) {
+        // If we were notified about a seek, adopt the new position immediately.
+        m_prevSamplePos = m_seekSamplePos;
```
Comment (daschuer) [inline src/engine/positionscratchcontroller.cpp:138]: How does the m_seekSamplePos relates to currentSamplePos? 
Can you add a comment? Are they equal for one call?

File: src/engine/positionscratchcontroller.cpp (hunk 1 above)
Comment (ronso0) [reply src/engine/positionscratchcontroller.cpp:206]: Thanks, we can try that.
Because this is actually not related to the scratch/seeking issue I've removed the commit from this branch and will create a separate one.

**Comment by ronso0** [comment]
In order to keep you review I have decided to close #14059, rebased this one (fix conflicts) and adopt the only different commit from #14059.
Also reworded a commit because the already merged parented_ptr commit already contains the PositionScratchController refactoring.

Will address your review soon.

File: src/engine/positionscratchcontroller.cpp (hunk 1 above)
Comment (ronso0) [reply src/engine/positionscratchcontroller.cpp]: took me a while with my non-math brain...
Yup, this looks good!

PR is #14379

File: src/engine/positionscratchcontroller.cpp (hunk 2 above)
Comment (daschuer) [reply src/engine/positionscratchcontroller.cpp:176]: I have tested a bit an it turns out that the new position is applied second `process()` call so you need to skip one or put the adoption of the seek position at the bottom of the process() call. The `adoptSeekPos` does also not work right. I think we need to reset the `m_samplePosDeltaSum` instead. I have tried this but it fails as well. At one version it seeks to the cue point and the immediately back to the original position. So we probably need to tweak the value and just subs tact the seek distance or such. (not tested). 

Testing with the maximum audio buffer size was by the way the best to trace what actually happens.

Comment (ronso0) [reply src/engine/positionscratchcontroller.cpp:176]: > I have tested a bit an it turns out that the new position is applied second process()

FWIW I could never observe that **exact** the seek position is used for `PositionScratchController::process()`, there was always a diff (usable minimum was ~100 samples). I figured that with a version where I waited until the currPos and stored seekPos were close and then adopted the seekPos as prevPos https://github.com/mixxxdj/mixxx/commit/6927fdc727422a8491f35215732946291c6ac257

> I think we need to reset the m_samplePosDeltaSum instead. I have tried this but it fails as well.

Thought so, too, and tried it as well as some other combinations, but none worked.
Except this one.

> At one version it seeks to the cue point and the immediately back to the original position.

Yes, IIUC that is the original issue that causes the high rate.

> So we probably need to tweak the value and just subs tact the seek distance or such. (not tested).

If you like to debug further (I don't) and you figure something I'm happy to test it!

**Comment by ronso0** [comment]
> there's always a visual stop and a dip in rate

I think that occured simply because I used hotkeys for seeking.
If I use a virt. MIDI script and let that do the timed seeking all is good, the waveform sticks to the pointer even while seeking :+1:

**Comment by daschuer** [comment]
Here is a final bit: https://github.com/ronso0/mixxx/pull/91

**Review by daschuer — APPROVED** [review]
LGTM, thank you.
