### PR TITLE
Library Scan dialog: add progress bar, plus some improvements

### LINKED ISSUE #15326: Show overall progress % in scanner progress dialog
### Feature Description

Taken from [Dexxter Clark's review on Deejay Plaza](https://www.deejayplaza.com/en/articles/mixxx-review#analyzing) 

> When you first start the software, you are prompted to select the music directory on your computer.
This process can take while, however the software lacks user feedback about the length of this process.
> 
> I would expect a progress bar or a background process to take care of this task.
But the software seems to freeze up and you can do nothing else for a couple of minutes.
Even the Windows task manager says that the software is not responding.
>
> Just a simple running number would be enough to communicate to the user: “I haven’t crashed”.

I've dived a bit into the scanner code for #15320 and it seems all RecursiveScanDirectoryTask and ImportFilesTask could report their number of found/queued directories and tracks, so we can show the overall progress in LibraryScannerDlg.

### PR DESCRIPTION
**Pull request by ronso0**
image

Adds a progress bar and allows to show the full path of the current (actually previous) task.
As before, the dialog should automatically grow in width but can still be expanded manually.
It grows in height if the file/directory paths require it. (previously paths were truncated even if the dialog was expanded)

Requires a small hack to not show 100% prematurely (and potentially for a confusing long time)  because we don't know the total of all tasks in advance. See inline comments for details.

**Fix:** cancel scan when clicking X window button
_____
I'm tempted to target 2.6 because IMO it's a nice UX fix, but I won't insist.

### CODE REVIEW

File: src/library/scanner/importfilestask.h [hunk 1]
```diff
@@ -22,6 +22,10 @@ class ImportFilesTask : public ScannerTask {
 
     virtual void run();
 
+    int numFilesToImport() const {
+        return static_cast<int>(m_filesToImport.size());
+    }
```
Comment (ronso0) [inline src/library/scanner/importfilestask.h:27]: might as well be virtual in `ScannerTask`, return 1 in `RecursiveScanDirectoryTask` and `m_filesToImport.size()` here, just to get around the extra include in `LibraryScanner`, but actually that include is pretty small, so 🤷‍♂️

File: src/library/scanner/libraryscannerdlg.cpp [hunk 2]
```diff
@@ -1,65 +1,129 @@
...
-    QVBoxLayout* pLayout = new QVBoxLayout(this);
-
     setWindowTitle(tr("Library Scanner"));
-    QLabel* pLabel = new QLabel(tr("It's taking Mixxx a minute to scan your music library, please wait..."),this);
-    pLayout->addWidget(pLabel);
+
+    // This is the widest item initially so it sets the dialog's minimum width.
+    QLabel* pLabel = new QLabel(
+            tr("It's taking Mixxx a minute to scan your music library, please wait..."),
+            this);
```
Comment (ronso0) [inline src/library/scanner/libraryscannerdlg.cpp]: TODO std::unique_ptr

**Comment by ronso0** [comment]
Shall I isolate commits 1-3 so we get the X-click fix into 2.6-beta soonish?

**Comment by daschuer** [comment]
I consider all of this a 2.6 fix. So you can keep it as it is.

**Comment by ronso0** [comment]
Rebased onto 2.6, ready for review

File: src/library/scanner/libraryscanner.cpp [hunk 3]
```diff
@@ -553,6 +554,21 @@ void LibraryScanner::queueTask(ScannerTask* pTask) {
         m_pool.clear();
         return;
     }
+
+    // Fetch number of files to be processed and add them to the total tasks
+    // for the progress dialog to set the value of the progress bar later on.
+    // Note that there may also be an unknown number of tasks for files
+    // outside the library directories. We deal with that in DlgLibraryScanProgress.
+    ImportFilesTask* pFileTask = dynamic_cast<ImportFilesTask*>(pTask);
```
Comment (daschuer) [inline src/library/scanner/libraryscanner.cpp]:
```suggestion
    ImportFilesTask* pFileTask = qobject_cast<ImportFilesTask*>(pTask);
```
is faster, because the type can is stored inside the object.

**Review by daschuer — CHANGES_REQUESTED** [review]
LGTM, one small imrovement.

**Comment by ronso0** [comment]
@daschuer I pushed the fixup, let's merge?

**Comment by acolombier** [comment]
@daschuer could you confirm your change request has been addressed?

**Review by daschuer — APPROVED** [review]
LGTM, Thank you.
