### PR TITLE
fix(waveform): use max the channel value on mono coloration

### LINKED ISSUE #14317: Regression: RGB high detail waveform no longer renders both channels
### Bug Description

Noticed this on the Mr. Brightside intro, which should look like this:

Image

and currently looks like this:

Image

Image

Disabling high details or acceleration both fix the issue.

This seems to be a regression, the last good commit was c0407e5614 and the first bad 4d9db3e5d0 ([diff](https://github.com/mixxxdj/mixxx/compare/c0407e561430a1dc216b3a7da1ec424017010f8e...4d9db3e5d0e4807bdcddaebf8c87bdc3e3970d53)), suggesting the issue was introduced in

- #13220

cc @acolombier 

### Version

2.6 (main)

### OS

macOS 15.2

### PR DESCRIPTION
**Pull request by acolombier**
Fixes #14317

### CODE REVIEW

File: src/waveform/renderers/allshader/waveformrenderertextured.cpp [hunk 1]
```diff
@@ -1,5 +1,9 @@
 #include "waveform/renderers/allshader/waveformrenderertextured.h"
 
+#include <qglobal.h>
```
Comment (Swiftb0y) [inline src/waveform/renderers/allshader/waveformrenderertextured.cpp]:
```suggestion
```

File: res/shaders/rgbsignal.frag [hunk 2]
```diff
@@ -51,7 +45,21 @@ void main(void) {
...
+        } else {
+            vec4 leftDataUnscaled = getWaveformData(new_currentIndex);
+            vec4 rightDataUnscaled = getWaveformData(new_currentIndex + 1);
+            new_currentDataUnscaled = vec4(
+                                              max(leftDataUnscaled.x, rightDataUnscaled.x),
+                                              max(leftDataUnscaled.y, rightDataUnscaled.y),
+                                              max(leftDataUnscaled.z, rightDataUnscaled.z),
+                                              max(leftDataUnscaled.w, rightDataUnscaled.w)) *
+                    allGain;
+        }
```
Comment (Swiftb0y) [inline res/shaders/rgbsignal.frag]:
```suggestion
            new_currentDataUnscaled = max(leftDataUnscaled, rightDataUnscaled) * allGain;
        }
```

**Review by Swiftb0y — COMMENTED** [review]
Nits, LGTM otherwise, haven't tested locally though.

File: res/shaders/rgbsignal.frag (hunk 2 above)
Comment (acolombier) [reply res/shaders/rgbsignal.frag]: Would this apply a max on each value independently? For example, would this capture (A.x, B.y, B.z, A.w)? 
We use a vec to carry a tuple of 4 values, but these gets carried inside a 4D vector for compatibility, however my naive impression was that `max` on `vec4` would pick either a vector or the other based on their normalization value.

Comment (Swiftb0y) [reply res/shaders/rgbsignal.frag]: > Would this apply a max on each value independently? For example, would this capture (A.x, B.y, B.z, A.w)?

Yes. 

> however my naive impression was that max on vec4 would pick either a vector or the other based on their normalization value.

no, thats not naive enough ;). GLSL doesn't interpret these vectors geometrically, they simply apply the operation point-wise. Just like multiplying two vectors of the same size doesn't result in their inner product but just each component multiplied by the corresponding component in the other vector. I confirmed this myself.

**Comment by Swiftb0y** [comment]
This is the intended result right? (The track source material is hard panned to the right (in this example) but the renderer just takes the channel max). 

image

I tested this with the `max` change I suggested btw.

File: res/shaders/rgbsignal.frag (hunk 2 above)
Comment (acolombier) [reply res/shaders/rgbsignal.frag]: Oh great to know! I'll update that ASAP.

**Comment by acolombier** [comment]
> This is the intended result right? [..] I tested this with the max change I suggested btw.

Probably :) 

It's hard to visualise with a hard panned track, since the left vector will be null (0, 0, 0, 0). I will test with Pink Floyd - Money intro later, which as some L/R effects and is pretty good to compare that!

**Review by Swiftb0y — APPROVED** [review]
LGTM. Thank you.

**Comment by Swiftb0y** [comment]
Interesting, I think softfix breaks CI @daschuer

**Comment by acolombier** [comment]
> Interesting, I think softfix breaks CI @daschuer 

Yeah, what's going on is that `github-actions` induced event won't trigger any CI, so this is expected. This is why I had made some suggestion to move the action to the @mixxxbot

**Comment by Swiftb0y** [comment]
I see. Thanks for the manual push

**Comment by acolombier** [comment]
I swear I had done the work for it... (there is even the token already set!) but I cannot find where it is! I'll dig deeper later

**Comment by daschuer** [comment]
> Interesting, I think softfix breaks CI @daschuer

Yes it is just not triggered automatically from an other workflow to break recursive loops. You can also just edit the initial post as a workaround to trigger the workflow.
