### PR TITLE
Show time in the timestamp column 

### LINKED ISSUE #10726: Timestamp and Last Played column has only date
Reported by: **[daschuer](https://github.com/daschuer)**
Date: 2022-05-10T06:57:02Z
Status: In Progress
Importance: High
Launchpad Issue: [lp1972772](https://bugs.launchpad.net/bugs/1972772)
Tags: regression

---

Now we cannot sort any longer by played order.

### PR DESCRIPTION
**Pull request by daschuer**
This fixes bug: https://bugs.launchpad.net/mixxx/+bug/1972772

### CODE REVIEW

File: src/library/basetracktablemodel.cpp [hunk 1]
```diff
@@ -643,8 +643,15 @@ QVariant BaseTrackTableModel::roleValue(
             }
             QDateTime dt = mixxx::localDateTimeFromUtc(rawValue.toDateTime());
             if (role == Qt::ToolTipRole || role == kDataExportRole) {
+                // localized text date: "Wednesday, May 20, 1998 03:40:13 AM CEST"
                 return dt;
             }
+            if (field == ColumnCache::COLUMN_PLAYLISTTRACKSTABLE_DATETIMEADDED) {
+                // Timstamp column in history feature:
+                // Use localized date/time format without text: "5/20/98 03:40 AM"
+                return QLocale().toString(dt, QLocale::NarrowFormat);
```
Comment (uklotzde) [inline src/library/basetracktablemodel.cpp:652]: https://doc.qt.io/qt-6/qlocale.html#FormatType-enum
> Note: NarrowFormat might contain the same text for different months and days. It can even be an empty string if the locale doesn't support narrow names, so you should avoid using it for date formatting. Also, for the system locale this format is the same as ShortFormat.

We already have `displayLocalDateTime()` for this purpose.

**Comment by daschuer** [comment]
Done.

**Comment by ronso0** [comment]
Changing the 'Timestamp' sort order in History doesn't work unfortunately:
image

**Comment by daschuer** [comment]
Done, now sorting works as well.

File: src/library/rekordbox/rekordboxfeature.cpp [hunk 2]
```diff
@@ -1217,6 +1217,9 @@ void RekordboxPlaylistModel::initSortColumnMapping() {
     m_columnIndexBySortColumnId[static_cast<int>(
             TrackModel::SortColumnId::Position)] =
             fieldIndex(ColumnCache::COLUMN_PLAYLISTTRACKSTABLE_POSITION);
+    m_columnIndexBySortColumnId[static_cast<int>(
+            TrackModel::SortColumnId::PlaylistDateTimeAdded)] =
+            fieldIndex(ColumnCache::COLUMN_PLAYLISTTRACKSTABLE_DATETIMEADDED);
```
Comment (ronso0) [inline src/library/rekordbox/rekordboxfeature.cpp:1222]: Does it also need to be added to the Serato feature?
(note I never used any of those, thus the question..)

**Review by ronso0 — APPROVED** [review]
LGTM, works as desired, just a question.

File: src/library/rekordbox/rekordboxfeature.cpp (hunk 2 above)
Comment (ronso0) [reply src/library/rekordbox/rekordboxfeature.cpp:1222]: *ping

**Comment by ronso0** [comment]
Thank you!

**Comment by daschuer** [comment]
@ronso0 sorry, I messed up a merge. Fixed here: https://github.com/mixxxdj/mixxx/pull/11020
