### PR TITLE
Fullscreen on Linux: fix issues caused by Ubuntu Unity workaround

### LINKED ISSUE #11281: View menu hotkeys don't work after toggling fullscreen on Ubuntu 22.04
### Bug Description

all other main menu hotkeys/actions that are not [`VisibilityControlConnection`](https://github.com/mixxxdj/mixxx/blob/620242d8002eafe8dfa968bda9276dd03a1ab0be/src/widget/wmainmenubar.cpp#L711) still work.

So it's the 'menubar missing' workaround causing this
https://github.com/mixxxdj/mixxx/blob/620242d8002eafe8dfa968bda9276dd03a1ab0be/src/mixxx.cpp#L1425-L1450

### Version

2.3.3, and newer as well IIRC

### OS

Ubuntu 22.04 ~~with Unity desktop~~

### LINKED ISSUE #11294: Menubar not visible after starting in fullscreen on Ubuntu with Unity desktop and global menu
### Bug Description

Start in fullscreen mode, either by checking the respective option in the preferences or via command line argument `-f`, `--f` or `--fullscreen`) and there is no menubar.
Toggle fullscreen off and on again, and the menubar is shown.

### Version

2.3.3

### OS

Ubuntu 22.04 with Unity desktop

### PR DESCRIPTION
**Pull request by ronso0**
supersedes #11259 

In order to fix #6072 the menubar is recreated and reconected when toggling fullscreen on Linux.
This causes issues on some distros. 
Fixes #11281
Fixes #11294 

* reconnect `VisibilityControlConnection`s in View menu after toglling fullscreen
* relocate the menubar when starting in fullscreen on desktops that have global menu

### CODE REVIEW

**Review by daschuer — APPROVED** [review]
Works like a charm on  Mint Tara + Mate and Ununtu Focal with Ubuntu and Unity desktop. 
Thank you.

**Comment by daschuer** [comment]
Next one is https://github.com/mixxxdj/mixxx/pull/11275 and than https://github.com/mixxxdj/mixxx/pull/11278 to make the release happen.

File: src/mixxx.cpp [hunk 1]
```diff
@@ -265,6 +265,13 @@ void MixxxMainWindow::initialize(QApplication* pApp, const CmdlineArgs& args) {
             ConfigKey("[Config]", "StartInFullscreen"));
     if (args.getStartInFullscreen() || fullscreenPref) {
         showFullScreen();
+#ifdef __LINUX__
+        // If the desktop features a global menubar and we go fullscreen during
+        // startup, move the menubar to the window like in slotViewFullScreen()
+        if (m_pMenuBar->isNativeMenuBar()) {
+            m_pMenuBar->setNativeMenuBar(false);
+        }
+#endif
```
Comment (ronso0) [inline src/mixxx.cpp:274]: looks like this was already fixed in main by simply calling `slotViewFullScreen(true)`
