### PR TITLE
Musicbrainz: Elide long error messages in the  progress bar

### LINKED ISSUE #13664: Musicbrainz error is too long for progress bar
### Bug Description

grafik

### Version

2.5-beta 52

### OS

Ubuntu Jammy

### PR DESCRIPTION
**Pull request by daschuer**
And put the full text into a tooltip, like we do in the library table. 
This fixes #13664

### CODE REVIEW

**Review by acolombier — APPROVED** [review]
LGTM

File: src/library/dlgtagfetcher.cpp [hunk 1]
```diff
@@ -535,8 +537,16 @@ void DlgTagFetcher::slotNetworkResult(
         const QString& app,
         const QString& message,
         int code) {
-    QString cantConnect = tr("Can't connect to %1: %2");
-    loadingProgressBar->setFormat(cantConnect.arg(app, message));
+    QString cantConnect = tr("Can't connect to %1: %2").arg(app, message);
+    QFontMetrics metrics(loadingProgressBar->font());
+    QString elidedCantConnect = metrics.elidedText(
```
Comment (ronso0) [inline src/library/dlgtagfetcher.cpp:542]: All are const, right?

**Comment by ronso0** [comment]
I wonder if we need the full error string/url at all.
Wouldn't it suffice to show "Can't connect to MusicBrainz" and log the full string?
Or "Can't connect to MusicBrainz. See log for details."

Besides, I wouldn't expect a tooltip on a progressbar.
(is the tooltip always shown, regardless the tooltip setting in Interface preferences?)

File: src/library/dlgtagfetcher.cpp [hunk 2]
```diff
@@ -535,8 +537,16 @@ void DlgTagFetcher::slotNetworkResult(
...
+            cantConnect,
+            Qt::ElideRight,
+            loadingProgressBar->width() - 4);
+    loadingProgressBar->setFormat(elidedCantConnect);
+    if (cantConnect.size() != elidedCantConnect.size()) {
```
Comment (Swiftb0y) [inline src/library/dlgtagfetcher.cpp:547]: Is there the possibility of the edge case that the elided text has the same length as the non-elided text? Could this happen when the text gets elided but then the added ellipses pads it back out to the same length again? That would cause information to be missing (not much sure, but still a character or two) and no tooltip being shown. 
Unless we know this is a performance problem, I would just always set the tooltip. makes the code simpler and avoids the edge case.

**Comment by daschuer** [comment]
> I wonder if we need the full error string/url at all.
> Wouldn't it suffice to show "Can't connect to MusicBrainz" and log the full string?

We show the translated error string form the Qt backend that is intendend to be displayed to the user. So I consider it a good idea to show it. The errror message is long if it contains a long path auto generated path, so eliding will probably not cut off sigificant data and we may consider to remove the tooltip.

> is the tooltip always shown, regardless the tooltip setting in Interface preferences?

Only if the original message is too long and independent froem the preferendes. 

This was just a quick workaround. If you prefer I will remove the tooltip. Please give a hint.

File: src/library/dlgtagfetcher.cpp (hunk 2 above)
Comment (daschuer) [reply src/library/dlgtagfetcher.cpp:547]: Right, that is likely, but no gurantee, because the elipsis can be either the … (https://www.compart.com/de/unicode/U+2026) or ... (three dots) depending on the font.

**Review by Swiftb0y — APPROVED** [review]
LGTM. Thank you.

**Comment by daschuer** [comment]
Merge? @ronso0 Is that OK for now?

**Review by ronso0 — APPROVED** [review]
Yup, LGTM.
Thank you!
