### PR TITLE
Fix crash due to concurrent access in MidiController (Alternative)

### LINKED ISSUE #13940: qhash.h:790 ASSERT on multiple MIDI messages in quick succession
### Bug Description

When my script sends multiple MIDI messages in quick succession, it often makes Mixxx trigger an assert;
```
 [Controller] fatal /usr/include/qt6/QtCore/qhash.h:790 ASSERT: "!isUnused()" in file /usr/include/qt6/QtCore/qhash.h, line 790
```

### Version

_No response_

### OS

_No response_

### PR DESCRIPTION
**Pull request by daschuer**
This is an alternative to fix #13940

I have now "hopfully" managed to wrap my head around the issue. The issue was that the mapping has been cloned from the GUI thread while the Controller thread has applied JS created mappings. This creates a broken copy of the mapping that crashes Mixxx after it was applied back to the Controller thread.  

The solution here keeps now a clean mutable copy of the mapping for the GUI thread. The GUI thread waits until the controller thread has cloned the mapping during "Apply" this way we have sorted out all concurrent access to the mappings. 

This PR is unfortunately a big bigger than expected, because some related code and comments have not been maintained over the years and was misleading making the issue hard to understand.

### CODE REVIEW

**Comment by daschuer** [comment]
@mxmilkiib I have added mutex with debug Information. 
This will hopefully finally fix the crash. However It needs some polishing.
Please Test and provide the mixxx.log. (or the backtrace if it is still crashing)

**Comment by daschuer** [comment]
@mxmilkiib Does this still crash?

**Comment by mxmilkiib** [comment]
yes 

maaaybe this is config file related, removing files manually but Mixxx not forgetting

can't remember the state from before though

**Comment by daschuer** [comment]
Can you please share the mixxx.log of the crash? 
A backtrace is also helpful.

**Comment by mxmilkiib** [comment]
ah this is the older issue

I'll see if I can replicate now, not had any recent ones for this issue though, building from this branch that is

**Comment by daschuer** [comment]
Cool, please also share the mixxx.log from a short test run without crash. This will help me polishing.

**Comment by mxmilkiib** [comment]
https://gist.github.com/mxmilkiib/b223874ec20f85b07840b7e0d2a5ba55

[I managed to make it crash](https://gist.github.com/mxmilkiib/b223874ec20f85b07840b7e0d2a5ba55), on clicking play though.

`DEBUG ASSERT: "it == cbegin() || it == cend() || *it >= position" in function mixxx::Beats::ConstIterator mixxx::Beats::iteratorFrom(mixxx::audio::FramePos) const at ./src/track/beats.cpp:470`

**Comment by daschuer** [comment]
The crasher is unrelated and tracked here: 
https://github.com/mixxxdj/mixxx/issues/13262

**Comment by daschuer** [comment]
@mxmilkiib Please test if the crasher is fixed now.

**Comment by mxmilkiib** [comment]
I haven't had any further issues so I guess draw a line under it for now.

**Review by acolombier — APPROVED** [review]
Code's LGTM, but no Midi mapping to test it with. Looks reasonably safe to merge without it, thanks!

File: src/controllers/dlgprefcontroller.cpp [hunk 1]
```diff
@@ -103,7 +103,11 @@ DlgPrefController::DlgPrefController(
     connect(this,
             &DlgPrefController::applyMapping,
             m_pControllerManager.get(),
-            &ControllerManager::slotApplyMapping);
+            &ControllerManager::slotApplyMapping,
+            Qt::BlockingQueuedConnection);
```
Comment (acolombier) [inline src/controllers/dlgprefcontroller.cpp:107]: This has introduced a deadlock when using with screen controller, which rely on the main thread (GUI) availability ([see doc](https://doc.qt.io/qt-6/qoffscreensurface.html#create))
