### PR TITLE
Hotcue: allow setting hotcue inside active, saved loop

### LINKED ISSUE #12618: simplify setting hot cue inside a loop from the GUI
### Bug Description

I don't think it's possible currently; creating one will make it be at the start of the loop as a loop;

image

### Version

2.4-beta

### PR DESCRIPTION
**Pull request by ronso0**
Fixes #12618 

* activate a loop
* seek inside the loop
* trigger `hotcue_A_activate` or `hotcue_A_set`
   * new loop cue at loop start position
* trigger `hotcue_B_activate` or `hotcue_B_set`
   * new hotcue at current position

Probably need to adjust some tests

### CODE REVIEW

File: src/engine/controls/cuecontrol.cpp [hunk 1]
```diff
@@ -852,7 +852,25 @@ void CueControl::hotcueSet(HotcueControl* pControl, double value, HotcueSetMode
 
     bool loopEnabled = m_pLoopEnabled->toBool();
     if (mode == HotcueSetMode::Auto) {
-        mode = loopEnabled ? HotcueSetMode::Loop : HotcueSetMode::Cue;
+        if (loopEnabled) {
+            // Don't create a hotcue at loop start if there is one already.
+            // This allows to set a hotuce inside an active, saved loop with
+            // 'hotcue_X_activate'.
+            auto pSavedLoopControl = m_pCurrentSavedLoopControl.loadAcquire();
```
Comment (daschuer) [inline src/engine/controls/cuecontrol.cpp:859]:
```suggestion
            auto* pSavedLoopControl = m_pCurrentSavedLoopControl.loadAcquire();
```

**Review by daschuer — CHANGES_REQUESTED** [review]
Thank you, need to test.

**Comment by daschuer** [comment]
I can confirm the issue and that it is fixed with this PR.

**Comment by Holzhaus** [comment]
Should there be a way to disable this magic? I sometimes use this to clone loop cues and then clear the original one.

**Comment by ronso0** [comment]
> I sometimes use this to move loop cues

You mean store the loop in another cue?
If so, you can do it the other way around:
* activate the saved loop `4`
* clear the cue (loop still active)
* hit hotcue `2`, done

Related: #9968

**Comment by ronso0** [comment]
Wouldn't hurt to add a test for this.

**Comment by ronso0** [comment]
Okay, this is ready.

**Review by daschuer — APPROVED** [review]
LGTM, Thank you
