### PR TITLE
[fix] Fix automatic trimming of search bar text

### LINKED ISSUE #14486: Search bar automatically trims spaces in the UI
### Bug Description

The search field automatically seems to trim spaces when the user leaves the cursor idle for a moment:

https://github.com/user-attachments/assets/8d0198e3-4684-4cf2-923d-d11678f00b3a

Filing this as a bug, since at least from a UX perspective that feels unintuitive (and a bit annoying when taking a quick break while writing a search query).

### Version

2.6/main (most recent snapshot build)

### OS

macOS 15.2

### PR DESCRIPTION
**Pull request by dhunstack**
https://github.com/user-attachments/assets/7ea62478-1a1f-47b6-befe-eab3788b1a63

As described in issue #14486, the search bar trims leading and trailing spaces in user's current text input after the auto-save timeout. 
This PR fixes the issue by removing the problematic `trimmed()` call.

### CODE REVIEW

File: src/widget/wsearchlineedit.cpp [hunk 1]
```diff
@@ -543,7 +543,7 @@ void WSearchLineEdit::slotTriggerSearch() {
 /// saves the current query as selection
 void WSearchLineEdit::slotSaveSearch() {
     m_saveTimer.stop();
-    QString cText = currentText().trimmed();
+    QString cText = currentText();  // Keep original text with spaces for UI
```
Comment (ronso0) [inline src/widget/wsearchlineedit.cpp:546]:
```suggestion
    // Keep original text for UI, potentially with trailing spaces
    QString cText = currentText();
```

**Review by ronso0 — CHANGES_REQUESTED** [review]
Thank you, the whitespace fix LGTM

But I think you need to adjust [`findCurrentTextIndex()`](https://github.com/mixxxdj/mixxx/blob/0b025c49214a4452f15e7d91bcb999bc0563ba6d/src/widget/wsearchlineedit.h#L96), too. Currently the text (with spaces) is added to the list (without spaces) over and over again when you open the query list.

**Comment by ronso0** [comment]
Btw the bug already exists in 2.5, so please rebase and force-push.
And I think you can squash the commits.

File: src/widget/wsearchlineedit.cpp (hunk 1 above)
Comment (dhunstack) [reply src/widget/wsearchlineedit.cpp]: You're right, the query list was getting repeated updations. 
I've fixed this, and the behaviour seems to be okay now.

**Comment by dhunstack** [comment]
> Btw the bug already exists in 2.5, so please rebase and force-push. And I think you can squash the commits.

I was having trouble with rebase. So I squashed the commits and cherry-picked it onto `2.5` tag.

**Comment by ronso0** [comment]
Thank you, LGTM :+1: 
I'll do a final test tomorrow. Or some other @mixxxdj/developers does it.

FWIW I noticed a glitch in LateNight (PaleMoon) that _may_ also exist in 2.5:
type a query, open query list -> searchbar shrinks in height (happens only on first call)
height is restored when the text cursor is moved in the searchbar.

**Review by ronso0 — APPROVED** [review]
LGTM, thank you!

**Comment by ronso0** [comment]
Oh, and we still need you sign the [Mixxx Contributor Agreement](https://docs.google.com/forms/d/e/1FAIpQLScC9QG327sjLL0eWftmfGUasxFFLxg6LCXJ2xHDYRzFIRqyiw/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ) and comment here when you have done so. It gives us permission to distribute your contribution under the GPL v2 or later license and the Apple Mac App Store. It is also helpful for us to have contact information for contributors in case we may need it in the future.

**Comment by ronso0** [comment]
Can you please rebase onto 2.5 to trigger CI?
Idk why it's not running, maybe because we didn't trigger all checks before the force-push? :shrug:

**Comment by dhunstack** [comment]
> LGTM, thank you!

Hi, thanks for approving the PR. I've been occupied with a conference deadline for this Friday, apologies for the delay. 



> Oh, and we still need you sign the [Mixxx Contributor Agreement](https://docs.google.com/forms/d/e/1FAIpQLScC9QG327sjLL0eWftmfGUasxFFLxg6LCXJ2xHDYRzFIRqyiw/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ) and comment here when you have done so. It gives us permission to distribute your contribution under the GPL v2 or later license and the Apple Mac App Store. It is also helpful for us to have contact information for contributors in case we may need it in the future.

Done

> Can you please rebase onto 2.5 to trigger CI? Idk why it's not running, maybe because we didn't trigger all checks before the force-push? 🤷

I just force pushed after rebase, still doesn't trigger CI. 
I see this message on my end actually, says some maintainer needs to approve the workflow?

ApprovalAwaiting

**Comment by ronso0** [comment]
> I see this message on my end actually, says some maintainer needs to approve the workflow?

Yeah, now it's there again. weird..

**Comment by ronso0** [comment]
Thank you very much!
