### PR TITLE
AutoDJ: fix GUI freeze when updating duration for many selected tracks

### LINKED ISSUE #12520: Selecting many tracks in the AutoDJ queue may freeze the GUI
### Bug Description

Reported here https://mixxx.discourse.group/t/i-did-something-stupid/28750, and confirmed.

I suspect it's the function that updates the track count and play duration of the queue.
https://github.com/mixxxdj/mixxx/blob/f610d58a25b6f97172b097fb2a7a79147d863f7d/src/library/autodj/dlgautodj.cpp#L365-L375

### Version

_No response_

### OS

_No response_

### PR DESCRIPTION
**Pull request by ronso0**
fixes #12520 

* ~~move the duration collection to TrackDAO~~
* ~~query the database duration column instead of inspecting each Track object~~
____
* move the duration collection to PlaylistTableModel
(could also be in any of the classes that is derived from but... YAGNI?)
* query the duration column of each row instead of inspecting each Track object

Now updating the info for ~16k tracks takes ~5ms here.
With the 2.4 code, updating the info for 3 tracks already takes ~40ms :grimacing:

### CODE REVIEW

**Comment by ronso0** [comment]
@uklotzde Do you have time to take a look?

**Comment by ronso0** [comment]
I'll check if this should better be a helper function in PlaylistDAO, for example `getDuration(int playlistId, QList<int> positions)`.

**Comment by ronso0** [comment]
> Hmm, no, this should better be a helper in PlaylistTableModel

Yes, and that's also much faster: ~5ms vs. 28ms for 16k tracks

File: src/library/playlisttablemodel.cpp [hunk 1]
```diff
@@ -319,6 +319,22 @@ void PlaylistTableModel::shuffleTracks(const QModelIndexList& shuffle, const QMo
     m_pTrackCollectionManager->internalCollection()->getPlaylistDAO().shuffleTracks(m_iPlaylistId, positions, allIds);
 }
 
+double PlaylistTableModel::getDurationOfRows(const QModelIndexList& indices) {
```
Comment (ywwg) [inline src/library/playlisttablemodel.cpp:322]: can you add a short explanatory comment, like:
// Derive total duration from the display widget instead of the database to speed up calculation.

**Review by ywwg — APPROVED** [review]

File: src/library/playlisttablemodel.cpp (hunk 1 above)
Comment (ronso0) [reply src/library/playlisttablemodel.cpp:322]: I'll add that in DlgAutoDJ where it is called, no need to mention that here IMO

File: src/library/playlisttablemodel.cpp [hunk 2]
```diff
@@ -319,6 +319,22 @@ void PlaylistTableModel::shuffleTracks(const QModelIndexList& shuffle, const QMo
...
+    double durationTotal = 0.0;
+    if (indices.isEmpty()) {
+        return durationTotal;
+    }
+
+    const int durationColumnIndex = fieldIndex(ColumnCache::COLUMN_LIBRARYTABLE_DURATION);
+    for (const auto index : indices) {
```
Comment (daschuer) [inline src/library/playlisttablemodel.cpp:329]:
```suggestion
    for (const auto& index : indices) {
```

**Review by daschuer — CHANGES_REQUESTED** [review]
just on missing &

**Comment by ronso0** [comment]
Done.

**Review by daschuer — APPROVED** [review]
LGTM, thank you

**Comment by ronso0** [comment]
Oh, I just pushed the changes suggested by @uklotzde (it was a comment not a formal change request).
https://github.com/mixxxdj/mixxx/commit/4240e9056c48985ac91e747aeaead6ceadca125d?notification_referrer_id=NT_kwDOAFqMd7I5MDIwODc3MjE3OjU5MzQxOTk

The update is #12537
