### PR TITLE
Tracks: avoid re-sorting table when purging/hiding tracks

### LINKED ISSUE #12565: Library: visual glitch on removing item from Crate, cover art stays, rows move up but ~16 above
### Bug Description

I'm seeing this thing that on removing an item , there's a kind of glitch, the cover art for that row doesn't disappear, it steys the same one is removed like 16 items up, and other tracks' text all jump up one row, but the cover art stays the same height.

### Version

main

### OS

Arch

### PR DESCRIPTION
**Pull request by ronso0**
Should fix #12565 

### Reproduce the issue:
* go to Tracks, sort by "last played"
* play some tracks
  -> their "last played" values changes, track order is stable
* remove (purge) or hide a track, via hotkey, deck or table track menu
-> table is resorted by "last played" :| sometimes also the selected index is lost

After purge/hide `BaseSqlTableModel::select()` is called, which rebuilds the model cache with with new values from the db. This implies re-sorting.

### The fix:
Based on the assumption that metadata of the tracks remaning after purge/hide is unchanged, we don't need to call `select()` -- we can simply remove the obsolete rows.
This does however not apply to Playlists where removing tracks changes the 'position' value of the others. There we still `select()` for now.

**Note:** so far I only tested with Tracks.
Also test with the Crates and Hidden views.

### CODE REVIEW

File: src/library/basesqltablemodel.cpp [hunk 1]
```diff
@@ -844,7 +844,61 @@ void BaseSqlTableModel::hideTracks(const QModelIndexList& indices) {
...
+    // tracks by avoiding pointless/confusing re-sorting of the model.
+    // Since metadata of remaining tracks hasn't changed, we can simply remove
+    // the respective track rows.
+    //
+    // However, if this is a playlist model, track removal likely also changes
+    // the track's position in the playlist. We need to get the tracks' new
+    // positions from the database, so let's do a select().
+    // FIXME Update position without re-sorting
+    if (hasPositionColumn()) {
+        qWarning() << "-------------- BaseSqlTableModel::removeTrackRows has "
```
Comment (daschuer) [inline src/library/basesqltablemodel.cpp]: This seems to be a debug leftover

File: src/library/basesqltablemodel.cpp [hunk 2]
```diff
@@ -844,7 +844,61 @@ void BaseSqlTableModel::hideTracks(const QModelIndexList& indices) {
...
+                      "position column -> select()";
+        select();
+        return;
+    }
+
+    qWarning() << "-------------- BaseSqlTableModel::removeTrackRows";
```
Comment (daschuer) [inline src/library/basesqltablemodel.cpp]: debug leftover?

**Review by daschuer — CHANGES_REQUESTED** [review]
The fix is reasonable. 
This works for hiding, but now for delete form crates. Can you add it there as well?

**Comment by ronso0** [comment]
I also implemented it for crates and removed the debug stuff.

**Review by daschuer — APPROVED** [review]
LGTM, and works nice. Thank you.
