### PR TITLE
Fix building with clang 32 (macOS 12) 

### LINKED ISSUE #11762: Building Mixxx 2.4 fails with Xcode 12.4
### Bug Description

It looks like it insists to use the copy constructor when using operator[]

```
../src/effects/backends/effectprocessor.h:204:37: note: in instantiation of member function 'ChannelHandleMap<unique_ptr_vector<BalanceGroupState> >::operator[]' requested here
        auto& outputChannelStates = m_channelStateMatrix[inputChannel];
                                    ^
../src/effects/backends/builtin/balanceeffect.cpp:87:21: note: in instantiation of member function 'EffectProcessorImpl<BalanceGroupState>::initializeInputChannel' requested here
void BalanceEffect::loadEngineEffectParameters(
                    ^
/Applications/Xcode_12.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:2518:3: note: copy constructor is implicitly deleted because 'unique_ptr<BalanceGroupState, std::__1::default_delete<BalanceGroupState> >' has a user-declared move constructor
  unique_ptr(unique_ptr&& __u) _NOEXCEPT
  ^
1 error generated.
```

### Version

2.4-beta

### OS

macOS

### PR DESCRIPTION
**Pull request by daschuer**
Our current minimum is macOS 10.12

This fixes #11762

### CODE REVIEW

File: src/engine/channelhandle.h [hunk 1]
```diff
@@ -219,7 +219,7 @@ class ChannelHandleMap {
         } else {
             // We need to initialize simple types ourselves
             while (m_data.size() < iSize) {
-                m_data.append({});
+                m_data.append(std::move(T()));
```
Comment (Swiftb0y) [inline src/engine/channelhandle.h:222]: Move is unnecessary since this is already a prvalue iiuc
```suggestion
                m_data.append(T());
```

**Review by Swiftb0y — APPROVED** [review]
LGTM

**Comment by daschuer** [comment]
Done.

**Review by Swiftb0y — APPROVED** [review]
LGTM
