### PR TITLE
EGL

### LINKED ISSUE #11641: 2.4 doesn't start with QT_OPENGL=angle on Windows
### Bug Description

@m0dB :
I tried to start Mixxx with the environment variable QT_OPENGL set to angle. It fails to start:
```
debug [Main] Set root GL Context widget valid: WInitialGLWidget(0x19544c9bb10) false
critical [Main] Failed to load libEGLd (Das angegebene Modul wurde nicht gefunden.)
warning [Main] QWindowsEGLStaticContext::create: Failed to load and resolve libEGL functions
debug [Main] Displaying main window
debug [Main] Running Mixxx
critical [Main] Failed to load libEGLd (Das angegebene Modul wurde nicht gefunden.)
warning [Main] QWindowsEGLStaticContext::create: Failed to load and resolve libEGL functions
warning [Main] QOpenGLWindow::beginPaint: Failed to create context
warning [Main] QOpenGLWindow::beginPaint: Failed to make context current
```

### Version

2.4.0

### OS

Windows11

### PR DESCRIPTION
**Pull request by daschuer**
This brings back the GLES support required for Windows drivers that are ignored by QT and on Single PCB devices like Raspberry PI. 

The spinnies are still black. https://github.com/mixxxdj/mixxx/issues/11930

Fixes https://github.com/mixxxdj/mixxx/issues/11641

### CODE REVIEW

File: src/waveform/waveformwidgetfactory.cpp [hunk 1]
```diff
@@ -1168,14 +1171,17 @@ QString WaveformWidgetFactory::buildWidgetDisplayName() const {
         extras.push_back(tr("legacy"));
     }
     if (isOpenGlAvailable() || isOpenGlesAvailable()) {
-        if (WaveformT::useOpenGLShaders()) {
+        if (WaveformT::useOpenGles()) {
+            if (WaveformT::useOpenGLShaders()) {
+                extras.push_back(QStringLiteral("GLSL ES"));
+            } else {
+                extras.push_back(QStringLiteral("GLES"));
```
Comment (Swiftb0y) [inline src/waveform/waveformwidgetfactory.cpp:1178]:
```suggestion
                extras.push_back(QStringLiteral("GL ES"));
```

File: src/shaders/endoftrackshader.cpp [hunk 2]
```diff
@@ -15,12 +15,12 @@ void main()
 )--");
 
     QString fragmentShaderCode = QStringLiteral(R"--(
-uniform vec4 color;
-varying float vgradient;
+uniform highp vec4 color;
+varying highp float vgradient;
```
Comment (Swiftb0y) [inline src/shaders/endoftrackshader.cpp:19]: `highp` support is optional in the fragment shader. `lowp` is sufficient for color afaik.
```suggestion
uniform lowp vec4 color;
varying mediump float vgradient;
```

File: src/waveform/waveformwidgetfactory.cpp (hunk 1 above)
Comment (Swiftb0y) [inline src/waveform/waveformwidgetfactory.cpp:1178]: we now have a bunch of shaders being compatible with plain openGL and OpenGL ES, what "backend" does it choose by default?

**Review by Swiftb0y — CHANGES_REQUESTED** [review]
Thank you. I'll do a manual test soon. also, iiuc this has nothing to do with EGL and is only concerning GL ES support/compatibility...

File: src/waveform/waveformwidgetfactory.cpp (hunk 1 above)
Comment (daschuer) [reply src/waveform/waveformwidgetfactory.cpp:1178]: This is currently not visible anyway but this is taken from: [OpenGL ES or GLES](https://en.wikipedia.org/wiki/OpenGL_ES)

File: src/shaders/endoftrackshader.cpp (hunk 2 above)
Comment (daschuer) [reply src/shaders/endoftrackshader.cpp:19]: I have read that the hardware takes anyway the ALU it has which should be 32 bit for all floats. So I think there is no point in reducing it and risk regression compared to the OpenGL version that is 32 bit anyway. 

If we have a ES hardware that has only 24 bit floats among our targets, we need to reduce all float to mediump.

File: src/waveform/waveformwidgetfactory.cpp (hunk 1 above)
Comment (Swiftb0y) [reply src/waveform/waveformwidgetfactory.cpp:1178]: Right, that strategy makes sense, but it does not reflect how the name is chosen here where ES is prioritized just based on what the shader supports.

File: src/shaders/endoftrackshader.cpp (hunk 2 above)
Comment (daschuer) [reply src/shaders/endoftrackshader.cpp:19]: I have no interest maintain two precisions for no reason. Do you have an example device, that is not supported right now? If not, let's learn from the user once rendering fails and save our developer resources here.

File: src/waveform/waveformwidgetfactory.cpp (hunk 1 above)
Comment (daschuer) [reply src/waveform/waveformwidgetfactory.cpp:1178]: The name is dynamically changed according to the context that is used.  You will see 
"RGB (GLSL ES)" on a Raberry Pie and "RGB (GLES)" on your Laptop.

File: src/shaders/endoftrackshader.cpp (hunk 2 above)
Comment (Swiftb0y) [reply src/shaders/endoftrackshader.cpp:19]: there is no reason to maintain two precisions. We don't need `highp` for many of these fragment shader uniforms, so lets just choose the safer default.

File: src/waveform/waveformwidgetfactory.cpp (hunk 1 above)
Comment (daschuer) [reply src/waveform/waveformwidgetfactory.cpp:1178]: Oh I see that is currently broken. I will fix it.

File: src/shaders/endoftrackshader.cpp (hunk 2 above)
Comment (daschuer) [reply src/shaders/endoftrackshader.cpp:19]: Yes that's why I picked highp. It works like OpenGL and we don't need to test two versions.

Comment (daschuer) [reply src/shaders/endoftrackshader.cpp:19]: We can change it at any time, no objections. It just requires tests, I don't want to do right now.

Comment (Swiftb0y) [reply src/shaders/endoftrackshader.cpp:19]: Right. My argument is that we change it now because in the case where the GLES waveforms are broken because of `highp` people will just fallback to the cpu waveforms assuming their hardware is incapable, even though it technically would be.

Comment (Swiftb0y) [reply src/shaders/endoftrackshader.cpp:19]: The alternative would to be `ifdef` it in the shader, that would likely be most robust, but creates a bunch of duplicated code across the shaders.

Comment (daschuer) [reply src/shaders/endoftrackshader.cpp:19]: The ifdef is already there in the Qt shader wrapper. 
`#define highp` 
Removing highp for the GL case.

Comment (Swiftb0y) [reply src/shaders/endoftrackshader.cpp:19]: No I meant
```glsl
#ifndef GL_FRAGMENT_PRECISION_HIGH
#define highp mediump
#endif
```
in the fragment shader. Then the shader will use highp if available and fallback if otherwise.

Comment (daschuer) [reply src/shaders/endoftrackshader.cpp:19]: It turns out that it is already there behind the scenes: 
https://github.com/qt/qtbase/blob/737dd9595058a457fdd8f336ee8630cb1e2c57bb/src/opengl/qopenglshaderprogram.cpp#L445

Not sure if it is in action though.

Comment (Swiftb0y) [reply src/shaders/endoftrackshader.cpp:19]: Ok weird, well I'll take the gamble then and hope it is in action on the platforms where it makes sense.

**Review by Swiftb0y — APPROVED** [review]
No regressions on fedora as far as I can tell. LGTM

**Comment by daschuer** [comment]
Thank you.

**Comment by JoergAtGithub** [comment]
I just build 2.4 and now Mixxx does no longer start up under Windows 11, when started from install directory of `x64_legacy` with `$env:QT_OPENGL = 'angle'`
```
warning [Main] QWindowsEGLContext: Failed to create context, eglError: 3004, this: 0x25b91296890
warning [Main] QOpenGLWindow::beginPaint: Failed to create context
warning [Main] QOpenGLWindow::beginPaint: Failed to make context current
```
With `$env:QT_OPENGL = 'desktop'` or  `$env:QT_OPENGL = 'software'` everything works still fine using the AMD OpenGL driver.

**Comment by Swiftb0y** [comment]
Have you considered removing the `QSurfaceFormat::setProfile` call? The qt docs say that it'll be ignored when not supported but maybe that's broken?

**Comment by JoergAtGithub** [comment]
It seem my previous test result was not correct. I cleaned the install directory and installed again, and now get:
```
debug [Main] OpenGL driver version string "OpenGL ES 3.0.0 (ANGLE 2.1.5414 git hash: aa63ea230e0c)", vendor "Google Inc. (AMD)", renderer "ANGLE (AMD, AMD Radeon(TM) Graphics Direct3D11 vs_5_0 ps_5_0, D3D11-31.0.12044.50003)"
debug [Main] Supported OpenGL version: 3.0
```
but later it fails with:
```
warning [Main] QOpenGLShader::compile(Fragment): ERROR: 0:7: '0.75f' : Floating-point suffix unsupported prior to GLSL ES 3.00
ERROR: 0:7: '0.75f' : syntax error

warning [Main] *** Problematic Fragment shader source code ***
#ifdef GL_KHR_blend_equation_advanced
#extension GL_ARB_fragment_coord_conventions : enable
#extension GL_KHR_blend_equation_advanced : enable
#endif
#line 1

uniform sampler2D sampler;
uniform highp vec4 color;
varying highp vec3 vTexcoor;
void main()
{
    gl_FragColor = vec4(color.xyz, texture2D(sampler, vTexcoor.xy) * 0.75f);
}

***
DEBUG ASSERT: "addShaderFromSourceCode( GLShader::Fragment, fragmentShaderCode)" in function void __cdecl mixxx::Shader::load(const class QString &,const class QString &) at C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\shaders\shader.cpp:24
```

**Comment by Swiftb0y** [comment]
right, thats a clearer error now at least. Can you fix the shaders locally and try again?
