### PR TITLE
(fix/UX) Cue button: start drag only if press started preview from Cue

### LINKED ISSUE #16302: GUI: Cue Drag'n'drop on Play
### Bug Description

Cue can be drag'n'drop to play.
Sequence: cue, dnd, play -> play.
During playing, cue stops the deck and drag'n'drop should be unable, but it's enabled.  

### Version

v.2.7 alpha 223
Skin: LateNight

### OS

_No response_

### PR DESCRIPTION
**Pull request by ronso0**
Fixes #16302 by addressing my own TODO for polished UX

### CODE REVIEW

File: src/widget/wcuebutton.cpp [hunk 1]
```diff
@@ -42,7 +43,13 @@ void WCueButton::mouseMoveEvent(QMouseEvent* pEvent) {
         return;
     }
 
-    // TODO Initiate drag only if pressing this button actually starts cue preview?
+    // Initiate drag only if pressing this button actually started cue preview.
+    // (it has already been stopped on press if the track was playing,
+    // so drop onto Play would have no effect anyway)
+    if (ControlObject::get(ConfigKey(m_group, QStringLiteral("play"))) <= 0) {
```
Comment (vespadj) [inline src/widget/wcuebutton.cpp]: or "play_latched" ?

Comment (vespadj) [reply src/widget/wcuebutton.cpp]: "play" should be OK, I can try after build.

Comment (ronso0) [reply src/widget/wcuebutton.cpp]: `play_latched` would be wrong.
As soon as you **press** Cue, it either
* starts previewing -> `play` = 1, `play_latched` = 0
* stops playing, seeks to Cue -> `play` = 0, `play_latched` = 0

And the DnD (`mouseMoveEvent`) is called afterwards (and only if the button is pressed)

**Comment by vespadj** [comment]
I try the amd64 build and now this work as expected. 🚀

File: src/widget/wcuebutton.cpp (hunk 1 above)
Comment (daschuer) [inline src/widget/wcuebutton.cpp]: Looking up the control object is a locking function. Since mouse move hapens often it is reasonable to use here a PoliingControlProxy

**Review by daschuer — CHANGES_REQUESTED** [review]

File: src/widget/wcuebutton.cpp (hunk 1 above)
Comment (daschuer) [reply src/widget/wcuebutton.cpp]: You can also use toBool()

**Review by daschuer — APPROVED** [review]
LGTM, thank you. Please squash and I will merge.

**Review by daschuer — APPROVED** [review]
LGTM thank you.
