### PR TITLE
Remove autdated ASSERT fixing #13164

### LINKED ISSUE #13164: DEBUG_ASSERT in basetracktablemodel.cpp on header splitter click
### Bug Description

```
critical [Main] DEBUG ASSERT: "siblingColumn != index.column()" in function virtual QVariant BaseTrackTableModel::rawSiblingValue(const QModelIndex&, ColumnCache::Column) const at ./src/library/basetracktablemodel.cpp:492
```

### Version

2.4.0

### OS

Ubuntu Focal

### PR DESCRIPTION
**Pull request by daschuer**
fixes #13164

### CODE REVIEW

**Comment by daschuer** [comment]
cleaning up the 2.4.1 milestone from this hard to reproduce issue

File: src/library/basetracktablemodel.cpp [hunk 1]
```diff
@@ -489,10 +489,6 @@ QVariant BaseTrackTableModel::rawSiblingValue(
         // FIXME: This should never happen but it does. But why??
         return QVariant();
     }
-    VERIFY_OR_DEBUG_ASSERT(siblingColumn != index.column()) {
```
Comment (acolombier) [inline src/library/basetracktablemodel.cpp:492]: Should this be replaced with a `if` instead of removing the condition check entirely like above? Reading the comment, since it seems the early return was here to prevent infinite recursion. Or is that comment incorrect/out of date?

**Comment by daschuer** [comment]
I have made rawValue() pure virtual to show that we have no infinitive recursive call issue.

**Review by Swiftb0y — APPROVED** [review]
LGTM :shrug:

**Comment by daschuer** [comment]
@Swiftb0y merge?

**Comment by Swiftb0y** [comment]
I guess :shrug:
