### PR TITLE
(fix) Library scanner: make Cancel button work again

### LINKED ISSUE #14940: Library Scanner Cancel button broken.
### Bug Description

When I start a long library scan, the progress dialog pops up. 
When I press abort, the HDD is still spinning in background and library work continues making Mixxx virtually unusable. 

The attempt to load a new tracks stalls the Mixxx GUI completely. The current track was playing to the end and then silence. 

In another atempt I have tried to close Mixxx after aborting. But this did not work either. The GUI disappears, but the Mixxx process keeps accessing the disk. 

This is the log: 
```
08:59:21.920 Debug [LibraryScanner 1] TrackDAO - TrackDAO: Adding track "/home/daniel/Musik/Volume_Musik/Meghan Trainor - 2015 - Title/Meghan Trainor - 07 - Bang Dem Sticks.mp3"
08:59:22.084 Debug [LibraryScanner 1] TrackDAO - TrackDAO: Adding track "/home/daniel/Musik/Volume_Musik/Meghan Trainor - 2015 - Title/Meghan Trainor - 08 - Walkashame.mp3"
08:59:22.255 Debug [LibraryScanner 1] TrackDAO - TrackDAO: Adding track "/home/daniel/Musik/Volume_Musik/Meghan Trainor - 2015 - Title/Meghan Trainor - 09 - Title.mp3"
08:59:22.293 Warning [Main] ./src/library/dao/playlistdao.cpp 432 FAILED QUERY [ "INSERT INTO PlaylistTracks (playlist_id, track_id, position, pl_datetime_added)VALUES (:playlist_id, :track_id, :position, CURRENT_TIMESTAMP)" ] QSqlError("5", "Der Datensatz konnte nicht abgeholt werden", "database is locked")
08:59:22.293 Debug [Main] Rolling back transaction on "MIXXX-1" result: true
08:59:22.326 Debug [Main] dropEventFiles() true QList(QUrl("file:///home/daniel/Musik/Volume_Musik/KeyFinder/Vector Lovers - Tokyo Glitterati.mp3"))
08:59:22.326 Debug [Main] mimeData.hasText() true "library"
08:59:22.328 Debug [Main] dropEventFiles() true QList(QUrl("file:///home/daniel/Musik/Volume_Musik/KeyFinder/Vector Lovers - Tokyo Glitterati.mp3"))
08:59:22.328 Debug [Main] mimeData.hasText() true "library"
08:59:22.428 Debug [LibraryScanner 1] TrackDAO - TrackDAO: Adding track "/home/daniel/Musik/Volume_Musik/Meghan Trainor - 2015 - Title/Meghan Trainor - 10 - What If I.mp3"
08:59:22.595 Debug [LibraryScanner 1] TrackDAO - TrackDAO: Adding track "/home/daniel/Musik/Volume_Musik/Meghan Trainor - 2015 - Title/Meghan Trainor - 11 - Lips Are Movin'.mp3"
08:59:22.751 Debug [LibraryScanner 1] TrackDAO - TrackDAO: Adding track "/home/daniel/Musik/Volume_Musik/Meghan Trainor - 2015 - Title/Meghan Trainor - 12 - No Good For You.mp3"
```

### Version

2.5.2-26

### OS

Ubuntu 24.04

### PR DESCRIPTION
**Pull request by ronso0**
Closes #14940 

Extracted fixes from #15156 which traces the scan flow.

1. **Cancel button "doesn't work"**
Pretty quickly after starting the scan, many ImportFilesTask (separate thread(s)) queue many `addNewTrack()` signals.
So when cancelling the scan via Cancel button, the `cancel` signal is at the end of the queue and is not processed immediately.
Fix: use explicit Qt:DirectConnection
2. **Even if, with fix 1., the dialog is closed, but the track import keeps running in the background**
`ScannerGlobal::shouldCancel()` is considered only when/before each file import task is processing a file and queing signals, and as mentioned, that happens almost immediately after starting the scan.
= Cancel has currently no effect in `slotAddTrack()` calls and Mixxx continues processing the queued signals and keeps adding/analyzing tracks as if nothing happened.
Fix: check `shouldCancel()` when entering `slotAddTrack()` and return if it's true.

### CODE REVIEW

File: src/library/scanner/libraryscanner.cpp [hunk 1]
```diff
@@ -573,6 +574,17 @@ void LibraryScanner::slotTrackExists(const QString& trackPath) {
...
+        // Fix/workaround for Cancel not cancelling the entire scan process
+        // https://github.com/mixxxdj/mixxx/issues/14940
+        // Pretty quickly after starting the scan, many ImportFilesTask queue
+        // many addNewTrack() signals connected to this slot. When cancelling the
+        // scan via Cancel button in the progress dialog, all signals are usually
+        // already queued, hence Cancel has no effect on these calls and Mixxx
+        // keeps adding/analyzing tracks as if nothing happened.
+        // Simply abort here does the trick.
+        return;
+    }
```
Comment (ronso0) [inline src/library/scanner/libraryscanner.cpp:589]: Note: we might also try `disconnect()` here or in `slotCancel()`, but I didn't manage to disconnect just `slotAddNewTrack()` when the task pointer isn't available anymore. And disconnecting ALL signals is probably not what we want :\

**edit** ... and queued signals may still call slots after disconnect()

**Comment by ronso0** [comment]
@ywwg Wanna take a look?

File: src/library/scanner/libraryscanner.cpp [hunk 2]
```diff
@@ -138,7 +138,8 @@ LibraryScanner::LibraryScanner(
     connect(m_pProgressDlg.data(),
             &LibraryScannerDlg::scanCancelled,
             this,
-            &LibraryScanner::slotCancel);
+            &LibraryScanner::slotCancel,
+            Qt::DirectConnection);
```
Comment (daschuer) [inline src/library/scanner/libraryscanner.cpp:142]: Making this a direct connection introduces some concurrency issues. Is this strictly required for the solution?

Comment (ronso0) [reply src/library/scanner/libraryscanner.cpp:142]: After fix2 I thought the same, and yes, it was necessary.
The dialog just wouldn't close, IMO because the `cancel()` signal is queued after all these (poetntially thousands of) `addTrack()` signals.
-> In my case at least, I'm building with Qt 6.2.3 but I doubt that makes a difference.

Please try yourself without this explicit connection.

I'm not sure which concurrency issues you expect?
Cancel is supposed to cancel immediatly, or at least as fast as possible, like not process another hundred tracks so we get GUI feedback asap.

Comment (ronso0) [reply src/library/scanner/libraryscanner.cpp:142]: Taking a look at `slotCancel()` -> `cancel()`, the latter does `m_pool.waitForDone()`.
Isn't that sufficient?

**Comment by daschuer** [comment]
I took a closer look and I can confirm that threading should be fine.

**Review by daschuer — APPROVED** [review]
LGTM, Thank you.

**Comment by ronso0** [comment]
FWIW I have the feeling that it would be better to just disconnect all slots we connect in [`queueTask()`](https://github.com/mixxxdj/mixxx/blob/4a225f95731c14be12d2c7a27e3101ab2244af7d/src/library/scanner/libraryscanner.cpp#L547-L573)

**Comment by daschuer** [comment]
Oh I have just missed to press merge. Do you want to check it out or do we want to go ahead?

**Review by daschuer — CHANGES_REQUESTED** [review]
Oh, I just noticed that we have a memory leak here the task is not deleted when the library scanner has been already canceled: 

https://github.com/mixxxdj/mixxx/blob/4a225f95731c14be12d2c7a27e3101ab2244af7d/src/library/scanner/libraryscanner.cpp#L551

**Comment by ronso0** [comment]
> FWIW I have the feeling that it would be better to just disconnect all slots we connect in [`queueTask()`](https://github.com/mixxxdj/mixxx/blob/4a225f95731c14be12d2c7a27e3101ab2244af7d/src/library/scanner/libraryscanner.cpp#L547-L573)

Is not guaranteed to work, says the documentation
> Note: If a [queued connection](https://doc.qt.io/qt-6/qt.html#ConnectionType-enum) is disconnected, already scheduled events may still be delivered, causing the receiver to be called after the connection is disconnected.
____
> Oh, I just noticed that we have a memory leak here the task is not deleted when the library scanner has been already canceled:

Do you have a fix handy?

**Comment by daschuer** [comment]
I think there is a major underlying design flaw that is around QThreadPool that is the root cause for this issue. 
However this is a bit of a refactoring, probably no longer a stable bug fix. So I suggest to fix the memory leak here and postpone the complete fix to main. 

This is my understanding: 

We have a QThreadPool with one thread. This means that all tasks are queued up and only one is executed at a time. 
This means all tasks are executed one after another until they reach the rend of there run() function. 

This means  
* RecursiveScanDirectoryTask is done for the root directory. 
* Task ImportFilesTask is queued 
* A Task for each sub directory is RecursiveScanDirectoryTask queued. 

This means we have a task for each directory and file, filling the queue in the QThreadPool. 

They however relative fast because the operate only on the directory. 
The result is cued up in the Qt event queue as "slotAddNewTrack" waiting for the library task to. 

All these new and delete and connect() calls are locking, potentially locking main Mixxx. They have probably been introduced for a full concurrent scanner. Which makes the regression for main Mixxx even worse, that's why we have probably only one worker. 

However the user expectation (my expectation) is that they can cancel the scan and have all info since then saved.  The stacked "slotAddNewTrack" + stacked Tasks in QThreadPool prevent this. 

Both cues do not speed up the scan, they only reorder the task in a user unexpected manner and may lock the main Mixxx thread. 

Idea: 
* Dispose the QThreadPool and run everything form the Library Scanner Tasks
* All as a direct call
* Less memory allocation
* Less connect/disconnect 
* No thread switching 


Threading: 
* We may reintroduce threading for long lasting tasks. 
 * Reading directory hash
 * Reading file metadata 
 * Sqlite access.

However we need to make sure that the fast task are waiting for the slow once to not stack up so much work as we do right now.

**Comment by daschuer** [comment]
delete pTask before return is the simplest solution. OK for me. 
If you want to avoid new and delete you may move a std::unique_ptr around.

**Comment by daschuer** [comment]
In addition you should call `m_pool.clear()` when the scanner is canceled. This should speed up the `wait()` at the very end.

**Comment by ronso0** [comment]
> delete pTask before return is the simplest solution. OK for me.
If you want to avoid new and delete you may move a std::unique_ptr around.

I went with `delete` as I didn't manage to get it workign with neither `std::unique_ptr` nor `std::shared_ptr`.

File: src/library/scanner/libraryscanner.cpp [hunk 3]
```diff
@@ -496,6 +497,7 @@ void LibraryScanner::queueTask(ScannerTask* pTask) {
     //kLogger.debug() << "queueTask" << pTask;
     ScopedTimer timer(u"LibraryScanner::queueTask");
     if (m_scannerGlobal.isNull() || m_scannerGlobal->shouldCancel()) {
+        delete pTask;
```
Comment (daschuer) [inline src/library/scanner/libraryscanner.cpp:500]: This implies the disconnecting pending tasks by removing and deleting them:
```suggestion
        delete pTask;
        m_pool.clear();
```

**Review by daschuer — CHANGES_REQUESTED** [review]
This should help as well.

**Comment by ronso0** [comment]
> However the user expectation (my expectation) is that they can cancel the scan and have all info since then saved.

Isn't that true already?
If I add a ~3k tracks directory and cancel the scan after a few seconds, Tracks is updated with new tracks.

File: src/library/scanner/libraryscanner.cpp (hunk 3 above)
Comment (ronso0) [reply src/library/scanner/libraryscanner.cpp:500]: thanks, I adopted it

**Comment by daschuer** [comment]
> Isn't that true already?

It depends on the perspective. We keep already saved tracks in the library. But we discard all stacked up signals.

**Review by daschuer — APPROVED** [review]
This is good enough for a stable branch fix. Thank you for taking care.

**Comment by ronso0** [comment]
> But we discard all stacked up signals.

Yep, because there are only "track exists" (rescan) or "add this track" (new track or new directory).
The 1st is not that relevant IMO, the 2nd causes track imports to continue -- which is what we want to prevent, right?

**Comment by daschuer** [comment]
Correct. The room for improvement is to not stack up the work in the first place.
