### PR TITLE
(fix)/controllers: use `playposition` instead of non-existant `visual_playposition`, add comments

### LINKED ISSUE #14603: CO visual_playposition used in mappings, but does not exist in C++ code
### Bug Description

https://mixxx.discourse.group/t/translating-old-controller-mapping-to-new-mixxx-version/31590
Used in 4 official mappings:
https://github.com/search?q=repo%3Amixxxdj%2Fmixxx%20visual_playposition&type=code

### Version

2.5.0

### OS

_No response_

### PR DESCRIPTION
**Pull request by ronso0**
Fixes #14603 

The affected scripts have formatting issues but I only tried to fix surrounding code.
I this looks good, I suggest to merge it even though eslint will not be happy.

@JoergAtGithub

### CODE REVIEW

**Comment by JoergAtGithub** [comment]
Is `playposition` the same, as `visual_playposition` was at the time, when these mappings were debugged? Is this just a CO renaming where we forgot to add an alias to the old name, or something functional different?

**Comment by ronso0** [comment]
TL;DR
yes, they did hold them same value, just the update rate differs
____
At least two of these mappings have been added 13 years ago.
Back then (commit 90421f2), there was also a  `visual_playposition` control in EngineBuffer. It was identical to `playposition` but it was updated more often:
* `playposition` update is **fixed**, 15 times per second, ie. every 66,66 ms
* `visual_playposition` is updated on every engine call, depends on lateny/buffer length, 1-96 ms

And at some point the `visual_playposition` has been removed and became a data member of new `VisualPlayPosition`.

File: res/controllers/EKS-Otus.js [hunk 1]
```diff
@@ -729,9 +729,13 @@ EksOtus.activateSpinningPlatterLEDs = function() {
 EksOtus.enableSpinningPlatterLEDs = function() {
     if (EksOtus.activeSpinningPlatterGroup==undefined)
         return;
+    // TODO: This control is updated on each audio callback which is
+    // way more often than what's necessary to update LEDs. It would
+    // make more sense (and save CPU) to hook up to [App],indicator_250ms
+    // instead and read the playposition on each callback.
```
Comment (ronso0) [inline res/controllers/EKS-Otus.js:735]: Maybe we can drop that comment.
Currently, `playposition` is updated 15 times persecond, ie. every 0.0666 ms

Comment (JoergAtGithub) [reply res/controllers/EKS-Otus.js:735]: If I look at this video: https://youtu.be/LO7nWuw8PuQ?t=20
the update rate must be even higher here. For 33rpm and 64 LEDs per round we've a time difference of 28ms between two position LEDs.

Comment (ronso0) [reply res/controllers/EKS-Otus.js:735]: Okay, true. So [`kPlaypositionUpdateRate`](https://github.com/mixxxdj/mixxx/blob/476123ba5290e2c359fa313a1efa36204d36ea9d/src/engine/enginebuffer.cpp#L51) had to be increased, or a CO being added to customize the update rate as required.

FWIW we also have this comment in the script
https://github.com/mixxxdj/mixxx/blob/81b9e38f8a0e4756721a8838a2d12a10aa9b208a/res/controllers/EKS-Otus.js#L764-L766

I'll remove the comments.

Comment (ronso0) [reply res/controllers/EKS-Otus.js:735]: Nice, but doesn't matter here since we currently don't have a high-res position control anyway.

Please remember this is only about making this script work again. We can also remove the playpos connection altogether and add a TODO (+ log a warning) to the script and to the manual. I don't care.

Comment (JoergAtGithub) [reply res/controllers/EKS-Otus.js:735]: Yes, please just remove these unrelated ToDos und reduce this PR to the bugfixes itself.

**Review by JoergAtGithub — APPROVED** [review]
LGTM! Thank you!
