### PR TITLE
(fix) Search: add proper DateAddedFilter

### LINKED ISSUE #14873: Ocassionally old tracks show up in Analyze view
### Bug Description

I opened the analyze view today to process some music and there is an old track in it:

A track showing that it was added on 1/27/2025

"New" is selected at the top, not "All" and everything else in the view is the same stuff that was in here when I imported it a few days ago. This track had been analyzed and played before, but I was just playing it and adding some loops before switching over to analyze view, I'm not sure why it would remain in the view or what information would be useful in finding this.

### Version

2.5.1

### OS

Arch Linux

### PR DESCRIPTION
**Pull request by ronso0**
This is currently just a text filter, so basically unusable IMO because
a) expcets `-` delimiter and ISO 8601 (fragments)
b) only search for explicit days/months/years, for example
`added:2025-09-22` -> day
`added:25-09` -> month
`added:12-12` -> 2012-12 or [any year]-12-12

I sometimes want so find tracks before/after a certain date, so here we go..
____
### `DateAddedFilterNode`
New version expects date strings like shown in the library, eg. 25.10.25
(2-digits years are made 2000-based)

It supports single operator queries with =, <, >, <=, >=
`added:<03.12.24` = before december 3rd 2024

### TODO
- [x] use user locale -> the `Date added` column uses the system locale, nothing to do
- [x] read user time zone, convert to UTC
- [x] test date locales other than `de`

### Postponed
* use in **Analyze** and use `OrNode` for extraFilter in `SearchQueryParser::parseQuery()` to fix #14873 and make #15571 obsolete
-> addressed in #15597 
* restore 'month' search, ie. turn `added:12.24` into `added:01.12.24-31.12.24`
Not sure how this works / is expected to work with short formats like `mm-dd-yy`. Requires parsing the format strig to find the month position
* range queries like `added:01.01.22-23.04.24`
Probably not feasible as the localized short format may be `mm-dd-yy`.
We may use `--` as delimiter, but that wouldn't be consistent with other range queries (BPM, rating)

### CODE REVIEW

**Comment by ronso0** [comment]
This is the first step towards fixing the bug hacked around by ~~#15571~~ #15597

**Comment by ronso0** [comment]
> - [ ] restore 'month' search, ie. turn `added:12.24` into `added:01.12.24-31.12.24`

This one is a bit tricky, like it's possible but cumbersome to parse the current `QLocale::shortFormat` (used in the library to display the date).
I'll implement it sooner or later, but IMO this first batch of improvements is mergable without it already.

File: src/library/searchquery.cpp [hunk 1]
```diff
@@ -809,3 +810,109 @@ QString YearFilterNode::toSql() const {
...
+// TODO Convert to DateFilterNode and allow searching for "last_played"
+DateAddedFilterNode::DateAddedFilterNode(const QString& argument)
+        : m_operatorQuery(false),
+          m_operator("="),
+          m_opDate(QDateTime()),
+          m_rangeQuery(false),
+          m_dateStart(QDateTime()),
+          m_dateEnd(QDateTime()) {
+    QRegularExpressionMatch opMatch = kNumericOperatorRegex.match(argument);
+    QStringList rangeArgs = argument.split("-");
```
Comment (daschuer) [inline src/library/searchquery.cpp]: How does this deal with - in date formats? 
2025-11-02-12-01

Comment (daschuer) [reply src/library/searchquery.cpp]: At one point we have moved form 2025-11-08 to 11/08/25 for en_US, which makes sense for US citizen but not for other people who better use en_US than their own incomplete version native language. en_UK has 08/11/2025 btw. The history feature uses 2025-11-08 for all. 
German has 08.11.25 in the library, which is wrong according to: https://www.din-5008-richtlinien.de/startseite/datum/ it should be 08.11.2025.
A library option to bring iso 2025-11-08 back would be nice.

Comment (ronso0) [reply src/library/searchquery.cpp]: > How does this deal with - in date formats? 2025-11-02-12-01

it doesn't : \
I'll remove the range parser, then we can still use two queries to get a range `added:>12.01.24 added:<08.04.25`
My impression is that not many are using this at all, otherwise we'd have more bug reports.

Comment (ronso0) [reply src/library/searchquery.cpp]: For me, all dates are localized correctly (system date locale):
image

> German has 08.11.25 in the library, which is wrong according to: https://www.din-5008-richtlinien.de/startseite/datum/ it should be 08.11.2025

Yes, because we use the QLocale::shortFormat which is mostly two digits for each, dd.MM.yy or mm/dd/yy or d/m/yy

**Comment by ronso0** [comment]
So let me try to summarize what I think would be a good first set of fixes:
* use the date format users see in the library (localized, short format)
* support operators < <= > >= (`added:` equals `added:=`)

I think that would make it predictable.

> A library option to bring iso 2025-11-08 back would be nice.

Why do you think that would be helpful? It's inconsistent with the display.
I think we can make the parser detect both the short dd-MM-yy format as well as ISO with leading yyyy.

**Comment by ronso0** [comment]
> So let me try to summarize what I think would be a good first set of fixes:
> * use the date format users see in the library (localized, short format)
> * support operators < <= > >= (added: equals added:=)

That would also allow to fix #15586
I'll try to finish it soon so we can squeeze it in 2.5.4

**Comment by ronso0** [comment]
> * use the date format users see in the library (localized, short format)
> * support operators < <= > >= (added: equals added:=)

Done.

#15597 makes use of it for the Analyze view and reworks `BaseTrackCache::filterAndSort()` in order to fix #14873

**Comment by daschuer** [comment]
>>  A library option to bring iso 2025-11-08 back would be nice.

> Why do you think that would be helpful? It's inconsistent with the display.

I mean for all occurrences. It is helpful for users in who likes to use the en-US (untranslated) version, but can't read 22/23/25 as I do. Currently we use the ISO format for History.

File: src/library/searchquery.cpp [hunk 2]
```diff
@@ -809,3 +810,111 @@ QString YearFilterNode::toSql() const {
...
     return QString();
 }
+
+// TODO Convert to DateFilterNode and allow searching for "last_played"
+DateAddedFilterNode::DateAddedFilterNode(const QString& argument)
+        : m_operatorQuery(false),
+          m_operator("="),
+          m_opDate(QDateTime()) {
+    qWarning() << "     .";
+    qWarning() << "     DateAdded:" << argument;
```
Comment (daschuer) [inline src/library/searchquery.cpp]: debug leftover?

**Comment by daschuer** [comment]
Some issues 
added:<26.10.25  reveals also 25.10.25er Tracks. 

The search does not follow the library language settings. It is always using the system date and time setting. 
I think it is better to uses the same format as in the library.

**Review by daschuer — CHANGES_REQUESTED** [review]
Thank you. Not implementing a range, with "-",  looks good.

**Comment by ronso0** [comment]
I'm still unsure what you mean.
In my case my system locale for date (LC_TIME) is `de_DE.utf8`.
I'm using the untranslated version as well and **all dates** I see are in de shortfromat dd.MM.yy
This is a shot from a History playlist:
image
And this is the formatting for the library view:
https://github.com/mixxxdj/mixxx/blob/9d19b24072eac9c964d3dde2809412f64f523e1f/src/library/basetracktablemodel.cpp#L623-L669

What is your LC_TIME locale and what format do you see in the library?

### But
I missed that we indeed set the locale for the app (not just the translations) when one is set in the preferences.
Else the system (date) locale is used.
Fixed. For example with Uzbek locale:
image



Btw we're using the ISO format yyyy-mm-ddTHH:mm:ss.zzz only in the db.

**Comment by ronso0** [comment]
All roger and ready to roll now IMO, please test

**Comment by daschuer** [comment]
> In my case my system locale for date (LC_TIME) is de_DE.utf8.

This is mine as well. As soon I change the language settings in Mixxx to en_US, the date and all so time format changes also to the  (hard to read for me) en_US
format. The search box however still expects the short de_DE format. This is maximum confusing of you are in the UK for instance where day and month are swapped in the very same 10/11/12 notation. 

The "issue" (no bug IMHO). because I actually like the DIN recommendation to use the ISO format everywhere, is that the history playlist names are using the iso format.

**Comment by ronso0** [comment]
> is that the history playlist names are using the iso format.

I see. And Iso makes sense for those (it's just the initial name btw) because that's they're sorted by `id` (which is kind of the same as `date_created`) so you can easily spot a playlist from let's say 2023-09.

**Comment by ronso0** [comment]
> > In my case my system locale for date (LC_TIME) is de_DE.utf8.
> 
> This is mine as well. As soon I change the language settings in Mixxx to en_US, the date and all so time format changes also to the (hard to read for me) en_US format. The search box however still expects the short de_DE format. This is maximum confusing of you are in the UK for instance where day and month are swapped in the very same 10/11/12 notation.

To clarify, this are my relevant locale settings:
LANG=de_DE.UTF-8
LANGUAGE=de_DE:en
LC_CTYPE=en_GB.UTF-8
LC_TIME=de_DE.utf8

So with "system" in Mixxx it detects "C" and I get `en_US` for the translations and the date is `de_DE`.
If I select any other locale in Mixxx and restart, the translations **and date format** are adjusted accordingly. The searchbox is consistent with the library.

So, I don't understand why the search would expect de_DE in your case.
Did you try the current state with the fix for that?

**Comment by ronso0** [comment]
> because I actually like the DIN recommendation to use the ISO format everywhere

I'd say this is indeed a personal preference. IMO it makes sense to show dates in local format. For example if you sort tracks by date_added or last_played, users know intuitively at which part of the aa/bb/cc date they need to look to spot a certain range. Like with de_DE I can shrink the date_added column so I see dd.mm... and it's easy to spot tracks from October for example.

If you think a global date format switch makes sense, that's a feature and would go to 2.6 or main anyway.

**Comment by daschuer** [comment]
I confirm this is fixed now: 

> If I select any other locale in Mixxx and restart, the translations and date format are adjusted accordingly. The searchbox is consistent with the library.

I have 
LANG=de_DE.UTF-8
LANGUAGE=
LC_CTYPE=
LC_TIME= 

which is of my knowledge still on default for Ubuntu Jammy.  

System 

added:>=26.10.25

works. 

> I'd say this is indeed a personal preference.

Yes of cause. Can you confirm that there is a use case for "international" with en_US translation ans ISO date and time format? 
Than I will file a bug for it.

Issue: 

added:<26/10/2025

(en_UK)

reveals also 26/10/2025 tracks 

added:>=26/10/2025

does nor reveal 26/10/2025

**Comment by ronso0** [comment]
> Issue:
>
> added:<26/10/2025
(en_UK)
reveals also 26/10/2025 tracks
>
>added:>=26/10/2025
does nor reveal 26/10/2025

I improved the debug output, please post what's logged for that query.

**edit** can ot confirm, works fine here, no matter which locale

**Comment by daschuer** [comment]
It works here. I have probably whatched the wrong column, sorry.

**Comment by ronso0** [comment]
Alright, thanks for verifying.
I reverted the trace commit and this is now ready for merge.

I'll open a manual PR soonish.

**Comment by daschuer** [comment]
There is still an issue with 
added:02.10.25 and added:=02.10.25

```
warning [Main]      .
warning [Main]      DateAdded: "02.10.25"
warning [Main]      .
warning [Main]      .
warning [Main]      DateAdded toSql: ! invalid, return true
warning [Main]    
```

And added:>=02.10.25 AND added:<03.10.25

```
warning [Main]      .
warning [Main]      DateAdded: ">=02.10.25"
warning [Main]        opMatch:  ">="
warning [Main]        arg:      "02.10.25"
warning [Main]        parseDate: app locale: QLocale(German, Latin, Germany) "dd.MM.yy"
warning [Main]                system locale: QLocale(German, Latin, Germany) "dd.MM.yy"
warning [Main]        date auto: QDate("1925-10-02")
warning [Main]        date adj.: QDate("2025-10-02")
warning [Main]      date valid, to string: "2025-10-01T22:00:00.000"
warning [Main]      -> opQuery
warning [Main]      .
warning [Main]      .
warning [Main]      DateAdded: "<03.10.25"
warning [Main]        opMatch:  "<"
warning [Main]        arg:      "03.10.25"
warning [Main]        parseDate: app locale: QLocale(German, Latin, Germany) "dd.MM.yy"
warning [Main]                system locale: QLocale(German, Latin, Germany) "dd.MM.yy"
warning [Main]        date auto: QDate("1925-10-03")
warning [Main]        date adj.: QDate("2025-10-03")
warning [Main]      date valid, to string: "2025-10-02T22:00:00.000"
warning [Main]      -> opQuery
warning [Main]      .
warning [Main]      .
warning [Main]      DateAdded toSql: op: "datetime_added >= '2025-10-01T22:00:00.000'"
warning [Main]      .
warning [Main]      .
warning [Main]      DateAdded toSql: op: "datetime_added < '2025-10-02T22:00:00.000'"
warning [Main]      .
```
Why 22:00:00?

**Comment by ronso0** [comment]
> Why 22:00:00?

Because timestamps are in UTC and you're currently in CET (Berlin, UTC+1) + 1h daylight saving time.
So UTC = local - 2h.
That's the same conversion like for the library if I'm not mistaking.

Will look into the other issue (sadly I already removed the trace commit..)

**Comment by ronso0** [comment]
Got it!
Now works also with `=` and pure `:` (implicit `=`).
Though I didn't polish, maybe you have ideas to optimize it?

File: src/library/searchquery.cpp [hunk 3]
```diff
@@ -809,3 +810,149 @@ QString YearFilterNode::toSql() const {
...
     return QString();
 }
+
+// TODO Convert to DateFilterNode and allow searching for "last_played"
+DateAddedFilterNode::DateAddedFilterNode(const QString& argument)
+        : m_operatorQuery(false),
+          m_operator("="),
+          m_opDate(QDateTime()),
+          m_dateStart(QDateTime()),
+          m_dateEnd(QDateTime()) {
```
Comment (daschuer) [inline src/library/searchquery.cpp]: This is redundant. 

```suggestion
          m_operator("=") {
```

File: src/library/searchquery.cpp [hunk 4]
```diff
@@ -809,3 +810,149 @@ QString YearFilterNode::toSql() const {
...
+        return;
+    }
+
+    if (m_operator == '=') {
+        // Note: due to literal = time comparison in Sql we need to set up
+        // a range from [date]T00:00:00.000 to [date]T23:59:59.999 and then
+        // convert start/end to UTC.
+        m_equalsQuery = true;
+        m_dateStart = QDateTime(date, QTime(0, 0)).toUTC();
+        m_dateEnd = QDateTime(date, QTime(23, 59, 59, 999)).toUTC();
```
Comment (daschuer) [inline src/library/searchquery.cpp]: I think this needs to be a full day. 

The query should become 

"datetime_added >= '%1' AND datetime_added < '%2'"



datetime_added >= 2025-11-17T00:00:00Z000   AND datetime_added < 2025-11-18T00:00:00Z0000

File: src/library/searchquery.cpp [hunk 5]
```diff
@@ -809,3 +810,149 @@ QString YearFilterNode::toSql() const {
...
+        qWarning() << "                           end:" << dateStringIsoNoZ(m_dateEnd);
+        return;
+    }
+
+    m_operatorQuery = true;
+    if (m_operator == '>') {
+        qWarning() << "       op == > -> add 1 day";
+        // "added:>25.10.2025" would include any time until 25.10.2025T23:59:59Z999
+        // Add one day to make it truly > 25.10.2025
+        date = date.addDays(1);
```
Comment (daschuer) [inline src/library/searchquery.cpp]:
```suggestion
        // "added:>25.10.2025" would include any time from 2025-10-25T00:00:00Z001
        // Add one day for >= 25.10.2026T00:00:00Z000 to exclude the whole day
        date = date.addDays(1);
        m_operator = '>='
```

**Review by daschuer — CHANGES_REQUESTED** [review]
I think (not tested) one ms slips trough. See suggestions.

**Comment by ronso0** [comment]
Thanks!
I think all cases are now covered correctly.

**Comment by ronso0** [comment]
@daschuer this is ready.
Let me know when I can remove the trace commit.

**Review by daschuer — APPROVED** [review]
LGTM, thank you.

**Comment by ronso0** [comment]
Cool, thanks for testing!

> Let me know when I can remove the trace commit.

Done.
