### PR TITLE
STEM: Allow pre-mastered stream not to match stem streams properties

### LINKED ISSUE #14572: Stems: ATM Mixxx displays failute if original pre-mixed stereo track has other samplerate/bitdepth thenstemstreams
### Bug Description

ATM there is a check executed in soundsourcestem (enginebuffer->cachingreader->cachingreaderworker->soundsourceproxy) when loading a stem to a deck.

When the samplerate is not equal in all streams, a loadfailure is displayed.
IMO this is not correct: the original pre-mixed stereo track can have other specs then the stemstreams.

As the htdemucs is trained for 16b 44.1 it will creates output streams with these specs, even if the original has a higher/lower bitdepth/samplerate. 

The check should be: do the stemstreams have equal specs undependant from the pre-mixed stereo (original) stream. (In order to replace the original file with the stem-file, else 2 times the original take storagespace)

If not an on-deùand-realtime conversion from a track to a stem will have to convert the original track to 16b/44.1 as well (for lossless).

### Version

_No response_

### OS

_No response_

### PR DESCRIPTION
**Pull request by acolombier**
This fixes #14572

Also spotted a bug leading the waveform to react to STEM CO even loaded as pre-mixed, fixed as 0c32d1cd223b4be5a8c1731b3984febdeaa6fbbf

### CODE REVIEW

**Comment by JoergAtGithub** [comment]
I don't understand the explanation why we don't load the pre-mixed track. This 5th track is the track mastered by the sound engineer in the studio. This is the one that don't need DSP (limiter, equalizer, compressor), because the mastering is already done.
The DSP code is needed if we mix the 4 stem tracks together, to achieve 'nearly' the same output as the manually mastered 5th track.

**Comment by acolombier** [comment]
> This 5th track is the track mastered by the sound engineer in the studio. This is the one that don't need DSP (limiter, equalizer, compressor), because the mastering is already done.

That's actually the first one, but otherwise, yes that correct

> I don't understand the explanation why we don't load the pre-mixed track
> The DSP code is needed if we mix the 4 stem tracks together, to achieve 'nearly' the same output as the manually mastered 5th track.

Please see #13268 for context reminder on why we did this.
TLDR is:
```
Since it is impossible to load that track without invalidating the replaygain 
due to the missing DSP support, all the four stem are currently mixed upstream. 
In the future, the pre-mastered track will be used.
```

Edit: amended the commit to add this reference (and fix some typos)

File: src/sources/soundsourcestem.cpp [hunk 1]
```diff
@@ -372,26 +373,45 @@ SoundSource::OpenResult SoundSourceSTEM::tryOpen(
...
-            // The main mix is only used to detect the stream parameters
+        if (!foundPremixedStream) {
+            // When using demuxing solutions, while the NI spec suggest that the
+            // main stream should match other stem stream s in properties, the
+            // main stream never get mixed with the stem streams, so we allow
+            // mismatch, and enable user to store their original file without
+            // degradation inside the STEM MP4 container (see #13268 for more context)
+            // NOTE: we can currently allow this as we NEVER LOAD the pre-mixed
+            // track, due to missing DSP support, and instead mixes all stems on
+            // the fly
```
Comment (JoergAtGithub) [inline src/sources/soundsourcestem.cpp]:
```suggestion
            // We can currently allow this, as we NEVER LOAD the pre-mastered
            // track, as we do not have analyzer data for it.
            // This is because we only support one set of metadata for the whole STEM file,
            // where we determine the track parameters from an on-the-fly mix of all 4 stems.
            // Especially the replaygain differs between the on-the-fly mix and the pre-mastered track,
            // because we do not apply DSP (limiter, equalizer, compressor) to the on-the-fly mix.
```

**Comment by acolombier** [comment]
Thanks for the review @JoergAtGithub - I amended the commit directly since this was the only comment!

**Review by JoergAtGithub — APPROVED** [review]
LGTM! Thank you!
