### PR TITLE
fix Reloop Beatmix controller overriding persisted fx routing

### LINKED ISSUE #14917: FX routing only partially remembered
### Bug Description

#10232

FX routing for decks 3/4 is remembered after restart, but the FX routing for decks 1/2 is forgotten

### Version

_No response_

### OS

_No response_

### PR DESCRIPTION
**Pull request by mxmilkiib**
the Reloop Beatmix 2/4 controller script was explicitly setting fx routing to disabled on init, overriding the persisted settings from usersettings.

fx routing for decks 3/4 appeared to work because those channels were registered later, after the controller script ran. decks 1/2 were registered first and then immediately overridden by the controller script.

removed the engine.setValue calls that forced fx routing to 0, keeping only the trigger calls needed to sync controller leds with the actual (now persisted) state.

fixes #14917

### CODE REVIEW

File: res/controllers/Reloop-Beatmix-2-4-scripts.js [hunk 1]
```diff
@@ -172,10 +172,7 @@ ReloopBeatmix24.connectControls = function() {
             ReloopBeatmix24.loopDefined);
         engine.trigger(group, "loop_end_position");
         engine.softTakeover(group, "rate", true);
-        engine.setValue("[EffectRack1_EffectUnit1]",
-            "group_" + group + "_enable", 0);
-        engine.setValue("[EffectRack1_EffectUnit2]",
-            "group_" + group + "_enable", 0);
+        // Don't override FX routing - respect persisted settings
```
Comment (ronso0) [inline res/controllers/Reloop-Beatmix-2-4-scripts.js]: What about
```suggestion
        // Update Fx controls from the state that is restored from fx config
```

and I don't think we need the other comment below

Comment (ronso0) [reply res/controllers/Reloop-Beatmix-2-4-scripts.js]: LGTM otherwise

**Review by Swiftb0y — APPROVED** [review]
LGTM, you wouldn't even have to add comments IMO, but the current state is fine

**Comment by Swiftb0y** [comment]
You may want to rebase on 2.5 or 2.6 to get this released sooner

**Comment by mxmilkiib** [comment]
rebased onto 2.5 for earlier release, updated comment wording and removed unnecessary second comment per @ronso0's suggestion

**Review by Swiftb0y — APPROVED** [review]
LGTM. Thank you.
