### PR TITLE
Fix writing metadata via symlink 

### LINKED ISSUE #13707: Mixxx destroys symlinks when writing metadata.
### Bug Description

A smylinked track can be loaded with Mixxx. When metadata is written, the symlink is replaced by the actual track. 

### Version

2.4.1

### OS

Ubuntu Focal

### PR DESCRIPTION
**Pull request by daschuer**
and add a test that verified the issue and the fix.

This fixes #13707 

Note: Mixxx does not support following Windows Shortcuts (*.lnk).

### CODE REVIEW

File: src/test/taglibtest.cpp [hunk 1]
```diff
@@ -70,3 +70,61 @@ TEST_F(TagLibTest, WriteID3v2Tag) {
...
+
+    const QString linkFileName = tempDir.filePath("no_id3v1_mp3_link");
+    EXPECT_TRUE(QFile::link(tmpFileName, linkFileName));
+
+    auto linkFileInfoBefore = QFileInfo(linkFileName);
+    EXPECT_TRUE(linkFileInfoBefore.exists());
+    EXPECT_TRUE(linkFileInfoBefore.isSymLink());
+    EXPECT_EQ(linkFileInfoBefore.canonicalFilePath().toStdString(), tmpFileName.toStdString());
+
+    // Verify that the file has no tags
```
Comment (cr7pt0gr4ph7) [inline src/test/taglibtest.cpp:95]: Suggestion: `// Verify that the file (accessed via the symlink) has no tags`

File: src/test/taglibtest.cpp [hunk 2]
```diff
@@ -70,3 +70,61 @@ TEST_F(TagLibTest, WriteID3v2Tag) {
...
+        TagLib::MPEG::File mpegFile(
+                TAGLIB_FILENAME_FROM_QSTRING(linkFileName));
+        EXPECT_FALSE(mixxx::taglib::hasID3v1Tag(mpegFile));
+        EXPECT_FALSE(mixxx::taglib::hasID3v2Tag(mpegFile));
+        EXPECT_FALSE(mixxx::taglib::hasAPETag(mpegFile));
+    }
+
+    qDebug() << "Setting track title";
+
+    // Write metadata -> only an ID3v2 tag should be added
```
Comment (cr7pt0gr4ph7) [inline src/test/taglibtest.cpp:106]: Suggestion: `// Write metadata (via the symlink) -> ...`

File: src/test/taglibtest.cpp [hunk 3]
```diff
@@ -70,3 +70,61 @@ TEST_F(TagLibTest, WriteID3v2Tag) {
...
+
+    // Generate a file name for the temporary file
+    const QString tmpFileName = tempDir.filePath("no_id3v1_mp3");
+
+    // Create the temporary file by copying an existing file
+    mixxxtest::copyFile(
+            MixxxTest::getOrInitTestDir().filePath(QStringLiteral("id3-test-data/empty.mp3")),
+            tmpFileName);
+
+    const QString linkFileName = tempDir.filePath("no_id3v1_mp3_link");
```
Comment (cr7pt0gr4ph7) [inline src/test/taglibtest.cpp:87]: Suggestion: `// Access the MP3 file indirectly via a symlink when reading & writing the tags`

File: src/test/taglibtest.cpp [hunk 4]
```diff
@@ -70,3 +70,61 @@ TEST_F(TagLibTest, WriteID3v2Tag) {
...
+    // Check that the file only has an ID3v2 tag after writing metadata
+    {
+        TagLib::MPEG::File mpegFile(
+                TAGLIB_FILENAME_FROM_QSTRING(linkFileName));
+        EXPECT_FALSE(mixxx::taglib::hasID3v1Tag(mpegFile));
+        EXPECT_TRUE(mixxx::taglib::hasID3v2Tag(mpegFile));
+        EXPECT_FALSE(mixxx::taglib::hasAPETag(mpegFile));
+    }
+
+    auto linkFileInfoAfter = QFileInfo(linkFileName);
```
Comment (cr7pt0gr4ph7) [inline src/test/taglibtest.cpp:125]: Suggestion: `// Verify that the symlink still exists and still points to the correct file`

File: src/test/taglibtest.cpp [hunk 5]
```diff
@@ -70,3 +70,61 @@ TEST_F(TagLibTest, WriteID3v2Tag) {
...
+
+    EXPECT_TRUE(linkFileInfoAfter.exists());
+    EXPECT_EQ(linkFileInfoAfter.canonicalFilePath().toStdString(), tmpFileName.toStdString());
```
Comment (cr7pt0gr4ph7) [inline src/test/taglibtest.cpp:128]: Shouldn't we also verify for completeness sake that `linkFileName` is, in fact, still a symlink, and has not been overwritten?
```cpp
EXPECT_TRUE(linkFileInfoAfter.isSymLink());
```

**Review by cr7pt0gr4ph7 — APPROVED** [review]
A few small nitpicks, otherwise LGTM.

**Review by cr7pt0gr4ph7 — APPROVED** [review]

**Review by acolombier — APPROVED** [review]
Code LGTM - didn't test but change looked small enough so merging.

Thanks!

**Comment by doodlebro** [comment]
I think there's an incorrect assumption being made in this solution with respect to how many symlinks are followed consecutively, which led to me laughing heartily in ZFS snapshots and turning off metadata sync in Mixxx to fix temporarily.

You can symlink to a symlink. I do this for some mixes which have re-used tracks from old ones. This Mixxx logic handling metadata sync back to symlinks stops after one level on 2.6 beta 6. In my case (Mac accessing files via SMB) this turned my multilevel symlinks into copies of files when metadata was written. Not great, definitely a footgun. When this happens, other file metadata (extended attributes) attached to the original file that the symlink pointed are also lost.

**Comment by ronso0** [comment]
[According to the documenation, `QFileInfo::canonicalPath()`](https://doc.qt.io/qt-6/qfileinfo.html#canonicalPath) should already resolve all levels of symlinks in a given file path.

(compared to [`QFileInfo::filesystemSymLinkTarget()`](https://doc.qt.io/qt-6/qfileinfo.html#filesystemSymLinkTarget) which only resolves the next link level.)

Could this be an issue with your SMB permissions / configuration?
CC @daschuer
