### PR TITLE
fix(stem): improve waveform channel visibility

### LINKED ISSUE #14870: STEMS waveforms: increase opacity of switched off channels
### Feature Description

I'm loving the new STEMs feature in 2.6.

One thing that might improve it is better visibility of the channels that are not playing in the waveform.

Currently when you switch a channel off the element of the waveform that represents that channel is significantly dimmed/grey scaled in the waveform, to the extent that it is very hard to see, especially if obscured by the remaining elements of the wave form.

It might be useful if this could be made more visible (ie not dimmed as much, but still dimmed?) to assist with timing of when you might want to switch given channels back on again. 

Would it be possible to make that a user selectable amount of dimming?

I just noticed that the same dim outline is present if you reduce the volume of the channel, with the 'actual' volume of the channel showing in normal brightness, which again makes me feel that it would be best if this could be user 
selectable.

Hopefully I have explained myself properly, but please feel free to comment if you need further explanation.

### PR DESCRIPTION
**Pull request by acolombier**
This improves customisation of the stem waveform visibility. This feature will allow opacity customisation, as well as bringing the last adjusted stem on foreground for better visibility 

This should fix #14870

### CODE REVIEW

File: src/waveform/renderers/allshader/waveformrendererstem.h [hunk 1]
```diff
@@ -1,13 +1,16 @@
 #pragma once
 
+#include <qstack.h>
```
Comment (Swiftb0y) [inline src/waveform/renderers/allshader/waveformrendererstem.h]:
```suggestion
#include <QStack>
```

File: src/waveform/renderers/allshader/waveformrendererstem.h [hunk 2]
```diff
@@ -37,13 +40,31 @@ class allshader::WaveformRendererStem final
     void setSplitStemTracks(bool splitStemTracks) {
         m_splitStemTracks = splitStemTracks;
     }
+    void setReorderOnChange(bool value) {
+        m_reorderOnChange = value;
+        std::iota(m_stackOrder.begin(), m_stackOrder.end(), 0);
```
Comment (Swiftb0y) [inline src/waveform/renderers/allshader/waveformrendererstem.h:43]: this just resets the order, right?

File: src/waveform/renderers/allshader/waveformrendererstem.cpp [hunk 3]
```diff
@@ -152,15 +192,16 @@ bool WaveformRendererStem::preprocessInner() {
     const double maxSamplingRange = visualIncrementPerPixel / 2.0;
 
     for (int visualIdx = 0; visualIdx < stripLength; visualIdx++) {
-        for (int stemIdx = 0; stemIdx < mixxx::kMaxSupportedStems; stemIdx++) {
+        int stemLayer = 0;
+        for (int stemIdx : m_stackOrder) {
```
Comment (Swiftb0y) [inline src/waveform/renderers/allshader/waveformrendererstem.cpp]: clazy
```suggestion
        for (int stemIdx : std::as_const(m_stackOrder)) {
```

File: src/waveform/renderers/allshader/waveformrendererstem.h [hunk 4]
```diff
@@ -37,13 +40,31 @@ class allshader::WaveformRendererStem final
...
-    std::vector<std::unique_ptr<PollingControlProxy>> m_pStemGain;
-    std::vector<std::unique_ptr<PollingControlProxy>> m_pStemMute;
+    bool m_reorderOnChange;
+    float m_outlineOpacity;
+    float m_opacity;
+
+    std::vector<std::unique_ptr<ControlProxy>> m_pStemGain;
+    std::vector<std::unique_ptr<ControlProxy>> m_pStemMute;
+
+    QStack<int> m_stackOrder;
```
Comment (Swiftb0y) [inline src/waveform/renderers/allshader/waveformrendererstem.h]: QStack doesn't make sense, you're not using the Stack interface, instead you're just using it as a list...
Consider using a `QVarLengthArray<int, kMaxSupportedStems>` (since C++26 `inplace_vector` is still in the stars).

**Review by Swiftb0y — COMMENTED** [review]
couple nits, rest looks sensible

File: src/waveform/renderers/allshader/waveformrendererstem.h (hunk 2 above)
Comment (acolombier) [reply src/waveform/renderers/allshader/waveformrendererstem.h:43]: Yep, that's right, resting the collection to `[0, 1, 2, 3]`

Comment (Swiftb0y) [reply src/waveform/renderers/allshader/waveformrendererstem.h:43]: Thanks for clarifying. Its not clear why this is done in `setReorderOnChange` though.

**Comment by Swiftb0y** [comment]
Code looks very good, but since this involves UX, I'd live to get @ronso0's thoughts too.

File: src/waveform/renderers/allshader/waveformrendererstem.cpp [hunk 5]
```diff
@@ -46,12 +50,48 @@ bool WaveformRendererStem::init() {
...
                         QStringLiteral("mute")));
+        m_pStemMute.back()->connectValueChanged(this, [this, stemIdx](double) {
+            if (!m_reorderOnChange) {
+                return;
+            }
+            m_stackOrder.removeAll(stemIdx);
+            m_stackOrder.append(stemIdx);
+        });
     }
+
```
Comment (Swiftb0y) [inline src/waveform/renderers/allshader/waveformrendererstem.cpp]: I'm fairly certain you can deduplicate this by simply storing the lambda in an `auto` local variable and passing it twice to `connectValueChanged`.

File: src/waveform/waveformwidgetfactory.cpp [hunk 6]
```diff
@@ -427,6 +427,12 @@ bool WaveformWidgetFactory::setConfig(UserSettingsPointer config) {
     setUntilMarkTextHeightLimit(toUntilMarkTextHeightLimit(
             m_config->getValue(ConfigKey("[Waveform]", "UntilMarkTextHeightLimit"),
                     toUntilMarkTextHeightLimitIndex(m_untilMarkTextHeightLimit))));
+    setStemReorderOnChange(m_config->getValue(
+            ConfigKey("[Waveform]", "stem_reorder_on_change"), true));
+    setStemOpacity(static_cast<float>(
+            m_config->getValue(ConfigKey("[Waveform]", "stem_opacity"), 0.75)));
+    setStemOutlineOpacity(static_cast<float>(m_config->getValue(
+            ConfigKey("[Waveform]", "stem_outline_opacity"), 0.15)));
```
Comment (Swiftb0y) [inline src/waveform/waveformwidgetfactory.cpp:436]: NIT
```suggestion
    setStemOpacity(m_config->getValue<float>(ConfigKey("[Waveform]", "stem_opacity"), 0.75));
    setStemOutlineOpacity(m_config->getValue<float>(ConfigKey("[Waveform]", "stem_outline_opacity"), 0.15));

```

File: src/waveform/waveformwidgetfactory.cpp [hunk 7]
```diff
@@ -1362,6 +1368,33 @@ void WaveformWidgetFactory::setUntilMarkTextHeightLimit(float value) {
...
+    emit stemOutlineOpacityChanged(value);
+}
+
+void WaveformWidgetFactory::setStemOpacity(float value) {
+    m_stemOpacity = value;
+    if (m_config) {
+        m_config->setValue(ConfigKey("[Waveform]", "stem_opacity"),
+                static_cast<double>(value));
+    }
+    emit stemOpacityChanged(value);
```
Comment (Swiftb0y) [inline src/waveform/waveformwidgetfactory.cpp:1395]: NIT, no need to cast.
```suggestion
void WaveformWidgetFactory::setStemOutlineOpacity(float value) {
    m_stemOutlineOpacity = value;
    if (m_config) {
        m_config->setValue(ConfigKey("[Waveform]", "stem_outline_opacity"),
                value);
    }
    emit stemOutlineOpacityChanged(value);
}

void WaveformWidgetFactory::setStemOpacity(float value) {
    m_stemOpacity = value;
    if (m_config) {
        m_config->setValue(ConfigKey("[Waveform]", "stem_opacity"),
                value);
    }
    emit stemOpacityChanged(value);
```

**Review by Swiftb0y — COMMENTED** [review]
couple more nits

File: src/waveform/renderers/allshader/waveformrendererstem.h (hunk 2 above)
Comment (acolombier) [reply src/waveform/renderers/allshader/waveformrendererstem.h:43]: I've added a comment

File: src/waveform/renderers/allshader/waveformrendererstem.cpp [hunk 8]
```diff
@@ -46,12 +50,43 @@ bool WaveformRendererStem::init() {
...
+            m_stackOrder.append(stemIdx);
+        };
+        m_pStemGain.back()->connectValueChanged(this, bringToForeground);
+        m_pStemMute.back()->connectValueChanged(this, bringToForeground);
     }
+
+    m_stackOrder.resize(mixxx::kMaxSupportedStems);
+    std::iota(m_stackOrder.begin(), m_stackOrder.end(), 0);
+
+#ifndef __SCENEGRAPH__
```
Comment (Swiftb0y) [inline src/waveform/renderers/allshader/waveformrendererstem.cpp:72]: why is this disabled on scenegraph?

File: src/waveform/waveformwidgetfactory.cpp (hunk 7 above)
Comment (Swiftb0y) [reply src/waveform/waveformwidgetfactory.cpp:1395]: I'm sorry, this suggestion was BS... I've misread the code. Feel free to either revert or add the template specializations that make this work.

File: src/waveform/renderers/allshader/waveformrendererstem.cpp (hunk 8 above)
Comment (acolombier) [reply src/waveform/renderers/allshader/waveformrendererstem.cpp:72]: Because on Scenegraph/Mixxx 3.0, the `WaveformWidgetFactory` isn't used and should eventually go away. Instead we will solely rely on property binding. If you want to see how that will look like, you might want to look [here](https://github.com/mixxxdj/mixxx/pull/14887/files#diff-e8d76e827e5ecce82c5bf5f4682f86f80054c094b9ff8e9a216094af2ca169a4R718) (obliviously, that
case is slightly different as this is the one needed for setting preview, but you get the gist of it)

Comment (Swiftb0y) [reply src/waveform/renderers/allshader/waveformrendererstem.cpp:72]: right. I was confused because that means this feature has a short shelf-live.

**Review by Swiftb0y — APPROVED** [review]
LGTM. Thank you. /softfix

**Comment by acolombier** [comment]
Sadly, I broke softfix. I'm just looking at the action in @daschuer's repo - Daniel, would you be open with me capturing [this script](https://github.com/daschuer/softfix/blob/v4/entrypoint.sh) directly inside the action so it easier to manage? It would go inside a dedicated `.github/actions` folder so would still be nicely encapsulated.

(FYI, The [hardcoded use of GITHUB_TOKEN](https://github.com/daschuer/softfix/blob/52fa9b7ccdb4f7c227f2f2c012ac5c57c941039a/entrypoint.sh#L12) is the root cause of the problem)

**Comment by daschuer** [comment]
My idea is to keep it reusable for all our repositories. So the logical move would be cloning it into mixxxdj. 
I suggest to clone from upstream rather than from mine. Than I can make mine following mixxxdj.

**Comment by acolombier** [comment]
After consideration, I've decided to stick with the existing action. I think we might want to move it inside Mixxx org at some point later, but don't have time now.
I took the freedom to push ~[a oneliner](https://github.com/mixxxdj/mixxx/commit/e7281a4c1d64f378c528277d370da59f458dcf3c) to the CI to address this.~ [a fix for my breaking change merged yesterday](https://github.com/mixxxdj/mixxx/commit/d7d5934719d3465243a41866f9b489d61ebe154a)

**Comment by Swiftb0y** [comment]
still borked @acolombier ...

**Comment by acolombier** [comment]
I'm giving up. I consider this GH script too much of a hack and too hard to maintain. Happy to help moving this into the Mixxx repo, and migrate as an organisation action once it gets stabilised, in case you change your mind @daschuer

**Comment by acolombier** [comment]
Rebased manually now @Swiftb0y

**Comment by Swiftb0y** [comment]
Thanks.

**Review by JoergAtGithub — APPROVED** [review]
I just tested it, and it works as intended.
