### PR TITLE
qopenglwindow-based replacement of qglwidget, full glsl shader based waveforms, vumeters and spinnies

### LINKED ISSUE #8539: CSS not considered when there is a connection
Reported by: **[jmigual](https://github.com/jmigual)**
Date: 2016-05-04T08:28:19Z
Status: Confirmed
Importance: Low
Launchpad Issue: [lp1578111](https://bugs.launchpad.net/bugs/1578111)
Tags: skin

---

When a widget has a connection the CSS is ignored.

    Steps to reproduce:
    1. Create a widget with a connection
    2. Set to this widget  "qproperty-layoutSpacing: 2;"

The spacing is not shown but if you remove the connection the space is shown again. This can be seen in Deere skin in hotcue buttons.

Operating System: Ubuntu 16.04
CPU: Intel Xeon x5650 2.66GHz

This bug is related to: https://bugs.launchpad.net/mixxx/+bug/1285836

### LINKED ISSUE #11460: Waveforms dissapear after window resized
Hi, on my M2 mac the waveform is visible (in all themes that show it). But as I resize the window or make it full screen the waveform is replaced by a white background. The vertical grid lines and markers are visible. Resizing it smaller and the waveform re-appears.

image

This is for Mixxx 2.3.4 on MacOs Ventura 13.3.1, on a M2 Macbook Pro.

### PR DESCRIPTION
**Pull request by m0dB**
This PR addresses performance issues, particularly on macOS, by replacing the (deprecated) QGLWidget with a new class WGLWidget. When cmake option QOPENGL is ON (the default), WGLWidget is derived from QWidget and uses QOpenGLWindow for drawing. When cmake option QOPENGL is OFF, WGLWidget derives directly from QGLWidget, effectively leaving everything as before.

Additionally, this PR implements waveform, spinny and vu-meter rendering using GLSL shaders for drawing for better performance. The original implementations were combining QPainter-based drawing with openGL. Using QPainter with QOpenGLWindow as a paint device causes performance issues.

The original WSpinny and WVuMeter classes are still available as fall back for when GLSL is not available or in case we encounter issues. By default the new WSpinnyGLSL and WVuMeterGLSL are used.

All original waveform types are also still available, but the new (all-shader) type waveforms should perform better on all platforms.

Notes:
- The QOPENGL cmake option sets preprocessor define MIXXX_USE_QOPENGL, which is used to select the QOpenGLWIndow based code instead of the QGLWidget based code.
- When WGLWidget derives from QGLWidget, it adds some methods, this is merely to have a common API for both implementations
- I also tried an alternative approach: replacing QGLWidget with the newer QOpenGLWidget, but that required too many changes to get to work
- I have tried to address all the comments in the reviews have been addressed, with the notable exception of a requested API improvement of the shader and vertex code, but this can be done later and will mainly be aesthetics.

Known issues:
- alpha transparency of the beat lines in the legacy GL waveforms causes a graphical artifact and had to be forced to 1.0
- when changing the layout / resizing, the QOpenGLWindows are moved/resized ahead (?) of the rest of the widgets.

### CODE REVIEW

**Comment by JoergAtGithub** [comment]
I tried to build it on Windows, but I got:
```
CMake Error at buildenv/mixxx-deps-2.4-x64-windows-f9cdab3/scripts/buildsystems/vcpkg.cmake:613 (_add_library):
  Cannot find source file:
    src/widget/qopengl/wspinny.cpp

```

**Comment by m0dB** [comment]
Yes, I see the CI build also failed. I guess I didn't add the file. I'll have a look when I am back at my computer.

**Comment by m0dB** [comment]
Please try again, @JoergAtGithub . Note that I have no idea if/how this will run on windows (or linux for that matter) and if it requires additional steps when setting up the QOpenGL stuff, so YMMV.

**Comment by JoergAtGithub** [comment]
I get now:
```
  [718/870] Building CXX object CMakeFiles\mixxx-lib.dir\src\waveform\renderers\qopengl\waveformrendermarkrange.cpp.obj
  FAILED: CMakeFiles/mixxx-lib.dir/src/waveform/renderers/qopengl/waveformrendermarkrange.cpp.obj 
  C:\PROGRA~1\MICROS~1\2022\COMMUN~1\VC\Tools\MSVC\1433~1.316\bin\Hostx64\x64\cl.exe  /nologo /TP -DAMD64 -DHAVE_WINSOCK2_H -DMIXXX_BUILD_RELEASE -DMIXXX_DEBUG_ASSERTIONS_ENABLED -DMIXXX_DEBUG_ASSERTIONS_FATAL -DMIXXX_USE_QOPENGL -DNDEBUG -DNOMINMAX -DQT_CONCURRENT_LIB -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_PRINTSUPPORT_LIB -DQT_QMLMODELS_LIB -DQT_QML_LIB -DQT_QUICKWIDGETS_LIB -DQT_QUICK_LIB -DQT_SQL_LIB -DQT_SVG_LIB -DQT_TABLET_SUPPORT -DQT_TESTCASE_BUILDDIR=\"C:/Users/Joerg.WORLDWARTWEB/source/repos/JoergAtGithub/mixxx/build/x64__portable\" -DQT_TESTLIB_LIB -DQT_USE_QSTRINGBUILDER -DQT_WIDGETS_LIB -DQT_XML_LIB -DSFC_SUPPORTS_SET_COMPRESSION_LEVEL -DUNICODE -DWIN32 -DWINVER=0x0601 -D_ATL_MIN_CRT -D_CRT_SECURE_NO_WARNINGS -D_SILENCE_CXX17_ITERATOR_BASE_CLASS_DEPRECATION_WARNING -D_USE_MATH_DEFINES -D_WIN32_WINNT=0x0601 -D_WINSOCK_DEPRECATED_NO_WARNINGS -D__BATTERY__ -D__BROADCAST__ -D__ENGINEPRIME__ -D__HID__ -D__HSS1394__ -D__LILV__ -D__MAD__ -D__MEDIAFOUNDATION__ -D__MODPLUG__ -D__OPUS__ -D__QTKEYCHAIN__ -D__SNDFILE__ -D__SQLITE3__ -D__SSE2__ -D__SSE__ -D__VINYLCONTROL__ -D__WINDOWS__ -D__WV__ -IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\build\x64__portable\mixxx-lib_autogen\include -IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src -IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\build\x64__portable\src -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-f9cdab3\installed\x64-windows\include -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\lib\fidlib -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\lib\googletest\googletest\include -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\lib\portaudio -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\lib\rigtorp\SPSCQueue\include -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\lib\replaygain -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\lib\reverb -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\lib\libshout-idjc\include -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\lib\kaitai -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\lib\mp3guessenc-0.27.4 -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-f9cdab3\installed\x64-windows\include\qt5 -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-f9cdab3\installed\x64-windows\include\qt5\QtConcurrent -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-f9cdab3\installed\x64-windows\include\qt5\QtCore -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-f9cdab3\installed\x64-windows\tools\qt5\mkspecs\win32-msvc -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-f9cdab3\installed\x64-windows\include\qt5\QtGui -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-f9cdab3\installed\x64-windows\include\qt5\QtNetwork -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-f9cdab3\installed\x64-windows\include\qt5\QtOpenGL -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-f9cdab3\installed\x64-windows\include\qt5\QtWidgets -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-f9cdab3\installed\x64-windows\include\qt5\QtPrintSupport -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-f9cdab3\installed\x64-windows\include\qt5\QtQml -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-f9cdab3\installed\x64-windows\include\qt5\QtQuickWidgets -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-f9cdab3\installed\x64-windows\include\qt5\QtQuick -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-f9cdab3\installed\x64-windows\include\qt5\QtQmlModels -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-f9cdab3\installed\x64-windows\include\qt5\QtSql -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-f9cdab3\installed\x64-windows\include\qt5\QtSvg -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-f9cdab3\installed\x64-windows\include\qt5\QtTest -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-f9cdab3\installed\x64-windows\include\qt5\QtXml -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\lib\qm-dsp -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\lib\qm-dsp\include -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-f9cdab3\installed\x64-windows\include\taglib -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-f9cdab3\installed\x64-windows\include\opus -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-f9cdab3\installed\x64-windows\include\hidapi -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\lib\xwax -external:W0 /DWIN32 /D_WINDOWS /GR /EHsc /Zc:__cplusplus /Z7 /O2 /Ob1 /DNDEBUG -MD /UTF8 /fp:fast /Gy /W3 -std:c++20 /showIncludes /FoCMakeFiles\mixxx-lib.dir\src\waveform\renderers\qopengl\waveformrendermarkrange.cpp.obj /FdCMakeFiles\mixxx-lib.dir\mixxx-lib.pdb /FS -c C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermarkrange.cpp
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermarkrange.cpp(19): error C2872: 'WaveformRenderMarkRange': ambiguous symbol
  C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform/renderers/waveformmarkrange.h(79): note: could be 'WaveformRenderMarkRange'
  C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform/renderers/qopengl/waveformrendermarkrange.h(15): note: or       'qopengl::WaveformRenderMarkRange'
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermarkrange.cpp(19): error C2027: use of undefined type 'WaveformRenderMarkRange'
  C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform/renderers/waveformmarkrange.h(79): note: see declaration of 'WaveformRenderMarkRange'
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermarkrange.cpp(20): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermarkrange.cpp(20): error C2550: '{ctor}': constructor initializer lists are only allowed on constructor definitions
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermarkrange.cpp(21): warning C4508: '{ctor}': function should return a value; 'void' return type assumed
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermarkrange.cpp(23): error C2872: 'WaveformRenderMarkRange': ambiguous symbol
  C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform/renderers/waveformmarkrange.h(79): note: could be 'WaveformRenderMarkRange'
  C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform/renderers/qopengl/waveformrendermarkrange.h(15): note: or       'qopengl::WaveformRenderMarkRange'
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermarkrange.cpp(23): error C2872: 'WaveformRenderMarkRange': ambiguous symbol
  C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform/renderers/waveformmarkrange.h(79): note: could be 'WaveformRenderMarkRange'
  C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform/renderers/qopengl/waveformrendermarkrange.h(15): note: or       'qopengl::WaveformRenderMarkRange'
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermarkrange.cpp(23): error C2027: use of undefined type 'WaveformRenderMarkRange'
  C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform/renderers/waveformmarkrange.h(79): note: see declaration of 'WaveformRenderMarkRange'
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermarkrange.cpp(23): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermarkrange.cpp(24): warning C4508: '{dtor}': function should return a value; 'void' return type assumed
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermarkrange.cpp(26): error C2872: 'WaveformRenderMarkRange': ambiguous symbol
  C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform/renderers/waveformmarkrange.h(79): note: could be 'WaveformRenderMarkRange'
  C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform/renderers/qopengl/waveformrendermarkrange.h(15): note: or       'qopengl::WaveformRenderMarkRange'
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermarkrange.cpp(26): error C2027: use of undefined type 'WaveformRenderMarkRange'
  C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform/renderers/waveformmarkrange.h(79): note: see declaration of 'WaveformRenderMarkRange'
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermarkrange.cpp(44): error C2065: 'm_shaderProgram': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermarkrange.cpp(48): error C2065: 'm_shaderProgram': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermarkrange.cpp(53): error C2065: 'm_shaderProgram': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermarkrange.cpp(57): error C2065: 'm_shaderProgram': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermarkrange.cpp(61): error C2872: 'WaveformRenderMarkRange': ambiguous symbol
  C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform/renderers/waveformmarkrange.h(79): note: could be 'WaveformRenderMarkRange'
  C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform/renderers/qopengl/waveformrendermarkrange.h(15): note: or       'qopengl::WaveformRenderMarkRange'
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermarkrange.cpp(61): error C2027: use of undefined type 'WaveformRenderMarkRange'
  C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform/renderers/waveformmarkrange.h(79): note: see declaration of 'WaveformRenderMarkRange'
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermarkrange.cpp(70): error C2065: 'm_shaderProgram': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermarkrange.cpp(71): error C2065: 'm_shaderProgram': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermarkrange.cpp(73): error C2065: 'm_shaderProgram': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermarkrange.cpp(75): error C2065: 'm_shaderProgram': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermarkrange.cpp(76): error C2065: 'm_shaderProgram': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermarkrange.cpp(82): error C2872: 'WaveformRenderMarkRange': ambiguous symbol
  C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform/renderers/waveformmarkrange.h(79): note: could be 'WaveformRenderMarkRange'
  C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform/renderers/qopengl/waveformrendermarkrange.h(15): note: or       'qopengl::WaveformRenderMarkRange'
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermarkrange.cpp(82): error C2027: use of undefined type 'WaveformRenderMarkRange'
  C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform/renderers/waveformmarkrange.h(79): note: see declaration of 'WaveformRenderMarkRange'
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermarkrange.cpp(83): error C2065: 'm_markRanges': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermarkrange.cpp(84): error C2065: 'm_markRanges': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermarkrange.cpp(89): error C2065: 'm_markRanges': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermarkrange.cpp(91): error C2065: 'm_waveformRenderer': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermarkrange.cpp(94): error C2065: 'm_waveformRenderer': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermarkrange.cpp(90): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'WaveformMarkRange'
  C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermarkrange.cpp(94): note: No constructor could take the source type, or constructor overload resolution was ambiguous
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermarkrange.cpp(100): error C2872: 'WaveformRenderMarkRange': ambiguous symbol
  C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform/renderers/waveformmarkrange.h(79): note: could be 'WaveformRenderMarkRange'
  C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform/renderers/qopengl/waveformrendermarkrange.h(15): note: or       'qopengl::WaveformRenderMarkRange'
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermarkrange.cpp(100): error C2027: use of undefined type 'WaveformRenderMarkRange'
  C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform/renderers/waveformmarkrange.h(79): note: see declaration of 'WaveformRenderMarkRange'
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermarkrange.cpp(105): error C2065: 'm_waveformRenderer': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermarkrange.cpp(105): error C2065: 'm_waveformRenderer': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermarkrange.cpp(105): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'QRectF'
  C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermarkrange.cpp(105): note: No constructor could take the source type, or constructor overload resolution was ambiguous
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermarkrange.cpp(106): error C2065: 'm_shaderProgram': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermarkrange.cpp(108): error C2065: 'm_shaderProgram': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermarkrange.cpp(109): error C2065: 'm_shaderProgram': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermarkrange.cpp(111): error C2065: 'm_markRanges': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermarkrange.cpp(111): error C2530: 'markRange': references must be initialized
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermarkrange.cpp(111): error C3531: 'markRange': a symbol whose type contains 'auto' must have an initializer
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermarkrange.cpp(111): error C2143: syntax error: missing ';' before ':'
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermarkrange.cpp(111): error C2143: syntax error: missing ';' before ')'
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermarkrange.cpp(128): error C2065: 'm_waveformRenderer': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermarkrange.cpp(130): error C2065: 'm_waveformRenderer': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermarkrange.cpp(138): error C2065: 'm_waveformRenderer': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermarkrange.cpp(145): error C2065: 'm_waveformRenderer': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermarkrange.cpp(145): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'QRectF'
  C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermarkrange.cpp(145): note: No constructor could take the source type, or constructor overload resolution was ambiguous
  [719/870] Building CXX object CMakeFiles\mixxx-lib.dir\src\waveform\renderers\qopengl\waveformrenderersignalbase.cpp.obj
  [720/870] Building CXX object CMakeFiles\mixxx-lib.dir\src\waveform\renderers\qopengl\waveformrendererrgb.cpp.obj
  [721/870] Building CXX object CMakeFiles\mixxx-lib.dir\src\waveform\widgets\qopengl\waveformwidget.cpp.obj
  [722/870] Building CXX object CMakeFiles\mixxx-lib.dir\src\waveform\widgets\qopengl\rgbwaveformwidget.cpp.obj
  [723/870] Building CXX object CMakeFiles\mixxx-lib.dir\src\waveform\renderers\qopengl\waveformrendererpreroll.cpp.obj
  [724/870] Building CXX object CMakeFiles\mixxx-lib.dir\src\waveform\renderers\qopengl\waveformrendermark.cpp.obj
  FAILED: CMakeFiles/mixxx-lib.dir/src/waveform/renderers/qopengl/waveformrendermark.cpp.obj 
  C:\PROGRA~1\MICROS~1\2022\COMMUN~1\VC\Tools\MSVC\1433~1.316\bin\Hostx64\x64\cl.exe  /nologo /TP -DAMD64 -DHAVE_WINSOCK2_H -DMIXXX_BUILD_RELEASE -DMIXXX_DEBUG_ASSERTIONS_ENABLED -DMIXXX_DEBUG_ASSERTIONS_FATAL -DMIXXX_USE_QOPENGL -DNDEBUG -DNOMINMAX -DQT_CONCURRENT_LIB -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_PRINTSUPPORT_LIB -DQT_QMLMODELS_LIB -DQT_QML_LIB -DQT_QUICKWIDGETS_LIB -DQT_QUICK_LIB -DQT_SQL_LIB -DQT_SVG_LIB -DQT_TABLET_SUPPORT -DQT_TESTCASE_BUILDDIR=\"C:/Users/Joerg.WORLDWARTWEB/source/repos/JoergAtGithub/mixxx/build/x64__portable\" -DQT_TESTLIB_LIB -DQT_USE_QSTRINGBUILDER -DQT_WIDGETS_LIB -DQT_XML_LIB -DSFC_SUPPORTS_SET_COMPRESSION_LEVEL -DUNICODE -DWIN32 -DWINVER=0x0601 -D_ATL_MIN_CRT -D_CRT_SECURE_NO_WARNINGS -D_SILENCE_CXX17_ITERATOR_BASE_CLASS_DEPRECATION_WARNING -D_USE_MATH_DEFINES -D_WIN32_WINNT=0x0601 -D_WINSOCK_DEPRECATED_NO_WARNINGS -D__BATTERY__ -D__BROADCAST__ -D__ENGINEPRIME__ -D__HID__ -D__HSS1394__ -D__LILV__ -D__MAD__ -D__MEDIAFOUNDATION__ -D__MODPLUG__ -D__OPUS__ -D__QTKEYCHAIN__ -D__SNDFILE__ -D__SQLITE3__ -D__SSE2__ -D__SSE__ -D__VINYLCONTROL__ -D__WINDOWS__ -D__WV__ -IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\build\x64__portable\mixxx-lib_autogen\include -IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src -IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\build\x64__portable\src -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-f9cdab3\installed\x64-windows\include -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\lib\fidlib -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\lib\googletest\googletest\include -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\lib\portaudio -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\lib\rigtorp\SPSCQueue\include -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\lib\replaygain -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\lib\reverb -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\lib\libshout-idjc\include -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\lib\kaitai -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\lib\mp3guessenc-0.27.4 -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-f9cdab3\installed\x64-windows\include\qt5 -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-f9cdab3\installed\x64-windows\include\qt5\QtConcurrent -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-f9cdab3\installed\x64-windows\include\qt5\QtCore -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-f9cdab3\installed\x64-windows\tools\qt5\mkspecs\win32-msvc -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-f9cdab3\installed\x64-windows\include\qt5\QtGui -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-f9cdab3\installed\x64-windows\include\qt5\QtNetwork -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-f9cdab3\installed\x64-windows\include\qt5\QtOpenGL -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-f9cdab3\installed\x64-windows\include\qt5\QtWidgets -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-f9cdab3\installed\x64-windows\include\qt5\QtPrintSupport -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-f9cdab3\installed\x64-windows\include\qt5\QtQml -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-f9cdab3\installed\x64-windows\include\qt5\QtQuickWidgets -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-f9cdab3\installed\x64-windows\include\qt5\QtQuick -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-f9cdab3\installed\x64-windows\include\qt5\QtQmlModels -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-f9cdab3\installed\x64-windows\include\qt5\QtSql -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-f9cdab3\installed\x64-windows\include\qt5\QtSvg -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-f9cdab3\installed\x64-windows\include\qt5\QtTest -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-f9cdab3\installed\x64-windows\include\qt5\QtXml -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\lib\qm-dsp -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\lib\qm-dsp\include -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-f9cdab3\installed\x64-windows\include\taglib -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-f9cdab3\installed\x64-windows\include\opus -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-f9cdab3\installed\x64-windows\include\hidapi -external:IC:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\lib\xwax -external:W0 /DWIN32 /D_WINDOWS /GR /EHsc /Zc:__cplusplus /Z7 /O2 /Ob1 /DNDEBUG -MD /UTF8 /fp:fast /Gy /W3 -std:c++20 /showIncludes /FoCMakeFiles\mixxx-lib.dir\src\waveform\renderers\qopengl\waveformrendermark.cpp.obj /FdCMakeFiles\mixxx-lib.dir\mixxx-lib.pdb /FS -c C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(23): error C2872: 'WaveformRenderMark': ambiguous symbol
  C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\waveformmark.h(123): note: could be 'WaveformRenderMark'
  C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform/renderers/qopengl/waveformrendermark.h(16): note: or       'qopengl::WaveformRenderMark'
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(23): error C2027: use of undefined type 'WaveformRenderMark'
  C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\waveformmark.h(123): note: see declaration of 'WaveformRenderMark'
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(24): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(24): error C2550: '{ctor}': constructor initializer lists are only allowed on constructor definitions
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(25): warning C4508: '{ctor}': function should return a value; 'void' return type assumed
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(27): error C2872: 'WaveformRenderMark': ambiguous symbol
  C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\waveformmark.h(123): note: could be 'WaveformRenderMark'
  C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform/renderers/qopengl/waveformrendermark.h(16): note: or       'qopengl::WaveformRenderMark'
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(27): error C2872: 'WaveformRenderMark': ambiguous symbol
  C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\waveformmark.h(123): note: could be 'WaveformRenderMark'
  C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform/renderers/qopengl/waveformrendermark.h(16): note: or       'qopengl::WaveformRenderMark'
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(27): error C2027: use of undefined type 'WaveformRenderMark'
  C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\waveformmark.h(123): note: see declaration of 'WaveformRenderMark'
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(27): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(28): error C2065: 'm_marks': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(28): error C2530: 'pMark': references must be initialized
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(28): error C3531: 'pMark': a symbol whose type contains 'auto' must have an initializer
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(28): error C2143: syntax error: missing ';' before ':'
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(28): error C2143: syntax error: missing ';' before ')'
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(31): warning C4508: '{dtor}': function should return a value; 'void' return type assumed
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(33): error C2872: 'WaveformRenderMark': ambiguous symbol
  C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\waveformmark.h(123): note: could be 'WaveformRenderMark'
  C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform/renderers/qopengl/waveformrendermark.h(16): note: or       'qopengl::WaveformRenderMark'
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(33): error C2027: use of undefined type 'WaveformRenderMark'
  C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\waveformmark.h(123): note: see declaration of 'WaveformRenderMark'
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(34): error C2065: 'm_waveformRenderer': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(35): error C2065: 'm_marks': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(35): error C2065: 'm_waveformRenderer': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(38): error C2872: 'WaveformRenderMark': ambiguous symbol
  C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\waveformmark.h(123): note: could be 'WaveformRenderMark'
  C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform/renderers/qopengl/waveformrendermark.h(16): note: or       'qopengl::WaveformRenderMark'
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(38): error C2027: use of undefined type 'WaveformRenderMark'
  C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\waveformmark.h(123): note: see declaration of 'WaveformRenderMark'
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(39): error C3861: 'initGradientShader': identifier not found
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(40): error C3861: 'initTextureShader': identifier not found
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(42): error C3861: 'generatePlayPosMarkTexture': identifier not found
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(45): error C2872: 'WaveformRenderMark': ambiguous symbol
  C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\waveformmark.h(123): note: could be 'WaveformRenderMark'
  C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform/renderers/qopengl/waveformrendermark.h(16): note: or       'qopengl::WaveformRenderMark'
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(45): error C2027: use of undefined type 'WaveformRenderMark'
  C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\waveformmark.h(123): note: see declaration of 'WaveformRenderMark'
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(67): error C2065: 'm_gradientShaderProgram': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(71): error C2065: 'm_gradientShaderProgram': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(76): error C2065: 'm_gradientShaderProgram': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(80): error C2065: 'm_gradientShaderProgram': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(85): error C2872: 'WaveformRenderMark': ambiguous symbol
  C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\waveformmark.h(123): note: could be 'WaveformRenderMark'
  C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform/renderers/qopengl/waveformrendermark.h(16): note: or       'qopengl::WaveformRenderMark'
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(85): error C2027: use of undefined type 'WaveformRenderMark'
  C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\waveformmark.h(123): note: see declaration of 'WaveformRenderMark'
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(107): error C2065: 'm_textureShaderProgram': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(111): error C2065: 'm_textureShaderProgram': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(116): error C2065: 'm_textureShaderProgram': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(120): error C2065: 'm_textureShaderProgram': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(125): error C2872: 'WaveformRenderMark': ambiguous symbol
  C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\waveformmark.h(123): note: could be 'WaveformRenderMark'
  C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform/renderers/qopengl/waveformrendermark.h(16): note: or       'qopengl::WaveformRenderMark'
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(125): error C2027: use of undefined type 'WaveformRenderMark'
  C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\waveformmark.h(123): note: see declaration of 'WaveformRenderMark'
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(126): error C2065: 'm_waveformRenderer': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(126): error C2737: 'devicePixelRatio': const object must be initialized
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(141): error C2065: 'm_waveformRenderer': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(141): error C2065: 'm_waveformRenderer': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(141): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'QRectF'
  C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(141): note: No constructor could take the source type, or constructor overload resolution was ambiguous
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(143): error C2065: 'm_textureShaderProgram': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(145): error C2065: 'm_textureShaderProgram': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(146): error C2065: 'm_textureShaderProgram': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(147): error C2065: 'm_textureShaderProgram': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(148): error C2065: 'm_textureShaderProgram': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(150): error C2065: 'm_textureShaderProgram': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(152): error C2065: 'm_textureShaderProgram': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(153): error C2065: 'm_textureShaderProgram': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(155): error C2065: 'm_textureShaderProgram': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(156): error C2065: 'm_textureShaderProgram': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(159): error C2065: 'm_textureShaderProgram': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(166): error C2872: 'WaveformRenderMark': ambiguous symbol
  C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\waveformmark.h(123): note: could be 'WaveformRenderMark'
  C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform/renderers/qopengl/waveformrendermark.h(16): note: or       'qopengl::WaveformRenderMark'
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(166): error C2027: use of undefined type 'WaveformRenderMark'
  C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\waveformmark.h(123): note: see declaration of 'WaveformRenderMark'
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(182): error C2065: 'm_waveformRenderer': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(182): error C2065: 'm_waveformRenderer': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(182): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'QRectF'
  C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(182): note: No constructor could take the source type, or constructor overload resolution was ambiguous
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(183): error C2065: 'm_gradientShaderProgram': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(185): error C2065: 'm_gradientShaderProgram': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(186): error C2065: 'm_gradientShaderProgram': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(187): error C2065: 'm_gradientShaderProgram': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(188): error C2065: 'm_gradientShaderProgram': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(190): error C2065: 'm_gradientShaderProgram': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(191): error C2065: 'm_gradientShaderProgram': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(193): error C2065: 'm_gradientShaderProgram': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(194): error C2065: 'm_gradientShaderProgram': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(196): error C2065: 'm_gradientShaderProgram': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(197): error C2065: 'm_gradientShaderProgram': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(203): error C2872: 'WaveformRenderMark': ambiguous symbol
  C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\waveformmark.h(123): note: could be 'WaveformRenderMark'
  C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform/renderers/qopengl/waveformrendermark.h(16): note: or       'qopengl::WaveformRenderMark'
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(203): error C2027: use of undefined type 'WaveformRenderMark'
  C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\waveformmark.h(123): note: see declaration of 'WaveformRenderMark'
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(204): error C2065: 'm_waveformRenderer': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(204): error C2737: 'devicePixelRatio': const object must be initialized
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(207): error C3861: 'checkCuesUpdated': identifier not found
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(212): error C2065: 'm_marks': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(212): error C2530: 'pMark': references must be initialized
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(212): error C3531: 'pMark': a symbol whose type contains 'auto' must have an initializer
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(212): error C2143: syntax error: missing ';' before ':'
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(212): error C2143: syntax error: missing ';' before ')'
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(224): error C3861: 'generateMarkImage': identifier not found
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(227): error C2737: 'samplePosition': const object must be initialized
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(230): error C2065: 'm_waveformRenderer': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(231): error C2737: 'sampleEndPosition': const object must be initialized
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(235): error C2065: 'm_waveformRenderer': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(239): error C2737: 'markHalfWidth': const object must be initialized
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(246): error C2065: 'm_waveformRenderer': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(248): error C2660: 'drawTexture': function does not take 2 arguments
  C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(125): note: see declaration of 'drawTexture'
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(256): error C2065: 'm_waveformRenderer': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(268): error C2065: 'm_waveformRenderer': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(267): error C2440: '<function-style-cast>': cannot convert from 'double' to 'QPointF'
  C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(269): note: No constructor could take the source type, or constructor overload resolution was ambiguous
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(266): error C2440: '<function-style-cast>': cannot convert from 'QPointF' to 'QRectF'
  C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(269): note: No constructor could take the source type, or constructor overload resolution was ambiguous
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(277): error C2679: binary '[': no operator found which takes a right-hand operand of type 'int' (or there is no acceptable conversion)
  C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-f9cdab3\installed\x64-windows\include\qt5\QtCore/qmap.h(385): note: could be 'const T QMap<WaveformMarkPointer,T>::operator [](const Key &) const'
          with
          [
              T=int,
              Key=WaveformMarkPointer
          ]
  C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-f9cdab3\installed\x64-windows\include\qt5\QtCore/qmap.h(384): note: or       'T &QMap<WaveformMarkPointer,T>::operator [](const Key &)'
          with
          [
              T=int,
              Key=WaveformMarkPointer
          ]
  C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(277): note: while trying to match the argument list '(QMap<WaveformMarkPointer,int>, int)'
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(280): error C2737: 'markHalfHeight': const object must be initialized
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(286): error C2065: 'm_waveformRenderer': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(288): error C2660: 'drawTexture': function does not take 2 arguments
  C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(125): note: see declaration of 'drawTexture'
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(296): error C2065: 'm_waveformRenderer': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(299): error C2065: 'm_waveformRenderer': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(304): error C2065: 'm_waveformRenderer': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(304): error C2440: '<function-style-cast>': cannot convert from 'double' to 'QPointF'
  C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(305): note: No constructor could take the source type, or constructor overload resolution was ambiguous
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(303): error C2440: '<function-style-cast>': cannot convert from 'QPointF' to 'QRectF'
  C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(305): note: No constructor could take the source type, or constructor overload resolution was ambiguous
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(313): error C2679: binary '[': no operator found which takes a right-hand operand of type 'int' (or there is no acceptable conversion)
  C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-f9cdab3\installed\x64-windows\include\qt5\QtCore/qmap.h(385): note: could be 'const T QMap<WaveformMarkPointer,T>::operator [](const Key &) const'
          with
          [
              T=int,
              Key=WaveformMarkPointer
          ]
  C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-f9cdab3\installed\x64-windows\include\qt5\QtCore/qmap.h(384): note: or       'T &QMap<WaveformMarkPointer,T>::operator [](const Key &)'
          with
          [
              T=int,
              Key=WaveformMarkPointer
          ]
  C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(313): note: while trying to match the argument list '(QMap<WaveformMarkPointer,int>, int)'
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(318): error C2065: 'm_waveformRenderer': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(321): error C2065: 'm_waveformRenderer': undeclared identifier
C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendermark.cpp(321): fatal error C1003: error count exceeds 100; stopping compilation
```

**Comment by m0dB** [comment]
Meh... I am using the same names as several existing waveform renderer classes, but in a different namespace (qopengl). Unfortunately namespace resolution is very compiler dependent. I don't think that without access to a windows machine I will be able to fix this. I will change using a namespace to using a prefix instead. Might be more clear anyway.

File: src/widget/qopengl/wspinny.cpp [hunk 1]
```diff
@@ -0,0 +1,824 @@
+#include "widget/wspinny.h"
```
Comment (JoergAtGithub) [inline src/widget/qopengl/wspinny.cpp:1]:
```suggestion
#include "widget/qopengl/wspinny.h"
```
I guess this file is meant to be included here?

**Comment by ronso0** [comment]
Just a side note:
The `<details>` element allows to hide extra info like pages of compiler messages, and increases the lifespan of readers' mouse wheels ; )

Just `<details>quite a few lines of code or whatever</details>` works.
(more info https://gist.github.com/scmx/eca72d44afee0113ceb0349dd54a84a2)

File: src/widget/qopengl/wspinny.cpp (hunk 1 above)
Comment (m0dB) [reply src/widget/qopengl/wspinny.cpp:1]: it doesn't matter, "widget/wspinny.h" will include "widget/qopengl/wspinny.h" when MIXXX_USE_QOPENGL is defined.

**Comment by JoergAtGithub** [comment]
All the includes from the new qopengl can't find the file to be included:
grafik
The syntax is exactly the same as one hierachy level above. I even retyped it, to exclude encoding issues.

File: src/waveform/renderers/qopengl/oglwaveformrendermark.cpp [hunk 2]
```diff
@@ -0,0 +1,694 @@
+#include "waveform/renderers/qopengl/oglwaveformrendermark.h"
+
+#include <QDomNode>
+#include <QOpenGLTexture>
```
Comment (JoergAtGithub) [inline src/waveform/renderers/qopengl/oglwaveformrendermark.cpp:4]:
```suggestion
#include <QOpenGLTexture>
#include <QPainterPath>
```

**Comment by JoergAtGithub** [comment]
I got it working on Windows. I had to add replace `WaveformRenderMark `with `qopengl::WaveformRenderMark` everywhere in
src/waveform/renderers/qopengl/waveformrendermark.cpp
and `WaveformRenderMarkRange` with `qopengl::WaveformRenderMarkRange` everywhere in
src/waveform/renderers/qopengl/waveformrendermarkrange.cpp

I could use this new Waveform-Type under Windows: Waveforms, Spinnies and VUMeter looked good, but the frame rate was rather low.

**Comment by m0dB** [comment]
Ok, thanks. I will revert the last commit and add the namespace, I prefer that over the prefix. 

Too bad that on windows it does not give the same good results as on macOS. Clearly Qt does things very differently under the hood.

**Comment by JoergAtGithub** [comment]
I tested this again on Windows11, but this time with the new buildenv from #11074. This time the results were better:
- I got the expected frame rate up to 60fps
- But there were some frame drops

If I move the cross fader of my controller fast, the crossfader in the GUI jumps, if I select a high OpenGL frame rate. Same as on normal GLSL.

**Comment by JoergAtGithub** [comment]
Something is gone wrong while rebasing (Ubuntu and Windows builds fail now):
```
/home/runner/work/mixxx/mixxx/src/widget/wvumetergl.cpp: In member function ‘virtual void WVuMeterGL::showEvent(QShowEvent*)’:
Error: /home/runner/work/mixxx/mixxx/src/widget/wvumetergl.cpp:162:5: error: ‘m_iRendersPending’ was not declared in this scope
  162 |     m_iRendersPending = 2;
      |     ^~~~~~~~~~~~~~~~~
```

**Comment by m0dB** [comment]
I see, I only checked the macOS build with QOPENGL=on, where this code isn't compiled. I'll fix it.

**Comment by JoergAtGithub** [comment]
To fix the pre-commit issues, download [pre-commit.patch](https://github.com/mixxxdj/mixxx/suites/9789216954/artifacts/470785514) from the build artifacts, unzip it into your mixx directory, and call
`git apply pre-commit patch`
Or you set up automatical code checking locally on your system: https://github.com/mixxxdj/mixxx/wiki/Using-Git#set-up-automatic-code-checking

**Comment by fwcd** [comment]
Any updates on this? This does improve waveform performance noticeably on M1 macs too.

**Comment by JoergAtGithub** [comment]
I added the completion of this on the list of GSoC 2023 projects: https://github.com/mixxxdj/mixxx/wiki/GSOC-2023-Ideas/#unify-opengl-waveform-code-for-macos-to-use-qt-515-or-later
If Mixxx will be accepted as GSoC organisation this year again, and someone of you want to finish this, you might get a student salary for it. Or maybe you know a skilled student, who want to apply for this summer job.

**Comment by JoergAtGithub** [comment]
Why not fix the CI issues and remove the "WIP" from the titel of this PR, to make clear, that it's ready for review now?
It's not to late for 2.4, especially as this fixes a serious problem for many users.

**Comment by m0dB** [comment]
I must say that I got a bit demotivated because after investing a lot of time and energy, I got the impression that it was not going to be accepted into 2.4. But if you think it could be, I will pick it back up.

**Comment by daschuer** [comment]
We are planning a short 2.4 beta phase and than starting a six month release cycle after the 2.4 release, so if we think this requires more testing it is not shifted by two years. I think it depends on how much testing will be done here. A least we should not delay 2.4 beta because of this. 
My plan is do dedicate my time to prepare the 2.3.4 release and the 2.4-beta now.

**Comment by JoergAtGithub** [comment]
I thought Mixxx 2.4 on Mac Intel is so slow, that it's unusable. In my opinion this would be an absolute showstopper for a 2.4 release. But maybe there are also other solution to fix this?

**Comment by daschuer** [comment]
> I thought Mixxx 2.4 on Mac Intel is so slow, that it's unusable. 

We have no clear evidence for that. For my understanding it works OKish with QT 5.12 but we need to test. 
What are your results comparing the Mixxx 2.3 and 2.4 branch. Is there e difference for you?

**Comment by Swiftb0y** [comment]
I just tested 2.4 on a MacBook and I don't think its very usable. The framerate for the GL waveforms is hovering around 45fps, 25fps for the GLSL waveforms. GUI input lags behind for a solid 2 seconds or so when the spinnies are on. That problem sometimes vanishes but then comes back and I don't know why. 
This branch (no matter what waveform is selected?) is buttery smooth compared to 2.4 with almost no framedrops.

File: src/waveform/renderers/qopengl/waveformrendererrgb.cpp [hunk 3]
```diff
@@ -0,0 +1,297 @@
...
+        m_colors[m_colorIndex++] = g;
+        m_colors[m_colorIndex++] = b;
+    }
+}
+
+void WaveformRendererRGB::renderGL() {
+    // The source of our data are uint8_t values (waveformData.filtered.low/mid/high).
+    // We can avoid type conversion by calculating the values needed for drawing
+    // using fixed point. Since the range of the intermediate values is limited, we
+    // can take advantage of this and use a lookup table instead of sqrtf.
```
Comment (Swiftb0y) [inline src/waveform/renderers/qopengl/waveformrendererrgb.cpp:101]: is that optimization really necessary though? It seems premature to me.

File: src/waveform/renderers/qopengl/waveformrendererrgb.cpp [hunk 4]
```diff
@@ -0,0 +1,297 @@
...
+            "\
+varying vec3 vcolor;\n\
+void main()\n\
+{\n\
+    gl_FragColor = vec4(vcolor,1.0);\n\
+}\n";
+
+    if (!m_shaderProgram.addShaderFromSourceCode(QOpenGLShader::Vertex, vertexShaderCode)) {
+        return;
+    }
```
Comment (Swiftb0y) [inline src/waveform/renderers/qopengl/waveformrendererrgb.cpp:49]: these should probably all be `VERIFY_OR_DEBUG_ASSERT`s.

**Review by Swiftb0y — COMMENTED** [review]
A couple thoughts. Everything but a proper review. I think this could use a little more care to clean up the code until someone can actually take a proper look at this.

**Comment by fwcd** [comment]
Even under Rosetta the new waveforms are much smoother, so I'd vote for including it in 2.4 too.

**Comment by m0dB** [comment]
@Swiftb0y thanks for taking the time to review this, much appreciated!

File: CMakeLists.txt [hunk 5]
```diff
@@ -109,6 +109,15 @@ if(NOT CMAKE_CONFIGURATION_TYPES)
...
 option(QT6 "Build with Qt6" OFF)
+if(APPLE)
+option(QOPENGL "Use QOpenGL... classes instead of QGLWidget" ON)
+else()
+option(QOPENGL "Use QOpenGL... classes instead of QGLWidget" OFF)
+endif()
+
+if(QOPENGL)
+    add_compile_definitions(MIXXX_USE_QOPENGL)
+endif()
```
Comment (fwcd) [inline CMakeLists.txt:120]: Style nit, but we'd probably want to use two-space indent for both of these.

File: src/waveform/renderers/qopengl/waveformrenderbeat.cpp [hunk 6]
```diff
@@ -0,0 +1,149 @@
...
+
+void WaveformRenderBeat::initializeGL() {
+    QString vertexShaderCode =
+            "\
+uniform mat4 matrix;\n\
+attribute vec4 position;\n\
+void main()\n\
+{\n\
+    gl_Position = matrix * position;\n\
+}\n";
```
[the remark this answers is not in the document]
Comment (m0dB) [reply src/waveform/renderers/qopengl/waveformrenderbeat.cpp:30]: Very nice, I didn't know this (and I simply took this construction from elsewhere in the code). I will apply this everywhere.

File: src/waveform/renderers/qopengl/waveformrendererendoftrack.cpp [hunk 7]
```diff
@@ -0,0 +1,134 @@
...
+
+bool WaveformRendererEndOfTrack::init() {
+    m_timer.restart();
+
+    m_pEndOfTrackControl = new ControlProxy(
+            m_waveformRenderer->getGroup(), "end_of_track");
+    m_pTimeRemainingControl = new ControlProxy(
+            m_waveformRenderer->getGroup(), "time_remaining");
+    return true;
+}
```
[the remark this answers is not in the document]
Comment (m0dB) [reply src/waveform/renderers/qopengl/waveformrendererendoftrack.cpp:43]: Yes for smart pointers. The thing is that there are still many raw pointers all over the code, but I understand that the intention is to gradually change them and use smart pointers in new code.

File: src/waveform/renderers/qopengl/waveformrendererendoftrack.cpp [hunk 8]
```diff
@@ -0,0 +1,134 @@
...
+        return;
+    }
+
+    if (!m_shaderProgram.link()) {
+        return;
+    }
+
+    if (!m_shaderProgram.bind()) {
+        return;
+    }
```
[the remark this answers is not in the document]
Comment (m0dB) [reply src/waveform/renderers/qopengl/waveformrendererendoftrack.cpp:91]: I guess so, though the class hierarchy is not always trivial and some code duplication might be easier than trying to restructure things (not saying that is the case here, I will have a look).

File: src/waveform/renderers/qopengl/waveformrendererrgb.cpp (hunk 3 above)
Comment (m0dB) [reply src/waveform/renderers/qopengl/waveformrendererrgb.cpp:101]: When I first started looking into the performance issues I thought this code was particularly inefficient and I did this optimization (and I have used it without any issues for a long time). I did some benchmarking and it was definitely faster, but of course the real performance issue was elsewhere. I imagine your concern is that the fixed point math doesn't make it easier to read. I will create a version that uses floats and do another comparison to see if the reduced readability is worth the gain.

File: src/waveform/renderers/qopengl/waveformrendererrgb.cpp (hunk 4 above)
Comment (m0dB) [reply src/waveform/renderers/qopengl/waveformrendererrgb.cpp:49]: agreed

File: CMakeLists.txt (hunk 5 above)
Comment (m0dB) [reply CMakeLists.txt:120]: got it

**Comment by m0dB** [comment]
@daschuer I am a bit lost now if I should rebase on main or on 2.4

**Comment by JoergAtGithub** [comment]
> This branch (no matter what waveform is selected?) is buttery smooth compared to 2.4 with almost no framedrops (and no input lags).

@fwcd @m0dB Can you confirm, that the perfomance issue on MacOS is solved by this PR also for other waveform types than `RGB (QOpenGL) (GLSL)` ?

File: src/waveform/renderers/glslwaveformrenderersignal.cpp [hunk 9]
```diff
@@ -1,6 +1,11 @@
 #include "waveform/renderers/glslwaveformrenderersignal.h"
 #if !defined(QT_NO_OPENGL) && !defined(QT_OPENGL_ES_2)
 
+#ifdef MIXXX_USE_QOPENGL
+#include <QOpenGLFramebufferObject>
+#include <QOpenGLShaderProgram>
+#else
+#endif
```
Comment (JoergAtGithub) [inline src/waveform/renderers/glslwaveformrenderersignal.cpp:8]: This #else / #endif  looks placed wrong here?

**Comment by m0dB** [comment]
@JoergAtGithub yes and no.

Let me start with explaining the general approach: I found that QGLWidget was the main culprit of the performance issues. I replaced all uses of QGLWidget with a new class WGLWidget.

If cmake option QOPENGL is ON and therefore preprocessor define MIXXX_USE_QOPENGL is set, WGLWidget is a class derived from QWidget and uses QOpenGLWindow for the drawing (I tried deriving from QOpenGLWidget but that required too many changes to get to work). See wglwidgetqopengl.h / cpp

If you don't use this option, WGLWidget derives directly from QGLWidget, which means that everything works as before (WGLWidget does add some methods on top of QGLWidget, this is merely to have a common API for both implementations). See wglwidgetqglwidget.h / cpp

Now, to answer your question:

Yes, in the sense that, with this option, all waveform types, or rather all WGLWidget derived widgets, so also wspinny and wvumetergl, are now using QOpenGLWindow.

No, in the sense that I found that doing QPainter stuff inside the QOpenGL context was still causing performance issues, at least on my old 2015 MacBook pro. But it is very well possible that on newer hardware this is not as noticable. (@Swiftb0y @fwcd what kind of hardware have you tested this on?)

Now, there is another reason I wanted to get rid of all QPainter-inside-QOpenGL code: I wanted to do all rendering in a dedicated thread instead of from the main qevent loop, and this doesn't work with QPainter. My initial experiments with this were very promising, so I might pick that up again in the future.

File: src/waveform/renderers/glslwaveformrenderersignal.cpp (hunk 9 above)
Comment (m0dB) [reply src/waveform/renderers/glslwaveformrenderersignal.cpp:8]: absolutely, good catch

File: src/waveform/renderers/qopengl/waveformrendererendoftrack.cpp (hunk 8 above)
[the remark this answers is not in the document]
Comment (m0dB) [reply src/waveform/renderers/qopengl/waveformrendererendoftrack.cpp]: done

File: src/waveform/renderers/qopengl/waveformrendererendoftrack.cpp (hunk 7 above)
[the remark this answers is not in the document]
Comment (m0dB) [reply src/waveform/renderers/qopengl/waveformrendererendoftrack.cpp]: done

**Comment by JoergAtGithub** [comment]
I just build the latest version (e914ba9) of this PR on Windows11 with `QOPENGL = ON`.
All waveform types look correct, including `RGB (QOpenGL) (GLSL)`. This time the UI was responsive in any case.
`RGB (QOpenGL) (GLSL)` looked slightly smoother than the other waveform types, but all run at 60fps (on a fast laptop) without significiant framedrops.

File: src/waveform/renderers/qopengl/waveformrendererrgb.cpp (hunk 3 above)
Comment (m0dB) [reply src/waveform/renderers/qopengl/waveformrendererrgb.cpp]: now using floats

**Comment by m0dB** [comment]
I have addressed all issues mentioned in the reviews. There are still some TODOs though. For example, I just remembered that I have not implemented all variations when it comes to orientation and alignment. None of that should be complicated, but I need to go through all renderers to check this. But in the mean time I would but great if others can test this. Maybe I should set QOPENGL=ON by default for all platforms? Or at least for windows, until someone can compile and confirm that it works on linux too.

**Comment by JoergAtGithub** [comment]
> Maybe I should set QOPENGL=ON by default for all platforms?

Yes please! All CI jobs should run with `QOPENGL=ON` for now. Based on the outcome, we can later decide if we've to set it back before merging.

**Comment by JoergAtGithub** [comment]
The Qt6 CI fails are now fixed in 2.4 branch

**Comment by Swiftb0y** [comment]
> @Swiftb0y thanks for taking the time to review this, much appreciated!

You're very welcome. We highly appreciate your work on this PR. I will try to review more code asap, but keep in mind im everything but an expert in macos or graphics programming. 

> (@Swiftb0y @fwcd what kind of hardware have you tested this on?)

Screenshot 2023-02-11 at 13 38 24

**Comment by foss-** [comment]
First things first: thanks so much for your work on keeping Mixxx usable on macOS, which is greatly appreciated.

MacBookPro14,3 (2017), 3,1 GHz Quad-Core Intel Core i7, Radeon Pro 560,Intel HD Graphics 630 
Tested 2.4-alpha-1415-g239e950669 (HEAD) briefly

Issues noticed:

- when scrolling library, waveform slightly slows down / lags, drop frames increase while doing this (known issue, no regression)
- Filtered - Qt (GL) lagging, very choppy, CPU goes to ~100 % and fans kick in, lots of dropped frames at 30 fps
- when increasing / decreasing the waveform size with the handle for that, the entire waveform is glitching in red, this only happens when size is changed and stops as soon as the mouse is not moving to resize, even with the handle still clicked (not a big problem)

**Comment by fwcd** [comment]
> what kind of hardware have you tested this on?

2022 Mac Studio (M1 Max) and a 2021 MacBook Pro (M1 Pro), both running Ventura 13.1

**Comment by m0dB** [comment]
> First things first: thanks so much for your work on keeping Mixxx usable on macOS, which is greatly appreciated.

Thanks @foss-  :-)

> MacBookPro14,3 (2017), 3,1 GHz Quad-Core Intel Core i7, Radeon Pro 560,Intel HD Graphics 630 Tested 2.4-alpha-1415-g239e950669 (HEAD)
> 
> Issues noticed:
> 
> * when scrolling library, waveform slightly slows down / lags, drop frames increase while doing this (known issue, no regression)

Right, this can potentially be fixed by running the OpenGL rendering in a dedicated thread. I have this working (experimental) on macOS, but on Windows it reportedly causes issues. Anyway, I will revisit this in the future, but I prefer to concentrate on finalizing this first. (Alternatively, we might try to move the library to its own thread, IIRC this has been attempted in the past but was never finished?)

> * Filtered - Qt (GL) lagging, very choppy, CPU goes to ~100 % and fans kick in, lots of dropped frames at 30 fps (regression, not happening with most recent development build)

Yes, that is not surprising. Using QPainter with the QOpenGLWindow as paint device causes performance issues, which is why I decided to port all rendering to OpenGL code. I don't see a way to avoid this. Does it even make sense to keep this renderer around?

> * when increasing / decreasing the waveform size with the handle for that, the entire waveform is glitching in red, this only happens when size is changed and stops as soon as the mouse is not moving to resize, even with the handle still clicked (not a big problem)

Hm, indeed. Not in red in my case, but glitching indeed. I will try to solve this, I simply (and surprisingly) hadn't tried this.

And something else I noticed myself: when moving mixxx from a retina to not-retina screen the change in device pixel ratio is not handled, which leads to weird things such as the markers being twice their size.

**Comment by m0dB** [comment]
> The Qt6 CI fails are now fixed in 2.4 branch

Any chance that fix will be merged to main?

**Comment by m0dB** [comment]
> > Maybe I should set QOPENGL=ON by default for all platforms?
> 
> Yes please! All CI jobs should run with `QOPENGL=ON` for now. Based on the outcome, we can later decide if we've to set it back before merging.

done

**Comment by foss-** [comment]
Honestly I do not know why 11 different waveform options are needed. I always found that number overwhelming and since I was lacking technical understanding for the past years just stuck with any colored RGB renderer that worked somewhat reliably.

Left out this aspect of that very high number of renderers, since I found it better to postpone to later and focus on getting this in. If a single renderer is causing trouble, dropping it should certainly be taken into consideration. Maybe someone else can elaborate on why that specific renderer would still be needed.

**Comment by daschuer** [comment]
The different renders are there for different personal preferences and different CPU load / GPU type situations. 
Some settings are causing trouble for some devices. Since it is easy to add a new one and it is hard to find rectifications for removing old once we have this grown collection.

**Comment by daschuer** [comment]
That means we need only one set of waveform that is optimized for one hardware. If we have in this case a Filtered and RGB type running smooth it is more than enough. We may even consider to hide the others without the --developer flag when running on MacOS.  

@Swiftb0y: 
> I just tested 2.4 on a MacBook and I don't think its very usable. 

Do you experience the same issues with the 2.3 branch? 

@fwcd: how does this branch, 2.4 and 2.3 compare for you?  

@m0dB 
> Now, there is another reason I wanted to get rid of all QPainter-inside-QOpenGL code: I wanted to do all rendering in a dedicated thread instead of from the main qevent loop, and this doesn't work with QPainter. My initial experiments with this were very promising, so I might pick that up again in the future.

In terms of risk minimization this sounds as a bigger refactoring. Does it makes sense to merge the single thread version first? 

I am curious to hear if this has has an impact to the 2.3 branch?

**Comment by fwcd** [comment]
> And something else I noticed myself: when moving mixxx from a retina to not-retina screen the change in device pixel ratio is not handled, which leads to weird things such as the markers being twice their size.

IIRC this was an issue with the current version already, so perhaps something that should be addressed separately.

> how does this branch, 2.4 and 2.3 compare for you?

This branch feels quite a bit more snappy than 2.3 and 2.4, both under Rosetta and natively (though admittedly I don't have a native 2.3 ARM build to compare to). This is especially noticeable during scratching, where the old implementation would almost always drop down in framerate while this implementation stays at a smooth 60 fps.

**Comment by daschuer** [comment]
@m0dB: When in doubt, rebase form the lowest possible branch. In this case 2.4 (or 2.3 ??). Because than the PR can be merged to any target branch without merging also unrelated files.

**Comment by Swiftb0y** [comment]
> Do you experience the same issues with the 2.3 branch?

No, 2.3.3 from our website is completely fine.

**Comment by daschuer** [comment]
> No, 2.3.3 from our website is completely fine. 

Great, thank you for confirming. So my vote would be to merge this to 2.4 without any threading refactoring. 
@m0dB, what do you think?

File: src/widget/wslidercomposed.cpp [hunk 10]
```diff
@@ -12,30 +12,35 @@
...
+          m_dBarStart(0.0),
+          m_dBarEnd(0.0),
+          m_dBarBgStart(0.0),
+          m_dBarBgEnd(0.0),
+          m_dBarAxisPos(0.0),
+          m_bBarUnipolar(true),
+          m_barColor(nullptr),
+          m_barBgColor(nullptr),
+          m_barPenCap(Qt::FlatCap),
+          m_pSlider(nullptr),
```
Comment (daschuer) [inline src/widget/wslidercomposed.cpp:31]: Remove? This is a QSharedPointer() initialized with null anyway.

File: src/widget/wslidercomposed.cpp [hunk 11]
```diff
@@ -12,30 +12,35 @@
...
+          m_dBarWidth(0.0),
+          m_dBarBgWidth(0.0),
+          m_dBarStart(0.0),
+          m_dBarEnd(0.0),
+          m_dBarBgStart(0.0),
+          m_dBarBgEnd(0.0),
+          m_dBarAxisPos(0.0),
+          m_bBarUnipolar(true),
+          m_barColor(nullptr),
+          m_barBgColor(nullptr),
```
Comment (daschuer) [inline src/widget/wslidercomposed.cpp:29]: This is not a pointer: QColor m_barColor; and QColor m_barBgColor;
I think this initialized the color with black. I think we should remove it for letting it be invalid by default.

File: src/widget/wglwidgetqglwidget.h [hunk 12]
```diff
@@ -0,0 +1,27 @@
...
+
+#ifndef WGLWIDGET_H
+#error "Do not include this file, include wglwidget.h instead"
+#endif
+
+#include <QGLWidget>
+
+///////////////////////////////////////
+// WGLWidget as a subclass of QGLWidget
+///////////////////////////////////////
```
Comment (daschuer) [inline src/widget/wglwidgetqglwidget.h:11]: Yes, we can see it below. Remove?

File: src/widget/wglwidgetqglwidget.cpp [hunk 13]
```diff
@@ -0,0 +1,34 @@
...
+
+bool WGLWidget::shouldRender() const {
+    return true;
+    return isValid() && isVisible() && windowHandle() && windowHandle()->isExposed();
+}
+
+void WGLWidget::makeCurrentIfNeeded() {
+    // TODO m0dB is this really needed? is calling makeCurrent without this 'if' really a problem?
+    // if (context() != QGLContext::currentContext()) {
+    makeCurrent();
```
Comment (daschuer) [inline src/widget/wglwidgetqglwidget.cpp:32]: I have followed the Qt code and it looks like it is save to call it even if we are already current. but it is not a null op. So the original check may speed up the code.

File: src/widget/wglwidgetqglwidget.cpp [hunk 14]
```diff
@@ -0,0 +1,34 @@
...
+    return context()->isValid();
+}
+
+bool WGLWidget::isContextSharing() const {
+    return context()->isSharing();
+}
+
+bool WGLWidget::shouldRender() const {
+    return true;
+    return isValid() && isVisible() && windowHandle() && windowHandle()->isExposed();
```
Comment (daschuer) [inline src/widget/wglwidgetqglwidget.cpp:26]: This code cannot be reached.

File: src/widget/wglwidgetqglwidget.cpp [hunk 15]
```diff
@@ -0,0 +1,34 @@
...
+    setAttribute(Qt::WA_NoSystemBackground);
+    setAttribute(Qt::WA_OpaquePaintEvent);
+    setAutoFillBackground(false);
+    setAutoBufferSwap(false);
+    // Not interested in repaint or update calls, as we draw from the vsync thread
+    setUpdatesEnabled(false);
+}
+
+bool WGLWidget::isContextValid() const {
+    return context()->isValid();
```
Comment (daschuer) [inline src/widget/wglwidgetqglwidget.cpp:17]: is context always not null? Please add a comment if so.

**Review by daschuer — CHANGES_REQUESTED** [review]
Thank you for this PR, I have added some comment.

**Comment by m0dB** [comment]
Thanks @daschuer for all the comments. I will address them as soon as I can find the time, hopefully later this week.

File: src/widget/wglwidgetqglwidget.cpp (hunk 15 above)
Comment (m0dB) [reply src/widget/wglwidgetqglwidget.cpp:17]: Rather than a comment, in such cases I prefer an assert to express that "as a developer I never expect that to be null". Would that work for you too?

**Comment by daschuer** [comment]
With Ubuntu Focal and Qt 5.12 and Intel UHD Graphics the GLSL RGB waveforms are looking like this: 
grafik
All GL waveform types have this backround. 

After recompiling it with `QOPENGL=OFF` everything is back to normal. This is not a real issue, because we can default to OFF under certain conditions. On the other hand it would be nice to remove the old waveforms one day. 

We also have a report of a similar issue with the current waveforms: https://github.com/mixxxdj/mixxx/issues/11164

File: src/widget/wglwidgetqglwidget.cpp (hunk 15 above)
Comment (daschuer) [reply src/widget/wglwidgetqglwidget.cpp:17]: Yes, of cause. However that will only make a crash more descriptive in a developer build. My original question was more, if there is a theoretical condition/exceptional code that this can become null?

**Comment by daschuer** [comment]
Without QOPENGL get a lot of these messages for all waveform types:
``` 
warning [Main] QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined
```
coming from here: 
https://github.com/mixxxdj/mixxx/blob/a38d1e910b441d6e23d0ddc59f4cc393c18a443f/src/waveform/waveformwidgetfactory.cpp#L752

**Comment by daschuer** [comment]
> What can you say about the perfomance under Linux? w/ and w/o QOPENGL

Both versions are equal fast. I have steady 60 fps and no jerking.

**Comment by daschuer** [comment]
I have just noticed that the "RGB (QOpneGL) GL" With QOPENGL=ON is the only GL waveform without a green background. 

The "OpenGL status" field in the waveform preferences is empty. Normally It is 
`4.3 (Mesa Intel(R) UHD Graphics (CML GT2))` in my case.

File: src/waveform/renderers/qopengl/iwaveformrenderer.h [hunk 16]
```diff
@@ -0,0 +1,18 @@
...
+
+#include <QOpenGLFunctions>
+
+/// Interface for QOpenGL-based waveform renderers
+
+namespace qopengl {
+class IWaveformRenderer;
+}
+
+class qopengl::IWaveformRenderer : public QOpenGLFunctions {
```
[the remark this answers is not in the document]
Comment (m0dB) [reply src/waveform/renderers/qopengl/iwaveformrenderer.h:11]: I don't think it's a problem that WaveformRendererAbstract exists (after all, I am reusing many names here, but in the qopengl namespace).  So while exactly the counterpart of ::WaveformRendererAbstract, I think qopengl::WaveformRendererAbstract would work just fine. If you are okay with that I'll make the change.

**Comment by m0dB** [comment]
@daschuer wrote:
> Great, thank you for confirming. So my vote would be to merge this to 2.4 without any threading refactoring. @m0dB, what do you think?

Yes, definitely without the threading refactoring. I would like to see this merged to 2.4 very much. I think the main question is whether to use QOPENGL=ON only on macOS or on all platforms.

File: src/waveform/renderers/qopengl/iwaveformrenderer.h [hunk 17]
```diff
@@ -0,0 +1,18 @@
...
+  public:
+    virtual void initializeGL() {
+    }
+    virtual void resizeGL(int w, int h) {
```
[the remark this answers is not in the document]
Comment (m0dB) [reply src/waveform/renderers/qopengl/iwaveformrenderer.h:22]: I added a comment explain how this class is used (independent of a possible name change). Please let me know if you think it's clear enough.

File: src/widget/wslidercomposed.cpp (hunk 11 above)
Comment (m0dB) [reply src/widget/wslidercomposed.cpp:29]: this is not really part of my changes, it get included because of formatting

File: src/widget/wslidercomposed.cpp (hunk 10 above)
Comment (m0dB) [reply src/widget/wslidercomposed.cpp:31]: idem, this is not really part of my changes, it get included because of formatting

File: src/widget/wglwidgetqglwidget.h (hunk 12 above)
Comment (m0dB) [reply src/widget/wglwidgetqglwidget.h:11]: :-) absolutely!

File: src/widget/wglwidgetqglwidget.cpp (hunk 13 above)
Comment (m0dB) [reply src/widget/wglwidgetqglwidget.cpp:32]: Ok, I will add the check back

File: src/widget/wglwidgetqglwidget.cpp (hunk 14 above)
Comment (m0dB) [reply src/widget/wglwidgetqglwidget.cpp:26]: hm, this one has got me puzzled a bit. the second line seems very reasonable but i must have added the return true at some point to try something out. or maybe it's a merge gone wrong. i will try removing the first line and see if i notice anything strange.

File: src/widget/wglwidgetqglwidget.cpp (hunk 15 above)
Comment (m0dB) [reply src/widget/wglwidgetqglwidget.cpp:17]: from what I understand from the QGLWidget documentation, it will never be null

**Comment by m0dB** [comment]
@daschuer wrote:
> Without QOPENGL get a lot of these messages for all waveform types:
> 
> ```
> warning [Main] QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined
> ```
> 

Very likely because of the return true; in shouldRender() that you spotted in your review. Please test again.

**Comment by m0dB** [comment]
> I have just noticed that the "RGB (QOpneGL) GL" With QOPENGL=ON is the only GL waveform without a green background.

That is interesting. Tomorrow I might ask you to try some things to see if we can solve the issue.

> The "OpenGL status" field in the waveform preferences is empty. Normally It is `4.3 (Mesa Intel(R) UHD Graphics (CML GT2))` in my case.

Right... When QOPENGL is ON, I skip all the GL checking code (in MixxxMainWindow::initialize()) where is set (IIRC because there was not a easy 1:1 mapping of the deprecated functions / classes to new QOpenGL functions / classes. I will revisit this.

**Comment by m0dB** [comment]
@foss- 
> * when increasing / decreasing the waveform size with the handle for that, the entire waveform is glitching in red, this only happens when size is changed and stops as soon as the mouse is not moving to resize, even with the handle still clicked (not a big problem)

This is now solved. There still is some minor artefact when resizing smaller, because the waveforms become smaller immediately but section below (including the drag handle) lags behind a little bit, but it is much better than it was before. Can you please retry?

**Comment by foss-** [comment]
Only now got around to find the time. Testing 2.4-alpha-1417-g057c50b7be (HEAD), Monday, 20 February 2023 01:00:53 CET I can confirm that resizing the waveform is looking much better.

For QOpenGL GLSL: There is a new problem now, but that is of cosmetic nature: when increasing size background is fine. Decreasing size however results in a transparent line showing whatever is behind Mixxx window. This can be another app or in case of my demo the macOS background image:


Certainly not a blocker to this PR.

**Comment by JoergAtGithub** [comment]
Just tested on Windows 11 on a fast laptop with AMD OpenGL drivers. All waveform types look correct and are at least as fluent as before.
But I noticed one minor graphical issue with the QOpenGL waveforms. If I increase the height of the waveforms, the blue position marker remains on the initial height: 
grafik

**Comment by m0dB** [comment]
@JoergAtGithub This was supposedly fixed in 7548526cba propagate resizeGL to widget and renderers, resize markers i    n resizeGL (fixes playhead marker not being resized) , but that submit it prior to when you tested this. Can you please check again and make sure you have this fix?

**Comment by m0dB** [comment]
In the meantime, I have fixed several minor issues and I one "major" issue: Tooltips not being triggered for the QOpenGLWindow based WGLWidgets. I am not sure what causes this, I guess the Qt tooltip mechanism doesn't like windows inside windows. The fix is therefore more of a workaround, I added a mechanism that mimics the way Qt triggers tooltips for these widgets. Anyway, it's a very simple mechanism and it works well on macOS (as far as I can tell identical to the normal tooltips), but please test.

With this there are only three remaining issues that I am aware of:
1) vertical orientation is not implemented for all renderers
2) moving between hdpi and non-hdpi screens messes up scaling of some element
3) minor graphical artifact of wglwidgets "lagging" when resizing (the window or using the splitter)

My thoughts on these:

1) I have never used vertical orientation (does anybody actually this?) but this should be straightforward, so I will fix this.
2) I understand this issue also occurs with the other waveform renderers. But I think it will be easy to fix as well, so I will have a look, but not this weekend as I only have my laptop with me and no non-hdpi screen.
3) This one annoys me. It is hardly noticeable and it certainly isn't a problem, because as soon as you stop resizing the widgets are in place, but it is the one thing where my qopenglwindow wglwidget behaves worse than the legacy qglwidget. But I have no idea how to fix this. Not a show-stopper though.

**Comment by m0dB** [comment]
@foss- that transparency issue should be fixed

**Comment by uklotzde** [comment]
I wanted to test this branch but wasn't able to do so due to the various float/double type inconsistencies that cause lots of warnings/errors. Please fix them.

**Comment by m0dB** [comment]
@uklotzde I'm on it!

**Comment by uklotzde** [comment]
@m0dB Please file a separate PR for more restrictive compiler flags if these differ between platforms.

**Comment by m0dB** [comment]
@uklotzde the ubuntu 22.04 build is green

I don't think it's a matter of more restrictive compiler flags but of differences between gcc and clang. If I set `-Wconversion` globally I get way too many warnings all over the code.

**Comment by JoergAtGithub** [comment]
> @JoergAtGithub Can you please check again and make sure you have this fix?

Indeed, my local branch wasn't updated properly.

But with the latest version I have no OpenGL waveforms available anymore on Windows.  Only the non-GL appear in preferences.

I found out, that this is due to the changes in e9c79374fbf12ae45b5a596296becc0ae0fb29d1 `qopengl equivalent of querying opengl version and capabilities hide instead of delete
`

In the following line, the returned context is NULL and nothing happens afterwards: https://github.com/mixxxdj/mixxx/blob/e9c79374fbf12ae45b5a596296becc0ae0fb29d1/src/waveform/waveformwidgetfactory.cpp#L132

**Comment by m0dB** [comment]
@JoergAtGithub That is unfortunate... Thanks for tracking this down to the change. I am wondering if this fails on Linux too. I will have a look at the code and see if I understand what may cause this to fail, but without access to a Windows machine it might require some trial and error.

If you want to test the rest in the meantime, set these to true:
```
 110           m_openGlAvailable(false),
 112           m_openGLShaderAvailable(false),
```

**Comment by foss-** [comment]
2.4-alpha-1418-g4ca552a27b (HEAD)

**Confirming the transparency issue** when decreasing waveform size **is resolved** when using RGB (QOpenGL) (GLSL).

**Comment by JoergAtGithub** [comment]
I changed the two lines and now it works again. Still very fluent waveforms.

The blue position marker changes it's height now correctly when the waveform area is resized. Only during the resize I see some artifacts. It seems like the blue position marker is resized one frame later than the beat markers.

Than I noticed, that the Slip Mode position indicator in the spinnies is never shown.

**Comment by m0dB** [comment]
@JoergAtGithub Can you please try again with my latest changes? My theory is that on Windows the QOpenGLWindow is not created immediately when the WGLWidget is shown, so when WaveformWidgetFactory tries to use its context to check for OpenGL features it isn't valid yet. I now postpone the initialization until the QOpenGLWindow has been exposed.

I will look into the slip mode position indicator.

**Comment by m0dB** [comment]
The slip mode position indicator is fixed

**Comment by JoergAtGithub** [comment]
I tested the latest commit on Windows11 again and both issues are fixed! Thank you!

**Comment by m0dB** [comment]
Great! Thanks!

**Comment by uklotzde** [comment]
Now compiles without errors on GCC.

No issues so far. But the appearance of the waveforms is more "clunky" and with less detail (or a lower resolution?) compared to the standard RGB  (GLSL) option.

**Comment by ronso0** [comment]
I just tried to build this on Ubuntu 20.04 (I know it's not officially supported for main, but I didn't encounter any issues with other PRs so far) and I hit this cmake error:
```
/src/waveform/renderers/qopengl/waveformrendererendoftrack.h:35:10: error: ‘unique_ptr’ in namespace ‘std’ does not name a template type
   35 |     std::unique_ptr<ControlProxy> m_pEndOfTrackControl;
      |          ^~~~~~~~~~
/src/waveform/renderers/qopengl/waveformrendererendoftrack.h:9:1: note: ‘std::unique_ptr’ is defined in header ‘<memory>’; did you forget to ‘#include <memory>’?
    8 | #include "waveform/renderers/qopengl/waveformshaderrenderer.h"
  +++ |+#include <memory>
``` 
I added that and it builds fine.

**Comment by ronso0** [comment]
> I have just noticed that the "RGB (QOpneGL) GL" With QOPENGL=ON is the only GL waveform without a green background.

Same here, for me it's cyan.

If that matters, openGL status is
4.6 (Compatibility Profile) Mesa 21.2.6 (Mesa Intel(R) UHD Graphics 620 (KBL GT2))

**Comment by atskler** [comment]
> Same here, for me it's cyan.

For me also. Here it is how it looks.
https://www.youtube.com/watch?v=OB3Mlk_lsDQ
Also the cpu usage indicator has same randomly blinking yellow frame - quite annoying.

**Comment by ronso0** [comment]
> Also the cpu usage indicator has same randomly blinking yellow frame - quite annoying

This is the buffer overload indicator (on each flash the counter at the bottom of Preferences > Sound Hardware increases).
That is also implemented in `main`, so if you run that with the same (audio + waveform) configuration does it blink that often as well? (if you don't find a binary to test you'd get the source the same way described [here](url) except you'd go to https://github.com/mixxxdj/mixxx/ and make sure the `main` branch is selected. Backup your data & settings as usual)
If so, it's unrelated to this PR and you may look for [ways to reduce system load](https://github.com/mixxxdj/mixxx/wiki/Adjusting-Audio-Latency).

**Comment by atskler** [comment]
@ronso0 thank you, you are right regarding this. It is the same with the main. Also I would like note here that with same settings v2.3.4 runs fine, but the main's "Buffer Underflow Count" counts +1 in every second, especially at startup when, and generally when none of the decks are loaded.

**Comment by JoergAtGithub** [comment]
@atskler Does the flickering only occur for the old waveform types, or also for the new `RGB (QOpenGL) (GLSL)` waveform type?

**Comment by atskler** [comment]
@JoergAtGithub as you can see on the video I linked before, there is no flickering anymore just a blue background for the GLSL and GL types.

**Comment by JoergAtGithub** [comment]
This means `RGB (QOpenGL) (GLSL)` is not affect and looks fine?

**Comment by ronso0** [comment]
> with same settings v2.3.4 runs fine, but the main's "Buffer Underflow Count" counts +1 in every second, especially at startup when, and generally when none of the decks are loaded.

IMO that's worth reporting at https://github.com/mixxxdj/mixxx/issues so we can take a look.

**Comment by atskler** [comment]
> This means `RGB (QOpenGL) (GLSL)` is not affect and looks fine?

@JoergAtGithub in preferences I have the following "Waveform types":

1) Empty
2) Filtered
3) Filtered (GL)
4) Filtered (GLSL)
5) Filtered - Qt (GL)
6) HSV
7) HSV - Qt (GL)
8) RGB
9) RGB (GL)
10) RGB (GLSL)

The ones with the additional bad blue background are:
3, 4, 5, 7, 9, 10

The others are working correctly.

**Comment by JoergAtGithub** [comment]
Than the CMake option `QOPENGL` was propably `OFF` during yor build and you didn't tested the new code of this PR.

**Comment by atskler** [comment]
@JoergAtGithub then could you please instruct me how to enable it after I downloaded the source code from this page:
https://github.com/m0dB/mixxx/tree/qopengl_renderers

**Comment by uklotzde** [comment]
> @JoergAtGithub then could you please instruct me how to enable it after I downloaded the source code from this page: https://github.com/m0dB/mixxx/tree/qopengl_renderers

Did you actually start the executable from the `build` directory? No special build options required. You should see the new waveform renderer `RGB (QOpenGL) (GLSL)`, otherwise you are running a different version.

**Comment by m0dB** [comment]
Sorry for not being very responsive, and I won't be in the coming days. I agree with @JoergAtGithub , it sounds like you are not running a version build from this branch.

**Comment by atskler** [comment]
Probably I messed up something.
Now the "RGB (QOpenGL) (GLSL)" type is here and works correctly.

**Comment by JoergAtGithub** [comment]
Which steps are necessary to do, before this is ready for merge?

**Comment by ronso0** [comment]
figure out the root cause of the bg paint issue I guess
https://github.com/mixxxdj/mixxx/pull/10989#issuecomment-1457229888

**Comment by JoergAtGithub** [comment]
> figure out the root cause of the bg paint issue I guess
> [#10989 (comment)](https://github.com/mixxxdj/mixxx/pull/10989#issuecomment-1457229888)

AFAIK, the background flickering issue affects also the 2.4 branch: https://github.com/mixxxdj/mixxx/issues/11164
And the new QOpenGL waveform type added in this PR is not affected, only the existing ones.

**Comment by ronso0** [comment]
> AFAIK, the background flickering issue affects also the 2.4 branch: https://github.com/mixxxdj/mixxx/issues/11164

Not here: 2.4 and main are fine, only with this branch the existing waveform types are affected.

**Comment by ronso0** [comment]
> Which steps are necessary to do, before this is ready for merge?

and `#include <memory>`? See https://github.com/mixxxdj/mixxx/pull/10989#issuecomment-1457220405

**Comment by atskler** [comment]
@ronso0 
> Not here: 2.4 and main are fine, only with this branch the existing waveform types are affected.

Which Mesa version is installed on your system?

See: https://github.com/mixxxdj/mixxx/issues/11340#issuecomment-1461642080

**Comment by m0dB** [comment]
> > Which steps are necessary to do, before this is ready for merge?
> 
> and `#include <memory>`? See [#10989 (comment)](https://github.com/mixxxdj/mixxx/pull/10989#issuecomment-1457220405)

done

**Comment by m0dB** [comment]
> > Which steps are necessary to do, before this is ready for merge?
> 
> Considering how big this PR is, I'd prefer a couple more reviews if possible. I'll try to do one tomorrow.

Yes, I am well aware of this. I am thinking if there is a way to make reviewing this more manageable. I will look at the diff with main myself and update the comment at the top of this conversation with some more high level descriptions of the changes, maybe that helps.

**Comment by ronso0** [comment]
> > Not here: 2.4 and main are fine, only with this branch the existing waveform types are affected.
> 
> Which Mesa version is installed on your system?

openGL status says
4.6 (Compatibility Profile) **Mesa 21.2.6** (Mesa Intel(R) UHD Graphics 620 (KBL GT2))

**Comment by atskler** [comment]
> openGL status says
> 4.6 (Compatibility Profile) **Mesa 21.2.6** (Mesa Intel(R) UHD Graphics 620 (KBL GT2))

Then probably this why your are not affected by the problem; the newer Mesa introduces or brings forth the problem.

**Comment by ronso0** [comment]
> Not here: 2.4 and main are fine, **only with this branch the existing waveform types are affected**.

@daschuer is experiencing the same (he gets green, mine is cyan) https://github.com/mixxxdj/mixxx/pull/10989#issuecomment-1428728355

**Comment by m0dB** [comment]
I have added some explanations of the classes and files in this PR which hopefully will help when reviewing: https://github.com/m0dB/mixxx/blob/qopengl_renderers/README-QOpenGL.md

**Comment by m0dB** [comment]
Can you try if calling this from src/waveform/renderers/waveformrenderbackground.cpp  from  WaveformRenderBackground::draw helpers with the cyan / green background ?

```
        glClearColor(static_cast<float>(m_backgroundColor.redF()),
                static_cast<float>(m_backgroundColor.greenF()),
                static_cast<float>(m_backgroundColor.blueF()),
                1.f);
        glClear(GL_COLOR_BUFFER_BIT);
```

**Comment by m0dB** [comment]
I have submitted a potential fix for the background color issue.  6d4e81902fd7f225f70beaee3c2f95ff9a4c7658
Let me know if that helps.

**Comment by ronso0** [comment]
> I have submitted a potential fix for the background color issue. [6d4e819](https://github.com/mixxxdj/mixxx/commit/6d4e81902fd7f225f70beaee3c2f95ff9a4c7658) Let me know if that helps.

Great, that fixes it for me.

Remaning issues here:
* **Filtered - Qt (GL)** is super jerky, framerate ~3.5
* crash when I select **VSyncTest GL**, while VSyncT - Qt (GL) works fine
last logged:
`0x0000555555c499ce in GLVSyncTestRenderer::draw(QPainter*, QPaintEvent*) ()`
full backtrace:
[backtrace-vsynctest-gl.txt](https://github.com/mixxxdj/mixxx/files/11000850/backtrace-vsynctest-gl.txt)

**Comment by m0dB** [comment]
Crash fixed.

**Comment by atskler** [comment]
> I have submitted a potential fix for the background color issue. [6d4e819](https://github.com/mixxxdj/mixxx/commit/6d4e81902fd7f225f70beaee3c2f95ff9a4c7658)
> Let me know if that helps.

With that the flickering went away for me, but the blue background is still there.

**Comment by ronso0** [comment]
> Crash fixed.

I can confirm that, thanks!

**Comment by ronso0** [comment]
> > I have submitted a potential fix for the background color issue. [6d4e819](https://github.com/mixxxdj/mixxx/commit/6d4e81902fd7f225f70beaee3c2f95ff9a4c7658)
> > Let me know if that helps.
> 
> With that the flickering went away for me, but the blue background is still there.

Alright, so you're now 'only' affected by the Mesa issue also present in main.

**Comment by m0dB** [comment]
And to make sure: does the QOPENGL waveform type also have a blue background, or is that the only one looking correct?

**Review by Swiftb0y — CHANGES_REQUESTED** [review]
I didn't get much farther than the first 1/6. I'm posting this now because I don't want to keep you waiting. I'll try to get to the rest next week and I'll try to respond to comments asap during the weekend.

**Comment by atskler** [comment]
> And to make sure: does the QOPENGL waveform type also have a blue background, or is that the only one looking correct?

@m0dB QOPENGL is correct and all the others that are not (GL) and (GLSL) types.
And the "Filtered - Qt (GL)" has the problem that rons0 mentioned here: https://github.com/mixxxdj/mixxx/pull/10989#issuecomment-1473697304 and additionally it makes the complete ui laggy on my system.

**Comment by m0dB** [comment]
There is a crash on shutdown related to the tooltip.

File: src/waveform/renderers/glslwaveformrenderersignal.h [hunk 18]
```diff
@@ -7,8 +7,18 @@
...
-QT_FORWARD_DECLARE_CLASS(QGLFramebufferObject)
-QT_FORWARD_DECLARE_CLASS(QGLShaderProgram)
+#ifdef MIXXX_USE_QOPENGL
+#define GL_FBO_CLASS QOpenGLFramebufferObject
+#define GL_SHADER_CLASS QOpenGLShader
+#define GL_SHADER_PROGRAM_CLASS QOpenGLShaderProgram
+#else
+#define GL_FBO_CLASS QGLFramebufferObject
+#define GL_SHADER_CLASS QGLShader
+#define GL_SHADER_PROGRAM_CLASS QGLShaderProgram
```
[the remark this answers is not in the document]
Comment (m0dB) [reply src/waveform/renderers/glslwaveformrenderersignal.h:17]: I will try this

File: README-QOpenGL.md [hunk 19]
```diff
@@ -0,0 +1,117 @@
+# Mixxx QOpenGL classes and files
+
+This document describes the QOpenGL based WGLWidget that replace the legacy QGLWidget and the GLSL-based waveform widget and renderers and the GLSL-based VU meter and Spinny classes.
```
[the remark this answers is not in the document]
Comment (Swiftb0y) [reply README-QOpenGL.md:3]: I agree that having an overview would be nice, but I think that should be very short and only explain the rough architectural layout. That would preferably be a Readme in the `qopengl` directory. Also feel free to add more context, none of us core devs a very familiar with Graphics APIs in general so I'd be nice to know how the graphics API architecture relates to our architecture, if that makes sense?

File: src/waveform/renderers/qopengl/waveformrenderbackground.cpp [hunk 20]
```diff
@@ -0,0 +1,73 @@
...
+        m_backgroundPixmapPath = context.makeSkinPath(backgroundPixmapPath);
+    }
+    setDirty(true);
+}
+
+void WaveformRenderBackground::renderGL() {
+    if (isDirty()) {
+        // TODO @m0dB
+        //   generateImage();
+    }
```
[the remark this answers is not in the document]
Comment (m0dB) [reply src/waveform/renderers/qopengl/waveformrenderbackground.cpp:33]: the original waveformrenderbackground can draw and image as background. i will remove this from mine, i really doubt anybody is using that.

File: src/waveform/renderers/qopengl/waveformrenderbackground.cpp [hunk 21]
```diff
@@ -0,0 +1,73 @@
...
+
+    // If there is no background image, just fill the painter with the
+    // background color.
+    if (m_backgroundImage.isNull()) {
+        glClearColor(static_cast<float>(m_backgroundColor.redF()),
+                static_cast<float>(m_backgroundColor.greenF()),
+                static_cast<float>(m_backgroundColor.blueF()),
```
[the remark this answers is not in the document]
Comment (m0dB) [reply src/waveform/renderers/qopengl/waveformrenderbackground.cpp:40]: With qt5, these return qreal (with qt6 they changed this to float) and:
 
typedef qreal
Typedef for double unless Qt is configured with the -qreal float option.

(I believe I got double to float narrowing compiler warning here)

File: src/waveform/renderers/qopengl/waveformrenderbeat.cpp [hunk 22]
```diff
@@ -0,0 +1,142 @@
...
+        double beatPosition = it->toEngineSamplePos();
+        double xBeatPoint =
+                m_waveformRenderer->transformSamplePositionInRendererWorld(beatPosition);
+
+        xBeatPoint = std::floor(xBeatPoint);
+
+        // If we don't have enough space, double the size.
+        if (vertexCount >= m_beatLineVertices.size()) {
+            m_beatLineVertices.resize(m_beatLineVertices.size() * 2);
+        }
```
[the remark this answers is not in the document]
Comment (m0dB) [reply src/waveform/renderers/qopengl/waveformrenderbeat.cpp:101]: yes, totally agreed

[the remark this answers is not in the document]
Comment (m0dB) [reply src/waveform/renderers/qopengl/waveformrenderbeat.cpp:101]: reserve, not resize, though

**Comment by m0dB** [comment]
But as @ronso0 says, apparently this blue blackground also occurs on main with the QGLWidget code. Seeing that the qopengl::WaveformBackgroundRenderer doesn't have this problem, I will create a PR that uses the same way to set the background in the legacy WaveformBackgroundRenderer (using glClearColor and glClear, instead of filling the rectangle), so this can get solved in main already.

File: src/waveform/renderers/qopengl/waveformrenderbeat.cpp (hunk 22 above)
[the remark this answers is not in the document]
Comment (m0dB) [reply src/waveform/renderers/qopengl/waveformrenderbeat.cpp]: I will use the same approach for the waveform rgb renderer lines.

File: src/waveform/renderers/qopengl/waveformrenderbackground.cpp (hunk 20 above)
[the remark this answers is not in the document]
Comment (m0dB) [reply src/waveform/renderers/qopengl/waveformrenderbackground.cpp]: done

File: src/waveform/renderers/qopengl/waveformrenderbackground.cpp (hunk 21 above)
[the remark this answers is not in the document]
Comment (Swiftb0y) [reply src/waveform/renderers/qopengl/waveformrenderbackground.cpp]: Ah, sorry yes makes sense. I was looking at the Qt6 docs.

File: src/sources/audiosource.h [hunk 23]
```diff
@@ -311,12 +311,13 @@ class AudioSource : public UrlResource, public virtual /*implements*/ IAudioSour
 
     bool initSampleRateOnce(audio::SampleRate sampleRate);
     bool initSampleRateOnce(SINT sampleRate) {
-        return initSampleRateOnce(audio::SampleRate(sampleRate));
+        return initSampleRateOnce(audio::SampleRate(
+                static_cast<audio::SampleRate::value_t>(sampleRate)));
```
[the remark this answers is not in the document]
Comment (m0dB) [reply src/sources/audiosource.h:316]: applied

File: src/waveform/renderers/glslwaveformrenderersignal.h (hunk 18 above)
[the remark this answers is not in the document]
Comment (m0dB) [reply src/waveform/renderers/glslwaveformrenderersignal.h]: done

File: README-QOpenGL.md (hunk 19 above)
[the remark this answers is not in the document]
Comment (m0dB) [reply README-QOpenGL.md:3]: ok, i will move the text from the docs to the source, and add a readme in qopengl folder, as a final step.

File: src/waveform/renderers/glslwaveformrenderersignal.h [hunk 24]
```diff
@@ -7,8 +7,18 @@
...
+#endif
+
+QT_FORWARD_DECLARE_CLASS(GL_FBO_CLASS)
+QT_FORWARD_DECLARE_CLASS(GL_SHADER_PROGRAM_CLASS)
```
[the remark this answers is not in the document]
Comment (m0dB) [reply src/waveform/renderers/glslwaveformrenderersignal.h:21]: changed;

File: src/waveform/renderers/qopengl/waveformrenderbeat.cpp (hunk 22 above)
[the remark this answers is not in the document]
Comment (m0dB) [reply src/waveform/renderers/qopengl/waveformrenderbeat.cpp]: and colors

**Comment by m0dB** [comment]
I added also an implementation of filtered waveform.

BTW, I am not happy with the "QOpenGL" nomenclature for my waveforms widget (user facing, and, in the source the namespace and folders), . What distinguished my implementation from the other waveform widgets is not so much that they use QOpenGL - after all, the others now also use the QOpenGL classes - but the fact that the entire render stack is using shaders with modern GL, without using qpainter on the opengl window, which is what causes performances issues (as clearly noticable with the Filtered - Qt (GL) waveform), and no fixed pipeline OpenGL. I was thinking "modern GL". As in RGB (modern GL) (GLSL)". Does that make sense?

**Comment by JoergAtGithub** [comment]
The Filtered QOpenGL waveform type always asserts for me in waveformrendererfiltered.cpp L248

DEBUG ASSERT: "reserved[i] == m_lineValues[i].size()" in function void __cdecl qopengl::WaveformRendererFiltered::renderGL(void) 

grafik

File: src/widget/tooltipqopengl.cpp [hunk 25]
```diff
@@ -0,0 +1,46 @@
...
+#include <widget/wglwidget.h>
+
+#include <QStyle>
+#include <QTimer>
+#include <QToolTip>
+
+ToolTipQOpenGL::ToolTipQOpenGL()
+        : m_timer(new QTimer()) {
+    m_timer->setSingleShot(true);
+    connect(m_timer.get(), SIGNAL(timeout()), this, SLOT(onTimeout()));
```
Comment (JoergAtGithub) [inline src/widget/tooltipqopengl.cpp:12]:
```suggestion
    connect(m_timer.get(), SIGNAL(timeout()), this, SLOT(onTimeout()));
```
Please fix this Clazy warning, by using the modern connect syntax without SIGNAL and SLOT macros.

Comment (m0dB) [reply src/widget/tooltipqopengl.cpp:12]: Thanks for reviewing. I will remove the SIGNAL / SLOT macros. I will submit a fix for the debug assert in a moment, it's something silly (I forgot to run with a debug build).

Comment (m0dB) [reply src/widget/tooltipqopengl.cpp:12]: done

**Comment by JoergAtGithub** [comment]
Filtered QOpenGL waveforms work now as expected, without any asserts!

I noticed a difference between GLSL and QOpenGL regarding Stereo visualisation. The old GLSL seems to seperate both channels more clear. Could you have a look, which one is correct:
grafik
grafik

**Comment by m0dB** [comment]
It is not a matter of correct, it is different algorithms. I based my RGB waveform renderer on the algorithm used in src/waveform/renderers/waveformrendererrgb.cpp and src/waveform/renderers/glwaveformrendererrgb.cpp, which calculates the color based on the max low/mid/high of both channels (in c++). The RGB  waveform renderer src/waveform/renderers/glslwaveformrenderersignal.cpp uses a different approach: it stores the entire waveform data in a texture and does the color calculation in the shader, calculating different colors for the left and right channel.

I could have used the original, texture based GLSL RGB waveform renderer in my widget, and I can easily add another widget that uses my shader based renderer stack, but with the texture based GLSL RGB waveform renderer. Because as I said, what differentiates my shader based renderer stack is the use of modern GL with shaders for all layers.

But it is all a bit confusing and as I said before, I think it would make a lot of sense to simplify all this.

File: src/waveform/renderers/qopengl/waveformrendererendoftrack.cpp [hunk 26]
```diff
@@ -0,0 +1,133 @@
...
+}
+)--");
+
+    initShaders(vertexShaderCode, fragmentShaderCode);
+}
+
+void WaveformRendererEndOfTrack::fillWithGradient(QColor color) {
+    const float positionArray[] = {-1.f, -1.f, 1.f, -1.f, -1.f, 1.f, 1.f, 1.f};
+    const float verticalGradientArray[] = {1.f, 1.f, -1.f, -1.f};
+    const float horizontalGradientArray[] = {-1.f, 1.f, -1.f, 1.f};
```
Comment (Swiftb0y) [inline src/waveform/renderers/qopengl/waveformrendererendoftrack.cpp:82]: I think these should be `static constexpr` globals in its own anonymous namespace.

File: src/waveform/renderers/qopengl/waveformrendererfiltered.cpp [hunk 27]
```diff
@@ -0,0 +1,255 @@
...
+void main()
+{
+    gl_FragColor = color;
+}
+)--");
+
+    initShaders(vertexShaderCode, fragmentShaderCode);
+}
+
+inline void WaveformRendererFiltered::addRectangle(
```
Comment (Swiftb0y) [inline src/waveform/renderers/qopengl/waveformrendererfiltered.cpp:48]: why the `inline`?

File: src/waveform/renderers/qopengl/waveformrendererfiltered.cpp [hunk 28]
```diff
@@ -0,0 +1,255 @@
...
+        QVector<float>& lines,
```
Comment (Swiftb0y) [inline src/waveform/renderers/qopengl/waveformrendererfiltered.cpp:49]: mixxx follows the convention to not use mutable references for outparameters. use `gsl::not_null<QVector<float>*>` instead.

File: src/waveform/renderers/qopengl/waveformrendererfiltered.cpp [hunk 29]
```diff
@@ -0,0 +1,255 @@
...
+        return;
+    }
+
+    const float devicePixelRatio = m_waveformRenderer->getDevicePixelRatio();
+    const int length = static_cast<int>(m_waveformRenderer->getLength() * devicePixelRatio);
+
+    // Not multiplying with devicePixelRatio will also work, and on retina
+    // displays 2 pixels will be used to represent each block of samples. This
+    // is also what is done for the beat grid and the markers. const int n =
+    // static_cast<int>(static_cast<float>(m_waveformRenderer->getLength()));
```
Comment (Swiftb0y) [inline src/waveform/renderers/qopengl/waveformrendererfiltered.cpp:100]: Is this Apple-specific? Otherwise I'd prefer High-DPI-Display over retina. Also, there seems to be a stray statement at the end of the comment.

File: src/waveform/renderers/qopengl/waveformrendererfiltered.cpp [hunk 30]
```diff
@@ -0,0 +1,255 @@
...
+
+    QMatrix4x4 matrix;
+    matrix.ortho(QRectF(0.0,
+            0.0,
+            m_waveformRenderer->getWidth() * devicePixelRatio,
+            m_waveformRenderer->getHeight() * devicePixelRatio));
+    if (m_waveformRenderer->getOrientation() == Qt::Vertical) {
+        matrix.rotate(90.f, 0.0f, 0.0f, 1.0f);
+        matrix.translate(0.f, -m_waveformRenderer->getWidth() * devicePixelRatio, 0.f);
+    }
```
Comment (Swiftb0y) [inline src/waveform/renderers/qopengl/waveformrendererfiltered.cpp:222]: second time occuring. I think this deserves a function somewhere in the more abstract base-classes.

File: src/waveform/renderers/qopengl/waveformrendererfiltered.cpp [hunk 31]
```diff
@@ -0,0 +1,255 @@
...
+
+        visualIndexStart = std::max(visualIndexStart, 0);
+        visualIndexStop = std::min(visualIndexStop, dataSize);
+
+        // 3 bands, 2 channels
+        float max[3][2]{};
+
+        for (int i = visualIndexStart; i < visualIndexStop; i += 2) {
+            const WaveformData& waveformData = data[i];
+            const WaveformData& waveformDataNext = data[i + 1];
```
Comment (Swiftb0y) [inline src/waveform/renderers/qopengl/waveformrendererfiltered.cpp:179]: I think this makes the following code more easier to understand.
```suggestion
            const WaveformData& waveFormSampleRightChannel = data[i];
            const WaveformData& waveFormSampleLeftChannel = data[i + 1];
```

File: src/waveform/renderers/qopengl/waveformrendererfiltered.cpp [hunk 32]
```diff
@@ -0,0 +1,255 @@
...
+    // Not multiplying with devicePixelRatio will also work, and on retina
+    // displays 2 pixels will be used to represent each block of samples. This
+    // is also what is done for the beat grid and the markers. const int n =
+    // static_cast<int>(static_cast<float>(m_waveformRenderer->getLength()));
+
+    const double firstVisualIndex = m_waveformRenderer->getFirstDisplayedPosition() * dataSize;
+    const double lastVisualIndex = m_waveformRenderer->getLastDisplayedPosition() * dataSize;
+
+    // Represents the # of waveform data points per horizontal pixel.
+    const double gain = (lastVisualIndex - firstVisualIndex) / static_cast<double>(length);
```
Comment (Swiftb0y) [inline src/waveform/renderers/qopengl/waveformrendererfiltered.cpp:106]: I don't understand how this calculation is supposed to work. How does essentially the width of the waveform, correspond to the height?

**Review by Swiftb0y — COMMENTED** [review]
Thank you, another round of comments, I'm still only through the first 20%...

**Comment by daschuer** [comment]
Just testing with Tango Skin. All waveform have a background and are running smooth without dropped frames. It is running even smoother than without this PR :-)
The V-sync test plays perfect. 

There is only an issue with the "Filtered - Qt (GL)" type. It is running slooooow with 3.5 f/s instead of the desired 60 f/s The "Simple  - Qt (GL)" and "RGB  - Qt (GL)" are running smooth @ 60 f/s  with some dropped frames.  
 
Even though I have doubled the same track in two decks, I see an offset between both waveforms of 20 ms (one audio Buffer Size) after the waveform type. This goes away after changing to another type and back to the original. The audio is not affected.

File: src/widget/wglwidgetqopengl.cpp [hunk 33]
```diff
@@ -0,0 +1,96 @@
...
+}
+
+WGLWidget::~WGLWidget() {
+    ToolTipQOpenGL::singleton().stop(this);
+    if (m_pOpenGLWindow) {
+        m_pOpenGLWindow->widgetDestroyed();
+    }
+}
+
+QPaintDevice* WGLWidget::paintDevice() {
```
Comment (daschuer) [inline src/widget/wglwidgetqopengl.cpp:19]: Unsure here, the main issue is that this is not only a getter like the function name implies.  
Maybe you have an idea for improvement? 

The function describes the usage not what it does.  
Maybe prepareWindowForPainting() or something. 
Since this is also no abstract function we can return the OpenGLWindow*

File: src/widget/wglwidgetqopengl.h [hunk 34]
```diff
@@ -0,0 +1,48 @@
...
+    void swapBuffers();
+    void resizeEvent(QResizeEvent* event) override;
+
+    void showEvent(QShowEvent* event) override;
+
+    // called (indirectly) by WaveformWidgetFactory
+    virtual void renderGL();
+    // called by OpenGLWindow
+    virtual void resizeGL(int w, int h);
+    virtual void handleEventFromWindow(QEvent* ev);
```
Comment (daschuer) [inline src/widget/wglwidgetqopengl.h:42]: The original event(QEvent* ev) is already virtual. 
This function implements an extra entry point for events. User of the base class will bypass the wrapper. 
Is this desired? Can you drop a comment why?

**Review by daschuer — CHANGES_REQUESTED** [review]
I have added some comments. Thank you very much for this bis step ahead.

**Comment by m0dB** [comment]
Hey, just to let you know I haven't forgotten about this, but I don't have much free time at the moment.

**Comment by Swiftb0y** [comment]
No worries, take your time. :+1:

**Comment by JoergAtGithub** [comment]
This PR seems to solve https://github.com/mixxxdj/mixxx/issues/11450

**Comment by m0dB** [comment]
> This PR seems to solve #11450

That was the idea :-)

File: src/skin/legacy/legacyskinparser.cpp [hunk 35]
```diff
@@ -1313,8 +1313,13 @@ QWidget* LegacySkinParser::parseSpinny(const QDomElement& node) {
     connect(pWaveformWidgetFactory,
             &WaveformWidgetFactory::renderSpinnies,
             pSpinny,
-            &WSpinny::render);
-    connect(pWaveformWidgetFactory, &WaveformWidgetFactory::swapSpinnies, pSpinny, &WSpinny::swap);
+            &WSpinny::render,
+            Qt::DirectConnection);
```
[the remark this answers is not in the document]
Comment (m0dB) [reply src/skin/legacy/legacyskinparser.cpp:1317]: Thanks for spotting this, I believe this is a left-over from some experiments I did with acting on the frameSwapped signal. I'll revert it, and the same for the VuMeter connections in waveformwidgetfactory.cpp

[the remark this answers is not in the document]
Comment (m0dB) [reply src/skin/legacy/legacyskinparser.cpp:1317]: (Interesting though that apparently it doesn't case any issues)

File: src/widget/wglwidgetqopengl.cpp (hunk 33 above)
Comment (m0dB) [reply src/widget/wglwidgetqopengl.cpp:19]: I prefer to keep the name, but to add another function, clearPaintDevice(), and call this explicitly where relevant. Would that work for you?

IIRC this was a stop-gap solution to solve the legacy renderers showing green background on certain hardware.

Comment (daschuer) [reply src/widget/wglwidgetqopengl.cpp:19]: Yes. I have no strong opinion here. I have been just stumbled at this point and wrote that comment for thinking.

File: src/widget/wglwidgetqopengl.h (hunk 34 above)
Comment (m0dB) [reply src/widget/wglwidgetqopengl.h:42]: If I understand you correct, you are proposing to simply call event(ev) from the OpenGLWindow. Sure, that will work. I will make the change.

Comment (daschuer) [reply src/widget/wglwidgetqopengl.h:42]: Thank you.

Comment (m0dB) [reply src/widget/wglwidgetqopengl.h:42]: Ok, this is not possible. The problem is that event(QEvent* ev) is a protected member of QWidget, so OpenGLWindow cannot call it.

Comment (m0dB) [reply src/widget/wglwidgetqopengl.h:49]: Done. Please confirm this what you meant.

File: src/widget/wglwidgetqopengl.cpp (hunk 33 above)
Comment (m0dB) [reply src/widget/wglwidgetqopengl.cpp:19]: IIRC this was to fix the issue with the legacy renderers drawing with a green background on certain hardware.

I prefer to leave the function called paintDevice() (and I prefer to keep the return type QPaintDevice* for clarify) and add an explicit additional clearPaintDevice() call where needed.

File: src/waveform/renderers/qopengl/waveformrenderbackground.h [hunk 36]
```diff
@@ -0,0 +1,23 @@
...
+#include <QColor>
+#include <QImage>
+
+#include "util/class.h"
+#include "waveform/renderers/qopengl/waveformrenderer.h"
+
+namespace qopengl {
+class WaveformRenderBackground;
+}
+class qopengl::WaveformRenderBackground : public qopengl::WaveformRenderer {
```
[the remark this answers is not in the document]
Comment (m0dB) [reply src/waveform/renderers/qopengl/waveformrenderbackground.h:12]: final makes sense. I will make the change.

File: src/waveform/renderers/qopengl/waveformrenderbeat.h [hunk 37]
```diff
@@ -0,0 +1,29 @@
...
+    explicit WaveformRenderBeat(WaveformWidgetRenderer* waveformWidget);
+    ~WaveformRenderBeat() override;
+
+    void setup(const QDomNode& node, const SkinContext& context) override;
+    void renderGL() override;
+    void initializeGL() override;
+
+  private:
+    QColor m_beatColor;
+    QVector<float> m_beatLineVertices;
```
[the remark this answers is not in the document]
Comment (m0dB) [reply src/waveform/renderers/qopengl/waveformrenderbeat.h:26]: It does. I will change it.

File: src/waveform/renderers/qopengl/waveformrenderbeat.cpp [hunk 38]
```diff
@@ -0,0 +1,146 @@
...
+    }
+
+    m_shaderProgram.enableAttributeArray(vertexLocation);
+    m_shaderProgram.setAttributeArray(
+            vertexLocation, GL_FLOAT, m_beatLineVertices.constData(), 2);
+
+    m_shaderProgram.setUniformValue(matrixLocation, matrix);
+    m_shaderProgram.setUniformValue(colorLocation, m_beatColor);
+
+    glDrawArrays(GL_TRIANGLES, 0, m_beatLineVertices.size() / 2);
```
[the remark this answers is not in the document]
Comment (m0dB) [reply src/waveform/renderers/qopengl/waveformrenderbeat.cpp:145]: the array is used in glDrawArrays and after that it will not be accessed anymore.

File: src/waveform/renderers/qopengl/waveformrenderer.h [hunk 39]
```diff
@@ -0,0 +1,25 @@
...
+  public:
+    explicit WaveformRenderer(WaveformWidgetRenderer* widget);
+    ~WaveformRenderer();
+
+    void draw(QPainter* painter, QPaintEvent* event) override {
+    }
+
+    IWaveformRenderer* qopenglWaveformRenderer() override {
+        return this;
+    }
```
[the remark this answers is not in the document]
Comment (m0dB) [reply src/waveform/renderers/qopengl/waveformrenderer.h:24]: I added comments explaining the empty implementation of draw and the use of qopenglWaveformRenderer(), and I made both final.

File: src/waveform/renderers/qopengl/waveformrendererendoftrack.cpp [hunk 40]
```diff
@@ -0,0 +1,133 @@
...
+}
+
+void WaveformRendererEndOfTrack::setup(const QDomNode& node, const SkinContext& context) {
+    m_color = QColor(200, 25, 20);
+    const QString endOfTrackColorName = context.selectString(node, "EndOfTrackColor");
+    if (!endOfTrackColorName.isNull()) {
+        m_color.setNamedColor(endOfTrackColorName);
+        m_color = WSkinColor::getCorrectColor(m_color);
+    }
+    // m_pen = QPen(QBrush(m_color), 2.5 * scaleFactor());
```
[the remark this answers is not in the document]
Comment (m0dB) [reply src/waveform/renderers/qopengl/waveformrendererendoftrack.cpp:52]: done

File: src/waveform/renderers/qopengl/waveformrendererendoftrack.cpp (hunk 26 above)
Comment (m0dB) [reply src/waveform/renderers/qopengl/waveformrendererendoftrack.cpp]: Agreed. Done.

File: src/waveform/renderers/qopengl/waveformrendererfiltered.cpp (hunk 27 above)
Comment (m0dB) [reply src/waveform/renderers/qopengl/waveformrendererfiltered.cpp:48]: no idea. removed.

File: src/waveform/renderers/qopengl/waveformrendererfiltered.cpp (hunk 28 above)
Comment (m0dB) [reply src/waveform/renderers/qopengl/waveformrendererfiltered.cpp]: I changed the API slightly to index a member var instead.

File: src/waveform/renderers/qopengl/waveformrendererfiltered.cpp (hunk 29 above)
Comment (m0dB) [reply src/waveform/renderers/qopengl/waveformrendererfiltered.cpp:102]: improved comment.

File: src/waveform/renderers/qopengl/waveformrendererfiltered.cpp (hunk 31 above)
Comment (m0dB) [reply src/waveform/renderers/qopengl/waveformrendererfiltered.cpp:182]: Sure. this is the terminology used in the legacy renderers, but I agree this is much more clear.

So I started doing this but than I realised I could get rid of a lot of the code duplication for the channels by using arrays with 2 elements and for (int chn=0;chn<2;chn++).

File: src/waveform/renderers/qopengl/waveformrendererfiltered.cpp (hunk 32 above)
Comment (m0dB) [reply src/waveform/renderers/qopengl/waveformrendererfiltered.cpp:108]: height is not part of this. the word gain (also copy-paste from legacy renderers) is definitely confusing.
how about delta ? or visualIndexIncrementPerPixel

**Comment by m0dB** [comment]
@Swiftb0y you made some comments about code duplication, but I can't find them. Anyway, I have done a lot of additional cleanup and reduced a lot of code duplication in the code under waveforms/renderers/qopengl/ , which I think are in line with your comments.

I believe that with that I have addressed all review comments.

I would appreciate if you can retest on windows and linux, to make sure I didn't break anything on the way.

Something I still want to do is rethink the nomenclature for the waveform renderers, the express more clearly that what makes them different (and faster) is the fact that the entire render stack is done purely with modern GL.

After that, I think I can rebase (on main? on 2.4?) and request the PR to be applied.

File: src/waveform/renderers/glslwaveformrenderersignal.h (hunk 24 above)
[the remark this answers is not in the document]
Comment (m0dB) [reply src/waveform/renderers/glslwaveformrenderersignal.h]: done

File: src/waveform/renderers/qopengl/waveformrenderbeat.h (hunk 37 above)
[the remark this answers is not in the document]
Comment (m0dB) [reply src/waveform/renderers/qopengl/waveformrenderbeat.h]: done

File: src/waveform/renderers/qopengl/waveformrendererfiltered.cpp (hunk 30 above)
Comment (m0dB) [reply src/waveform/renderers/qopengl/waveformrendererfiltered.cpp]: i put it in a helper function, as there is no suitable common base class for this

File: src/waveform/renderers/qopengl/waveformrendererfiltered.cpp (hunk 31 above)
Comment (m0dB) [reply src/waveform/renderers/qopengl/waveformrendererfiltered.cpp]: which is done

**Review by Swiftb0y — COMMENTED** [review]
Did a quick test on Fedora, I'm dropping frames regularly but that is not specific to the QOpenGL shader versions.

Unfortunately I have a lot on my TODO list right now so I didn't get very far with this review either. I hope to add some more comments soon. Thank you for all your hard work and patience so far.

**Comment by Swiftb0y** [comment]
> Something I still want to do is rethink the nomenclature for the waveform renderers, the express more clearly that what makes them different (and faster) is the fact that the entire render stack is done purely with modern GL.

what do you have in mind? Where exactly would you like to change it? In the user-facing descriptions or more in terms of the namespace name and so forth?

File: src/waveform/renderers/qopengl/waveformrenderer.h [hunk 41]
```diff
@@ -0,0 +1,41 @@
...
+    ~WaveformRenderer();
+
+    void draw(QPainter* painter, QPaintEvent* event) override final {
+        // Pure virtual from WaveformRendererAbstract.
+        // Renderers that use QPainter functionality implement
+        // this. But as all classes derived from
+        // qopengl::WaveformRenderer will only use openGL
+        // functions (combining QPainter and QOpenGLWindow
+        // has bad performance), we leave this empty. Should
+        // never be called.
```
[the remark this answers is not in the document]
Comment (m0dB) [reply src/waveform/renderers/qopengl/waveformrenderer.h:27]: done

File: src/waveform/renderers/qopengl/colordata.h [hunk 42]
```diff
@@ -0,0 +1,20 @@
+#pragma once
+
+#include <QVector3D>
+#include <QVector>
+
+namespace qopengl {
+class ColorData;
+}
+
+class qopengl::ColorData : public QVector<QVector3D> {
```
[the remark this answers is not in the document]
Comment (m0dB) [reply src/waveform/renderers/qopengl/colordata.h:10]: i prefer it is a method, but i will use incapsulation instead of inheritance

File: src/waveform/renderers/qopengl/calculatematrix.cpp [hunk 43]
```diff
@@ -0,0 +1,19 @@
+#include "waveform/renderers/qopengl/calculatematrix.h"
+
+#include "waveform/renderers/waveformwidgetrenderer.h"
+
+QMatrix4x4 calculateMatrix(WaveformWidgetRenderer* const waveformRenderer,
```
[the remark this answers is not in the document]
Comment (m0dB) [reply src/waveform/renderers/qopengl/calculatematrix.cpp:5]: I see what you mean, but it's not just orientation, but also size...  how about ```deriveMatrixFromWidgetGeometry(...)``` ? (one can argue geometry includes both size and orientation). a bit large maybe. ```matrixForWidgetGeometry(...)``` maybe? With a comment "calculate the orthogonal projection matrix based on the widget's size and orientation"

File: src/waveform/renderers/qopengl/shaders/shader.h [hunk 44]
```diff
@@ -0,0 +1,16 @@
...
+class Shader;
+}
+
+class qopengl::Shader : public QOpenGLShaderProgram {
+  public:
+    Shader();
+    ~Shader();
+
+  protected:
+    void load(const QString& fragmentShader, const QString& vertexShader);
```
[the remark this answers is not in the document]
Comment (m0dB) [reply src/waveform/renderers/qopengl/shaders/shader.h:15]: it's not polymorphic (no virtuals). all derived shaders use the load function of the base class, that's all.

[the remark this answers is not in the document]
Comment (m0dB) [reply src/waveform/renderers/qopengl/shaders/shader.h:15]: shouldn't we be using modern c++ delete instead of this macro? it's a clang-tidy modernization:

https://clang.llvm.org/extra/clang-tidy/checks/modernize/replace-disallow-copy-and-assign-macro.html

File: src/waveform/renderers/qopengl/calculatematrix.cpp (hunk 43 above)
[the remark this answers is not in the document]
Comment (Swiftb0y) [reply src/waveform/renderers/qopengl/calculatematrix.cpp:5]: Well, I count size as part of the general transform matrix, but so is rotation and thus orientation. So my name isn't that great either. `matrixForWidgetGeometry` sounds good.

File: src/waveform/renderers/qopengl/colordata.h (hunk 42 above)
[the remark this answers is not in the document]
Comment (Swiftb0y) [reply src/waveform/renderers/qopengl/colordata.h]: > i prefer it is a method, but i will use incapsulation instead of inheritance

I agree that it looks nicer as a method, but that doesn't justify using inheritance. Maybe it'll be just as nice in a future version of C++ when we finally get UFCS.

File: src/waveform/renderers/qopengl/shaders/shader.h (hunk 44 above)
[the remark this answers is not in the document]
Comment (Swiftb0y) [reply src/waveform/renderers/qopengl/shaders/shader.h:15]: Yes, explicitly doing using `= delete` is better. The `DISALLOW_COPY_AND_ASSIGN` does exactly that anyways.

If you're not using polymorpism anyways, then I see little reason to use inheritance here as well. I personally consider using inheritance for the sole reason of code reuse to be generally an antipattern. I assume you disagree?

**Comment by m0dB** [comment]
> what do you have in mind? Where exactly would you like to change it? In the user-facing descriptions or more in terms of the namespace name and so forth?

In the user-facing descriptions (though while at it, I might as well adjust the namespace). I was thinking

(Pure GL)

And the documentation could contain a sentence along the lines of: "For improved performance, the 'Pure GL' waveform types use modern GL for all layers of the waveform display: The waveform itself, but also the additional layers such as beat markers, ranges, cue points, etcetera."

But this raises an important question. If the performance is better, why do we need all the other waveform types? I seems to me that the variety of waveform widgets is a) confusing for the user and b) doesn't offer any advantage and c) makes the code much more difficult to follow and to maintain.

Personally I would do a huge cleanup by:
- Removing all legacy waveform widgets. There are some that I haven't ported to pure qopengl, but I can do that quickly (e.g. the simple waveform and glsl ones that read the waveform data from a texture).
- Removing all QGL... code
- Remove the non-GL implementations of wspinny and wvumeter.

(Note that these cleanups are not mutually exclusive)

Once that is done it will be much easier to do some much needed refactoring under src/waveform: the current nomenclature is very confusing (the concept waveformrenderer being used for both the waveform widget with multiple layers, and for the renderer of each of the layers), and WaveformWidgetFactory does a lot more that what it's name suggests. It will also make it easier to do some additional improvements I have been experimenting with, such as doing all the rendering of waveforms, vumeters and spinnies in a separate thread.

I understand that such a radical cleanup would require a large consensus. And probably it should be done in a new PR once this one has been integrated. But I would like to hear your thoughts.

File: src/waveform/renderers/qopengl/colordata.h (hunk 42 above)
[the remark this answers is not in the document]
Comment (m0dB) [reply src/waveform/renderers/qopengl/colordata.h]: done

File: src/waveform/renderers/qopengl/shaders/shader.h (hunk 44 above)
[the remark this answers is not in the document]
Comment (m0dB) [reply src/waveform/renderers/qopengl/shaders/shader.h:17]: I extend QOpenGLShaderProgram with a convenience function, ```load(..)```. If instead I inherit all concrete shader classes from QOpenGLShaderProgram directly, I would either have to duplicate this ```load(..)``` function in all of them, or I would need to make it a global function, where I pass the shader's this as argument. Which might work in this case, if it only uses public members of QOpenGLShaderProgram, but who knows. And the first thing I think when I see a function with this as argument is: why isn't this a method :-)

But maybe I am missing something!

File: src/waveform/renderers/qopengl/colordata.h [hunk 45]
```diff
@@ -0,0 +1,20 @@
...
+  public:
+    void addForRectangle(float r, float g, float b) {
+        push_back({r, g, b});
+        push_back({r, g, b});
+        push_back({r, g, b});
+        push_back({r, g, b});
+        push_back({r, g, b});
+        push_back({r, g, b});
+    }
```
[the remark this answers is not in the document]
Comment (m0dB) [reply src/waveform/renderers/qopengl/colordata.h]: It add the color attribute for all 6 vertices that are used to draw a line.

File: src/waveform/renderers/qopengl/colordata.h (hunk 42 above)
[the remark this answers is not in the document]
Comment (m0dB) [reply src/waveform/renderers/qopengl/colordata.h]: Have you seen how I replaced the inheritance with encapsulation? Do you like that better?

File: src/waveform/renderers/qopengl/calculatematrix.cpp (hunk 43 above)
[the remark this answers is not in the document]
Comment (m0dB) [reply src/waveform/renderers/qopengl/calculatematrix.cpp]: changed

**Comment by uklotzde** [comment]
AutoMoc: /.../mixxx/src/util/widgetrendertimer.h:0: Note: No relevant classes found. No output generated.

**Comment by m0dB** [comment]
@uklotzde I don't think this is due to my changes, but because you have stuff from building another branch in your build directory. Could that be?

**Comment by uklotzde** [comment]
Mesa 23
OpenGL status: 4.6 (Compatibility Profile) Mesa 23.0.1 (Mesa Intel(R) HD Graphics 530 (SKL GT2))
`-platform xcb`

image

image

Unfortunately, things seem to be falling apart with Qt 5. That is what I was afraid of.

**Comment by uklotzde** [comment]
> @uklotzde I don't think this is due to my changes, but because you have stuff from building another branch in your build directory. Could that be?

`main` + custom code. Warning appeared after merging your branch.

**Comment by m0dB** [comment]
Ah indeed, I also have the widgetrendertimer.h:0: Note: No relevant classes found warning. I will have a look.

About the screenshot: I am not sure what I am looking at. Can you give more details. Note that people are running this branch successfully (and particularly on macOS the performance is much better).

**Comment by uklotzde** [comment]
> About the screenshot: I am not sure what I am looking at.

I have added more context:

> See also: #11164. I was hoping that this version would fix those issues. Apparently not.

**Comment by m0dB** [comment]
@uklotzde so do I understand correctly that this is not specific for my branch but that it also happens with the QGLWidget based waveforms? (2.3, 2.4, main) ?
 
Have you tried different waveform types? Any difference? Do I understand correctly that when loading the waveform initially it looks correct, but when starting playback the background color changes?

**Comment by m0dB** [comment]
@uklotzde I will prepare a branch of this branch that builds with Qt 6. It would be interesting to see if with Qt 6 you get the issues.

**Comment by uklotzde** [comment]
> @uklotzde I will prepare a branch of this branch that builds with Qt 6. It would be interesting to see if with Qt 6 you get the issues.

With QOpenGL the waveforms are completely unusable as my screenshot shows. Separated into weird RGB areas.

**Comment by m0dB** [comment]
> With QOpenGL the waveforms are completely unusable as my screenshot shows. Separated into weird RGB areas.

That is the Filtered (QOpenGL) type, right? That is supposed to look like this.

What about the RGB  (QOpenGL) type or the RGB-L/R (QOpenGL) type or the Simple (QOpenGL) type ?

**Comment by m0dB** [comment]
@uklotzde Could you try building this branch https://github.com/m0dB/mixxx/tree/qopengl_renderers_qt6 

On macOS I am using the same buildenv as main, but point to the official Qt 6 install dir:

```
cmake -DCMAKE_PREFIX_PATH=~/Qt6/6.5.0/macos/ -DQT6=ON -DQTKEYCHAIN=OFF -DCMAKE_BUILD_TYPE=Release ..
```

Not sure what the steps are on Linux.

On macOS everything seems to work fine, except for the splitter between waveforms and mixer. But to test if it solved the rendering issues with the Intel 530 that should not matter.

**Comment by atskler** [comment]
> Mesa 23 OpenGL status: 4.6 (Compatibility Profile) Mesa 23.0.1 (Mesa Intel(R) HD Graphics 530 (SKL GT2)) `-platform xcb`
> 
> image
> 
> image
> 
> Unfortunately, things seem to be falling apart with Qt 5. That is what I was afraid of.
> 
> See also: #11164. I was hoping that this version would fix those issues. Apparently not.

On the current openSUSE Tumbleweed:
OpenGL version string: 3.3 (Compatibility Profile) Mesa 23.0.1

mixxx-20230416-Screenshot_20230416_022105

**Comment by atskler** [comment]
I built this:
https://github.com/m0dB/mixxx/tree/qopengl_renderers

Download: 2023-04-16, 0:59:31 CEST

**Comment by atskler** [comment]
> See also: #11164. I was hoping that this version would fix those issues. Apparently not.

Also there is no flickering and background issue for me with Filtered (QOpenGL) (GLSL).

**Comment by uklotzde** [comment]
I can confirm that the flickering is gone in the Qt 5 build.

The filtering type has this weird RGB color separation (see above) while all other waveform types are just yellow:

image

**Comment by m0dB** [comment]
Thanks @atskler . Do the RGB (QOpenGL) and RGB-LR (QOpenGL) also look correct? Is that with the same hardware as @uklotzde ?

**Comment by m0dB** [comment]
@uklotzde quite interesting. As said, the "weird RGB color separation" is how the filtered type is supposed to look (don't ask me, I just used the existing algorithm). If you mute all bands but one (so, only show either L M or H band), does the yellow change to R G or B ?

**Comment by uklotzde** [comment]
Mixxx is usable again with this PR after building with Clang 16.0 instead of GCC 13, see #11483.

Unfortunately I experienced a crashed when switching from RGB (L/R) to Filtered:

```
Process 67525 stopped
* thread #1, name = 'mixxx', stop reason = signal SIGSEGV: invalid address (fault address: 0xf5f5f5f9)
    frame #0: 0x0000000000853448 mixxx`qopengl::WaveformRendererFiltered::renderGL() [inlined] std::__atomic_base<int>::operator--(this=0x00000000f5f5f5f9) at atomic_base.h:410:16
   407 	
   408 	      __int_type
   409 	      operator--() noexcept
-> 410 	      { return __atomic_sub_fetch(&_M_i, 1, int(memory_order_seq_cst)); }
   411 	
   412 	      __int_type
   413 	      operator--() volatile noexcept
(lldb) bt
* thread #1, name = 'mixxx', stop reason = signal SIGSEGV: invalid address (fault address: 0xf5f5f5f9)
  * frame #0: 0x0000000000853448 mixxx`qopengl::WaveformRendererFiltered::renderGL() [inlined] std::__atomic_base<int>::operator--(this=0x00000000f5f5f5f9) at atomic_base.h:410:16
    frame #1: 0x0000000000853448 mixxx`qopengl::WaveformRendererFiltered::renderGL() [inlined] bool QAtomicOps<int>::deref<int>(_q_value=0x00000000f5f5f5f9) at qatomic_cxx11.h:289:16
    frame #2: 0x0000000000853448 mixxx`qopengl::WaveformRendererFiltered::renderGL() [inlined] QBasicAtomicInteger<int>::deref(this=0x00000000f5f5f5f9) at qbasicatomic.h:119:36
    frame #3: 0x0000000000853448 mixxx`qopengl::WaveformRendererFiltered::renderGL() [inlined] QSharedPointer<Waveform const>::deref(dd=0x00000000f5f5f5f5) at qsharedpointer_impl.h:457:28
    frame #4: 0x0000000000853443 mixxx`qopengl::WaveformRendererFiltered::renderGL() [inlined] QSharedPointer<Waveform const>::deref(this=0x00007fffffffce20) at qsharedpointer_impl.h:453:7
    frame #5: 0x000000000085343b mixxx`qopengl::WaveformRendererFiltered::renderGL() [inlined] QSharedPointer<Waveform const>::~QSharedPointer(this=0x00007fffffffce20) at qsharedpointer_impl.h:310:25
    frame #6: 0x000000000085343b mixxx`qopengl::WaveformRendererFiltered::renderGL(this=0x000000003f193200) at waveformrendererfiltered.cpp:200:1
    frame #7: 0x00000000005a0207 mixxx`qopengl::WaveformWidget::renderGL(this=<unavailable>) at waveformwidget.cpp:36:60
    frame #8: 0x00000000005a0170 mixxx`non-virtual thunk to qopengl::WaveformWidget::render() [inlined] qopengl::WaveformWidget::render(this=0x0000000041b3fd70) at waveformwidget.cpp:23:5
    frame #9: 0x00000000005a015b mixxx`non-virtual thunk to qopengl::WaveformWidget::render() at waveformwidget.cpp:0
    frame #10: 0x000000000058dbcb mixxx`WaveformWidgetFactory::render(this=0x0000000003d937a0) at waveformwidgetfactory.cpp:725:34
```

**Comment by uklotzde** [comment]
> @uklotzde quite interesting. As said, the "weird RGB color separation" is how the filtered type is supposed to look (don't ask me, I just used the existing algorithm).

Caused by #11483, not this branch.

**Comment by uklotzde** [comment]
Violated debug assertion, appeared repeatedly ~10x when continuing execution, at least no crash:

```
critical [Main] DEBUG ASSERT: "reserved == m_vertices.size()" in function virtual void qopengl::WaveformRenderBeat::renderGL() at /home/uk/volumes/Build/cpp/mixxx/src/waveform/renderers/qopengl/waveformrenderbeat.cpp:102
Process 139353 stopped
* thread #1, name = 'mixxx', stop reason = signal SIGINT

please file a bug report against lldb reporting this failure log, and as many details as possible
* thread #1, name = 'mixxx', stop reason = signal SIGINT
  * frame #0: 0x00007ffff2aafb94 libc.so.6`__pthread_kill_implementation + 276
    frame #1: 0x00007ffff2a5eaee libc.so.6`raise + 30
    frame #2: 0x0000000000553368 mixxx`mixxx::(anonymous namespace)::handleMessage(type=QtCriticalMsg, context=0x00007fffffffcbe8, input=0x00007fffffffca98) at logging.cpp:346:13
    frame #3: 0x00007ffff30ecb88 libQt5Core.so.5`qt_message_print(QtMsgType, QMessageLogContext const&, QString const&) + 280
    frame #4: 0x00007ffff30eccae libQt5Core.so.5`qt_message(QtMsgType, QMessageLogContext const&, char const*, __va_list_tag*) + 62
    frame #5: 0x00007ffff30b144b libQt5Core.so.5`QMessageLogger::critical(char const*, ...) const + 181
    frame #6: 0x00000000007d7955 mixxx`mixxx::Beats::iteratorFrom(mixxx::audio::FramePos) const [inlined] mixxx_debug_assert(assertion=<unavailable>, file=<unavailable>, line=455, function=<unavailable>) at assert.h:9:5
    frame #7: 0x00000000007d78f6 mixxx`mixxx::Beats::iteratorFrom(this=0x000000003bee7f90, position=(m_framePosition = -135427.51968503935)) const at beats.cpp:454:5
    frame #8: 0x00000000007dab7a mixxx`mixxx::Beats::numBeatsInRange(mixxx::audio::FramePos, mixxx::audio::FramePos) const [inlined] mixxx::Beats::findNthBeat(this=0x000000003bee7f90, position=(m_framePosition = 0), n=1) const at beats.cpp:464:15
    frame #9: 0x00000000007dab6c mixxx`mixxx::Beats::numBeatsInRange(this=0x000000003bee7f90, startPosition=(m_framePosition = 0), endPosition=(m_framePosition = 0)) const at beats.cpp:718:24
    frame #10: 0x000000000088b8a1 mixxx`qopengl::WaveformRenderBeat::renderGL(this=0x0000000035c527f0) at waveformrenderbeat.cpp:71:45
    frame #11: 0x0000000000584317 mixxx`qopengl::WaveformWidget::renderGL(this=<unavailable>) at waveformwidget.cpp:36:60
    frame #12: 0x0000000000584280 mixxx`non-virtual thunk to qopengl::WaveformWidget::render() [inlined] qopengl::WaveformWidget::render(this=0x0000000038e1cf50) at waveformwidget.cpp:23:5
```

**Comment by m0dB** [comment]
Thanks,  I will address this later this week.

**Comment by atskler** [comment]
> Thanks @atskler . Do the RGB (QOpenGL) and RGB-LR (QOpenGL) also look correct? Is that with the same hardware as @uklotzde ?

@m0dB  Yes and yes. I don't know. My hardware is the following:

```
atskler@localhost:~> inxi -GIMSayz
System:
  Kernel: 6.2.10-1-default arch: x86_64 bits: 64 compiler: gcc v: 13.0.1
    parameters: BOOT_IMAGE=/vmlinuz-6.2.10-1-default
    root=/dev/mapper/vlg--mnh-mnh--root splash=silent systemd.show_status=yes
    resume=/dev/vlg-mnh/mnh-swap quiet security=apparmor threadirqs
    [...] splash=verbose 
    plymouth.enable=0 [...]
  Desktop: KDE Plasma v: 5.27.4 tk: Qt v: 5.15.8 wm: kwin_x11 vt: 7 dm:
    1: GDM v: 44.0 2: SDDM note: stopped Distro: openSUSE Tumbleweed 20230414
Machine:
  Type: Laptop System: Dell product: Latitude E6520 v: 01
    serial: <superuser required> Chassis: type: 9 serial: <superuser required>
  Mobo: Dell model: 0NVF5K v: A01 serial: <superuser required> UEFI: Dell
    v: A21 date: 03/06/2018
Graphics:
  Device-1: Intel 2nd Generation Core Processor Family Integrated Graphics
    vendor: Dell driver: i915 v: kernel arch: Gen-6 process: Intel 32nm
    built: 2011 ports: active: LVDS-1 empty: DP-1, DP-2, DP-3, HDMI-A-1,
    HDMI-A-2, HDMI-A-3, VGA-1 bus-ID: 00:02.0 chip-ID: 8086:0126 class-ID: 0300
  Display: x11 server: X.Org v: 21.1.8 with: Xwayland v: 23.1.1
    compositor: kwin_x11 driver: X: loaded: modesetting dri: crocus gpu: i915
    display-ID: :0 screens: 1
  Screen-1: 0 s-res: 1920x1080 s-dpi: 96 s-size: 508x285mm (20.00x11.22")
    s-diag: 582mm (22.93")
  Monitor-1: LVDS-1 model: Seiko Epson 0x5448 built: 2010 res: 1920x1080
    hz: 60 dpi: 142 gamma: 1.2 size: 344x194mm (13.54x7.64") diag: 395mm (15.5")
    ratio: 16:9 modes: 1920x1080
  API: OpenGL v: 3.3 Mesa 23.0.1 renderer: Mesa Intel HD Graphics 3000 (SNB
    GT2) direct render: Yes
Info:
  Processes: 287 Uptime: 11h 5m wakeups: 369 Memory: 15.5 GiB
  used: 3.91 GiB (25.2%) Init: systemd v: 253 default: graphical
  tool: systemctl Compilers: gcc: 13.0.1 alt: 12/13 Packages: pm: rpm pkgs: N/A
  note: see --rpm tools: yast,zypper pm: flatpak pkgs: 6 Shell: Bash v: 5.2.15
  running-in: konsole inxi: 3.3.23
atskler@localhost:~> 
```

File: src/widget/wvumetergl.h [hunk 46]
```diff
@@ -72,4 +80,15 @@ class WVuMeterGL : public QGLWidget, public WBaseWidget {
...
+    bool m_hasOpenGLShaderPrograms{};
+    std::unique_ptr<QOpenGLTexture> m_pTextureBack;
+    std::unique_ptr<QOpenGLTexture> m_pTextureVu;
+    QOpenGLShaderProgram m_shaderProgram;
+
+    void initializeGL() override;
+    void cleanupGL();
+    void renderGL() override;
+    void drawTexture(QOpenGLTexture* texture, const QRectF& sourceRect, const QRectF& targetRect);
+#endif
```
Comment (Swiftb0y) [inline src/widget/wvumetergl.h:93]: So previously the `WVuMeterGL` didn't use GL? Or OpenGL? I don't quite understand this change here (same for `WSpinny`). Is there a way to do this less intrusively?

**Review by Swiftb0y — COMMENTED** [review]
Much less thorough review, but at least I got to the bottom of the page this time.

File: src/waveform/renderers/qopengl/colordata.h [hunk 47]
```diff
@@ -0,0 +1,34 @@
...
+
+  public:
+    void addForRectangle(float r, float g, float b) {
+        mData.push_back({r, g, b});
+        mData.push_back({r, g, b});
+        mData.push_back({r, g, b});
+        mData.push_back({r, g, b});
+        mData.push_back({r, g, b});
+        mData.push_back({r, g, b});
+    }
```
[the remark this answers is not in the document]
Comment (m0dB) [reply src/waveform/renderers/qopengl/colordata.h:21]: Yes, you guessed correct.

I am not quite sure would you mean with "implicitly coupled to the topology of that rectangle." :-) But do you have some particular other approach in mind? Or is this something that could simply be addressed with a more explicit function name?

File: src/waveform/renderers/qopengl/shaders/endoftrackshader.cpp [hunk 48]
```diff
@@ -0,0 +1,29 @@
...
+)--");
+
+    QString fragmentShaderCode = QStringLiteral(R"--(
+uniform vec4 color;
+varying float vgradient;
+void main()
+{
+    const float baseTransparency = 0.5;
+    const float additionalTransparency = 0.33;
+    gl_FragColor = vec4(color.xyz, color.w * (baseTransparency + additionalTransparency * max(0.,vgradient)));
```
[the remark this answers is not in the document]
Comment (m0dB) [reply src/waveform/renderers/qopengl/shaders/endoftrackshader.cpp:24]: The fact that I didn't know the built-in function mix shows that it's highly debatable who knows more about shaders!

I will make the change.

File: src/waveform/renderers/qopengl/shaders/gradientshader.cpp [hunk 49]
```diff
@@ -0,0 +1,28 @@
...
+    gl_Position = matrix * position;
+}
+)--");
+
+    QString fragmentShaderCode = QStringLiteral(R"--(
+uniform vec4 color;
+varying vec3 vGradient;
+void main()
+{
+    gl_FragColor = vec4(color.x, color.y, color.z, color.w * max(0.0, abs((vGradient.x + vGradient.y) * 4.0 - 2.0) - 1.0));
```
[the remark this answers is not in the document]
Comment (m0dB) [reply src/waveform/renderers/qopengl/shaders/gradientshader.cpp:23]: Looking at this again I feel it is a) overly complicated and b) misleading because the name suggests this is something generic while it reality its for drawing a very specific gradient (which fades from color.w to transparent in the first quarter of either x or y axis, and back to color.w in the last quarter).

I will either rename this (and explain with a comment) or do the same by using more generic code.

File: src/waveform/renderers/qopengl/shaders/textureshader.cpp [hunk 50]
```diff
@@ -0,0 +1,28 @@
...
+    gl_Position = matrix * position;
+}
+)--");
+
+    QString fragmentShaderCode = QStringLiteral(R"--(
+uniform sampler2D sampler;
+varying vec3 vTexcoor;
+void main()
+{
+    gl_FragColor = texture2D(sampler, vec2(vTexcoor.x, vTexcoor.y));
```
[the remark this answers is not in the document]
Comment (m0dB) [reply src/waveform/renderers/qopengl/shaders/textureshader.cpp:23]: Definitely!

File: src/widget/qopengl/wspinny.cpp
[the remark this answers is not in the document]
Comment (m0dB) [reply src/widget/qopengl/wspinny.cpp:1]: Agreed

File: src/widget/qopengl/wvumetergl.cpp
[the remark this answers is not in the document]
Comment (m0dB) [reply src/widget/qopengl/wvumetergl.cpp:1]: Agreed

File: src/widget/tooltipqopengl.h [hunk 51]
```diff
@@ -0,0 +1,28 @@
...
+class QTimer;
+class WGLWidget;
+
+// Tooltips don't work for the qopengl-based WGLWidget. This
+// singleton mimics the standard tooltip behaviour for them.
+class ToolTipQOpenGL : public QObject {
+    Q_OBJECT
+
+    bool m_active{true};
+    std::unique_ptr<QTimer> m_timer;
```
[the remark this answers is not in the document]
Comment (m0dB) [reply src/widget/tooltipqopengl.h:15]: To be able to use forward declaration.

But since tooltipqopengl.h is only included in four cpp files I agree that the simplicity of using QTimer as a member is preferable. I'll make the change.

File: src/widget/wknob.cpp [hunk 52]
```diff
@@ -43,7 +38,7 @@ void WKnob::leaveEvent(QEvent* e) {
 }
 
 void WKnob::inputActivity() {
-#ifdef __APPLE__
+#ifdef USE_WIDGET_RENDER_TIMER
     m_renderTimer.activity();
 #else
```
[the remark this answers is not in the document]
Comment (m0dB) [reply src/widget/wknob.cpp:43]: Ok.

File: src/widget/wvumetergl.h (hunk 46 above)
Comment (m0dB) [reply src/widget/wvumetergl.h:93]: Correct,  previously, or now without MIXXX_USE_QOPENGL, they would use a QPainter on the OpenGL paint device, which worked kind of okay with QGLWidget, but results to be very inefficient with the QOpenGLWindow based solution.

I guess a cleaner solution could be to have a base class with the common code, and derive both the qpainter version and the pure qopengl version from that base class. Same for spinny.

Comment (m0dB) [reply src/widget/wvumetergl.h:93]: Ok, after looking at the code I remember why I did it like this. In the case of MIXXX_USE_QOPENGL I also keep the QPainter code, to use as a fallback in case GLSL is not supported on the system. So this actually does suggest that a situation exists where both the QPainter and the GLSL version coexist (and the GLSL version is used if the system supports GLSL, otherwise fall back to the QPainter version). I will make the change accordingly.

Comment (uklotzde) [reply src/widget/wvumetergl.h:93]: Update: The first debug assertion is triggered ~10 times, finally followed by the `reserved == ...` assertion after repeatedly continuing execution:

```
critical [Main] DEBUG ASSERT: "it == cbegin() || it == cend() || (*it >= position && *std::prev(it) < position)" in function mixxx::Beats::ConstIterator mixxx::Beats::iteratorFrom(mixxx::audio::FramePos) const at /home/uk/volumes/Build/cpp/mixxx/src/track/beats.cpp:454
Process 76706 stopped
* thread #1, name = 'mixxx', stop reason = signal SIGINT
    frame #0: 0x00007ffff2aafb94 libc.so.6`__pthread_kill_implementation + 276
libc.so.6`__pthread_kill_implementation:
->  0x7ffff2aafb94 <+276>: movl   %eax, %ebx
    0x7ffff2aafb96 <+278>: negl   %ebx
    0x7ffff2aafb98 <+280>: cmpl   $0xfffff000, %eax         ; imm = 0xFFFFF000 
    0x7ffff2aafb9d <+285>: movl   $0x0, %eax
(lldb) c
Process 76706 resuming
critical [Main] DEBUG ASSERT: "reserved == m_vertices.size()" in function virtual void qopengl::WaveformRenderBeat::renderGL() at /home/uk/volumes/Build/cpp/mixxx/src/waveform/renderers/qopengl/waveformrenderbeat.cpp:102
Process 76706 stopped
* thread #1, name = 'mixxx', stop reason = signal SIGINT
    frame #0: 0x00007ffff2aafb94 libc.so.6`__pthread_kill_implementation + 276
libc.so.6`__pthread_kill_implementation:
->  0x7ffff2aafb94 <+276>: movl   %eax, %ebx
    0x7ffff2aafb96 <+278>: negl   %ebx
    0x7ffff2aafb98 <+280>: cmpl   $0xfffff000, %eax         ; imm = 0xFFFFF000 
    0x7ffff2aafb9d <+285>: movl   $0x0, %eax
```

Forgot to create a backtrace when it happened. Will do so next time.

Comment (uklotzde) [reply src/widget/wvumetergl.h:93]:
```
critical [Main] DEBUG ASSERT: "it == cbegin() || it == cend() || (*it >= position && *std::prev(it) < position)" in function mixxx::Beats::ConstIterator mixxx::Beats::iteratorFrom(mixxx::audio::FramePos) const at /home/uk/volumes/Build/cpp/mixxx/src/track/beats.cpp:454
Process 83843 stopped
* thread #1, name = 'mixxx', stop reason = signal SIGINT
    frame #0: 0x00007ffff2aafb94 libc.so.6`__pthread_kill_implementation + 276
libc.so.6`__pthread_kill_implementation:
->  0x7ffff2aafb94 <+276>: movl   %eax, %ebx
    0x7ffff2aafb96 <+278>: negl   %ebx
    0x7ffff2aafb98 <+280>: cmpl   $0xfffff000, %eax         ; imm = 0xFFFFF000 
    0x7ffff2aafb9d <+285>: movl   $0x0, %eax
(lldb) bt
* thread #1, name = 'mixxx', stop reason = signal SIGINT
  * frame #0: 0x00007ffff2aafb94 libc.so.6`__pthread_kill_implementation + 276
    frame #1: 0x00007ffff2a5eaee libc.so.6`raise + 30
    frame #2: 0x0000000000683a01 mixxx`mixxx::(anonymous namespace)::handleMessage(QtMsgType, QMessageLogContext const&, QString const&) at logging.cpp:346:18
    frame #3: 0x00007ffff30ecb88 libQt5Core.so.5`qt_message_print(QtMsgType, QMessageLogContext const&, QString const&) + 280
    frame #4: 0x00007ffff30eccae libQt5Core.so.5`qt_message(QtMsgType, QMessageLogContext const&, char const*, __va_list_tag*) + 62
    frame #5: 0x00007ffff30b144b libQt5Core.so.5`QMessageLogger::critical(char const*, ...) const + 181
    frame #6: 0x00000000004a5c76 mixxx`mixxx_debug_assert(assertion=<unavailable>, file=<unavailable>, line=<unavailable>, function=<unavailable>) at assert.h:9:14
    frame #7: 0x0000000000513a97 mixxx`mixxx::Beats::iteratorFrom(mixxx::audio::FramePos) const (.cold) at beats.cpp:454:5
    frame #8: 0x00000000009cabde mixxx`mixxx::Beats::numBeatsInRange(mixxx::audio::FramePos, mixxx::audio::FramePos) const at beats.cpp:464:27
    frame #9: 0x0000000000ac3676 mixxx`qopengl::WaveformRenderBeat::renderGL() at waveformrenderbeat.cpp:71:60
    frame #10: 0x00000000006c8770 mixxx`qopengl::WaveformWidget::renderGL() at waveformwidget.cpp:36:68
    frame #11: 0x00000000006c86d2 mixxx`non-virtual thunk to qopengl::WaveformWidget::render() at waveformwidget.h:20:21
    frame #12: 0x00000000006adf40 mixxx`WaveformWidgetFactory::render() at waveformwidgetfactory.cpp:725:40
    frame #13: 0x00007ffff32df5db libQt5Core.so.5`QObject::event(QEvent*) + 539
```

Comment (uklotzde) [reply src/widget/wvumetergl.h:93]: After ~10 repetitions finally followed by:

```
critical [Main] DEBUG ASSERT: "reserved == m_vertices.size()" in function virtual void qopengl::WaveformRenderBeat::renderGL() at /home/uk/volumes/Build/cpp/mixxx/src/waveform/renderers/qopengl/waveformrenderbeat.cpp:102
Process 83843 stopped
* thread #1, name = 'mixxx', stop reason = signal SIGINT
    frame #0: 0x00007ffff2aafb94 libc.so.6`__pthread_kill_implementation + 276
libc.so.6`__pthread_kill_implementation:
->  0x7ffff2aafb94 <+276>: movl   %eax, %ebx
    0x7ffff2aafb96 <+278>: negl   %ebx
    0x7ffff2aafb98 <+280>: cmpl   $0xfffff000, %eax         ; imm = 0xFFFFF000 
    0x7ffff2aafb9d <+285>: movl   $0x0, %eax
(lldb) bt
* thread #1, name = 'mixxx', stop reason = signal SIGINT
  * frame #0: 0x00007ffff2aafb94 libc.so.6`__pthread_kill_implementation + 276
    frame #1: 0x00007ffff2a5eaee libc.so.6`raise + 30
    frame #2: 0x0000000000683a01 mixxx`mixxx::(anonymous namespace)::handleMessage(QtMsgType, QMessageLogContext const&, QString const&) at logging.cpp:346:18
    frame #3: 0x00007ffff30ecb88 libQt5Core.so.5`qt_message_print(QtMsgType, QMessageLogContext const&, QString const&) + 280
    frame #4: 0x00007ffff30eccae libQt5Core.so.5`qt_message(QtMsgType, QMessageLogContext const&, char const*, __va_list_tag*) + 62
    frame #5: 0x00007ffff30b144b libQt5Core.so.5`QMessageLogger::critical(char const*, ...) const + 181
    frame #6: 0x00000000004a5c76 mixxx`mixxx_debug_assert(assertion=<unavailable>, file=<unavailable>, line=<unavailable>, function=<unavailable>) at assert.h:9:14
    frame #7: 0x0000000000531a38 mixxx`qopengl::WaveformRenderBeat::renderGL() (.cold) at waveformrenderbeat.cpp:102:5
    frame #8: 0x00000000006c8770 mixxx`qopengl::WaveformWidget::renderGL() at waveformwidget.cpp:36:68
    frame #9: 0x00000000006c86d2 mixxx`non-virtual thunk to qopengl::WaveformWidget::render() at waveformwidget.h:20:21
    frame #10: 0x00000000006adf40 mixxx`WaveformWidgetFactory::render() at waveformwidgetfactory.cpp:725:40
    frame #11: 0x00007ffff32df5db libQt5Core.so.5`QObject::event(QEvent*) + 539
```

Comment (m0dB) [reply src/widget/wvumetergl.h:93]: Thanks for the detailed report, @uklotzde , I will look into this.

Comment (m0dB) [reply src/widget/wvumetergl.h:93]: @uklotzde is this with a specific track? I can't reproduce this.

Comment (m0dB) [reply src/widget/wvumetergl.h:93]: I have submitted a possible fix. It's a bit of a guess, as I can't reproduce the issue, but I see that elsewhere the arguments for Beats::numBeatsInRange(startPos, endPos) are validated before the call. so I am doing the same now.

(I think it would be safer to do this validation inside numBeatsInRange, but first let's see if this solves the issue)

Comment (m0dB) [reply src/widget/wvumetergl.h:93]: So my possible fix didn't make a difference?

Comment (m0dB) [reply src/widget/wvumetergl.h]: @Swiftb0y I have restructured the WSpinny and WVuMeter classes a bit:

WSpinnyBase with derived WSpinny (which draws using QPainter) and WSpinnyGLSL (which draws using shaders). WSpinnyGLSL is used by default, unless there is no GLSL support or when QOPENGL=OFF.

WVumeterBase with derived WVumeter (which draws uses QPainter) and WVumeterGLSL (which draws using shaders). WVumeterGLSL is used by default, unless there is no GLSL support or when QOPENGL=OFF.

(Note that I have renamed WVuMeterGL to WVuMeter (so the naming scheme matches WSpinny), and the old WVuMeter (which doesn't use the WGLWidget as basis, but standard QWidget updates and thus hogs the event loop on macOS) to WVuMeterLegacy)

File: src/widget/tooltipqopengl.h (hunk 51 above)
[the remark this answers is not in the document]
Comment (m0dB) [reply src/widget/tooltipqopengl.h]: DONE (removed unique_ptr, using QTimer as member)

[the remark this answers is not in the document]
Comment (Swiftb0y) [reply src/widget/tooltipqopengl.h]: May I ask why you would prefer forward declaration here? I assume to speed up compile-times?

File: src/widget/qopengl/wvumetergl.cpp
[the remark this answers is not in the document]
Comment (m0dB) [reply src/widget/qopengl/wvumetergl.cpp:1]: DONE: using the TextureShader from waveforms/renderer/qopengl/shaders.

What I don't like it that WSpinny and WVuMeter now use this shader that is deep inside the waveforms folder. Maybe I should move all the shaders to a different level and more common location? Maybe util/qopengl/shaders/ ?

File: src/widget/qopengl/wspinny.cpp
[the remark this answers is not in the document]
Comment (m0dB) [reply src/widget/qopengl/wspinny.cpp:1]: DONE (see below)

File: src/waveform/renderers/qopengl/shaders/unicolorshader.h [hunk 53]
```diff
@@ -0,0 +1,17 @@
+#pragma once
+
+#include "waveform/renderers/qopengl/shaders/shader.h"
+
+namespace qopengl {
+class UnicolorShader;
+}
+
+class qopengl::UnicolorShader final : public qopengl::Shader {
```
[the remark this answers is not in the document]
Comment (m0dB) [reply src/waveform/renderers/qopengl/shaders/unicolorshader.h:9]: I think that might actually become more confusing, it will trick you into thinking that you are looking at scenegraph code.

File: src/waveform/renderers/qopengl/shaders/gradientshader.cpp (hunk 49 above)
[the remark this answers is not in the document]
Comment (m0dB) [reply src/waveform/renderers/qopengl/shaders/gradientshader.cpp]: I have reimplemented this with a much simpler shader (RGBAShader) that interpolates between to color vertices to draw the same gradients.

File: src/waveform/renderers/qopengl/shaders/endoftrackshader.cpp (hunk 48 above)
[the remark this answers is not in the document]
Comment (m0dB) [reply src/waveform/renderers/qopengl/shaders/endoftrackshader.cpp]: DONE

File: src/waveform/renderers/qopengl/colordata.h (hunk 47 above)
[the remark this answers is not in the document]
Comment (m0dB) [reply src/waveform/renderers/qopengl/colordata.h]: I am waiting for some clarification / suggestion on how to improve this. But I don't think it should block this PR, it's something that can be done later. It works.

**Comment by uklotzde** [comment]
GCC 13:

```
/home/uk/volumes/Build/cpp/mixxx/src/waveform/renderers/waveformsignalcolors.cpp: In member function ‘void WaveformSignalColors::fallBackFromSignalColor()’:
/home/uk/volumes/Build/cpp/mixxx/src/waveform/renderers/waveformsignalcolors.cpp:143:32: error: conversion from ‘double’ to ‘float’ may change value [-Werror=float-conversion]
  143 |         const float sMax = 1.0 - h;
      |                            ~~~~^~~
/home/uk/volumes/Build/cpp/mixxx/src/waveform/renderers/waveformsignalcolors.cpp:149:36: error: conversion from ‘double’ to ‘float’ may change value [-Werror=float-conversion]
  149 |             const float lMax = 1.0 - l;
      |                                ~~~~^~~
/home/uk/volumes/Build/cpp/mixxx/src/waveform/renderers/waveformsignalcolors.cpp:154:36: error: conversion from ‘double’ to ‘float’ may change value [-Werror=float-conversion]
  154 |             const float lMax = 1.0 - l;
      |                                ~~~~^~~
cc1plus: all warnings being treated as errors
```

**Comment by m0dB** [comment]
@uklotzde  only here or at other places too?

File: src/widget/tooltipqopengl.h (hunk 51 above)
[the remark this answers is not in the document]
Comment (m0dB) [reply src/widget/tooltipqopengl.h]: Yes, compile time and also to keep dependencies between modules to a minimum. If you include headers from other headers when it's not strictly necessary, before you know it touching something in one header can trigger recompilation of many files that are not even remotely related.  In this case, this header is only included from a couple of cpp files, so there is no such risk of excessively propagating dependencies and the use of the forward declaration was exaggerated (also because we are going to touch QTimer).

It also helps to structure the code in modules without having to drag along a lot of public include paths of other modules. The mixxx CMakeLists.txt is really bad practice, one huge CMakeLists.txt instead of having proper modules in folders. But improving that will be a huge undertaking...

File: src/widget/tooltipqopengl.cpp [hunk 54]
```diff
@@ -0,0 +1,46 @@
...
+}
+
+void ToolTipQOpenGL::onTimeout() {
+    if (m_widget) {
+        QToolTip::showText(m_pos, m_widget->toolTip(), m_widget);
+    }
+}
+
+ToolTipQOpenGL::~ToolTipQOpenGL() {
+}
```
Comment (Swiftb0y) [inline src/widget/tooltipqopengl.cpp:22]: no need for default ctor, especially if empty.

File: src/waveform/widgets/waveformwidgettype.h [hunk 55]
```diff
@@ -23,10 +23,10 @@ class WaveformWidgetType {
...
 #ifdef MIXXX_USE_QOPENGL
-        QOpenGLRGBWaveform,      // 17 RGB (QOpenGL)
-        QOpenGLLRRGBWaveform,    // 18 RGB (QOpenGL)
-        QOpenGLFilteredWaveform, // 19 Filtered (QOpenGL)
-        QOpenGLSimpleWaveform,   // 20 Simple (QOpenGL)
+        QOpenGLRGBWaveform,      // 17 RGB (all-shaders)
+        QOpenGLLRRGBWaveform,    // 18 L/R RGB (all-shaders)
+        QOpenGLFilteredWaveform, // 19 Filtered (all-shaders)
+        QOpenGLSimpleWaveform,   // 20 Simple (all-shaders)
 #endif
```
Comment (Swiftb0y) [inline src/waveform/widgets/waveformwidgettype.h]: I'm not sure I agree with the `(all-shaders)` naming, whats the reasoning for that? It doesn't really tell the user anything and neither does it tell anything to developers when users are filing waveform-related issues.

**Review by Swiftb0y — COMMENTED** [review]
This has only been a look at the new commits since the last review. Didn't take a super in-depth look since 6ea3d909551e4b3efb4cb61d4060dd87aa8aea6a is so massive.

File: src/widget/qopengl/wvumetergl.cpp
[the remark this answers is not in the document]
Comment (Swiftb0y) [reply src/widget/qopengl/wvumetergl.cpp:1]: Yeah, the shaders are not really waveform specific so they deserve to be somewhere else. not sure if `util` is the correct folder for GUI related classes though.

File: src/waveform/renderers/qopengl/shaders/unicolorshader.h (hunk 53 above)
[the remark this answers is not in the document]
Comment (Swiftb0y) [reply src/waveform/renderers/qopengl/shaders/unicolorshader.h:9]: Well, the scenegraph-related classes are always prefixed with `QSG`, but lets keep it like this for now.

File: src/waveform/renderers/qopengl/colordata.h (hunk 47 above)
[the remark this answers is not in the document]
Comment (Swiftb0y) [reply src/waveform/renderers/qopengl/colordata.h]: Right, so to elaborate: The operations here are tied to how opengl is actually interpreting the underlying mesh. You could use this method, but when you actually draw the mesh, it could be specified as `GL_LINE` or something other than `GL_TRIANGLE*`. The result will obviously look nothing alike. So the issue I have with this is that it tries to abstract the vertices into primitives, but that abstraction is incomplete because vertices have more than just position information (such as color). Color and position information are related to each other via their index in the array but this abstraction removes that. So its now very easy to create vertices without color (or rather vertices which are matched with the wrong color). So for this abstraction to work properly, it would need to work by taking all attributes of a vertex at once. In the end, it really boils down to the classic "struct of arrays vs array of structs" problem. 

So no, it doesn't block this PR, but IMO its not a huge improvement either because of its leaky-ness.

**Comment by Swiftb0y** [comment]
While testing I encountered the issue that the new waveforms catch focus. So the keyboard shortcuts (such as pressing D for play on Channel1) no longer work. I guess the issue stems from the fact that the waveforms are a separate window?

File: src/widget/openglwindow.cpp [hunk 56]
```diff
@@ -0,0 +1,75 @@
...
+    if (m_pWidget) {
+        m_pWidget->initializeGL();
+    }
+}
+
+void OpenGLWindow::paintGL() {
+    if (m_pWidget && isExposed()) {
+        m_pWidget->renderGL();
+        m_pWidget->swapBuffers();
+        m_pWidget->renderGL();
```
Comment (Swiftb0y) [inline src/widget/openglwindow.cpp:33]: this looks to me like the widget is being rendered twice. Or is something else happening here?

File: src/waveform/renderers/qopengl/waveformrenderbeat.cpp [hunk 57]
```diff
@@ -68,7 +68,9 @@ void WaveformRenderBeat::renderGL() {
     const float rendererBreadth = m_waveformRenderer->getBreadth();
 
     const int numVerticesPerLine = 6; // 2 triangles
-    const int numBeatsInRange = trackBeats->numBeatsInRange(startPosition, endPosition);
+    const int numBeatsInRange = startPosition.isValid() && endPosition.isValid()
```
[the remark this answers is not in the document]
Comment (m0dB) [reply src/waveform/renderers/qopengl/waveformrenderbeat.cpp:71]: I'm not sure, but I checked other uses of numBeatsInRange, and there the start and end position are also checked. I have not been able to reproduce the issue, but looking at the code it does make sense that the asserts that @uklotzde reported fails when the positions are invalid. Anyway, it certainly doesn't hurt to check!

File: src/widget/tooltipqopengl.cpp (hunk 54 above)
Comment (m0dB) [reply src/widget/tooltipqopengl.cpp:22]: True that. I'll remove it.

File: src/waveform/widgets/waveformwidgettype.h (hunk 55 above)
Comment (m0dB) [reply src/waveform/widgets/waveformwidgettype.h]: Yeah, I am not convinced either, but (QOpenGL) was even less interesting.

The reasoning is that I want to express that these waveform types use a full stack of renderer layers that only use glsl shaders and no QPainter calls, which is what make them stand out.

I am very open to suggestions.

File: src/widget/qopengl/wvumetergl.cpp
[the remark this answers is not in the document]
Comment (m0dB) [reply src/widget/qopengl/wvumetergl.cpp:1]: Maybe they could go directly under src/qopengl/shaders/ ?

File: src/waveform/renderers/qopengl/colordata.h (hunk 47 above)
[the remark this answers is not in the document]
Comment (m0dB) [reply src/waveform/renderers/qopengl/colordata.h]: Ok, I see what you mean, and I have some ideas on how to address this. But I feel that we are piling reviews upon reviews, so let's just stick with this solution for now and in the future do a refactoring on top of this.

**Comment by Swiftb0y** [comment]
also possibly interesting note: When I start mixxx without `-platform xcb` just out of curiosity the waveforms get disabled because mixxx thinks there is no opengl(es) available. However, the the `GL_RENDERER` says 4.6. `majorVersion` is 2 while `minorVersion` is 0. Is that a driver or a Wayland issue? Or is this a fault in the detection code that you added as part of this PR? I'm too unfamiliar with troubleshooting GL and driver issues to determine this myself.

File: src/waveform/widgets/waveformwidgettype.h (hunk 55 above)
Comment (Swiftb0y) [reply src/waveform/widgets/waveformwidgettype.h]: Not sure, maybe just `(no QPainter)` would work I guess? I think discussing whats best for the user is futile anyways since they already have to decide what variant to choose out of the 4 different waveforms styles. It would best best if they didn't have to choose a variant, but thats out-of-scope. So the naming of one of those variants doesn't really matter IMO.

File: src/waveform/renderers/qopengl/waveformrenderbeat.cpp (hunk 57 above)
[the remark this answers is not in the document]
Comment (Swiftb0y) [reply src/waveform/renderers/qopengl/waveformrenderbeat.cpp:71]: Mhmm. Then the thing I'm concerned about is whether 0 is actually a good default value in case of failure. Also in case its 0, the debug assert later in the code will also trip because the vector is larger than 0.

File: src/widget/tooltipqopengl.h (hunk 51 above)
[the remark this answers is not in the document]
Comment (Swiftb0y) [reply src/widget/tooltipqopengl.h]: I fully I agree. In the case of Qt headers, I would argue it doesn't really hurt to include the headers when possible since those headers are fairly stable.

File: src/widget/qopengl/wvumetergl.cpp
[the remark this answers is not in the document]
Comment (Swiftb0y) [reply src/widget/qopengl/wvumetergl.cpp:1]: Yes, that seems appropriate.

File: src/waveform/renderers/qopengl/colordata.h (hunk 47 above)
[the remark this answers is not in the document]
Comment (Swiftb0y) [reply src/waveform/renderers/qopengl/colordata.h]: Yes, I agree.

**Comment by Swiftb0y** [comment]
None of the commits you pushed until now pass pre-commit. I guess you didn't set it up? Please do that and run it manually `pre-commit run --from-ref main --to-ref HEAD`.

**Comment by Swiftb0y** [comment]
Please be aware that there are still open review questions which github has collapsed by default. 
Screenshot from 2023-04-27 21-48-34

**Comment by m0dB** [comment]
> None of the commits you pushed until now pass pre-commit. I guess you didn't set it up? Please do that and run it manually `pre-commit run --from-ref main --to-ref HEAD`.

I actually do have it set up, and have had it set up since day one, so not sure what it wrong here. I will see if running it manually helps.

**Comment by m0dB** [comment]
> While testing I encountered the issue that the new waveforms catch focus. So the keyboard shortcuts (such as pressing D for play on Channel1) no longer work. I guess the issue stems from the fact that the waveforms are a separate window?

Interesting. I will try to reproduce this and see if I can find a workaround (yes, I am actively forwarding events from the qopenglwindow, so it might be I need to add something for the shortkeys)

**Comment by Swiftb0y** [comment]
> I actually do have it set up, and have had it set up since day one, so not sure what it wrong here. I will see if running it manually helps.

Ah, I misinterpreted the log output. Yes, the actual issues are only very minimal. Pre-commit only ever looks at the current commit, so if the commit was made without pre-commit having a say in it (for example via the github web ui) it'll only complain on CI since it actually checks the entire PR on CI, but not locally. 

Seems it passed now with your latest commit. :+1:

**Comment by Swiftb0y** [comment]
> > While testing I encountered the issue that the new waveforms catch focus. So the keyboard shortcuts (such as pressing D for play on Channel1) no longer work. I guess the issue stems from the fact that the waveforms are a separate window?
> 
> Interesting. I will try to reproduce this and see if I can find a workaround (yes, I am actively forwarding events from the qopenglwindow, so it might be I need to add something for the shortkeys)

I'm sorry I just noticed that my initial message wasn't very good. To reproduce, you just need to load a track onto a deck and then "scratch" the track by using your mouse on the waveform. Just clicking the waveform also causes the same issue.

File: src/waveform/renderers/qopengl/waveformrenderbeat.cpp [hunk 58]
```diff
@@ -0,0 +1,123 @@
...
+
+    m_shader.setAttributeArray(
+            vertexLocation, GL_FLOAT, m_vertices.constData(), 2);
+
+    m_shader.setUniformValue(matrixLocation, matrix);
+    m_shader.setUniformValue(colorLocation, m_color);
+
+    glDrawArrays(GL_TRIANGLES, 0, m_vertices.size());
+
+    m_shader.disableAttributeArray(vertexLocation);
```
[the remark this answers is not in the document]
Comment (m0dB) [reply src/waveform/renderers/qopengl/waveformrenderbeat.cpp:123]: Yes, I agree. But I would also leave this for a subsequent and dedicated PR.

File: src/waveform/renderers/qopengl/waveformrendermark.cpp [hunk 59]
```diff
@@ -0,0 +1,535 @@
...
+
+    const float posarray[] = {posx1, posy1, posx2, posy1, posx1, posy2, posx2, posy2};
+    const float grdarray[] = {grdx1, grdy1, grdx2, grdy1, grdx1, grdy2, grdx2, grdy2};
+
+    QMatrix4x4 matrix;
+    matrix.ortho(QRectF(0.0, 0.0, m_waveformRenderer->getWidth(), m_waveformRenderer->getHeight()));
+    if (m_waveformRenderer->getOrientation() == Qt::Vertical) {
+        matrix.rotate(90.f, 0.0f, 0.0f, 1.0f);
+        matrix.translate(0.f, -m_waveformRenderer->getWidth(), 0.f);
+    }
```
[the remark this answers is not in the document]
Comment (m0dB) [reply src/waveform/renderers/qopengl/waveformrendermark.cpp:127]: No, you are right, I overlooked this one.

File: src/waveform/renderers/qopengl/waveformrendermark.cpp [hunk 60]
```diff
@@ -0,0 +1,535 @@
...
+
+    QImage image(static_cast<int>(imgwidth * devicePixelRatio),
+            static_cast<int>(imgheight * devicePixelRatio),
+            QImage::Format_ARGB32_Premultiplied);
+    image.setDevicePixelRatio(devicePixelRatio);
+    image.fill(QColor(0, 0, 0, 0).rgba());
+
+    QPainter painter;
+
+    painter.begin(&image);
```
[the remark this answers is not in the document]
Comment (m0dB) [reply src/waveform/renderers/qopengl/waveformrendermark.cpp:255]: Yes, using QPainter with the QOpenGLWindow as paint device is slow. But this is painting in an image (which is than used as a texture drawn with the textureshader), so there is no problem here. (Also, these images are only painted into once)

File: src/waveform/renderers/qopengl/waveformrendermark.cpp [hunk 61]
```diff
@@ -0,0 +1,535 @@
...
+void qopengl::WaveformRenderMark::slotCuesUpdated() {
+    m_bCuesUpdates = true;
+}
+
+void qopengl::WaveformRenderMark::checkCuesUpdated() {
+    if (!m_bCuesUpdates) {
+        return;
+    }
+    // TODO @m0dB use atomic?
+    m_bCuesUpdates = false;
```
[the remark this answers is not in the document]
Comment (m0dB) [reply src/waveform/renderers/qopengl/waveformrendermark.cpp:342]: This comment trickled over from a branch where I experimented with rendering in a dedicated thread. I'll delete the comment.

File: src/waveform/renderers/waveformrenderbeat.cpp [hunk 62]
```diff
@@ -40,7 +40,12 @@ void WaveformRenderBeat::draw(QPainter* painter, QPaintEvent* /*event*/) {
     if (alpha == 0) {
         return;
     }
+#ifdef MIXXX_USE_QOPENGL
+    // TODO @m0dB using alpha transparency for the beat lines causes has artifacts with QOpenGL.
+    m_beatColor.setAlphaF(1.f);
```
[the remark this answers is not in the document]
Comment (m0dB) [reply src/waveform/renderers/waveformrenderbeat.cpp:45]: I don't remember, I will try if this is still the case.

File: src/waveform/widgets/qopengl/filteredwaveformwidget.h [hunk 63]
```diff
@@ -0,0 +1,46 @@
...
+    static inline bool useOpenGles() {
+        return false;
+    }
+    static inline bool useOpenGLShaders() {
+        return true;
+    }
+    static inline bool developerOnly() {
+        return false;
+    }
+
```
[the remark this answers is not in the document]
Comment (m0dB) [reply src/waveform/widgets/qopengl/filteredwaveformwidget.h:36]: yeah, copy pasted fro other widgets.

File: src/waveform/widgets/qopengl/waveformwidget.cpp [hunk 64]
```diff
@@ -0,0 +1,61 @@
...
+            m_rendererStack[i]->qopenglWaveformRenderer()->renderGL();
+        }
+    }
+}
+
+void WaveformWidget::initializeGL() {
+    for (int i = 0; i < m_rendererStack.size(); ++i) {
+        m_rendererStack[i]->qopenglWaveformRenderer()->initializeOpenGLFunctions();
+        m_rendererStack[i]->qopenglWaveformRenderer()->initializeGL();
+    }
```
[the remark this answers is not in the document]
Comment (m0dB) [reply src/waveform/widgets/qopengl/waveformwidget.cpp:45]: sure. copy pasted from old code I guess.

File: src/widget/paintable.cpp [hunk 65]
```diff
@@ -134,6 +134,10 @@ QRectF Paintable::rect() const {
     return QRectF();
 }
 
+QImage Paintable::toImage() const {
+    return m_pPixmap.isNull() ? QImage() : m_pPixmap->toImage();
```
[the remark this answers is not in the document]
Comment (m0dB) [reply src/widget/paintable.cpp:138]: a null QPixmap isn't the same as a null QImage. so the conditonal says: if m_pPixmap is a null QPixmap, return a null QImage, otherwise return the m_pPixmap converted to QImage. makes sense?

[the remark this answers is not in the document]
Comment (uklotzde) [reply src/widget/paintable.cpp:138]: If something is not obvious then please add comments to the code instead of answering questions here in the PR were the answer is lost after merging.

Ideally, code doesn't need to be commented and is self-explaining. Inline code comments should be considered a crutch.

File: src/waveform/renderers/qopengl/waveformrendermark.cpp (hunk 60 above)
[the remark this answers is not in the document]
Comment (Swiftb0y) [reply src/waveform/renderers/qopengl/waveformrendermark.cpp:255]: Ah, that makes sense, so its just drawing the image on the CPU which is fast enough and then reusing the images on the GPU? Can you make that more explicit in a comment (that using QPainter in this fashion is fine but not when trying to use QPainter in "GPU-mode")?

File: src/widget/paintable.cpp (hunk 65 above)
[the remark this answers is not in the document]
Comment (Swiftb0y) [reply src/widget/paintable.cpp:138]: Right, but won't a null QPixmap converted to a QImage result in a null QImage?

**Comment by uklotzde** [comment]
Happened again:

```
(lldb) bt
* thread #1, name = 'mixxx', stop reason = signal SIGINT
  * frame #0: 0x00007ffff2aafb94 libc.so.6`__pthread_kill_implementation + 276
    frame #1: 0x00007ffff2a5eaee libc.so.6`raise + 30
    frame #2: 0x0000000000684d01 mixxx`mixxx::(anonymous namespace)::handleMessage(QtMsgType, QMessageLogContext const&, QString const&) at logging.cpp:346:18
    frame #3: 0x00007ffff30ecb88 libQt5Core.so.5`qt_message_print(QtMsgType, QMessageLogContext const&, QString const&) + 280
    frame #4: 0x00007ffff30eccae libQt5Core.so.5`qt_message(QtMsgType, QMessageLogContext const&, char const*, __va_list_tag*) + 62
    frame #5: 0x00007ffff30b144b libQt5Core.so.5`QMessageLogger::critical(char const*, ...) const + 181
    frame #6: 0x00000000004a6c56 mixxx`mixxx_debug_assert(assertion=<unavailable>, file=<unavailable>, line=<unavailable>, function=<unavailable>) at assert.h:9:14
    frame #7: 0x00000000005143e1 mixxx`mixxx::Beats::iteratorFrom(mixxx::audio::FramePos) const (.cold) at beats.cpp:454:5
    frame #8: 0x00000000009cbbae mixxx`mixxx::Beats::numBeatsInRange(mixxx::audio::FramePos, mixxx::audio::FramePos) const at beats.cpp:464:27
    frame #9: 0x0000000000ac96c1 mixxx`qopengl::WaveformRenderBeat::renderGL() at waveformrenderbeat.cpp:72:42
```

```
(lldb) frame select 8
frame #8: 0x00000000009cbbae mixxx`mixxx::Beats::numBeatsInRange(mixxx::audio::FramePos, mixxx::audio::FramePos) const at beats.cpp:464:27
   461 	        return audio::kInvalidFramePos;
   462 	    }
   463 	
-> 464 	    auto it = iteratorFrom(position);
   465 	    const bool searchForward = n > 0;
   466 	    if (searchForward) {
   467 	        n--;
(lldb) frame select 9
frame #9: 0x0000000000ac96c1 mixxx`qopengl::WaveformRenderBeat::renderGL() at waveformrenderbeat.cpp:72:42
   69  	
   70  	    const int numVerticesPerLine = 6; // 2 triangles
   71  	    const int numBeatsInRange = startPosition.isValid() && endPosition.isValid()
-> 72  	            ? trackBeats->numBeatsInRange(startPosition, endPosition)
   73  	            : 0;
   74  	
   75  	    // In corner cases numBeatsInRange returns -1, while the for loop below
(lldb) frame variable
(lldb) 
```

Unfortunately not variable values in an optimized debug build :shrug:

File: src/waveform/renderers/qopengl/shaders/endoftrackshader.cpp [hunk 66]
```diff
@@ -0,0 +1,29 @@
...
+void EndOfTrackShader::init() {
+    QString vertexShaderCode = QStringLiteral(R"--(
+attribute vec4 position;
+attribute float gradient;
+varying float vgradient;
+void main()
+{
+    vgradient = gradient;
+    gl_Position = position;
+}
```
Comment (Swiftb0y) [inline src/waveform/renderers/qopengl/shaders/endoftrackshader.cpp:14]: isn't this missing the matrix?

File: src/widget/wspinnybase.cpp [hunk 67]
```diff
@@ -0,0 +1,658 @@
...
+            this,
+            &WSpinnyBase::slotCoverInfoSelected);
+    connect(m_pCoverMenu, &WCoverArtMenu::reloadCoverArt, this, &WSpinnyBase::slotReloadCoverArt);
+}
+
+WSpinnyBase::~WSpinnyBase() {
+#ifdef __VINYLCONTROL__
+    m_pVCManager->removeSignalQualityListener(this);
+#endif
+}
```
Comment (Swiftb0y) [inline src/widget/wspinnybase.cpp:104]: Can you convert the owned pointer members of the class to smart pointers? Otherwise they'll get leaked.

**Review by Swiftb0y — COMMENTED** [review]
last review, ignoring the renderers this time. Found a lot of potential for cleanup, but we can postpone that.

**Comment by Swiftb0y** [comment]
this PR is currently targetting `main` (Mixxx 2.5 Alpha essentially). I think we should rebase it onto 2.4 instead. wdyt? @daschuer

**Comment by daschuer** [comment]
I don't like that idea. 2.4 is overdue. I have discussed a shortened beta of 3 Month. For my feeling it has already received a good amount of testing.

This one deserves a full beta period. We can release it any time once we are confident with it. But I like to keep it decoupled. To be able to revise the decision at any time.

As of 2.4: normally we where already in the beta phase. Unfortunately the 2.3 regression have eaten all our resources.

**Comment by Swiftb0y** [comment]
Right, I agree that this PR is somewhat risky (especially considering that subsequent needed refactorings could introduce regressions). My reasoning for advocating a quick merge is that this PR is the only fix we have for #11164 afaik.

**Comment by JoergAtGithub** [comment]
I see this as the main showstopper for 2.4! Because without this, we would need to drop MacOS support for the 2.4 release. 
The current 2.4 branch is reported as unusable slow on MacOS by multiple users - and this is the PR which fixes this regression.
We should merge this PR before the 2.4 Beta phase starts!

File: src/widget/openglwindow.cpp (hunk 56 above)
Comment (m0dB) [reply src/widget/openglwindow.cpp:33]: I don't remember why I did this (so yeah, a comment would have been nice). I will figure it out and leave that comment.

File: src/widget/paintable.cpp (hunk 65 above)
[the remark this answers is not in the document]
Comment (m0dB) [reply src/widget/paintable.cpp:138]: No, but the qt docs are indeed very clear. I will remove the ternary expression.

File: src/waveform/renderers/qopengl/shaders/endoftrackshader.cpp (hunk 66 above)
Comment (m0dB) [reply src/waveform/renderers/qopengl/shaders/endoftrackshader.cpp:14]: no need for a matrix, as the end of track applies to the entire view (so it just works on the coordinates going from 0,0 to 1,1)

File: src/widget/wspinnybase.cpp (hunk 67 above)
Comment (m0dB) [reply src/widget/wspinnybase.cpp:104]: note that this is not my code, but the original wspinny code, so if you think this leaks, it should be addressed in 2.3 / 2.4 / main as well.

**Comment by Swiftb0y** [comment]
> Note that it would be possible to mitigate large part of the risk by only compiling with MIXXX_USE_QOPENGL on macOS and stick with the old QGLWidget code on Windows and Linux. When compiling without MIXXX_USE_QOPENGL the differences introduced by this branch are minimal.

I had that thought as well, but came to the conclusion that its probably not a good idea. None of the maintainers is a macOS user and almost none of the other active contributors are using macOS. Having potentially more bug-prone code running on a platform none of the devs have access too will make it very hard for us to spot issues during regular use and it'll make it hard to debug issues reported by macOS users.

**Comment by Swiftb0y** [comment]
IMO we should merge this soon and then go into a 6 month 2.4 beta.

File: src/widget/wspinnybase.cpp (hunk 67 above)
Comment (Swiftb0y) [reply src/widget/wspinnybase.cpp:104]: Yes, I'm aware its not your code. I just double-checked it and it doesn't leak because its using the QObject-based hierarchical memory management. I'll make that explicit in a future cleanup PR by making the members `parented_ptr`s. Let's postpone that until after merge this to avoid merge conflicts.

Comment (Swiftb0y) [reply src/widget/wspinnybase.cpp:104]: Sorry for the false alarm.

File: src/waveform/renderers/qopengl/shaders/endoftrackshader.cpp (hunk 66 above)
Comment (Swiftb0y) [reply src/waveform/renderers/qopengl/shaders/endoftrackshader.cpp:14]: Ok, I didn't know that it was automatically transformed into the view-space.

**Comment by Swiftb0y** [comment]
> Happened again:
> 
> ```
> (lldb) bt
> * thread #1, name = 'mixxx', stop reason = signal SIGINT
>   * frame #0: 0x00007ffff2aafb94 libc.so.6`__pthread_kill_implementation + 276
>     frame #1: 0x00007ffff2a5eaee libc.so.6`raise + 30
>     frame #2: 0x0000000000684d01 mixxx`mixxx::(anonymous namespace)::handleMessage(QtMsgType, QMessageLogContext const&, QString const&) at logging.cpp:346:18
>     frame #3: 0x00007ffff30ecb88 libQt5Core.so.5`qt_message_print(QtMsgType, QMessageLogContext const&, QString const&) + 280
>     frame #4: 0x00007ffff30eccae libQt5Core.so.5`qt_message(QtMsgType, QMessageLogContext const&, char const*, __va_list_tag*) + 62
>     frame #5: 0x00007ffff30b144b libQt5Core.so.5`QMessageLogger::critical(char const*, ...) const + 181
>     frame #6: 0x00000000004a6c56 mixxx`mixxx_debug_assert(assertion=<unavailable>, file=<unavailable>, line=<unavailable>, function=<unavailable>) at assert.h:9:14
>     frame #7: 0x00000000005143e1 mixxx`mixxx::Beats::iteratorFrom(mixxx::audio::FramePos) const (.cold) at beats.cpp:454:5
>     frame #8: 0x00000000009cbbae mixxx`mixxx::Beats::numBeatsInRange(mixxx::audio::FramePos, mixxx::audio::FramePos) const at beats.cpp:464:27
>     frame #9: 0x0000000000ac96c1 mixxx`qopengl::WaveformRenderBeat::renderGL() at waveformrenderbeat.cpp:72:42
> ```
> 
> ```
> (lldb) frame select 8
> frame #8: 0x00000000009cbbae mixxx`mixxx::Beats::numBeatsInRange(mixxx::audio::FramePos, mixxx::audio::FramePos) const at beats.cpp:464:27
>    461 	        return audio::kInvalidFramePos;
>    462 	    }
>    463 	
> -> 464 	    auto it = iteratorFrom(position);
>    465 	    const bool searchForward = n > 0;
>    466 	    if (searchForward) {
>    467 	        n--;
> (lldb) frame select 9
> frame #9: 0x0000000000ac96c1 mixxx`qopengl::WaveformRenderBeat::renderGL() at waveformrenderbeat.cpp:72:42
>    69  	
>    70  	    const int numVerticesPerLine = 6; // 2 triangles
>    71  	    const int numBeatsInRange = startPosition.isValid() && endPosition.isValid()
> -> 72  	            ? trackBeats->numBeatsInRange(startPosition, endPosition)
>    73  	            : 0;
>    74  	
>    75  	    // In corner cases numBeatsInRange returns -1, while the for loop below
> (lldb) frame variable
> (lldb) 
> ```
> 
> Unfortunately not variable values in an optimized debug build shrug

@uklotzde I can't reproduce this, regardless of what I try.

**Comment by ywwg** [comment]
I think it's acceptable to merge unstable code since it's separated from the qt5 stable builds.  We can continue to debug and locate this crash

**Comment by ywwg** [comment]
> unusable slow on MacOS by multiple users

my coworker reported that the Mac OS ARM64 build worked great on his machine, and I think that is a 2.4 build. I think it's more important that we get 2.4 out than we have perfect mac support.  A very large majority of our users are on Windows. If we have to temporarily drop support for mac in 2.4 and bring it back in 2.5, I think that's fine. Or we can just say "we apologize that 2.4 may ve too slow on Mac, please bear with us while we address these issues in a future version". We will no doubt get some complaints but we always get complaints about something! We are not permanently dropping macos.

So I would prefer to keep this as a 2.5 merge and proceed with releasing 2.4 as planned.

**Comment by uklotzde** [comment]
Mixxx 2.3/2.4 is also hardly usable for other, non-macOS users: #11164

**Comment by atskler** [comment]
(I would say that without this PR Mixxx is a crippled contender.)

**Comment by daschuer** [comment]
> IMO we should merge this soon and then go into a 6 month 2.4 beta.

@Swiftb0y: You mean 2.5 beta, right? For me, it is not acceptable to delay 2.4 for this.

File: src/waveform/renderers/qopengl/waveformrenderbeat.cpp (hunk 57 above)
[the remark this answers is not in the document]
Comment (m0dB) [reply src/waveform/renderers/qopengl/waveformrenderbeat.cpp:71]: Will do.

I could also remove the call to numBeatsInRange altogether and just reserve a fixed size that is sufficient to contain the vertices for a maximum amount of beats. That might be the safest solution for now.

File: src/widget/wspinnybase.cpp (hunk 67 above)
Comment (m0dB) [reply src/widget/wspinnybase.cpp:104]: No problem at all! The mixture of QObject memory management and smart pointers is always tricky.

File: src/waveform/renderers/waveformrenderbeat.cpp (hunk 62 above)
[the remark this answers is not in the document]
Comment (m0dB) [reply src/waveform/renderers/waveformrenderbeat.cpp:45]: Screenshot 2023-04-29 at 21 00 06

[the remark this answers is not in the document]
Comment (m0dB) [reply src/waveform/renderers/waveformrenderbeat.cpp:45]: This is what happens.

File: src/waveform/widgets/qopengl/waveformwidget.cpp [hunk 68]
```diff
@@ -0,0 +1,61 @@
...
+    m_rendererStack.clear();
+    doneCurrent();
+}
+
+mixxx::Duration WaveformWidget::render() {
+    makeCurrentIfNeeded();
+    renderGL();
+    doneCurrent();
+    // not used, here for API compatibility
+    return mixxx::Duration();
```
[the remark this answers is not in the document]
Comment (m0dB) [reply src/waveform/widgets/qopengl/waveformwidget.cpp:26]: Looking at the other widgets, it "returns timer for painter setup", which is not relevant in this case. Also, this return value is not used at all, so it might be better to just remove it everywhere. But I will make the comment a bit more clear.

**Comment by JoergAtGithub** [comment]
On Windows I get reproduceable
`Run-Time Check Failure #2 - Stack around the variable 'colors' was corrupted.`
when I use All-Shaders-Filtered-Waveform type. All other waveform types work.


Stack, Locals and Autos:
<details>
```mixxx.exe!qopengl::WaveformRendererFiltered::renderGL() Line 200
	at C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\renderers\qopengl\waveformrendererfiltered.cpp(200)
mixxx.exe!qopengl::WaveformWidget::renderGL() Line 37
	at C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\widgets\qopengl\waveformwidget.cpp(37)
mixxx.exe!qopengl::WaveformWidget::render() Line 24
	at C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\widgets\qopengl\waveformwidget.cpp(24)
mixxx.exe!WaveformWidgetFactory::render() Line 728
	at C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\waveform\waveformwidgetfactory.cpp(728)
mixxx.exe!QtPrivate::FunctorCall<QtPrivate::IndexesList<>,QtPrivate::List<>,void,void (__cdecl WaveformWidgetFactory::*)(void)>::call(void(WaveformWidgetFactory::*)() f, WaveformWidgetFactory * o, void * * arg) Line 152
	at C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-db02b82\installed\x64-windows\include\qt5\QtCore\qobjectdefs_impl.h(152)
mixxx.exe!QtPrivate::FunctionPointer<void (__cdecl WaveformWidgetFactory::*)(void)>::call<QtPrivate::List<>,void>(void(WaveformWidgetFactory::*)() f, WaveformWidgetFactory * o, void * * arg) Line 186
	at C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-db02b82\installed\x64-windows\include\qt5\QtCore\qobjectdefs_impl.h(186)
mixxx.exe!QtPrivate::QSlotObject<void (__cdecl WaveformWidgetFactory::*)(void),QtPrivate::List<>,void>::impl(int which, QtPrivate::QSlotObjectBase * this_, QObject * r, void * * a, bool * ret) Line 419
	at C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\buildenv\mixxx-deps-2.4-x64-windows-db02b82\installed\x64-windows\include\qt5\QtCore\qobjectdefs_impl.h(419)
[External Code]
mixxx.exe!MixxxApplication::notify(QObject * target, QEvent * event) Line 170
	at C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\mixxxapplication.cpp(170)
[External Code]
mixxx.exe!`anonymous namespace'::runMixxx(MixxxApplication * pApp, const CmdlineArgs & args) Line 82
	at C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\main.cpp(82)
mixxx.exe!main(int argc, char * * argv) Line 213
	at C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx\src\main.cpp(213)
[External Code]
```

<!DOCTYPE html>
<HTML>
<head>
<body>



  | Name | Value | Type
-- | -- | -- | --
▶ | this | 0x00000164c94753f0 {m_shader={...} m_vertices=0x00000164c9475500 {{mData={ size = 10878 } }, {mData=...}, ...} } | qopengl::WaveformRendererFiltered *
  | allGain | 5.28328943 | float
◢ | bandGain | 0x0000001213369c68 {1.00000000, 1.00000000, 1.00000000} | float[3]
  | [0] | 1.00000000 | float
  | [1] | 1.00000000 | float
  | [2] | 1.00000000 | float
  | breadth | 146.000000 | const float
  | colorLocation | 1 | const int
◢ | colors | 0x0000001213369e50 {{cspec=Rgb (1) ct={argb={alpha=65535 red=65535 green=17733 ...} ahsv={alpha=65535 ...} ...} }, ...} | QColor[4]
  | ◢ [0] | {cspec=Rgb (1) ct={argb={alpha=65535 red=65535 green=17733 ...} ahsv={alpha=65535 hue=65535 saturation=...} ...} } | QColor
  | cspec | Rgb (1) | QColor::Spec
  | ◢ ct | {argb={alpha=65535 red=65535 green=17733 ...} ahsv={alpha=65535 hue=65535 saturation=17733 ...} acmyk=...} | QColor::CT
  | ◢ argb | {alpha=65535 red=65535 green=17733 ...} | QColor::CT::<unnamed-type-argb>
  | alpha | 65535 | unsigned short
  | red | 65535 | unsigned short
  | green | 17733 | unsigned short
  | blue | 0 | unsigned short
  | pad | 0 | unsigned short
  | ◢ ahsv | {alpha=65535 hue=65535 saturation=17733 ...} | QColor::CT::<unnamed-type-ahsv>
  | alpha | 65535 | unsigned short
  | hue | 65535 | unsigned short
  | saturation | 17733 | unsigned short
  | value | 0 | unsigned short
  | pad | 0 | unsigned short
  | ◢ acmyk | {alpha=65535 cyan=65535 magenta=17733 ...} | QColor::CT::<unnamed-type-acmyk>
  | alpha | 65535 | unsigned short
  | cyan | 65535 | unsigned short
  | magenta | 17733 | unsigned short
  | yellow | 0 | unsigned short
  | black | 0 | unsigned short
  | ◢ ahsl | {alpha=65535 hue=65535 saturation=17733 ...} | QColor::CT::<unnamed-type-ahsl>
  | alpha | 65535 | unsigned short
  | hue | 65535 | unsigned short
  | saturation | 17733 | unsigned short
  | lightness | 0 | unsigned short
  | pad | 0 | unsigned short
  | ◢ argbExtended | {alphaF16=65535 redF16=65535 greenF16=17733 ...} | QColor::CT::<unnamed-type-argbExtended>
  | alphaF16 | 65535 | unsigned short
  | redF16 | 65535 | unsigned short
  | greenF16 | 17733 | unsigned short
  | blueF16 | 0 | unsigned short
  | pad | 0 | unsigned short
  | ◢ array | 0x0000001213369e54 {65535, 65535, 17733, 0, 0} | unsigned short[5]
  | [0] | 65535 | unsigned short
  | [1] | 65535 | unsigned short
  | [2] | 17733 | unsigned short
  | [3] | 0 | unsigned short
  | [4] | 0 | unsigned short
  | ◢ [1] | {cspec=Rgb (1) ct={argb={alpha=65535 red=0 green=25700 ...} ahsv={alpha=65535 hue=0 saturation=25700 ...} ...} } | QColor
  | cspec | Rgb (1) | QColor::Spec
  | ◢ ct | {argb={alpha=65535 red=0 green=25700 ...} ahsv={alpha=65535 hue=0 saturation=25700 ...} acmyk={alpha=...} ...} | QColor::CT
  | ◢ argb | {alpha=65535 red=0 green=25700 ...} | QColor::CT::<unnamed-type-argb>
  | alpha | 65535 | unsigned short
  | red | 0 | unsigned short
  | green | 25700 | unsigned short
  | blue | 0 | unsigned short
  | pad | 0 | unsigned short
  | ◢ ahsv | {alpha=65535 hue=0 saturation=25700 ...} | QColor::CT::<unnamed-type-ahsv>
  | alpha | 65535 | unsigned short
  | hue | 0 | unsigned short
  | saturation | 25700 | unsigned short
  | value | 0 | unsigned short
  | pad | 0 | unsigned short
  | ◢ acmyk | {alpha=65535 cyan=0 magenta=25700 ...} | QColor::CT::<unnamed-type-acmyk>
  | alpha | 65535 | unsigned short
  | cyan | 0 | unsigned short
  | magenta | 25700 | unsigned short
  | yellow | 0 | unsigned short
  | black | 0 | unsigned short
  | ◢ ahsl | {alpha=65535 hue=0 saturation=25700 ...} | QColor::CT::<unnamed-type-ahsl>
  | alpha | 65535 | unsigned short
  | hue | 0 | unsigned short
  | saturation | 25700 | unsigned short
  | lightness | 0 | unsigned short
  | pad | 0 | unsigned short
  | ◢ argbExtended | {alphaF16=65535 redF16=0 greenF16=25700 ...} | QColor::CT::<unnamed-type-argbExtended>
  | alphaF16 | 65535 | unsigned short
  | redF16 | 0 | unsigned short
  | greenF16 | 25700 | unsigned short
  | blueF16 | 0 | unsigned short
  | pad | 0 | unsigned short
  | ◢ array | 0x0000001213369e64 {65535, 0, 25700, 0, 0} | unsigned short[5]
  | [0] | 65535 | unsigned short
  | [1] | 0 | unsigned short
  | [2] | 25700 | unsigned short
  | [3] | 0 | unsigned short
  | [4] | 0 | unsigned short
  | ◢ [2] | {cspec=Rgb (1) ct={argb={alpha=65535 red=0 green=0 ...} ahsv={alpha=65535 hue=0 saturation=0 ...} acmyk=...} } | QColor
  | cspec | Rgb (1) | QColor::Spec
  | ◢ ct | {argb={alpha=65535 red=0 green=0 ...} ahsv={alpha=65535 hue=0 saturation=0 ...} acmyk={alpha=65535 cyan=...} ...} | QColor::CT
  | ◢ argb | {alpha=65535 red=0 green=0 ...} | QColor::CT::<unnamed-type-argb>
  | alpha | 65535 | unsigned short
  | red | 0 | unsigned short
  | green | 0 | unsigned short
  | blue | 52685 | unsigned short
  | pad | 0 | unsigned short
  | ◢ ahsv | {alpha=65535 hue=0 saturation=0 ...} | QColor::CT::<unnamed-type-ahsv>
  | alpha | 65535 | unsigned short
  | hue | 0 | unsigned short
  | saturation | 0 | unsigned short
  | value | 52685 | unsigned short
  | pad | 0 | unsigned short
  | ◢ acmyk | {alpha=65535 cyan=0 magenta=0 ...} | QColor::CT::<unnamed-type-acmyk>
  | alpha | 65535 | unsigned short
  | cyan | 0 | unsigned short
  | magenta | 0 | unsigned short
  | yellow | 52685 | unsigned short
  | black | 0 | unsigned short
  | ◢ ahsl | {alpha=65535 hue=0 saturation=0 ...} | QColor::CT::<unnamed-type-ahsl>
  | alpha | 65535 | unsigned short
  | hue | 0 | unsigned short
  | saturation | 0 | unsigned short
  | lightness | 52685 | unsigned short
  | pad | 0 | unsigned short
  | ◢ argbExtended | {alphaF16=65535 redF16=0 greenF16=0 ...} | QColor::CT::<unnamed-type-argbExtended>
  | alphaF16 | 65535 | unsigned short
  | redF16 | 0 | unsigned short
  | greenF16 | 0 | unsigned short
  | blueF16 | 52685 | unsigned short
  | pad | 0 | unsigned short
  | ◢ array | 0x0000001213369e74 {65535, 0, 0, 52685, 0} | unsigned short[5]
  | [0] | 65535 | unsigned short
  | [1] | 0 | unsigned short
  | [2] | 0 | unsigned short
  | [3] | 52685 | unsigned short
  | [4] | 0 | unsigned short
  | ◢ [3] | {cspec=Invalid (0) ct={argb={alpha=65535 red=0 green=0 ...} ahsv={alpha=65535 hue=0 saturation=0 ...} ...} } | QColor
  | cspec | Invalid (0) | QColor::Spec
  | ◢ ct | {argb={alpha=65535 red=0 green=0 ...} ahsv={alpha=65535 hue=0 saturation=0 ...} acmyk={alpha=65535 cyan=...} ...} | QColor::CT
  | ◢ argb | {alpha=65535 red=0 green=0 ...} | QColor::CT::<unnamed-type-argb>
  | alpha | 65535 | unsigned short
  | red | 0 | unsigned short
  | green | 0 | unsigned short
  | blue | 0 | unsigned short
  | pad | 0 | unsigned short
  | ◢ ahsv | {alpha=65535 hue=0 saturation=0 ...} | QColor::CT::<unnamed-type-ahsv>
  | alpha | 65535 | unsigned short
  | hue | 0 | unsigned short
  | saturation | 0 | unsigned short
  | value | 0 | unsigned short
  | pad | 0 | unsigned short
  | ◢ acmyk | {alpha=65535 cyan=0 magenta=0 ...} | QColor::CT::<unnamed-type-acmyk>
  | alpha | 65535 | unsigned short
  | cyan | 0 | unsigned short
  | magenta | 0 | unsigned short
  | yellow | 0 | unsigned short
  | black | 0 | unsigned short
  | ◢ ahsl | {alpha=65535 hue=0 saturation=0 ...} | QColor::CT::<unnamed-type-ahsl>
  | alpha | 65535 | unsigned short
  | hue | 0 | unsigned short
  | saturation | 0 | unsigned short
  | lightness | 0 | unsigned short
  | pad | 0 | unsigned short
  | ◢ argbExtended | {alphaF16=65535 redF16=0 greenF16=0 ...} | QColor::CT::<unnamed-type-argbExtended>
  | alphaF16 | 65535 | unsigned short
  | redF16 | 0 | unsigned short
  | greenF16 | 0 | unsigned short
  | blueF16 | 0 | unsigned short
  | pad | 0 | unsigned short
  | ◢ array | 0x0000001213369e84 {65535, 0, 0, 0, 0} | unsigned short[5]
  | [0] | 65535 | unsigned short
  | [1] | 0 | unsigned short
  | [2] | 0 | unsigned short
  | [3] | 0 | unsigned short
  | [4] | 0 | unsigned short
◢ | data | 0x00000164ff2d4aa0 {filtered={low=0 '\0' mid=0 '\0' high=0 '\0' ...} m_i=0 } | const WaveformData *
  | ◢ filtered | {low=0 '\0' mid=0 '\0' high=0 '\0' ...} | WaveformData::<unnamed-type-filtered>
  | low | 0 '\0' | unsigned char
  | mid | 0 '\0' | unsigned char
  | high | 0 '\0' | unsigned char
  | all | 0 '\0' | unsigned char
  | m_i | 0 | int
  | dataSize | 11252 | const int
  | devicePixelRatio | 1.00000000 | const float
  | firstVisualIndex | -1111.9631623552432 | const double
  | halfBreadth | 73.0000000 | const float
  | heightFactor | 1.51247108 | const float
  | lastVisualIndex | 2514.0471497963736 | const double
  | length | 1813 | const int
◢ | matrix | { m11 = 0.00110314391, m12 = 0.00000000, m13 = 0.00000000, m14 = -1.00000000, ... } | QMatrix4x4
  | [m11] | 0.00110314391 | float
  | [m12] | 0.00000000 | float
  | [m13] | 0.00000000 | float
  | [m14] | -1.00000000 | float
  | [m21] | 0.00000000 | float
  | [m22] | -0.0136986300 | float
  | [m23] | 0.00000000 | float
  | [m24] | 1.00000000 | float
  | [m31] | 0.00000000 | float
  | [m32] | 0.00000000 | float
  | [m33] | -1.00000000 | float
  | [m34] | 0.00000000 | float
  | [m41] | 0.00000000 | float
  | [m42] | 0.00000000 | float
  | [m43] | 0.00000000 | float
  | [m44] | 1.00000000 | float
  | ▶ [Raw View] | {m=0x0000001213369de0 {0x0000001213369de0 {0.00110314391, 0.00000000, 0.00000000, 0.00000000}, 0x0000001213369df0 {...}, ...} ...} | QMatrix4x4
  | matrixLocation | 0 | const int
  | numVerticesPerLine | 6 | const int
  | positionLocation | 0 | const int
◢ | pTrack | shared_ptr {m_qMutex={...} m_fileAccess={m_fileInfo={m_fileInfo={d_ptr=pointer to implicit shared object of type "QFileInfoPrivate" } } ...} ...} [27 strong refs, 1 weak ref] [{_Uses=27 _Weaks=2 }] | std::shared_ptr<Track>
  | ◢ [ptr] | 0x00000164d484d570 {m_qMutex={...} m_fileAccess={m_fileInfo={m_fileInfo={d_ptr=pointer to implicit shared object of type "QFileInfoPrivate" } } ...} ...} | Track *
  | ▶ QObject | {d_ptr=scoped pointer to a dynamically allocated object of type "QObjectData" } | QObject
  | ▶ m_qMutex | {...} | QRecursiveMutex
  | ▶ m_fileAccess | {m_fileInfo={m_fileInfo={d_ptr=pointer to implicit shared object of type "QFileInfoPrivate" } } m_pSecurityToken=...} | mixxx::FileAccess
  | ◢ m_record | {m_metadata={m_streamInfo={m_signalInfo={m_channelCount={m_value=2 '\x2' } m_sampleRate={m_value=48000 } } ...} ...} ...} | mixxx::TrackRecord
  | ▶ m_metadata | {m_streamInfo={m_signalInfo={m_channelCount={m_value=2 '\x2' } m_sampleRate={m_value=48000 } } m_bitrate=...} ...} | mixxx::TrackMetadata
  | ▶ m_id | {...} | TrackId
  | ▶ m_sourceSynchronizedAt | {d={d=0x0000000000000001 {...} data={status=1 msecs=0 } } } | QDateTime
  | ▶ m_coverInfo | {source=GUESSED (1) type=NONE (0) color=nullopt ...} | CoverInfoRelative
  | ▶ m_dateAdded | {d={d=0x0001866e6c182b1f {...} data={status=31 msecs=1676889823275 } } } | QDateTime
  | ▶ m_fileType | wav | QString
  | ▶ m_url |   | QString
  | ▶ m_playCounter | {m_timesPlayed=3 m_lastPlayedAt={d={d=0x000187cdddc9481f {...} data={status=31 msecs=1682786077000 } } } ...} | PlayCounter
  | ▶ m_color | nullopt | std::optional<mixxx::RgbColor>
  | ▶ m_mainCuePosition | {m_framePosition=0.0000000000000000 } | mixxx::audio::FramePos
  | m_rating | 0 | int
  | m_bpmLocked | false | bool
  | ▶ m_keys | {m_subVersion=vamp_plugin_id=qm-keydetector:2 m_keyMap={_impl_={_has_bits_={has_bits_=0x00000164d484d728 {...} } ...} } } | Keys
  | ▶ m_streamInfoFromSource | {m_signalInfo={m_channelCount={m_value=2 '\x2' } m_sampleRate={m_value=48000 } } m_bitrate={m_value=...} ...} | std::optional<mixxx::audio::StreamInfo>
  | m_headerParsed | true | bool
  | m_bDirty | false | bool
  | m_bMarkedForMetadataExport | false | bool
  | ◢ m_cuePoints | { size = 4 } | QList<CuePointer>
  | ▶ [referenced] | 1 | std::atomic<int>
  | ▶ [0] | shared_ptr {m_mutex={...} m_bDirty=false m_dbId={m_value=1234 } ...} [1 strong ref] [custom deleter] | CuePointer
  | ▶ [1] | shared_ptr {m_mutex={...} m_bDirty=false m_dbId={m_value=1235 } ...} [1 strong ref] [custom deleter] | CuePointer
  | ▶ [2] | shared_ptr {m_mutex={...} m_bDirty=false m_dbId={m_value=1236 } ...} [1 strong ref] [custom deleter] | CuePointer
  | ▶ [3] | shared_ptr {m_mutex={...} m_bDirty=false m_dbId={m_value=1384 } ...} [1 strong ref] [custom deleter] | CuePointer
  | ▶ [Raw View] | {p={d=0x00000164c96c9d90 {ref={atomic=1 } alloc=6 begin=0 ...} } d=0x00000164c96c9d90 {ref={atomic=1 } ...} } | QList<CuePointer>
  | ◢ m_pBeats | shared_ptr {m_markers={ size=0 } m_lastMarkerPosition={m_framePosition=0.0000000000000000 } m_lastMarkerBpm={m_value=...} ...} [6 strong refs] [default] | std::shared_ptr<mixxx::Beats const>
  | ◢ [ptr] | 0x00000164dd173e30 {m_markers={ size=0 } m_lastMarkerPosition={m_framePosition=0.0000000000000000 } ...} | const mixxx::Beats *
  | ▶ std::enable_shared_from_this<mixxx::Beats> | {_Wptr=empty } | std::enable_shared_from_this<mixxx::Beats>
  | ▶ m_markers | { size=0 } | std::vector<mixxx::BeatMarker,std::allocator<mixxx::BeatMarker>>
  | ▶ m_lastMarkerPosition | {m_framePosition=0.0000000000000000 } | mixxx::audio::FramePos
  | ▶ m_lastMarkerBpm | {m_value=125.49802398681641 } | mixxx::Bpm
  | ▶ m_sampleRate | {m_value=48000 } | mixxx::audio::SampleRate
  | ▶ m_subVersion |   | const QString
  | ▶ [control block] | default | std::_Ref_count_base {std::_Ref_count<mixxx::Beats>}
  | ▶ [Raw View] | {...} | std::shared_ptr<mixxx::Beats const>
  | ▶ m_waveform | strong reference to shared pointer of type "Waveform const" | QSharedPointer<Waveform const>
  | ◢ m_waveformSummary | strong reference to shared pointer of type "Waveform const" | QSharedPointer<Waveform const>
  | [is null] | false | bool
  | ▶ [weak referenced] | 3 | std::atomic<int>
  | ▶ [strong referenced] | 3 | std::atomic<int>
  | ▶ [Raw View] | {value=0x00000164b3acab80 {m_id=448 m_saveState=Saved (2) m_version=WaveformSummary-5.0 ...} d=0x00000164d6164750 {...} } | QSharedPointer<Waveform const>
  | ▶ m_pBeatsImporterPending | empty | std::shared_ptr<mixxx::BeatsImporter>
  | ▶ m_pCueInfoImporterPending | empty | std::shared_ptr<mixxx::CueInfoImporter>
  | ◢ [control block] | {_Uses=27 _Weaks=2 } | std::_Ref_count_base
  | ▶ __vfptr | 0x00007ff735392790 {mixxx.exe!void(* std::_Ref_count_resource<Track *,EvictAndSaveFunctor>::`vftable'[5])()} {...} | void * *
  | _Uses | 27 | unsigned long
  | _Weaks | 2 | unsigned long
  | ◢ [Raw View] | {...} | std::shared_ptr<Track>
  | ▶ std::_Ptr_base<Track> | {_Ptr=0x00000164d484d570 {m_qMutex={...} m_fileAccess={m_fileInfo={m_fileInfo={d_ptr=pointer to implicit shared object of type "QFileInfoPrivate" } } ...} ...} ...} | std::_Ptr_base<Track>
◢ | reserved | 0x0000001213369ca8 {10878, 10878, 10878, 6} | int[4]
  | [0] | 10878 | int
  | [1] | 10878 | int
  | [2] | 10878 | int
  | [3] | 6 | int
  | visualIncrementPerPixel | 2.0000056878938870 | const double
▶ | waveform | strong reference to shared pointer of type "Waveform const" | QSharedPointer<Waveform const>
  | xVisualSampleIndex | 2514.0471497964072 | double



</body>
</HTML>


<!DOCTYPE html>
<HTML>
<head>
<body>



  | Name | Value | Type
-- | -- | -- | --
◢ | m_shader | {...} | qopengl::UnicolorShader
  | ◢ qopengl::Shader | {...} | qopengl::Shader
  | ◢ QOpenGLShaderProgram | {...} | QOpenGLShaderProgram
  | ◢ QObject | {d_ptr=scoped pointer to a dynamically allocated object of type "QObjectData" } | QObject
  | ◢ __vfptr | 0x00007ff73627a838 {mixxx.exe!void(* qopengl::UnicolorShader::`vftable'[13])()} {0x00007ff73485c48b {mixxx.exe!QOpenGLShaderProgram::metaObject(void)const }, ...} | void * *
  | [0] | 0x00007ff73485c48b {mixxx.exe!QOpenGLShaderProgram::metaObject(void)const } | void *
  | [1] | 0x00007ff73485c491 {mixxx.exe!QOpenGLShaderProgram::qt_metacast(char const *)} | void *
  | [2] | 0x00007ff73485c497 {mixxx.exe!QOpenGLShaderProgram::qt_metacall(enum QMetaObject::Call,int,void * *)} | void *
  | [3] | 0x00007ff733b83fa6 {mixxx.exe!qopengl::UnicolorShader::`vector deleting destructor'(unsigned int)} | void *
  | [4] | 0x00007ff7348b008f {mixxx.exe!QObject::event(class QEvent *)} | void *
  | [5] | 0x00007ff7348b0095 {mixxx.exe!QObject::eventFilter(class QObject *,class QEvent *)} | void *
  | [6] | 0x00007ff7348b009b {mixxx.exe!QObject::timerEvent(class QTimerEvent *)} | void *
  | [7] | 0x00007ff7348b00a1 {mixxx.exe!QObject::childEvent(class QChildEvent *)} | void *
  | [8] | 0x00007ff7348b00a7 {mixxx.exe!QObject::customEvent(class QEvent *)} | void *
  | [9] | 0x00007ff7348b00ad {mixxx.exe!QObject::connectNotify(class QMetaMethod const &)} | void *
  | [10] | 0x00007ff7348b00b3 {mixxx.exe!QObject::disconnectNotify(class QMetaMethod const &)} | void *
  | ◢ d_ptr | scoped pointer to a dynamically allocated object of type "QObjectData" | QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData>>
  | [is null] | false | bool
  | ◢ [Raw View] | {d=0x00000164ff65aae0 <Information not available, no symbols loaded for Qt5Guid.dll> } | QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData>>
  | ▶ d | 0x00000164ff65aae0 <Information not available, no symbols loaded for Qt5Guid.dll> | QObjectData *
  | positionLocation | 0 | const int
◢ | this | 0x00000164c94753f0 {m_shader={...} m_vertices=0x00000164c9475500 {{mData={ size = 10878 } }, {mData=...}, ...} } | qopengl::WaveformRendererFiltered *
  | ▶ qopengl::WaveformRendererSignalBase | {...} | qopengl::WaveformRendererSignalBase
  | ◢ m_shader | {...} | qopengl::UnicolorShader
  | ◢ qopengl::Shader | {...} | qopengl::Shader
  | ◢ QOpenGLShaderProgram | {...} | QOpenGLShaderProgram
  | ▶ QObject | {d_ptr=scoped pointer to a dynamically allocated object of type "QObjectData" } | QObject
  | ◢ m_vertices | 0x00000164c9475500 {{mData={ size = 10878 } }, {mData={ size = 10878 } }, {mData={ size = 10878 } }, ...} | qopengl::VertexData[4]
  | ▶ [0] | {mData={ size = 10878 } } | qopengl::VertexData
  | ▶ [1] | {mData={ size = 10878 } } | qopengl::VertexData
  | ▶ [2] | {mData={ size = 10878 } } | qopengl::VertexData
  | ▶ [3] | {mData={ size = 6 } } | qopengl::VertexData



</body>
</HTML>

</details>

**Comment by Swiftb0y** [comment]
> > IMO we should merge this soon and then go into a 6 month 2.4 beta.
> 
> @Swiftb0y: You mean 2.5 beta, right? For me, it is not acceptable to delay 2.4 for this.

Sorry, I was not aware we were already in the 2.4 beta phase. But no, I meant 2.4.

Our current waveform implementations are falling apart with newer drivers (I just didn't notice sooner because Mixxx silently fell back to the CPU-rendered waveforms some time ago). I don't want to go in to the bug vs feature discussion but IMO our current waveforms are buggy on multiple platforms and this is the only consistent long-term fix! If delaying 2.4 is out of the question, then lets stay on-schedule, but Mixxx 2.4 is significantly worse without this PR than with, even if the code is not not bug-free and well tested nor very polished, our current waveforms are anything but bug-free either!

File: src/waveform/widgets/qopengl/waveformwidget.cpp [hunk 69]
```diff
@@ -32,23 +35,23 @@ void WaveformWidget::renderGL() {
...
+            renderer->qopenglWaveformRenderer()->renderGL();
         }
     }
 }
 
 void WaveformWidget::initializeGL() {
-    for (int i = 0; i < m_rendererStack.size(); ++i) {
-        m_rendererStack[i]->qopenglWaveformRenderer()->initializeOpenGLFunctions();
-        m_rendererStack[i]->qopenglWaveformRenderer()->initializeGL();
+    for (auto renderer : m_rendererStack) {
```
Comment (Swiftb0y) [inline src/waveform/widgets/qopengl/waveformwidget.cpp:45]: to fix clazy, same below.
```suggestion
    for (auto renderer : std::as_const(m_rendererStack)) {
```

Comment (m0dB) [reply src/waveform/widgets/qopengl/waveformwidget.cpp]: thanks. DONE.

**Comment by m0dB** [comment]
> On Windows I get reproduceable `Run-Time Check Failure #2 - Stack around the variable 'colors' was corrupted.` when I use All-Shaders-Filtered-Waveform type. All other waveform types work.

Thanks, fixed. A stupid typo.

**Comment by JoergAtGithub** [comment]
> > On Windows I get reproduceable `Run-Time Check Failure #2 - Stack around the variable 'colors' was corrupted.` when I use All-Shaders-Filtered-Waveform type. All other waveform types work.
> 
> Thanks, fixed. A stupid typo.

Confirm that this is fixed now! All waveform types work now on Windows!

**Comment by JoergAtGithub** [comment]
I noticed another assert, when I scratch with the mouse far before the begin of the track:
grafik

**Comment by JoergAtGithub** [comment]
> Sorry, I was not aware we were already in the 2.4 beta phase.

Of cause we are not, we are in step 9 "**Polish the 2.4-alpha** for beta tests" of the [Beta checklist](https://github.com/mixxxdj/mixxx/wiki/Mixxx-Beta-Checklist-2.4-beta)

File: src/widget/openglwindow.cpp (hunk 56 above)
Comment (m0dB) [reply src/widget/openglwindow.cpp]: This was to avoid flickering when resizing. I have moved the extra call to renderGL and swapBuffers to resizeGL and added a comment to make this more clear.

**Comment by Swiftb0y** [comment]
Great, so lets merge and go into the 6 month beta. Any further refactorings and fixes on top of this one can just go into the beta branch.

**Comment by daschuer** [comment]
To clarify: 
This should go to main for Mixxx 2.5 scheduled to for release in 6 month.
In the meantime we will release 2.3.5 (immediately after the checklist is done) and 2.4.0 (after 3 Month beta)   
Once this is merged we can prepare the 2.5 beta in a 2.5 branch. This is required to avoid feature creep. Unrelated new features can go to main. Unrelated bug fixes can go to 2.3 or 2.4.    
This way nothing is delayed. 
Do we all agree?

**Comment by JoergAtGithub** [comment]
I strictly disagree! This PR fixes severe bugs and it must go into 2.4!
But this does not mean any delay for 2.4, because we can merge it immediately into 2.4 branch. As @Swiftb0y and others pointed out above, this PR is already better than the current 2.4 branch.

**Comment by daschuer** [comment]
The issue is that this PR deserves a full 6 month beta and will this way delay 2.4 which has already received a very good amount of testing. So we are not talking about delaying this PR reaching the stable state. We all agree that this needs to be released without further delay or any "one last PR" 

The question is if we have a 2.4 before or not. Since the process of releasing 2.4 beta has already started, I have no interest to delay it any further.

**Comment by m0dB** [comment]
@Swiftb0y I have solved the issue with key events and addressed something you mentioned some time ago: I was using my own method to forward events from the openglwindow to the widget. You suggested to call event(QEvent*) directly, but this wasn't possible because it is protected. But the correct way, which solves the key events and makes the custom method unnecessary is to use QApplication::sendEvent.

I was hoping this would also make the custom tooltip code unnecessary, but unfortunately that doesn't seem to be the case.

**Comment by m0dB** [comment]
@JoergAtGithub the debug assert in waveformrendererpreroll.cpp is fixed.

**Comment by m0dB** [comment]
I am sorry that this PR is causing conflicting opinions when it comes to inclusion in 2.4.

I strongly feel it should be included. I also think the risk is not that big. Sure, it's a lot of lines of code, but that's mainly because of the additional waveform types, which are optional, and the glsl based spinny and vumeter which are also optional  (at least in the code).

The remaining code is the QOpenGLWindow-based widget alternative for the deprecated QGLWidget, and some small changes in the code that uses these widgets, to allow to switch between the two at compile time. This is really not that much code, and it is all UI code, so any issues are likely to be quickly visible during beta.

As I mentioned before, we could also opt to stick with the QGLWidget based implementation on Window and Linux, which means that for those the changes would be minimal. On macOS the performance difference is so big (as in running at 30 fps with high CPU load vs 60 fps with low CPU load) that in my opinion it is certainly worth the risk.

**Comment by daschuer** [comment]
So you vote for a short 3 month beta? I am hesitating to do that, because of the big variety of system out there.

**Comment by JoergAtGithub** [comment]
> @JoergAtGithub the debug assert in waveformrendererpreroll.cpp is fixed.

Confirmed! All waveforms, old and new, work now without assertions on Windows11.

**Comment by Swiftb0y** [comment]
> The issue is that this PR deserves a full 6 month beta and will this way delay 2.4 which has already received a very good amount of testing. So we are not talking about delaying this PR reaching the stable state. We all agree that this needs to be released without further delay or any "one last PR"
> 
> The question is if we have a 2.4 before or not. Since the process of releasing 2.4 beta has already started, I have no interest to delay it any further.

There is no reason to delay 2.4. This PR is ready enough and can be merged any time. Releasing 2.4 without this PR will result in Mixxx being broken on our second largest platform, alienating lots of users.

**Comment by Swiftb0y** [comment]
> So you vote for a short 3 month beta? I am hesitating to do that, because of the big variety of system out there.

Can you elaborate?
IMO this PR is pretty rock-solid in terms of expected behavior from drivers and so forth because the implementations of the waveforms is very idiomatic. IMO Pushing a mesh to the GPU and then rendering that using simple vertex and fragment-shaders should be well supported by any graphics drivers. Any other "risky" code in this PR is mostly independent from any system-specific quirks so I don't expect any obscure or difficult to debug issues to arise from that.

**Comment by Swiftb0y** [comment]
Another small benefit, the new waveforms introduced here also significantly faster on the already working platforms:
* Empty (baseline / control)
Empty
* RGB (CPU)
RGB CPU
* RGB (GL)
RGB GL
* RGB (GLSL)
RGB GLSL
* RGB (all-shaders) (this PR)
RGB #10989

The same metrics also apply to all the other waveform styles. Unfortunately our waveforms still suffer from predictable hitches (already pointed out by daschauer previously), but that is common across all types and not a regression from this PR.

**Comment by Swiftb0y** [comment]
> @Swiftb0y I have solved the issue with key events and addressed something you mentioned some time ago: I was using my own method to forward events from the openglwindow to the widget. You suggested to call event(QEvent*) directly, but this wasn't possible because it is protected. But the correct way, which solves the key events and makes the custom method unnecessary is to use QApplication::sendEvent.
> 
> I was hoping this would also make the custom tooltip code unnecessary, but unfortunately that doesn't seem to be the case.

Thank you. I can confirm the "missing focus after scratching" issue has been resolved. Unfortunately the tooltip for the waveform doesn't work anymore now as far as I can tell (I didn't test it before the patch, so it might have never worked on my system). I'm also experiencing weird hovering behavior for the hotcue marks. They don't properly get "unhovered" after you move the cursor away.
I consider both of these issues minor enough to not be a blocker for merge though. We just need to keep track of them to fix them afterwards during the beta.

**Review by Swiftb0y — APPROVED** [review]

**Comment by daschuer** [comment]
@Swiftb0y: How long should the beta take. 
Yourself have confirmed 6 month above and I have confirmed that as a reasonable period. Once this is merged, every user has the freedom to use the target brach immediately.

For my understanding the issues solved here are also happening in  2.3 which was OK for the time being. The waveform background bug needs to be solved anyway independently for 2.3. 

From my experience there are many issues with different and partially outdated graphics driver out there we have no chystal ball to predict future issue. Every issue will delay a release. 

We have already cut out the 2.4 branch 6 month ago. So and have not merged mayor features since then. So we are very confident that 2.4 is pretty stable.

I see no reason to couple both topics inrevertable. Please let's keep both separate to have the feedom to decide when we release what. 

We are very good in delaying things because of minor issues and fail toget things out. 

What is your proposed schedule? 

Please consider also the open 2.3.5 issues. It feels mood to discuss waveform performance without releasing fixed for mayor regressions in our stable branch. Than have a look at the long list of features in the 2.4 branch that have been settled for many month ....

**Comment by m0dB** [comment]
> Another small benefit, the new waveforms introduced here also significantly faster on the already working platforms. I've made these measurements on Linux with integrated Intel graphics but I imagine you can observe similar metrics on Windows:

Nice! I assume you used this branch for all waveform types? It would be interesting to compare with the other waveforms using QGLWidget.

Btw, I think the fastest would be the combination of the GLSL waveform renderer implementation (the one that uses the waveform stored in a texture) with my renderers for the other layers. Would be trivial to add.

**Comment by Swiftb0y** [comment]
> @Swiftb0y: How long should the beta take.
Yourself have confirmed 6 month above and I have confirmed that as a reasonable period.

I don't particularly care. 6 months is fine, I'd even argue 3 months is fine as I don't expect any major regression to occur from this PR. 

> Once this is merged, every user has the freedom to use the target brach immediately.

Can you elaborate? 

> For my understanding the issues solved here are also happening in 2.3 which was OK for the time being. The waveform background bug needs to be solved anyway independently for 2.3.

Right, but the issues on 2.3 only started appearing recently (and possibly only using very new drivers). Any fix for 2.3 won't be very long term while I have simply much more trust in the sustainability of the solution implemented in this PR. 

**As I said previously: I don't want to open a feature vs bug debate but from the PoV of an ordinary user, this PR is not a feature but a necessary bug fix for an issue that we've been fighting for years!** From the PoV of our end-users which are suffering from performance and UI issues stemming from our current waveforms, upgrading to Mixxx 2.4 without this PR will not be an option. 

> What is your proposed schedule?

Merge this PR in the next coming days then carry on with the remaining tasks on the release checklist so we can carry on with getting the release out. During the beta phase, we can continue polishing the code. Do you want me to get into more detail?

---

I refuse to argue about this much longer. If this discussion continues for another round, I will call for a formal vote on Zulip!

**Comment by Swiftb0y** [comment]
> Nice! I assume you used this branch for all waveform types? It would be interesting to compare with the other waveforms using QGLWidget.

Yes. I might do that later today if I remember to do so. 

> Btw, I think the fastest would be the combination of the GLSL waveform renderer implementation (the one that uses the waveform stored in a texture) with my renderers for the other layers. Would be trivial to add.

Are you sure, from my tests the GLSL version has been by far the most demanding and also unusably slow. I think a much more promising optimization would be to generate the waveform mesh upfront and then only ever upload the parts of it that are actually on screen. Otherwise the CPU will do 95% of the same work on each frame (since most parts of the waveforms remain onscreen from the previous frame). But we can discuss that some other time. I don't know why the current texture based GLSL waveforms are running this badly but you can see on the screenshot that there are much higher IMC read and writes, and the GPU turbos to about 3-4 times the clockspeed of the other waveforms while still being unable to keep up.

**Comment by m0dB** [comment]
No, I am not sure, so trying it out is the only way. But yeah, not a priority.

**Comment by m0dB** [comment]
> Yes. I might do that later today if I remember to do so.

Running cmake with -DQOPENGL=OFF should do the trick :-)

**Comment by daschuer** [comment]
Ok, do we all agree to release this after a 6 month beta period? This sounds reasonable. Effected user can already use the beta branch, maybe we find a band aid for the 2.3 branch background issue as well. 

Now the critical question: what to do with the current 2.4 branch. We have maintained it already for 6 month without calling it beta. Lately it has only received low risk PRs and I'd full of nice features. 

Ideas? Please outline a plan. 

My current prior is to bring out 2.3.5 it includes important regression fixes. Is is kind of arwkward that we still call 2.3.4 "stable" . That is the most important thing IMHO.

**Comment by m0dB** [comment]
I could give fixing the background issue in 2.3 a try, but I wouldn't want that to make integrating this branch in 2.4 less urgent ;-)

On a side note, I think that there is another for good reason to merge this branch: it opens the door to other improvements, such as moving to Qt 6, using a dedicated thread for the waveform, spinnies and vumeters, and doing some cleanup (if the new waveform types are widely accepted and the QOpenGL stuff works for everyone, we could remove a lot of old code) and (maybe a stretch) potentially exploring the combination of QML and the legacy UI.

It's true that that could also be done only with main, but if we go for 2.4 all this would get a lot more traction.

**Comment by atskler** [comment]
@daschuer > Effected user can already use the beta branch, maybe we find a band aid for the 2.3 branch background issue as well.

Then 2.4 will be another crippled release, just as the 2.3.4 is, and again there will be no release for months with proper performance, and again a user have to build and use beta for himself, because only that will do the job properly.

**Comment by atskler** [comment]
> @daschuer > Effected user can already use the beta branch, maybe we find a band aid for the 2.3 branch background issue as well.
> 
> Then 2.4 will be another crippled release, just as the 2.3.4 is, and again there will be no release for months with proper performance, and again a user have to build and use beta for himself, because only that will do the job properly.

@daschuer I misunderstood what you wrote. I'm sorry for that. Please ignore what I wrote.

**Comment by m0dB** [comment]
> Unfortunately the tooltip for the waveform doesn't work anymore now as far as I can tell 

Fixed.

> (I didn't test it before the patch, so it might have never worked on my system).

It never worked. I hadn't realized the waveform viewer _had_ a tooltip!

> I'm also experiencing weird hovering behavior for the hotcue marks. They don't properly get "unhovered" after you move the cursor away.

It's when moving the cursor away and "away" is also outside the waveform widget, right? (typically moving down) ? Or are you seeing something else?

**Comment by Swiftb0y** [comment]
> Ideas? Please outline a plan.

Lets take this to zulip: https://mixxx.zulipchat.com/#narrow/stream/109171-development/topic/2.2E4.20beta

**Comment by m0dB** [comment]
hotcue hovering is fixed.

File: src/widget/wglwidgetqopengl.h [hunk 70]
```diff
@@ -35,6 +36,17 @@ class WGLWidget : public QWidget {
...
+    // WGLWidget. This function allows to override that with a different
+    // receiver. This is used for WWaveformViewer.
+    void setEventReceiver(QWidget* target) {
+        m_pEventReceiver = target;
+    }
+
+    QWidget* eventReceiver() const {
+        return m_pEventReceiver;
+    }
+
```
Comment (Swiftb0y) [inline src/widget/wglwidgetqopengl.h:49]: whats the ownership relationship here? Is this non-owning, if so what do the lifetime requirements look like?

File: src/widget/wwaveformviewer.cpp [hunk 71]
```diff
@@ -268,11 +268,12 @@ void WWaveformViewer::setWaveformWidget(WaveformWidgetAbstract* waveformWidget)
...
-        // normal Qt tooltip mechanism and uses it's own mechanism. We set the tooltip
-        // of the waveform widget to the tooltip of its parent WWaveformViewer so the
-        // OpenGLWindow will display it.
-        m_waveformWidget->getWidget()->setToolTip(toolTip());
+        if (m_waveformWidget->getGLWidget()) {
+            // The WGLWidget's OpenGLWindow should send its events here
+            // instead of to the WGLWidget itself. Also used for the
+            // OpenGLWindow's tooltip mechanism.
+            m_waveformWidget->getGLWidget()->setEventReceiver(this);
+        }
```
Comment (Swiftb0y) [inline src/widget/wwaveformviewer.cpp:276]: why can't the WGLWidget just forward its event to the viewer? this seems a little inflexible (I'm not super familiar with Qt's event delivery system).

**Comment by Swiftb0y** [comment]
> hotcue hovering is fixed.

Yes, thank you. I didn't have the time to properly respond to you earlier. I'll try to test this out tomorrow.

> It's when moving the cursor away and "away" is also outside the waveform widget, right? (typically moving down) ?

Ah yes, it gets stuck when I move the cursed outside the viewer of that particular channel, so in practice when I move it down. Exactly.

> I could give fixing the background issue in 2.3 a try, but I wouldn't want that to make integrating this branch in 2.4 less urgent ;-)

That would be highly appreciated.

File: src/widget/wwaveformviewer.cpp (hunk 71 above)
Comment (m0dB) [reply src/widget/wwaveformviewer.cpp:276]: Not the WGLWidget, but the derived waveform widget, but yes, I see what you mean, and this _is_ a bit convoluted. A potential problem is that the WGLWidget will receive events both from the openglwindow and from the mainwindow. But let me try if that really is a problem.

Comment (m0dB) [reply src/widget/wwaveformviewer.cpp]: Done.

**Comment by JoergAtGithub** [comment]
Could you please rebase to the latest version of the 2.4 branch, than I will do a full test on Windows 7 and Windows 11 again.

**Comment by m0dB** [comment]
I have adapted the solution for the background color bug for 2.3 , https://github.com/mixxxdj/mixxx/pull/11523 , to this branch and I have moved some files around and changes some namespaces (qopengl:: was a bad choice, as the shaders and waveform renderers and widgets aren't particularly tight to QOpenGL and can easily be adapted to the old QGL classes, it's only the qopengl version of WGLWidget that really depends on QOpenGL). I hope that this is my final commit to the branch. I will rebase on 2.4 now.

File: src/waveform/widgets/glwaveformwidgetabstract.h [hunk 72]
```diff
@@ -23,6 +23,12 @@ class GLWaveformWidgetAbstract : public WaveformWidgetAbstract, public WGLWavefo
     }
 
   protected:
+#ifdef MIXXX_USE_QOPENGL
+    void renderGL() override {
+        // called by OpenGLWindow to avoid flickering on resize
+        static_cast<WaveformWidgetAbstract*>(this)->render();
+    }
```
Comment (Swiftb0y) [inline src/waveform/widgets/glwaveformwidgetabstract.h]: The static cast seems unnecessary? I thought the correct way to call parent functions was `WaveformWidgetAbstract::render()`?

**Comment by Swiftb0y** [comment]
new formatting issues arose, can you fix them?

File: src/waveform/widgets/glwaveformwidgetabstract.h (hunk 72 above)
Comment (m0dB) [reply src/waveform/widgets/glwaveformwidgetabstract.h]: WaveformWidgetAbstract::render() is a virtual. Calling it like that will call that exact function, in the base class, and not the override.

Comment (Swiftb0y) [reply src/waveform/widgets/glwaveformwidgetabstract.h]: Ah, I thought that was the intention. Then if virtual dispatch is desired, why would just calling plain `render()` without the cast not work?

**Comment by m0dB** [comment]
Rebased on 2.4 and final clean-up pass done, which includes some minor changes in order to also compile the glsl shader based waveforms, spinnies and vumeters also when -DQOPENGL=OFF  (in other words, when using the legacy QGLWidget). (By default, the shader based versions of vumeter and spinny are used, but it is possible to revert this with a preprocessor define).

I have done some smoke-testing, of both -DQOPENGL=OFF and -DQOPENGL=ON builds, to make sure the rebase and these final changes didn’t break anything, and on macOS it's looking good, but please give it some more testing on windows and linux before potentially merging this into 2.4.

**Comment by Swiftb0y** [comment]
Thank you. still works just as well as before. Though I have two nitpicks:
1. The dropped frames readout is now pretty weird (regardless of waveform technology or style). Essentially when setting the limit to 59fps or anything below the dropped frame readout looks correct (occasionally reporting single digit drops), but when setting the limit to 60fps the dropped frames seem to report about 60 dropped frames per second even though they're visually perfectly smooth. So that's obviously wrong. This might just be a 2.3->2.4 regression which is unrelated to this PR, still waiting on a test 2.4 compile to test that.
2. The all-shaders variants pre- and post-roll shaders have a different look. The established ones just have outlined triangles, the new ones are filled in. I assume that was easier to implement? How much more complicated would it be to make them match?

**Comment by m0dB** [comment]
1) Hm, dropped frames count works fine here. Also, I have not touched this code at all.

2) Yes, it was easier to implement and I because liked it more myself than the original I decided to leave it like this. But I can implement something that mimics the original.

**Comment by JoergAtGithub** [comment]
1.) The Frame Rate and Dropped Frame count works for me on Windows 11
2.) I suggest to not change minor style issues, like the design of the Pre-Roll triangles - when it's needed to change the style, than it should be done in a Follow-Up PR.

**Comment by Swiftb0y** [comment]
1. Mhmm thats weird, I'll try to debug whats wrong with my system then. 
2. Sure, I mean this PR is ready anyway. I'm just writing down things I notice so we don't forget to address them in future follow-up PRs.

**Comment by JoergAtGithub** [comment]
I did some stress testing on Windows 11 and found a bug which needs to be fixed:
If I drag a track from the library and move the mouse over the spinny, Mixxx crashes reproduceable (seen with allshaders RGB waveform type)

<details>
Stack-Overflow:
Callstack:

```
 	Qt5Widgets.dll!00007ffd71ab28dc()	Unknown
 	Qt5Core.dll!00007ffd701f00cb()	Unknown
>	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!OpenGLWindow::event(QEvent * ev) Line 80	C++
 	[External Code]	
 	mixxx.exe!`anonymous namespace'::dragUrls(const QList<QUrl> & trackUrls, QWidget * pDragSource, const QString & sourceIdentifier) Line 30	C++
 	mixxx.exe!DragAndDropHelper::dragTrackLocations(const QList<QString> & locations, QWidget * pDragSource, const QString & sourceIdentifier) Line 211	C++
 	mixxx.exe!WTrackTableView::mouseMoveEvent(QMouseEvent * pEvent) Line 578	C++
 	[External Code]	
 	mixxx.exe!`anonymous namespace'::runMixxx(MixxxApplication * pApp, const CmdlineArgs & args) Line 82	C++
 	mixxx.exe!main(int argc, char * * argv) Line 213	C++
 	[External Code]	
```

Autos:
<!DOCTYPE html>
<HTML>
<head>
<body>



  | Name | Value | Type
-- | -- | -- | --
  | result | false | bool
◢ | this | 0x0000021e84f0c810 {m_pWidget=0x0000021eca981f80 {m_textureShader={m_matrixLocation=0 m_samplerLocation=...} ...} ...} | OpenGLWindow *
  | ◢ QOpenGLWindow | {...} | QOpenGLWindow
  | ◢ QPaintDeviceWindow | {...} | QPaintDeviceWindow
  | ◢ QWindow | {...} | QWindow
  | ◢ QObject | {d_ptr=scoped pointer to a dynamically allocated object of type "QObjectData" } | QObject
  | ▶ __vfptr | 0x00007ff78db8f6e0 {mixxx.exe!void(* OpenGLWindow::`vftable'[37])()} {0x00007ff78d5db7f0 {mixxx.exe!OpenGLWindow::metaObject(void)}, ...} | void * *
  | ▶ d_ptr | scoped pointer to a dynamically allocated object of type "QObjectData" | QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData>>
  | ◢ QSurface | {m_type=Window (0) m_reserved=0x0000000000000000 <NULL> } | QSurface
  | ▶ __vfptr | 0x00007ff78db8f808 {mixxx.exe!void(* OpenGLWindow::`vftable'[6])()} {0x00007ff78d92e848 {mixxx.exe![thunk]:OpenGLWindow::`vector deleting destructor'`adjustor{16}' (unsigned int)}, ...} | void * *
  | m_type | Window (0) | QSurface::SurfaceClass
  | m_reserved | 0x0000000000000000 <NULL> | QSurfacePrivate *
  | ▶ QPaintDevice | {painters=0 reserved=0x0000000000000000 <NULL> } | QPaintDevice
  | ◢ m_pWidget | 0x0000021eca981f80 {m_textureShader={m_matrixLocation=0 m_samplerLocation=1 m_positionLocation=1 ...} ...} | WGLWidget * {WSpinnyGLSL}
  | ◢ [WSpinnyGLSL] | {m_textureShader={m_matrixLocation=0 m_samplerLocation=1 m_positionLocation=1 ...} m_pBgTexture=unique_ptr {d_ptr=scoped pointer to a dynamically allocated object of type "QOpenGLTexturePrivate" } ...} | WSpinnyGLSL
  | ◢ WSpinnyBase | {m_group=[Channel2] m_pConfig=strong reference to shared pointer of type "ConfigObject<ConfigValue>" ...} | WSpinnyBase
  | ◢ WGLWidget | {m_pOpenGLWindow=0x0000021e84f0c810 {m_pWidget=0x0000021eca981f80 {m_textureShader={m_matrixLocation=...} ...} ...} ...} | WGLWidget
  | ▶ QWidget | {data=0x0000021efb940a60 {winid=0 widget_attributes=32898 window_flags={i=-2013204480 } ...} } | QWidget
  | ▶ m_pOpenGLWindow | 0x0000021e84f0c810 {m_pWidget=0x0000021eca981f80 {m_textureShader={m_matrixLocation=0 m_samplerLocation=...} ...} ...} | OpenGLWindow *
  | ▶ m_pContainerWidget | 0x0000021efc40d560 <Information not available, no symbols loaded for Qt5Widgets.dll> | QWidget *
  | ◢ WBaseWidget | {m_connections={ size = 0 } m_pDisplayConnection=0x0000000000000000 <NULL> m_leftConnections={ size = 0 } ...} | WBaseWidget
  | ▶ __vfptr | 0x00007ff78dba0590 {mixxx.exe!void(* WSpinnyGLSL::`vftable'[5])()} {0x00007ff78d975254 {mixxx.exe![thunk]:WSpinnyGLSL::`vector deleting destructor'`adjustor{64}' (unsigned int)}, ...} | void * *
  | ▶ m_connections | { size = 0 } | QList<ControlParameterWidgetConnection *>
  | ▶ m_pDisplayConnection | 0x0000000000000000 <NULL> | ControlParameterWidgetConnection *
  | ▶ m_leftConnections | { size = 0 } | QList<ControlParameterWidgetConnection *>
  | ▶ m_rightConnections | { size = 0 } | QList<ControlParameterWidgetConnection *>
  | ▶ m_propertyConnections | { size = 0 } | QList<ControlWidgetPropertyConnection *>
  | ▶ m_pWidget | 0x0000021eca981f80 {m_textureShader={m_matrixLocation=0 m_samplerLocation=1 m_positionLocation=1 ...} ...} | QWidget * {WSpinnyGLSL}
  | ▶ m_baseTooltip | Spinning Vinyl Rotates during playback and shows the position of a track. Use the mouse to scratch, spin-back or throw tracks. Right click to show cover art of loaded track. Drop tracks from library, ... | QString
  | ◢ VinylSignalQualityListener | {...} | VinylSignalQualityListener
  | ◢ __vfptr | 0x00007ff78dba05b8 {mixxx.exe!void(* WSpinnyGLSL::`vftable'[2])()} {0x00007ff78d69bf60 {mixxx.exe!WSpinnyBase::onVinylSignalQualityUpdate(const VinylSignalQualityReport &)}} | void * *
  | [0] | 0x00007ff78d69bf60 {mixxx.exe!WSpinnyBase::onVinylSignalQualityUpdate(const VinylSignalQualityReport &)} | void *
  | ◢ TrackDropTarget | {...} | TrackDropTarget
  | ▶ __vfptr | 0x00007ff78dba05c8 {mixxx.exe!void(* WSpinnyGLSL::`vftable'[4])()} {0x00007ff78d975260 {mixxx.exe![thunk]:WSpinnyGLSL::`vector deleting destructor'`adjustor{136}' (unsigned int)}, ...} | void * *
  | ▶ m_group | [Channel2] | const QString
  | ▶ m_pConfig | strong reference to shared pointer of type "ConfigObject<ConfigValue>" | QSharedPointer<ConfigObject<ConfigValue>>
  | ▶ m_pBgImage | shared_ptr {d=0x0000021ef9c2b950 {...} } [4 strong refs, 1 weak ref] [custom deleter] | std::shared_ptr<QImage>
  | ▶ m_pMaskImage | shared_ptr {d=0x0000021ef9c2bb30 {...} } [2 strong refs, 1 weak ref] [custom deleter] | std::shared_ptr<QImage>
  | ▶ m_pFgImage | shared_ptr {d=0x0000021ef9c2b590 {...} } [4 strong refs, 1 weak ref] [custom deleter] | std::shared_ptr<QImage>
  | ▶ m_fgImageScaled | {d=0x0000021e850b63b0 {...} } | QImage
  | ▶ m_pGhostImage | shared_ptr {d=0x0000021ef9c2bc70 {...} } [4 strong refs, 1 weak ref] [custom deleter] | std::shared_ptr<QImage>
  | ▶ m_ghostImageScaled | {d=0x0000021e850c4870 {...} } | QImage
  | ▶ m_pPlayPos | 0x0000021efbb9bb90 {m_pControl=strong reference to shared pointer of type "ControlDoublePrivate" } | ControlProxy *
  | ▶ m_pVisualPlayPos | strong reference to shared pointer of type "VisualPlayPosition" | QSharedPointer<VisualPlayPosition>
  | ▶ m_pTrackSamples | 0x0000021efbb9b890 {m_pControl=strong reference to shared pointer of type "ControlDoublePrivate" } | ControlProxy *
  | ▶ m_pTrackSampleRate | 0x0000021efbb9b710 {m_pControl=strong reference to shared pointer of type "ControlDoublePrivate" } | ControlProxy *
  | ▶ m_pScratchToggle | 0x0000021efbb9b950 {m_pControl=strong reference to shared pointer of type "ControlDoublePrivate" } | ControlProxy *
  | ▶ m_pScratchPos | 0x0000021efbb9b560 {m_pControl=strong reference to shared pointer of type "ControlDoublePrivate" } | ControlProxy *
  | ▶ m_pVinylControlSpeedType | 0x0000021efbb9b3b0 {m_pControl=strong reference to shared pointer of type "ControlDoublePrivate" } | ControlProxy *
  | ▶ m_pVinylControlEnabled | 0x0000021efbb9b980 {m_pControl=strong reference to shared pointer of type "ControlDoublePrivate" } | ControlProxy *
  | ▶ m_pSignalEnabled | 0x0000021efbb9b1d0 {m_pControl=strong reference to shared pointer of type "ControlDoublePrivate" } | ControlProxy *
  | ▶ m_pSlipEnabled | 0x0000021efbb9b5c0 {m_pControl=strong reference to shared pointer of type "ControlDoublePrivate" } | ControlProxy *
  | ▶ m_pShowCoverProxy | 0x0000021efbb9b7d0 {m_pControl=strong reference to shared pointer of type "ControlDoublePrivate" } | ControlProxy *
  | ▶ m_loadedTrack | empty | std::shared_ptr<Track>
  | ▶ m_loadedCover | {data=pointer to explicit shared object of type "QPlatformPixmap" } | QPixmap
  | ▶ m_loadedCoverScaled | {data=pointer to explicit shared object of type "QPlatformPixmap" } | QPixmap
  | ▶ m_lastRequestedCover | {trackLocation= } | CoverInfo
  | m_bShowCover | true | bool
  | ▶ m_pVCManager | 0x0000021ed948a8c0 {m_pConfig=strong reference to shared pointer of type "ConfigObject<ConfigValue>" ...} | VinylControlManager *
  | m_dInitialPos | 0.0000000000000000 | double
  | m_iVinylInput | 1 | int
  | m_bVinylActive | false | bool
  | m_bSignalActive | true | bool
  | ▶ m_qImage | {d=0x0000021efbb8ae60 {...} } | QImage
  | m_iVinylScopeSize | 100 | int
  | m_fAngle | 0.00000000 | float
  | m_dAngleCurrentPlaypos | -1.0000000000000000 | double
  | m_dAngleLastPlaypos | -1.0000000000000000 | double
  | m_fGhostAngle | 0.00000000 | float
  | m_dGhostAngleCurrentPlaypos | -1.0000000000000000 | double
  | m_dGhostAngleLastPlaypos | -1.0000000000000000 | double
  | m_iStartMouseX | -1 | int
  | m_iStartMouseY | -1 | int
  | m_iFullRotations | 0 | int
  | m_dPrevTheta | 0.0000000000000000 | double
  | m_dRotationsPerSecond | 0.55555555555555558 | double
  | m_bClampFailedWarning | false | bool
  | m_bGhostPlayback | false | bool
  | ▶ m_pPlayer | 0x0000021ed7b6cf00 {...} | BaseTrackPlayer * {Deck}
  | ▶ m_pCoverMenu | 0x0000021efbb8bb80 {m_pChange=0x0000021efb89fb70 {...} m_pReload=0x0000021efb89fbf0 {...} m_pUnset=0x0000021efb89fa50 {...} ...} | WCoverArtMenu *
  | ▶ m_pDlgCoverArt | 0x0000021efbb461b0 {m_pixmap={data=pointer to explicit shared object of type "QPlatformPixmap" } m_pLoadedTrack=...} | DlgCoverArtFullSize *
  | ▶ m_textureShader | {m_matrixLocation=0 m_samplerLocation=1 m_positionLocation=1 ...} | mixxx::TextureShader
  | ▶ m_pBgTexture | unique_ptr {d_ptr=scoped pointer to a dynamically allocated object of type "QOpenGLTexturePrivate" } | std::unique_ptr<QOpenGLTexture,std::default_delete<QOpenGLTexture>>
  | ▶ m_pMaskTexture | unique_ptr {d_ptr=scoped pointer to a dynamically allocated object of type "QOpenGLTexturePrivate" } | std::unique_ptr<QOpenGLTexture,std::default_delete<QOpenGLTexture>>
  | ▶ m_pFgTextureScaled | unique_ptr {d_ptr=scoped pointer to a dynamically allocated object of type "QOpenGLTexturePrivate" } | std::unique_ptr<QOpenGLTexture,std::default_delete<QOpenGLTexture>>
  | ▶ m_pGhostTextureScaled | unique_ptr {d_ptr=scoped pointer to a dynamically allocated object of type "QOpenGLTexturePrivate" } | std::unique_ptr<QOpenGLTexture,std::default_delete<QOpenGLTexture>>
  | ▶ m_pLoadedCoverTextureScaled | empty | std::unique_ptr<QOpenGLTexture,std::default_delete<QOpenGLTexture>>
  | ▶ m_pQTexture | unique_ptr {d_ptr=scoped pointer to a dynamically allocated object of type "QOpenGLTexturePrivate" } | std::unique_ptr<QOpenGLTexture,std::default_delete<QOpenGLTexture>>
  | ▶ QWidget | {data=0x0000021efb940a60 {winid=0 widget_attributes=32898 window_flags={i=-2013204480 } ...} } | QWidget
  | ◢ m_pOpenGLWindow | 0x0000021e84f0c810 {m_pWidget=0x0000021eca981f80 {m_textureShader={m_matrixLocation=0 m_samplerLocation=...} ...} ...} | OpenGLWindow *
  | ◢ QOpenGLWindow | {...} | QOpenGLWindow
  | ◢ QPaintDeviceWindow | {...} | QPaintDeviceWindow
  | ◢ QWindow | {...} | QWindow
  | ◢ QObject | {d_ptr=scoped pointer to a dynamically allocated object of type "QObjectData" } | QObject
  | ▶ __vfptr | 0x00007ff78db8f6e0 {mixxx.exe!void(* OpenGLWindow::`vftable'[37])()} {0x00007ff78d5db7f0 {mixxx.exe!OpenGLWindow::metaObject(void)}, ...} | void * *
  | ▶ d_ptr | scoped pointer to a dynamically allocated object of type "QObjectData" | QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData>>
  | ▶ QSurface | {m_type=Window (0) m_reserved=0x0000000000000000 <NULL> } | QSurface
  | ▶ QPaintDevice | {painters=0 reserved=0x0000000000000000 <NULL> } | QPaintDevice
  | ◢ m_pWidget | 0x0000021eca981f80 {m_textureShader={m_matrixLocation=0 m_samplerLocation=1 m_positionLocation=1 ...} ...} | WGLWidget * {WSpinnyGLSL}
  | ◢ [WSpinnyGLSL] | {m_textureShader={m_matrixLocation=0 m_samplerLocation=1 m_positionLocation=1 ...} m_pBgTexture=unique_ptr {d_ptr=scoped pointer to a dynamically allocated object of type "QOpenGLTexturePrivate" } ...} | WSpinnyGLSL
  | ◢ WSpinnyBase | {m_group=[Channel2] m_pConfig=strong reference to shared pointer of type "ConfigObject<ConfigValue>" ...} | WSpinnyBase
  | ◢ WGLWidget | {m_pOpenGLWindow=0x0000021e84f0c810 {m_pWidget=0x0000021eca981f80 {m_textureShader={m_matrixLocation=...} ...} ...} ...} | WGLWidget
  | ▶ QWidget | {data=0x0000021efb940a60 {winid=0 widget_attributes=32898 window_flags={i=-2013204480 } ...} } | QWidget
  | ▶ m_pOpenGLWindow | 0x0000021e84f0c810 {m_pWidget=0x0000021eca981f80 {m_textureShader={m_matrixLocation=0 m_samplerLocation=...} ...} ...} | OpenGLWindow *
  | ▶ m_pContainerWidget | 0x0000021efc40d560 <Information not available, no symbols loaded for Qt5Widgets.dll> | QWidget *
  | ◢ WBaseWidget | {m_connections={ size = 0 } m_pDisplayConnection=0x0000000000000000 <NULL> m_leftConnections={ size = 0 } ...} | WBaseWidget
  | ▶ __vfptr | 0x00007ff78dba0590 {mixxx.exe!void(* WSpinnyGLSL::`vftable'[5])()} {0x00007ff78d975254 {mixxx.exe![thunk]:WSpinnyGLSL::`vector deleting destructor'`adjustor{64}' (unsigned int)}, ...} | void * *
  | ▶ m_connections | { size = 0 } | QList<ControlParameterWidgetConnection *>
  | ▶ m_pDisplayConnection | 0x0000000000000000 <NULL> | ControlParameterWidgetConnection *
  | ▶ m_leftConnections | { size = 0 } | QList<ControlParameterWidgetConnection *>
  | ▶ m_rightConnections | { size = 0 } | QList<ControlParameterWidgetConnection *>
  | ▶ m_propertyConnections | { size = 0 } | QList<ControlWidgetPropertyConnection *>
  | ▶ m_pWidget | 0x0000021eca981f80 {m_textureShader={m_matrixLocation=0 m_samplerLocation=1 m_positionLocation=1 ...} ...} | QWidget * {WSpinnyGLSL}
  | ▶ m_baseTooltip | Spinning Vinyl Rotates during playback and shows the position of a track. Use the mouse to scratch, spin-back or throw tracks. Right click to show cover art of loaded track. Drop tracks from library, ... | QString
  | ◢ VinylSignalQualityListener | {...} | VinylSignalQualityListener
  | ▶ __vfptr | 0x00007ff78dba05b8 {mixxx.exe!void(* WSpinnyGLSL::`vftable'[2])()} {0x00007ff78d69bf60 {mixxx.exe!WSpinnyBase::onVinylSignalQualityUpdate(const VinylSignalQualityReport &)}} | void * *
  | ◢ TrackDropTarget | {...} | TrackDropTarget
  | ▶ __vfptr | 0x00007ff78dba05c8 {mixxx.exe!void(* WSpinnyGLSL::`vftable'[4])()} {0x00007ff78d975260 {mixxx.exe![thunk]:WSpinnyGLSL::`vector deleting destructor'`adjustor{136}' (unsigned int)}, ...} | void * *
  | ▶ m_group | [Channel2] | const QString
  | ▶ m_pConfig | strong reference to shared pointer of type "ConfigObject<ConfigValue>" | QSharedPointer<ConfigObject<ConfigValue>>
  | ▶ m_pBgImage | shared_ptr {d=0x0000021ef9c2b950 {...} } [4 strong refs, 1 weak ref] [custom deleter] | std::shared_ptr<QImage>
  | ▶ m_pMaskImage | shared_ptr {d=0x0000021ef9c2bb30 {...} } [2 strong refs, 1 weak ref] [custom deleter] | std::shared_ptr<QImage>
  | ▶ m_pFgImage | shared_ptr {d=0x0000021ef9c2b590 {...} } [4 strong refs, 1 weak ref] [custom deleter] | std::shared_ptr<QImage>
  | ▶ m_fgImageScaled | {d=0x0000021e850b63b0 {...} } | QImage
  | ▶ m_pGhostImage | shared_ptr {d=0x0000021ef9c2bc70 {...} } [4 strong refs, 1 weak ref] [custom deleter] | std::shared_ptr<QImage>
  | ▶ m_ghostImageScaled | {d=0x0000021e850c4870 {...} } | QImage
  | ▶ m_pPlayPos | 0x0000021efbb9bb90 {m_pControl=strong reference to shared pointer of type "ControlDoublePrivate" } | ControlProxy *
  | ▶ m_pVisualPlayPos | strong reference to shared pointer of type "VisualPlayPosition" | QSharedPointer<VisualPlayPosition>
  | ▶ m_pTrackSamples | 0x0000021efbb9b890 {m_pControl=strong reference to shared pointer of type "ControlDoublePrivate" } | ControlProxy *
  | ▶ m_pTrackSampleRate | 0x0000021efbb9b710 {m_pControl=strong reference to shared pointer of type "ControlDoublePrivate" } | ControlProxy *
  | ▶ m_pScratchToggle | 0x0000021efbb9b950 {m_pControl=strong reference to shared pointer of type "ControlDoublePrivate" } | ControlProxy *
  | ▶ m_pScratchPos | 0x0000021efbb9b560 {m_pControl=strong reference to shared pointer of type "ControlDoublePrivate" } | ControlProxy *
  | ▶ m_pVinylControlSpeedType | 0x0000021efbb9b3b0 {m_pControl=strong reference to shared pointer of type "ControlDoublePrivate" } | ControlProxy *
  | ▶ m_pVinylControlEnabled | 0x0000021efbb9b980 {m_pControl=strong reference to shared pointer of type "ControlDoublePrivate" } | ControlProxy *
  | ▶ m_pSignalEnabled | 0x0000021efbb9b1d0 {m_pControl=strong reference to shared pointer of type "ControlDoublePrivate" } | ControlProxy *
  | ▶ m_pSlipEnabled | 0x0000021efbb9b5c0 {m_pControl=strong reference to shared pointer of type "ControlDoublePrivate" } | ControlProxy *
  | ▶ m_pShowCoverProxy | 0x0000021efbb9b7d0 {m_pControl=strong reference to shared pointer of type "ControlDoublePrivate" } | ControlProxy *
  | ▶ m_loadedTrack | empty | std::shared_ptr<Track>
  | ▶ m_loadedCover | {data=pointer to explicit shared object of type "QPlatformPixmap" } | QPixmap
  | ▶ m_loadedCoverScaled | {data=pointer to explicit shared object of type "QPlatformPixmap" } | QPixmap
  | ▶ m_lastRequestedCover | {trackLocation= } | CoverInfo
  | m_bShowCover | true | bool
  | ▶ m_pVCManager | 0x0000021ed948a8c0 {m_pConfig=strong reference to shared pointer of type "ConfigObject<ConfigValue>" ...} | VinylControlManager *
  | m_dInitialPos | 0.0000000000000000 | double
  | m_iVinylInput | 1 | int
  | m_bVinylActive | false | bool
  | m_bSignalActive | true | bool
  | ▶ m_qImage | {d=0x0000021efbb8ae60 {...} } | QImage
  | m_iVinylScopeSize | 100 | int
  | m_fAngle | 0.00000000 | float
  | m_dAngleCurrentPlaypos | -1.0000000000000000 | double
  | m_dAngleLastPlaypos | -1.0000000000000000 | double
  | m_fGhostAngle | 0.00000000 | float
  | m_dGhostAngleCurrentPlaypos | -1.0000000000000000 | double
  | m_dGhostAngleLastPlaypos | -1.0000000000000000 | double
  | m_iStartMouseX | -1 | int
  | m_iStartMouseY | -1 | int
  | m_iFullRotations | 0 | int
  | m_dPrevTheta | 0.0000000000000000 | double
  | m_dRotationsPerSecond | 0.55555555555555558 | double
  | m_bClampFailedWarning | false | bool
  | m_bGhostPlayback | false | bool
  | ▶ m_pPlayer | 0x0000021ed7b6cf00 {...} | BaseTrackPlayer * {Deck}
  | ▶ m_pCoverMenu | 0x0000021efbb8bb80 {m_pChange=0x0000021efb89fb70 {...} m_pReload=0x0000021efb89fbf0 {...} m_pUnset=0x0000021efb89fa50 {...} ...} | WCoverArtMenu *
  | ▶ m_pDlgCoverArt | 0x0000021efbb461b0 {m_pixmap={data=pointer to explicit shared object of type "QPlatformPixmap" } m_pLoadedTrack=...} | DlgCoverArtFullSize *
  | ▶ m_textureShader | {m_matrixLocation=0 m_samplerLocation=1 m_positionLocation=1 ...} | mixxx::TextureShader
  | ▶ m_pBgTexture | unique_ptr {d_ptr=scoped pointer to a dynamically allocated object of type "QOpenGLTexturePrivate" } | std::unique_ptr<QOpenGLTexture,std::default_delete<QOpenGLTexture>>
  | ▶ m_pMaskTexture | unique_ptr {d_ptr=scoped pointer to a dynamically allocated object of type "QOpenGLTexturePrivate" } | std::unique_ptr<QOpenGLTexture,std::default_delete<QOpenGLTexture>>
  | ▶ m_pFgTextureScaled | unique_ptr {d_ptr=scoped pointer to a dynamically allocated object of type "QOpenGLTexturePrivate" } | std::unique_ptr<QOpenGLTexture,std::default_delete<QOpenGLTexture>>
  | ▶ m_pGhostTextureScaled | unique_ptr {d_ptr=scoped pointer to a dynamically allocated object of type "QOpenGLTexturePrivate" } | std::unique_ptr<QOpenGLTexture,std::default_delete<QOpenGLTexture>>
  | ▶ m_pLoadedCoverTextureScaled | empty | std::unique_ptr<QOpenGLTexture,std::default_delete<QOpenGLTexture>>
  | ▶ m_pQTexture | unique_ptr {d_ptr=scoped pointer to a dynamically allocated object of type "QOpenGLTexturePrivate" } | std::unique_ptr<QOpenGLTexture,std::default_delete<QOpenGLTexture>>
  | ◢ QWidget | {data=0x0000021efb940a60 {winid=0 widget_attributes=32898 window_flags={i=-2013204480 } ...} } | QWidget
  | ◢ QObject | {d_ptr=scoped pointer to a dynamically allocated object of type "QObjectData" } | QObject
  | ▶ __vfptr | 0x00007ff78dba03b0 {mixxx.exe!void(* WSpinnyGLSL::`vftable'[52])()} {0x00007ff78d5dbb30 {mixxx.exe!WSpinnyBase::metaObject(void)}, ...} | void * *
  | ▶ d_ptr | scoped pointer to a dynamically allocated object of type "QObjectData" | QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData>>
  | ◢ QPaintDevice | {painters=0 reserved=0x0000000000000000 <NULL> } | QPaintDevice
  | ▶ __vfptr | 0x00007ff78dba0550 {mixxx.exe!void(* WSpinnyGLSL::`vftable'[8])()} {0x00007ff78d975248 {mixxx.exe![thunk]:WSpinnyGLSL::`vector deleting destructor'`adjustor{16}' (unsigned int)}, ...} | void * *
  | painters | 0 | unsigned short
  | reserved | 0x0000000000000000 <NULL> | QPaintDevicePrivate *
  | ▶ data | 0x0000021efb940a60 {winid=0 widget_attributes=32898 window_flags={i=-2013204480 } ...} | QWidgetData *
  | ▶ m_pOpenGLWindow | 0x0000021e84f0c810 {m_pWidget=0x0000021eca981f80 {m_textureShader={m_matrixLocation=0 m_samplerLocation=...} ...} ...} | OpenGLWindow *
  | ▶ m_pContainerWidget | 0x0000021efc40d560 <Information not available, no symbols loaded for Qt5Widgets.dll> | QWidget *
  | m_dirty | false | bool
  | ▶ m_pContainerWidget | 0x0000021efc40d560 <Information not available, no symbols loaded for Qt5Widgets.dll> | QWidget *
  | m_dirty | false | bool



</body>
</HTML>


</details>

**Comment by m0dB** [comment]
Ok, that call stack is clear, infinite recursion. I expect this will be an easy fix.

**Comment by m0dB** [comment]
@JoergAtGithub can you please try again?

File: src/widget/openglwindow.cpp [hunk 73]
```diff
@@ -47,6 +47,18 @@ void OpenGLWindow::widgetDestroyed() {
...
+    // handling of the event as if it were received by the main window.
+    // With drag move and drag leave events it may happen that this function
+    // gets called recursive, potentially resulting in infinite recursion
+    // and a stack overflow. The boolean m_handlingEvent protects against
+    // this recursion.
+
+    if (m_handlingEvent) {
+        return false;
+    }
+    m_handlingEvent = true;
```
Comment (Swiftb0y) [inline src/widget/openglwindow.cpp:60]: IMO this is another indicator that the event delivery code for this needs to be redesigned. piling on workaround after workaround will come to bite us eventually.

Comment (m0dB) [reply src/widget/openglwindow.cpp:60]: I disagree.

The OpenGLWindow / WGLWidget event handling was actually a lot more convoluted a couple of iterations back (e.g. calling my own method to get events to the WGLWidget rather than using QApplication::sendEvent, and passing events from there to the parent widget in the case of the waveforms). It is now much simpler and IMO pretty elegant. For the WGLWidget and derived widgets it makes no difference whether the events come from the main event loop directly or from the QOpenGLWindow, and the two "workarounds" are concentrated here (tooltips and recursion in the case of drag move/leave). Besides, after debugging the issue yesterday, I really don't see a better solution. 

There is only one thing left here that is a bit ugly: the virtual method WGLWidget::isExposed, and calling that from the QOpenGLWindow exposed event. I will change that for something simpler.

Comment (Swiftb0y) [reply src/widget/openglwindow.cpp:60]: Thank you for your detailed assessment of the situation. I admit that I'm not very familiar with the issue at hand so I trust your opinion. Still, passing events from the child to the parent seems brittle, why do the events reach the child instead of the parent in the first place?

Comment (m0dB) [reply src/widget/openglwindow.cpp:60]: So what happens is this: Each WGLWidget has a child m_pContainerWidget, created with createWindowContainer, which contains the QOpenGLWindow. The QOpenGLWindow is placed at the location of the m_pContainerWidget, which is placed at the locaton of the WGLWidget and are kept like this. This means that for example a mouse click inside the WGLWidget is in fact a mouse click in the QOpenGLWindow. But obviously this mouse click was intended for the WGLWidget, so it only makes sense that is where the QOpenGLWindow sends it, by calling QApplication::sendEvent. Now, as far as I understand, what sendEvent does it this: if the widget does not use the event (accepted() isn't set), it will pass it on the the parent of the target, and so on all the way up to the window. I am pretty sure this is what I read (but I can't find it now) but it is also what I am seeing, as for example the mouse events sent to the waveform widget reach it's container WWaveformViewer. But I might be missing something still, because @JoergAtGithub reports a regression: drag&drop of tracks from library to waveform stopped working after I removed the explicit forwarding for events from waveform widget to WWaveformViewer. It works fine for me though on macOS. Does it work for you? Anybody else?

**Comment by m0dB** [comment]
Could you please let me know if drag&drop of tracks from library to waveforms works for you? (Works for me on macOS, not for @JoergAtGithub, on windows). Thx.

**Comment by atskler** [comment]
> Could you please let me know if drag&drop of tracks from library to waveforms works for you? (Works for me on macOS, not for @JoergAtGithub, on windows). Thx.

It does not work for me on Linux - if you mean the upper wide waveforms.

**Comment by m0dB** [comment]
Ok, thanks. I'll fix this tomorrow when I have access to a linux machine.

**Comment by atskler** [comment]
> Ok, thanks. I'll fix this tomorrow when I have access to a linux machine.

I left out out that I'm using openSUSE Tumbleweed, a rolling release distro with the newest system packages. So it can be that on Ubuntu or Debian it will work with their older system packages.

**Comment by m0dB** [comment]
Potential fix committed (not tested on linux or windows, but still works on mac).

**Comment by m0dB** [comment]
Reportedly doesn't fix. I'll revert and try to reproduce it.

**Comment by m0dB** [comment]
I have a fix that works on linux, compiling now to check macos.

File: src/waveform/widgets/glwaveformwidgetabstract.h (hunk 72 above)
Comment (m0dB) [reply src/waveform/widgets/glwaveformwidgetabstract.h]: Because of ambiguity. QWidget also has a method render(...) and even though that one has arguments, the compiler doesn't like this.

**Comment by JoergAtGithub** [comment]
I can confirm that Drag&Drop of tracks works now on Windows11 as suposed!

**Review by Swiftb0y — APPROVED** [review]
Great. We came to the conclusion to merge for 2.4, right?

**Comment by daschuer** [comment]
No. We have no conclusion to merge this to 2.4. 

This one has a real risk to delay the 2.4 release. 

The first 2.4 commit is from 2018-10-18 (5 years) we have cut out 7 month ago. When we where not dragged away by 2.3.5 we had already a 2.4 release since 4 month. 

From that point of view we can short the beta phase even more down. Please remember that merging this to main will also be immediately available for our user as alpha. 
So I see no real disadvantage. But the big advantage, that no one needs to promise that this branch works on all graphic drivers/OS/GPU combinations. And we don't put the 2.4 release on a risk. 

But let's outline the plans at zulip. I have the impression we all want to deliver fast and are somehow on the same page. We just need some fixed dates.

File: src/widget/wglwidgetqopengl.cpp [hunk 74]
```diff
@@ -0,0 +1,94 @@
...
+    makeCurrentIfNeeded();
+    return m_pOpenGLWindow;
+}
+
+void WGLWidget::setTrackDropTarget(TrackDropTarget* target) {
+    m_pTrackDropTarget = target;
```
Comment (daschuer) [inline src/widget/wglwidgetqopengl.cpp:29]:
```suggestion
void WGLWidget::setTrackDropTarget(TrackDropTarget* pTarget) {
    m_pTrackDropTarget = pTarget;
```

Comment (daschuer) [reply src/widget/wglwidgetqopengl.cpp:29]: The same below.

File: src/widget/wspinnybase.cpp [hunk 75]
```diff
@@ -0,0 +1,666 @@
...
+    if (m_pVCManager) {
+        m_iVinylInput = m_pVCManager->vinylInputFromGroup(m_group);
+    }
+    m_iVinylScopeSize = MIXXX_VINYL_SCOPE_SIZE;
+    m_qImage = QImage(m_iVinylScopeSize, m_iVinylScopeSize, QImage::Format_ARGB32);
+    // fill with transparent black
+    m_qImage.fill(qRgba(0, 0, 0, 0));
+#endif
+
+    m_pPlayPos = new ControlProxy(
```
Comment (daschuer) [inline src/widget/wspinnybase.cpp:203]: here you can make use of `make_parented<ControlProxy>(` which asserts for a parent.

Comment (daschuer) [reply src/widget/wspinnybase.cpp:203]: Or even better use the light weight `PollingControlProxy` in the object memory which is already a special SmartPointer.

**Review by daschuer — COMMENTED** [review]
Unfortunately I have experienced some issues with Qt 5.12.8

Compiling with QOPENGL=OFF the spinny is too big: 
grafik
grafik
The mouse control works with the correct, smaller size. 

The Tango VU-meter shows interferences:
grafik
Deere locks also not correct: 
grafik
With --disable-vumetergl they look normal again. 


Even though it is compiled with QOPENGL=OFF, the "Simple (all-shaders) (GLSL)" waveform is selectable and shown in the upper left corner:
grafik

I had just another crash when changing skins with QOPENGL=ON
```
pure virtual method called
terminate called without an active exception
Abgebrochen (Speicherabzug geschrieben)
```
Unfortunately I was not able to reproduce it under GDB 

I see an issue, that the waveform changes after changing the skin. 
* Shade: Select "RGB (GLSL)" 
* Select Deere* 
* Waveform is reset to Filtered. 
Expectation "RGB (GLSL)" is still selected.

File: src/widget/wspinnybase.cpp (hunk 75 above)
Comment (m0dB) [reply src/widget/wspinnybase.cpp:203]: This is not part of my code, this comes from the original WSpinny that has moved to WSpinnyBase

File: src/widget/wglwidgetqopengl.cpp (hunk 74 above)
Comment (m0dB) [reply src/widget/wglwidgetqopengl.cpp:29]: Ok. I will change this.

File: src/util/colorcomponents.cpp [hunk 76]
```diff
@@ -0,0 +1,46 @@
+#include "util/colorcomponents.h"
+
+void getHsvF(const QColor& color, float* h, float* s, float* v, float* a) {
```
[the remark this answers is not in the document]
Comment (m0dB) [reply src/util/colorcomponents.cpp:3]: Ok

File: src/widget/wglwidgetqglwidget.cpp [hunk 77]
```diff
@@ -0,0 +1,35 @@
...
+    return context()->isSharing();
+}
+
+bool WGLWidget::shouldRender() const {
+    return isValid() && isVisible() && windowHandle() && windowHandle()->isExposed();
+}
+
+void WGLWidget::makeCurrentIfNeeded() {
+    if (context() != QGLContext::currentContext()) {
+        makeCurrent();
```
[the remark this answers is not in the document]
Comment (m0dB) [reply src/widget/wglwidgetqglwidget.cpp:33]: I haven't tested with QOPENGL=OFF in quite a while, as I have focussed on QOPENGL=ON. Luckily at a first glance non of these issues seem hard to fix.

**Comment by m0dB** [comment]
@daschuer With the QOpenGL based widgets the widgets are opaque, so VU meters that rely on alpha transparency and showing the background below will look different. So this might require some tweaking of skins that rely on this. Could it be that this is the case? Cc @ronso0

**Comment by ronso0** [comment]
> I had just another crash when changing skins with QOPENGL=ON
>
> >pure virtual method called
> >terminate called without an active exception
> >Abgebrochen (Speicherabzug geschrieben)
>
> Unfortunately I was not able to reproduce it under GDB

Here you go. Happened when switching from Tango to Deere, with QOPENGL=OFF
<details><summary>ladh</summary>

Thread 1 (Thread 0x7fffeb4cc140 (LWP 207438)):
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
        set = {__val = {4096, 0, 93825499716720, 93825471437744, 0, 0, 236223201335, 0, 0, 0, 93825499716720, 93825471437744, 0, 0, 2, 9223372036854775822}}
        pid = <optimized out>
        tid = <optimized out>
#1  0x00007ffff2f31859 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0x7ffff30fc5c0 <_IO_2_1_stderr_>, sa_sigaction = 0x7ffff30fc5c0 <_IO_2_1_stderr_>}, sa_mask = {__val = {140737274722320, 3432, 140737269852072, 45, 93824999859168, 93825451658048, 140737271285184, 45, 45, 1, 140737274722320, 140737271268512, 140737269801921, 1, 93825484633520, 140737488330656}}, sa_flags = 1892019424, sa_restorer = 0x555572aeb5b0}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x00007ffff335a911 in  () at /lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff336638c in  () at /lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff33663f7 in  () at /lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff3367155 in  () at /lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff37c7328 in QMetaObject::activate(QObject*, int, int, void**) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#7  0x00005555559f24fd in CoverArtCache::coverFound(QObject const*, CoverInfo const&, QPixmap const&, unsigned long long, bool) (_t5=false, _t4=0, _t3=..., _t2=..., _t1=<optimized out>, this=0x7fffc4017350) at /home/ronso/Downloads/mixxx_source/src/xxx_master_build/Debug/mixxx-lib_autogen/include/moc_coverartcache.cpp:162
        _a = {0x0, 0x7fffffffa080, 0x7fffffffa200, 0x7fffffffa0c0, 0x7fffffffa0a0, 0x7fffffffa060}
        __PRETTY_FUNCTION__ = "QPixmap CoverArtCache::tryLoadCover(const QObject*, const TrackPointer&, const CoverInfo&, int, CoverArtCache::Loading)"
        requestedCacheKey = 0
        requestId = {first = 0x0, second = 140737185518768}
        cacheKey = {static null = {<No data fields>}, d = 0x5555565b0920 <Track::staticMetaObject>}
        pixmap = <incomplete type>
        future = {d = {<QFutureInterfaceBase> = {<No data fields>}, <No data fields>}}
#8  CoverArtCache::tryLoadCover(QObject const*, std::shared_ptr<Track> const&, CoverInfo const&, int, CoverArtCache::Loading) (this=0x7fffc4017350, pRequestor=<optimized out>, pTrack=..., coverInfo=..., desiredWidth=<optimized out>, loading=CoverArtCache::Loading::Default) at /home/ronso/Downloads/mixxx_source/src/master/src/library/coverartcache.cpp:97
        __PRETTY_FUNCTION__ = "QPixmap CoverArtCache::tryLoadCover(const QObject*, const TrackPointer&, const CoverInfo&, int, CoverArtCache::Loading)"
        requestedCacheKey = 0
        requestId = {first = 0x0, second = 140737185518768}
        cacheKey = {static null = {<No data fields>}, d = 0x5555565b0920 <Track::staticMetaObject>}
        pixmap = <incomplete type>
        future = {d = {<QFutureInterfaceBase> = {<No data fields>}, <No data fields>}}
#9  0x00005555559f372a in CoverArtCache::requestCover(QObject const*, CoverInfo const&, std::shared_ptr<Track> const&) (pRequestor=0x5555733f8560, coverInfo=..., pTrack=std::shared_ptr<class Track> (use count 20, weak count 1) = {...}) at /home/ronso/Downloads/mixxx_source/src/master/src/library/coverartcache.cpp:55
        pCache = <optimized out>
#10 0x00005555559f37a8 in CoverArtCache::requestTrackCover(QObject const*, std::shared_ptr<Track> const&) (pRequestor=0x5555733f8560, pTrack=std::shared_ptr<class Track> (use count 20, weak count 1) = {...}) at /home/ronso/Downloads/mixxx_source/src/master/src/library/coverartcache.cpp:70
        __PRETTY_FUNCTION__ = "static void CoverArtCache::requestTrackCover(const QObject*, const TrackPointer&)"
#11 0x0000555555c9b432 in WSpinnyBase::WSpinnyBase(QWidget*, QString const&, QSharedPointer<ConfigObject<ConfigValue> >, VinylControlManager*, BaseTrackPlayer*) (this=0x5555733f8560, parent=<optimized out>, group=..., pConfig=..., pVCMan=<optimized out>, pPlayer=<optimized out>) at /home/ronso/Downloads/mixxx_source/src/master/src/widget/wspinnybase.cpp:90
        pCache = <optimized out>
#12 0x0000555555f50366 in WSpinnyGLSL::WSpinnyGLSL(QWidget*, QString const&, QSharedPointer<ConfigObject<ConfigValue> >, VinylControlManager*, BaseTrackPlayer*) (this=0x5555733f8560, parent=<optimized out>, group=..., pConfig=..., pVCMan=<optimized out>, pPlayer=<optimized out>) at /usr/include/c++/10/bits/atomic_base.h:325
#13 0x0000555555eb7007 in LegacySkinParser::parseSpinny(QDomElement const&) (this=0x7fffffffc820, node=...) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qsharedpointer_impl.h:330
        pWaveformWidgetFactory = <optimized out>
        group = {static null = {<No data fields>}, d = 0x555570b948e0}
        pPlayer = 0x55555fbac010
        pSpinny = <optimized out>
        showCoverControl = <optimized out>
        configKey = {group = {static null = {<No data fields>}, d = 0xa}, item = {static null = {<No data fields>}, d = 0x555574c26ec8}}
#14 0x0000555555ebbaea in LegacySkinParser::parseNode(QDomElement const&) (this=0x7fffffffc820, node=...) at /home/ronso/Downloads/mixxx_source/src/master/src/skin/legacy/legacyskinparser.cpp:596
        result = {<QListSpecialMethods<QWidget*>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = -1}, static is_always_lock_free = true}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x7ffff387e760 <QListData::shared_null>}, d = 0x7ffff387e760 <QListData::shared_null>}}
        nodeName = {static null = {<No data fields>}, d = 0x555573f22240}
        __PRETTY_FUNCTION__ = "QList<QWidget*> LegacySkinParser::parseNode(const QDomElement&)"
#15 0x0000555555ebc682 in LegacySkinParser::parseChildren(QDomElement const&, WWidgetGroup*) (this=0x7fffffffc820, node=..., pGroup=0x5555792b27a0) at /home/ronso/Downloads/mixxx_source/src/master/src/skin/legacy/legacyskinparser.cpp:708
        children = {<QListSpecialMethods<QWidget*>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = -1}, static is_always_lock_free = true}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x7ffff387e760 <QListData::shared_null>}, d = 0x7ffff387e760 <QListData::shared_null>}}
        node = {impl = 0x555573f22290}
        i = 0
        children = {impl = 0x555578eac790}
        childrenNode = {impl = 0x555573f221c0}
        pOldParent = 0x55557b245c30
#16 0x0000555555ebc881 in LegacySkinParser::parseWidgetGroup(QDomElement const&) (this=0x7fffffffc820, node=...) at /home/ronso/Downloads/mixxx_source/src/master/src/skin/legacy/legacyskinparser.cpp:726
        pGroup = 0x5555792b27a0
#17 0x0000555555ebb742 in LegacySkinParser::parseNode(QDomElement const&) (this=0x7fffffffc820, node=...) at /home/ronso/Downloads/mixxx_source/src/master/src/skin/legacy/legacyskinparser.cpp:570
        result = {<QListSpecialMethods<QWidget*>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = -1}, static is_always_lock_free = true}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x7ffff387e760 <QListData::shared_null>}, d = 0x7ffff387e760 <QListData::shared_null>}}
        nodeName = {static null = {<No data fields>}, d = 0x555574c26e60}
        __PRETTY_FUNCTION__ = "QList<QWidget*> LegacySkinParser::parseNode(const QDomElement&)"
#18 0x0000555555ebe699 in LegacySkinParser::parseTemplate(QDomElement const&) (this=0x7fffffffc820, node=...) at /home/ronso/Downloads/mixxx_source/src/master/src/skin/legacy/legacyskinparser.cpp:1747
        childWidgets = {<QListSpecialMethods<QWidget*>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = -1}, static is_always_lock_free = true}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x7ffff387e760 <QListData::shared_null>}, d = 0x7ffff387e760 <QListData::shared_null>}}
        path = {static null = {<No data fields>}, d = 0x555570d40b70}
        pOldContext = <optimized out>
        templateNode = {<QDomNode> = {impl = 0x555573940810}, <No data fields>}
        widgets = {<QListSpecialMethods<QWidget*>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = -1}, static is_always_lock_free = true}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x7ffff387e760 <QListData::shared_null>}, d = 0x7ffff387e760 <QListData::shared_null>}}
        child = {impl = 0x555574c26f00}
#19 0x0000555555ebbdbf in LegacySkinParser::parseNode(QDomElement const&) (this=0x7fffffffc820, node=...) at /home/ronso/Downloads/mixxx_source/src/master/src/skin/legacy/legacyskinparser.cpp:616
        result = {<QListSpecialMethods<QWidget*>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = -1}, static is_always_lock_free = true}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x7ffff387e760 <QListData::shared_null>}, d = 0x7ffff387e760 <QListData::shared_null>}}
        nodeName = {static null = {<No data fields>}, d = 0x555570d40ad0}
        __PRETTY_FUNCTION__ = "QList<QWidget*> LegacySkinParser::parseNode(const QDomElement&)"
#20 0x0000555555ebc682 in LegacySkinParser::parseChildren(QDomElement const&, WWidgetGroup*) (this=0x7fffffffc820, node=..., pGroup=0x55557b245c30) at /home/ronso/Downloads/mixxx_source/src/master/src/skin/legacy/legacyskinparser.cpp:708
        children = {<QListSpecialMethods<QWidget*>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = -1}, static is_always_lock_free = true}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x7ffff387e760 <QListData::shared_null>}, d = 0x7ffff387e760 <QListData::shared_null>}}
        node = {impl = 0x555570d40c60}
        i = 0
        children = {impl = 0x5555796b7a80}
        childrenNode = {impl = 0x555570d40a20}
        pOldParent = 0x555579b8d960
#21 0x0000555555ebc881 in LegacySkinParser::parseWidgetGroup(QDomElement const&) (this=0x7fffffffc820, node=...) at /home/ronso/Downloads/mixxx_source/src/master/src/skin/legacy/legacyskinparser.cpp:726
        pGroup = 0x55557b245c30
#22 0x0000555555ebb742 in LegacySkinParser::parseNode(QDomElement const&) (this=0x7fffffffc820, node=...) at /home/ronso/Downloads/mixxx_source/src/master/src/skin/legacy/legacyskinparser.cpp:570
        result = {<QListSpecialMethods<QWidget*>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = -1}, static is_always_lock_free = true}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x7ffff387e760 <QListData::shared_null>}, d = 0x7ffff387e760 <QListData::shared_null>}}
        nodeName = {static null = {<No data fields>}, d = 0x55557af04290}
        __PRETTY_FUNCTION__ = "QList<QWidget*> LegacySkinParser::parseNode(const QDomElement&)"
#23 0x0000555555ebc682 in LegacySkinParser::parseChildren(QDomElement const&, WWidgetGroup*) (this=0x7fffffffc820, node=..., pGroup=0x555579b8d960) at /home/ronso/Downloads/mixxx_source/src/master/src/skin/legacy/legacyskinparser.cpp:708
        children = {<QListSpecialMethods<QWidget*>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = -1}, static is_always_lock_free = true}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x7ffff387e760 <QListData::shared_null>}, d = 0x7ffff387e760 <QListData::shared_null>}}
        node = {impl = 0x55557af042e0}
        i = 0
        children = {impl = 0x55557b245bf0}
        childrenNode = {impl = 0x55557af041e0}
        pOldParent = 0x55557332f2d0
#24 0x0000555555ebc881 in LegacySkinParser::parseWidgetGroup(QDomElement const&) (this=0x7fffffffc820, node=...) at /home/ronso/Downloads/mixxx_source/src/master/src/skin/legacy/legacyskinparser.cpp:726
        pGroup = 0x555579b8d960
#25 0x0000555555ebb742 in LegacySkinParser::parseNode(QDomElement const&) (this=0x7fffffffc820, node=...) at /home/ronso/Downloads/mixxx_source/src/master/src/skin/legacy/legacyskinparser.cpp:570
        result = {<QListSpecialMethods<QWidget*>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = -1}, static is_always_lock_free = true}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x7ffff387e760 <QListData::shared_null>}, d = 0x7ffff387e760 <QListData::shared_null>}}
        nodeName = {static null = {<No data fields>}, d = 0x55557af03e30}
        __PRETTY_FUNCTION__ = "QList<QWidget*> LegacySkinParser::parseNode(const QDomElement&)"
#26 0x0000555555ebc682 in LegacySkinParser::parseChildren(QDomElement const&, WWidgetGroup*) (this=0x7fffffffc820, node=..., pGroup=0x55557332f2d0) at /home/ronso/Downloads/mixxx_source/src/master/src/skin/legacy/legacyskinparser.cpp:708
        children = {<QListSpecialMethods<QWidget*>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = -1}, static is_always_lock_free = true}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x7ffff387e760 <QListData::shared_null>}, d = 0x7ffff387e760 <QListData::shared_null>}}
        node = {impl = 0x55557af03f10}
        i = 1
        children = {impl = 0x555575b0ba20}
        childrenNode = {impl = 0x55557393b910}
        pOldParent = 0x555576327ab0
#27 0x0000555555ebc881 in LegacySkinParser::parseWidgetGroup(QDomElement const&) (this=0x7fffffffc820, node=...) at /home/ronso/Downloads/mixxx_source/src/master/src/skin/legacy/legacyskinparser.cpp:726
        pGroup = 0x55557332f2d0
#28 0x0000555555ebb742 in LegacySkinParser::parseNode(QDomElement const&) (this=0x7fffffffc820, node=...) at /home/ronso/Downloads/mixxx_source/src/master/src/skin/legacy/legacyskinparser.cpp:570
        result = {<QListSpecialMethods<QWidget*>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = -1}, static is_always_lock_free = true}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x7ffff387e760 <QListData::shared_null>}, d = 0x7ffff387e760 <QListData::shared_null>}}
        nodeName = {static null = {<No data fields>}, d = 0x555577fc65e0}
        __PRETTY_FUNCTION__ = "QList<QWidget*> LegacySkinParser::parseNode(const QDomElement&)"
#29 0x0000555555ebe699 in LegacySkinParser::parseTemplate(QDomElement const&) (this=0x7fffffffc820, node=...) at /home/ronso/Downloads/mixxx_source/src/master/src/skin/legacy/legacyskinparser.cpp:1747
        childWidgets = {<QListSpecialMethods<QWidget*>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = -1}, static is_always_lock_free = true}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x7ffff387e760 <QListData::shared_null>}, d = 0x7ffff387e760 <QListData::shared_null>}}
        path = {static null = {<No data fields>}, d = 0x555572eb4c00}
        pOldContext = <optimized out>
        templateNode = {<QDomNode> = {impl = 0x55557a2d2b60}, <No data fields>}
        widgets = {<QListSpecialMethods<QWidget*>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = -1}, static is_always_lock_free = true}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x7ffff387e760 <QListData::shared_null>}, d = 0x7ffff387e760 <QListData::shared_null>}}
        child = {impl = 0x555577fc6680}
#30 0x0000555555ebbdbf in LegacySkinParser::parseNode(QDomElement const&) (this=0x7fffffffc820, node=...) at /home/ronso/Downloads/mixxx_source/src/master/src/skin/legacy/legacyskinparser.cpp:616
        result = {<QListSpecialMethods<QWidget*>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = -1}, static is_always_lock_free = true}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x7ffff387e760 <QListData::shared_null>}, d = 0x7ffff387e760 <QListData::shared_null>}}
        nodeName = {static null = {<No data fields>}, d = 0x55557f452710}
        __PRETTY_FUNCTION__ = "QList<QWidget*> LegacySkinParser::parseNode(const QDomElement&)"
#31 0x0000555555ebc128 in LegacySkinParser::parseSplitter(QDomElement const&) (this=0x7fffffffc820, node=...) at /home/ronso/Downloads/mixxx_source/src/master/src/skin/legacy/legacyskinparser.cpp:648
        children = {<QListSpecialMethods<QWidget*>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = -1}, static is_always_lock_free = true}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x7ffff387e760 <QListData::shared_null>}, d = 0x7ffff387e760 <QListData::shared_null>}}
        node = {impl = 0x55557261cae0}
        i = 1
        children = {impl = 0x55557332f060}
        pSplitter = 0x555576327ab0
        childrenNode = {impl = 0x5555752ca370}
        pOldParent = 0x5555787d5bf0
#32 0x0000555555ebbbde in LegacySkinParser::parseNode(QDomElement const&) (this=0x7fffffffc820, node=...) at /home/ronso/Downloads/mixxx_source/src/master/src/skin/legacy/legacyskinparser.cpp:602
        result = {<QListSpecialMethods<QWidget*>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = -1}, static is_always_lock_free = true}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x7ffff387e760 <QListData::shared_null>}, d = 0x7ffff387e760 <QListData::shared_null>}}
        nodeName = {static null = {<No data fields>}, d = 0x55557a2d5420}
        __PRETTY_FUNCTION__ = "QList<QWidget*> LegacySkinParser::parseNode(const QDomElement&)"
#33 0x0000555555ebd5c1 in LegacySkinParser::parseWidgetStack(QDomElement const&) (this=0x7fffffffc820, node=...) at /home/ronso/Downloads/mixxx_source/src/master/src/skin/legacy/legacyskinparser.cpp:777
        node = {impl = 0x555572871e00}
        pChild = <optimized out>
        on_hide_attr = {static null = {<No data fields>}, d = 0x7ffff387c680 <QArrayData::shared_null>}
        element = {<QDomNode> = {impl = 0x555572871e00}, <No data fields>}
        child_widgets = {<QListSpecialMethods<QWidget*>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = -1}, static is_always_lock_free = true}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x7ffff387e760 <QListData::shared_null>}, d = 0x7ffff387e760 <QListData::shared_null>}}
        pControl = <optimized out>
        trigger_configkey = {static null = {<No data fields>}, d = 0x7ffff387c680 <QArrayData::shared_null>}
        on_hide_select = <optimized out>
        i = 1
        children = {impl = 0x5555732ffb20}
        pNextControl = <optimized out>
        nextConfigKey = {group = {static null = {<No data fields>}, d = 0x7ffff387c680 <QArrayData::shared_null>}, item = {static null = {<No data fields>}, d = 0x7ffff387c680 <QArrayData::shared_null>}}
        pPrevControl = <optimized out>
        prevConfigKey = {group = {static null = {<No data fields>}, d = 0x7ffff387c680 <QArrayData::shared_null>}, item = {static null = {<No data fields>}, d = 0x7ffff387c680 <QArrayData::shared_null>}}
        pCurrentPageControl = <optimized out>
        currentPageConfigKey = {group = {static null = {<No data fields>}, d = 0x55556298cb00}, item = {static null = {<No data fields>}, d = 0x5555628bc8d0}}
        currentpage_co = {static null = {<No data fields>}, d = 0x555572e68da0}
        pStack = 0x5555787d5bf0
        pOldParent = 0x55557ae5e540
        childrenNode = {impl = 0x555572afbf10}
#34 0x0000555555ebb7d2 in LegacySkinParser::parseNode(QDomElement const&) (this=0x7fffffffc820, node=...) at /home/ronso/Downloads/mixxx_source/src/master/src/skin/legacy/legacyskinparser.cpp:574
        result = {<QListSpecialMethods<QWidget*>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = -1}, static is_always_lock_free = true}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x7ffff387e760 <QListData::shared_null>}, d = 0x7ffff387e760 <QListData::shared_null>}}
        nodeName = {static null = {<No data fields>}, d = 0x5555796c8b70}
        __PRETTY_FUNCTION__ = "QList<QWidget*> LegacySkinParser::parseNode(const QDomElement&)"
#35 0x0000555555ebc682 in LegacySkinParser::parseChildren(QDomElement const&, WWidgetGroup*) (this=0x7fffffffc820, node=..., pGroup=0x55557ae5e540) at /home/ronso/Downloads/mixxx_source/src/master/src/skin/legacy/legacyskinparser.cpp:708
        children = {<QListSpecialMethods<QWidget*>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = -1}, static is_always_lock_free = true}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x7ffff387e760 <QListData::shared_null>}, d = 0x7ffff387e760 <QListData::shared_null>}}
        node = {impl = 0x555572aec3a0}
        i = 2
        children = {impl = 0x5555728923d0}
        childrenNode = {impl = 0x555572f4b410}
        pOldParent = 0x5555730569b0
#36 0x0000555555ebc881 in LegacySkinParser::parseWidgetGroup(QDomElement const&) (this=0x7fffffffc820, node=...) at /home/ronso/Downloads/mixxx_source/src/master/src/skin/legacy/legacyskinparser.cpp:726
        pGroup = 0x55557ae5e540
#37 0x0000555555ebb742 in LegacySkinParser::parseNode(QDomElement const&) (this=0x7fffffffc820, node=...) at /home/ronso/Downloads/mixxx_source/src/master/src/skin/legacy/legacyskinparser.cpp:570
        result = {<QListSpecialMethods<QWidget*>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = -1}, static is_always_lock_free = true}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x7ffff387e760 <QListData::shared_null>}, d = 0x7ffff387e760 <QListData::shared_null>}}
        nodeName = {static null = {<No data fields>}, d = 0x5555796f1a80}
        __PRETTY_FUNCTION__ = "QList<QWidget*> LegacySkinParser::parseNode(const QDomElement&)"
#38 0x0000555555ebc682 in LegacySkinParser::parseChildren(QDomElement const&, WWidgetGroup*) (this=0x7fffffffc820, node=..., pGroup=0x5555730569b0) at /home/ronso/Downloads/mixxx_source/src/master/src/skin/legacy/legacyskinparser.cpp:708
        children = {<QListSpecialMethods<QWidget*>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = -1}, static is_always_lock_free = true}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x7ffff387e760 <QListData::shared_null>}, d = 0x7ffff387e760 <QListData::shared_null>}}
        node = {impl = 0x55557a74d160}
        i = 42
        children = {impl = 0x55557393aad0}
        childrenNode = {impl = 0x555573cd6840}
        pOldParent = 0x7fffffffdc00
#39 0x0000555555ebc881 in LegacySkinParser::parseWidgetGroup(QDomElement const&) (this=0x7fffffffc820, node=...) at /home/ronso/Downloads/mixxx_source/src/master/src/skin/legacy/legacyskinparser.cpp:726
        pGroup = 0x5555730569b0
#40 0x0000555555ebae2b in LegacySkinParser::parseNode(QDomElement const&) (this=0x7fffffffc820, node=...) at /home/ronso/Downloads/mixxx_source/src/master/src/skin/legacy/legacyskinparser.cpp:486
        layout = {static null = {<No data fields>}, d = 0x555572eed5e0}
        newStyle = true
        result = {<QListSpecialMethods<QWidget*>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = -1}, static is_always_lock_free = true}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x7ffff387e760 <QListData::shared_null>}, d = 0x7ffff387e760 <QListData::shared_null>}}
        nodeName = {static null = {<No data fields>}, d = 0x555574f438e0}
        __PRETTY_FUNCTION__ = "QList<QWidget*> LegacySkinParser::parseNode(const QDomElement&)"
#41 0x0000555555ec0560 in LegacySkinParser::parseSkin(QString const&, QWidget*) (this=this@entry=0x7fffffffc820, skinPath=..., pParent=pParent@entry=0x7fffffffdc00) at /home/ronso/Downloads/mixxx_source/src/master/src/skin/legacy/legacyskinparser.cpp:409
        timer = {_vptr.ScopedTimer = 0x5555565a6310 <vtable for ScopedTimer+16>, m_pTimer = 0x7fffffffc6b0, m_timerMem = "\300\200\177{UU\000\000o\000\000\000\001\177\000\000\071\301\001\000\000\000\000\000\032\354\000#\000\000\000", m_cancel = false}
        __PRETTY_FUNCTION__ = "virtual QWidget* LegacySkinParser::parseSkin(const QString&, QWidget*)"
        skinDocument = {<QDomNode> = {impl = 0x555579e34b30}, <No data fields>}
        manifest = {<google::protobuf::MessageLite> = {<No data fields>}, static kIndexInFileMessages = 1, static kAttributeFieldNumber = 7, static kTitleFieldNumber = 1, static kAuthorFieldNumber = 2, static kVersionFieldNumber = 3, static kLanguageFieldNumber = 4, static kDescriptionFieldNumber = 5, static kLicenseFieldNumber = 6, _internal_metadata_ = {<google::protobuf::internal::InternalMetadataWithArenaBase<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, google::protobuf::internal::InternalMetadataWithArenaLite>> = {ptr_ = 0x0, static kPtrTagMask = 1, static kPtrValueMask = -2}, <No data fields>}, _has_bits_ = {has_bits_ = {63}}, _cached_size_ = {size_ = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = 0}, static is_always_lock_free = true}}, attribute_ = {<google::protobuf::internal::RepeatedPtrFieldBase> = {static kInitialSize = 0, arena_ = 0x0, current_size_ = 56, total_size_ = 64, static kRepHeaderSize = 8, rep_ = 0x555571ff6b20}, <No data fields>}, title_ = {ptr_ = 0x55557a30c520}, author_ = {ptr_ = 0x55557105acf0}, version_ = {ptr_ = 0x555571eff800}, language_ = {ptr_ = 0x5555768e1240}, description_ = {ptr_ = 0x5555794b8bb0}, license_ = {ptr_ = 0x5555796b95b0}}
        widgets = {<QListSpecialMethods<QWidget*>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = -1}, static is_always_lock_free = true}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x7ffff387e760 <QListData::shared_null>}, d = 0x7ffff387e760 <QListData::shared_null>}}
#42 0x0000555555eae6e8 in mixxx::skin::legacy::LegacySkin::loadSkin(QWidget*, QSharedPointer<ConfigObject<ConfigValue> >, QSet<ControlObject*>*, mixxx::CoreServices*) const (this=0x555574ed49f0, pParent=0x7fffffffdc00, pConfig=..., pSkinCreatedControls=<optimized out>, pCoreServices=<optimized out>) at /home/ronso/Downloads/mixxx_source/src/master/src/skin/legacy/legacyskin.cpp:144
        __PRETTY_FUNCTION__ = "virtual QWidget* mixxx::skin::legacy::LegacySkin::loadSkin(QWidget*, UserSettingsPointer, QSet<ControlObject*>*, mixxx::CoreServices*) const"
        legacy = {<QObject> = {<No data fields>}, <SkinParser> = {_vptr.SkinParser = 0x5555565d93b0 <vtable for LegacySkinParser+144>}, static staticMetaObject = {d = {superdata = 0x7ffff3a4d980 <QObject::staticMetaObject>, stringdata = 0x55555635f0a0 <qt_meta_stringdata_LegacySkinParser>, data = 0x55555635f060 <qt_meta_data_LegacySkinParser>, static_metacall = 0x555555eaec90 <LegacySkinParser::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, relatedMetaObjects = 0x0, extradata = 0x0}}, m_pConfig = {value = 0x555556943d80, d = 0x555556804390}, m_pSkinCreatedControls = 0x7fffffffdca8, m_pKeyboard = 0x555556981960, m_pPlayerManager = 0x55555fe1c620, m_pControllerManager = 0x7fffc4012020, m_pLibrary = 0x5555628cda00, m_pVCManager = 0x55555fdc7380, m_pEffectsManager = 0x555556dd9f40, m_pRecordingManager = 0x55555fe18080, m_pParent = 0x5555792b27a0, m_pContext = std::unique_ptr<class SkinContext> = {get() = 0x555574c33770}, m_style = {static null = {<No data fields>}, d = 0x7ffff387c680 <QArrayData::shared_null>}, m_tooltips = {<QObject> = {<No data fields>}, static staticMetaObject = {d = {superdata = 0x7ffff3a4d980 <QObject::staticMetaObject>, stringdata = 0x55555635f160 <qt_meta_stringdata_Tooltips>, data = 0x55555635f120 <qt_meta_data_Tooltips>, static_metacall = 0x555555ec2b10 <Tooltips::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, relatedMetaObjects = 0x0, extradata = 0x0}}, m_tooltips = {{d = 0x5555709b9430, e = 0x5555709b9430}}}, m_templateCache = {{d = 0x55557bf7d1f0, e = 0x55557bf7d1f0}}, static s_sharedGroupStrings = {q_hash = {{d = 0x555570b94920, e = 0x555570b94920}}}}
#43 0x0000555555b592fe in mixxx::skin::SkinLoader::loadConfiguredSkin(QWidget*, QSet<ControlObject*>*, mixxx::CoreServices*) (this=0x555556738880, pParent=pParent@entry=0x7fffffffdc00, pSkinCreatedControls=pSkinCreatedControls@entry=0x7fffffffdca8, pCoreServices=0x55555673a640) at /usr/include/c++/10/bits/atomic_base.h:325
        timer = {_vptr.ScopedTimer = 0x5555565a6310 <vtable for ScopedTimer+16>, m_pTimer = 0x7fffffffca00, m_timerMem = " \336\000rUU\000\000o\000\000\000\001\177\000\000\071\301\001\000\000\000\000\000\346-\352\"\000\000\000", m_cancel = false}
        pSkin = std::shared_ptr<class mixxx::skin::Skin> (use count 1, weak count 0) = {get() = 0x555574ed49f0}
        __PRETTY_FUNCTION__ = "QWidget* mixxx::skin::SkinLoader::loadConfiguredSkin(QWidget*, QSet<ControlObject*>*, mixxx::CoreServices*)"
        pLoadedSkin = <optimized out>
#44 0x000055555584afd6 in MixxxMainWindow::loadConfiguredSkin() (this=0x7fffffffdc00) at /usr/include/c++/10/bits/shared_ptr_base.h:1324
#45 0x000055555584d3c7 in MixxxMainWindow::rebootMixxxView() (this=0x7fffffffdc00) at /home/ronso/Downloads/mixxx_source/src/master/src/mixxxmainwindow.cpp:1084
        __PRETTY_FUNCTION__ = "void MixxxMainWindow::rebootMixxxView()"
        initGeometry = {x1 = 575, y1 = 29, x2 = 1854, y2 = 1074}
        wasFullScreen = false
#46 0x00007ffff37c7328 in QMetaObject::activate(QObject*, int, int, void**) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#47 0x00007ffff37c7328 in QMetaObject::activate(QObject*, int, int, void**) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#48 0x0000555555afc6d3 in DlgPrefInterface::reloadUserInterface() (this=0x555567823b20) at /home/ronso/Downloads/mixxx_source/src/xxx_master_build/Debug/mixxx-lib_autogen/include/moc_dlgprefinterface.cpp:190
        locale = {static null = {<No data fields>}, d = 0x5555678320a0}
        scaleFactor = 1
        screensaverComboBoxState = 1
        screensaverConfiguredState = <optimized out>
#49 DlgPrefInterface::slotApply() (this=0x555567823b20) at /home/ronso/Downloads/mixxx_source/src/master/src/preferences/dialog/dlgprefinterface.cpp:442
        locale = {static null = {<No data fields>}, d = 0x5555678320a0}
        scaleFactor = 1
        screensaverComboBoxState = 1
        screensaverConfiguredState = <optimized out>
#50 0x00007ffff37c7328 in QMetaObject::activate(QObject*, int, int, void**) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#51 0x0000555555af2866 in DlgPreferences::applyPreferences() (this=0x5555649daa40) at /home/ronso/Downloads/mixxx_source/src/xxx_master_build/Debug/mixxx-lib_autogen/include/moc_dlgpreferences.cpp:239
        role = QDialogButtonBox::AcceptRole
        pCurrentPage = <optimized out>
        __PRETTY_FUNCTION__ = "void DlgPreferences::slotButtonPressed(QAbstractButton*)"
#52 DlgPreferences::slotButtonPressed(QAbstractButton*) (this=0x5555649daa40, pButton=<optimized out>) at /home/ronso/Downloads/mixxx_source/src/master/src/preferences/dialog/dlgpreferences.cpp:430
        role = QDialogButtonBox::AcceptRole
        pCurrentPage = <optimized out>
        __PRETTY_FUNCTION__ = "void DlgPreferences::slotButtonPressed(QAbstractButton*)"
#53 0x00007ffff37c7328 in QMetaObject::activate(QObject*, int, int, void**) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#54 0x00007ffff6d4f333 in QDialogButtonBox::clicked(QAbstractButton*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#55 0x00007ffff6d4faf9 in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#56 0x00007ffff37c71d0 in QMetaObject::activate(QObject*, int, int, void**) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#57 0x00007ffff6ca8806 in QAbstractButton::clicked(bool) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#58 0x00007ffff6ca8a2e in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#59 0x00007ffff6ca9799 in QAbstractButton::click() () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#60 0x00007ffff6db7854 in QDialog::keyPressEvent(QKeyEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#61 0x00007ffff6bf677d in QWidget::event(QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#62 0x00007ffff6bb3a66 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#63 0x00007ffff6bbd81e in QApplication::notify(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#64 0x00007ffff379b80a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#65 0x00007ffff6c15216 in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#66 0x00007ffff6bb3a66 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#67 0x00007ffff6bbd0f0 in QApplication::notify(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#68 0x00007ffff379b80a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#69 0x00007ffff6535b2b in QGuiApplicationPrivate::processKeyEvent(QWindowSystemInterfacePrivate::KeyEvent*) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#70 0x00007ffff653b0f1 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#71 0x00007ffff651535b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#72 0x00007fffeadaf32e in  () at /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#73 0x00007ffff267a17d in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#74 0x00007ffff267a400 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#75 0x00007ffff267a4a3 in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#76 0x00007ffff37f3435 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#77 0x00007ffff379a3ab in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#78 0x00007ffff37a2116 in QCoreApplication::exec() () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#79 0x000055555574cc4e in (anonymous namespace)::runMixxx (args=..., pApp=0x7fffffffdbc0) at /home/ronso/Downloads/mixxx_source/src/master/src/main.cpp:82
        mainWindow = {<QMainWindow> = {<No data fields>}, static staticMetaObject = {d = {superdata = 0x7ffff70bf4e0 <QMainWindow::staticMetaObject>, stringdata = 0x555556302d60 <qt_meta_stringdata_MixxxMainWindow>, data = 0x555556302b00 <qt_meta_data_MixxxMainWindow>, static_metacall = 0x55555584e680 <MixxxMainWindow::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, relatedMetaObjects = 0x0, extradata = 0x0}}, m_pCoreServices = std::shared_ptr<class mixxx::CoreServices> (use count 2, weak count 0) = {get() = 0x55555673a640}, m_pCentralWidget = 0x0, m_pLaunchImage = 0x0, m_pSkinLoader = std::shared_ptr<class mixxx::skin::SkinLoader> (use count 2, weak count 0) = {get() = 0x555556738880}, m_pGuiTick = 0x55555699e990, m_pVisualsManager = 0x555556d655e0, m_pMenuBar = {m_ptr = 0x7fffc4013400}, m_supportsGlobalMenuBar = true, m_pDeveloperToolsDlg = 0x0, m_pPrefDlg = 0x5555649daa40, m_pKeywheel = {m_ptr = 0x0}, m_pLibraryExporter = std::unique_ptr<class mixxx::LibraryExporter> = {get() = 0x555562d70360}, m_toolTipsCfg = mixxx::TooltipsPreference::TOOLTIPS_ON, m_inhibitScreensaver = (mixxx::ScreenSaverPreference::PREVENT_ON | unknown: 21844), m_skinCreatedControls = {q_hash = {{d = 0x555570a8a6b0, e = 0x555570a8a6b0}}}}
        exitCode = <optimized out>
        console = {<No data fields>}
        args = <optimized out>
        app = {<QApplication> = {<No data fields>}, static staticMetaObject = {d = {superdata = 0x7ffff70b4620 <QApplication::staticMetaObject>, stringdata = 0x5555562fd820 <qt_meta_stringdata_MixxxApplication>, data = 0x5555562fd7e0 <qt_meta_data_MixxxApplication>, static_metacall = 0x5555557b5ca0 <MixxxApplication::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, relatedMetaObjects = 0x0, extradata = 0x0}}, m_rightPressedButtons = 0, m_pTouchShift = 0x0}
        exitCode = <optimized out>
        __PRETTY_FUNCTION__ = "int main(int, char**)"
#80 main(int, char**) (argc=<optimized out>, argv=<optimized out>) at /home/ronso/Downloads/mixxx_source/src/master/src/main.cpp:213
        console = {<No data fields>}
        args = <optimized out>
        app = {<QApplication> = {<No data fields>}, static staticMetaObject = {d = {superdata = 0x7ffff70b4620 <QApplication::staticMetaObject>, stringdata = 0x5555562fd820 <qt_meta_stringdata_MixxxApplication>, data = 0x5555562fd7e0 <qt_meta_data_MixxxApplication>, static_metacall = 0x5555557b5ca0 <MixxxApplication::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, relatedMetaObjects = 0x0, extradata = 0x0}}, m_rightPressedButtons = 0, m_pTouchShift = 0x0}
        exitCode = <optimized out>
        __PRETTY_FUNCTION__ = "int main(int, char**)"
</details>

**Comment by daschuer** [comment]
Regarding the VU-Meter, I don't demand to make work every combination with the separate Vu Meter flag. 
So when it helps to simplyfy the issue, we may remove it.

**Comment by daschuer** [comment]
>> Even though it is compiled with QOPENGL=OFF, the "Simple (all-shaders) (GLSL)" waveform is selectable

> This is expected. The allshaders waveform should also work with QWidget.

Ok, if it only does not work on my Plattform (and similar) we can leaf it broken. The user has plenty of alternatives. 

If you have a quick idea to detect the broken state or even fix it. It is of cause welcome, but no stopper for this PR.

File: src/widget/wspinnybase.cpp (hunk 75 above)
Comment (daschuer) [reply src/widget/wspinnybase.cpp:203]: Ok than it is fine.

**Comment by m0dB** [comment]
@ronso0 @daschuer to be sure, switching skins works fine with QOPENGL=ON and crashes only with QOPENGL=OFF ?

**Comment by daschuer** [comment]
Yes, only with QOPENGL=OFF

**Comment by m0dB** [comment]
@Swiftb0y @uklotzde please note 
https://github.com/mixxxdj/mixxx/pull/10989/commits/132e33f86707050a9c682dc7cf4f92d21af55994
I changed this to ```return m_pPixmap->toImage();``` based on a review, but this is actually wrong. I changed it back and left a comment explaining why.

**Comment by ronso0** [comment]
> @ronso0 @daschuer to be sure, switching skins works fine with QOPENGL=ON and crashes only with QOPENGL=OFF ?

The OPENGL switch doesn't seem to make a difference here.
4.6 (Compatibility Profile) Mesa 21.2.6 Intel Mesa Intel(R) UHD Graphics 620 (KBL GT2)

I could always switch  skin **with main decks empty** (samplers were loaded but those don't have scrolling waveforms or spinnies).
With main decks loaded it would crash.
I also just encountered a crash when loaded a track after switching skins with empty decks.
IIRC all crashes were
```
pure virtual method called
terminate called without an active exception
```

**Comment by ronso0** [comment]
> I also just encountered a crash when loaded a track after switching skins with empty decks.

Oh, that's a separate issue I guess: happened again when dragging (cloning) a track to the other deck's overview.

FWIW just now I caould switch back and forth between Tango and LateNight with deck2 playing :shrug: 
Will try to find a pattern / skin that always crashes.

**Comment by ronso0** [comment]
> Oh, that's a separate issue I guess: happened again when dragging (cloning) a track to the other deck's overview.

That happens when dragging a track onto _any_ OpenGL widget: VU meter, spinny, waveform.

**Comment by JoergAtGithub** [comment]
> 
> That happens when dragging a track onto _any_ OpenGL widget: VU meter, spinny, waveform.

@ronso0 Just to confirm, are you sure you use the latest commit? This issue was reported before by me, and is now fixed for me.

**Comment by m0dB** [comment]
I have been running both with and without QOPENGL and addressed some issues (and acted on some reviews from @daschuer with minor aesthetic changes). On macOS both are running without crashes. I can switch skins without any issue both with and without QOPENGL and I can drag & drop without problems (as @JoergAtGithub says, it might be @ronso0 is not testing the latest version?).

I have decided to use the GLSL based vu-meter and spinnies only when QOPENGL=ON. I don't see a good reason why they wouldn't work with QOPENGL=OFF, but I don't really care at this point.

What worries me most now is the pure virtual call that @daschuer reports. I can't reproduce this at all on macOS but I remember we have seen something similar in the past and IIRC @daschuer tracked this down to xcb resulting in a double delete on teardown and the workaround was to set the parent of the vu meter and spinnies _after_ their construction. Maybe something similar is happening with the opengl-based WGLWidgets... Anyway, I also addressed some openGL issues that were triggering warnings (like creating QOpenGLTexture without a valid context), and that could also have caused trouble. So please test if this still occurs.

**Comment by ronso0** [comment]
> @ronso0 Just to confirm, are you sure you use the latest commit? This issue was reported before by me, and is now fixed for me.

Oh, I noticed just now that `gh pr checkout 10989` didn't fast-forward.
So, yes, the dnd issues is resolved. Great!

* I can switch skins without any issues
* all waveforms look smoooth @60 fps -- except **Filtered - Qt (GL)** (see below)
* spinnies are smooth and look good at all sizes
* VU meters are smooth

The only issues I see
* all **all-shaders** waveforms are broken with QOPENGL=OFF, idk if they're supposed to work at all: they're sluggish and don't use the available space. Probably we can just hide the with QOPENGL=OFF, I think users are overwhelmed with the current set already
image
* the **counter** is constantly reporting dropped frames @60 fps
* **Filtered - Qt (GL)** which is sluggish and won't get faster that 20 fps -- it works smooth in plain 2.4

@m0dB Thanks for all your work!

**Comment by m0dB** [comment]
Thanks @ronso0 ! Yes, I agree that it makes sense to hide the allshaders when QOPENGL=OFF. Like with the vumeters and the spinnies, I don't see a reason why they shouldn't work in combination with QGLWidget, but probably not worth investing any time and energy. It is with QOPENGL=ON that the use of the allshaders waveform types is most relevant (see below).

> Filtered - Qt (GL) which is sluggish and won't get faster that 20 fps -- it works smooth in plain 2.4

Right, I have mentioned this before: With the QOpenGLWindow based WGLWidget, using QPainter on the QOpenGLWindow has a performance penalty. (This is the main reason why I implemented the allshaders waveform types that use GLSL for all the layers, without any QPainter calls). This performance penalty is particularly noticeable with the Filtered - Qt (GL) waveform type and I see no way around this.

Of course this and "I think users are overwhelmed with the current set already" begs the question: why are we including all these waveform types? I would argue that the allshader renderers clearly give the best performance and that the code is very polished (there always room for improvement, but generally it is more polished than most of the other renderers). So with QOPENGL=ON, maybe we could consider hiding all other waveforms behind a command line option?

**Comment by ronso0** [comment]
> Right, I have mentioned this before: With the QOpenGLWindow based WGLWidget, using QPainter on the QOpenGLWindow has a performance penalty. ... This performance penalty is particularly noticeable with the Filtered - Qt (GL) waveform type and I see no way around this.

So let's hide that as well. There are other Filtered types that look similar, and we shouldn't offer it if it doesn't work satisfactorily.

**Comment by ronso0** [comment]
Oh, one more thing:
the spinnies' ghost indicator looks pixelated and doesn't move smoothly (with all skins).
Not sure if that's a transparency issue. I can take a look at the skins, though probably not before next week.

**Comment by m0dB** [comment]
> Oh, one more thing:
> the spinnies' ghost indicator looks pixelated and doesn't move smoothly (with all skins).
> Not sure if that's a transparency issue. I can take a look at the skins, though probably not before next week.

Interesting, I don't see that but I am using a HDPI display. When I have a moment I will check on 1:1 pixel ratio. I might need to tweak the texture settings. I don't think it's a transparency issue or skins related.

**Comment by Swiftb0y** [comment]
> @Swiftb0y @uklotzde please note [132e33f](https://github.com/mixxxdj/mixxx/commit/132e33f86707050a9c682dc7cf4f92d21af55994) I changed this to `return m_pPixmap->toImage();` based on a review, but this is actually wrong. I changed it back and left a comment explaining why.

Sorry for the bogus suggestion, thank you for the comment.

**Comment by m0dB** [comment]
> Sorry for the bogus suggestion, thank you for the comment.

No problem at all, it confused me as well, so well worth the comment.

**Comment by ronso0** [comment]
> Interesting, I don't see that but I am using a HDPI display. When I have a moment I will check on 1:1 pixel ratio. I might need to tweak the texture settings. I don't think it's a transparency issue or skins related.

Note it's just the ghost indicators (slip mode), the regular play position looks good.

**Comment by m0dB** [comment]
Yes. Here it looked good. Do you have a screenshot to show what you mean?
 
Screenshot 2023-05-13 at 19 09 47

**Comment by ronso0** [comment]
This video hopefully shows the lower fps of the ghost, and that it's shown briefly at 12 o'clock when slip mode is enabled
https://github.com/mixxxdj/mixxx/assets/5934199/56270c09-fc3a-415e-8e0d-0619b9bb7662

and hopefully it also shows that the rendering is not as smooth as the play pos (is it just the low fps that makes it look like no anti aliasing?)

**Comment by daschuer** [comment]
I can also confirm the missing anti-aliasing in with the normal spiny sticker and an QOPENGL=ON 
grafik


It looks like that in 2.3.5
grafik

**Comment by daschuer** [comment]
With QOPENGL=ON I am still able to crash Mixxx with 
```
debug [Main] WaveformWidgetFactory::setWaveformWidget - waveform widget added in factory, index 0
debug [Main] WSpinnyBase(): Created WGLWidget, Context Valid: false Sharing: true
pure virtual method called
terminate called without an active exception
```
After changing the Waveform overview. 

<details>
  <summary>Backtrace</summary>
```
Thread 1 "mixxx" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      in ../sysdeps/unix/sysv/linux/raise.c
(gdb) bt                                                                                                                                                                 
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff32f2859 in __GI_abort () at abort.c:79
#2  0x00007ffff371b911 in  () at /lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff372738c in  () at /lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff37273f7 in  () at /lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff3728155 in  () at /lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x0000555555cad6d5 in WSpinnyBase::slotCoverFound(QObject const*, CoverInfo const&, QPixmap const&, unsigned long long, bool) (pRequestor=<optimized out>, coverInfo=..., requestedCacheKey=<optimized out>, coverInfoUpdated=<optimized out>, pixmap=..., this=0x55556ee75c10) at ../../src/widget/wspinnybase.cpp:307
#7  WSpinnyBase::slotCoverFound(QObject const*, CoverInfo const&, QPixmap const&, unsigned long long, bool) (this=0x55556ee75c10, pRequestor=<optimized out>, coverInfo=..., pixmap=..., requestedCacheKey=<optimized out>, coverInfoUpdated=<optimized out>) at ../../src/widget/wspinnybase.cpp:295
#8  0x00007ffff3b86328 in QtPrivate::QSlotObjectBase::call(QObject*, void**) (a=0x7fffffff9250, r=0x55556ee75c10, this=0x55556f4902a0) at ../../include/QtCore/../../src/corelib/kernel/qobjectdefs_impl.h:394
#9  QMetaObject::activate(QObject*, int, int, void**) (sender=0x555560097480, signalOffset=<optimized out>, local_signal_index=<optimized out>, argv=<optimized out>) at kernel/qobject.cpp:3784
#10 0x00005555559f4ccd in CoverArtCache::coverFound(QObject const*, CoverInfo const&, QPixmap const&, unsigned long long, bool) (_t5=<optimized out>, _t4=<optimized out>, _t3=..., _t2=..., _t1=<optimized out>, this=0x555560097480) at mixxx-lib_autogen/include/moc_coverartcache.cpp:162
#11 CoverArtCache::tryLoadCover(QObject const*, std::shared_ptr<Track> const&, CoverInfo const&, int, CoverArtCache::Loading) (this=0x555560097480, pRequestor=<optimized out>, pTrack=..., coverInfo=..., desiredWidth=<optimized out>, loading=CoverArtCache::Loading::Default) at ../../src/library/coverartcache.cpp:97
#12 0x00005555559f5efa in CoverArtCache::requestCover(QObject const*, CoverInfo const&, std::shared_ptr<Track> const&) (pRequestor=0x55556ee75c10, coverInfo=..., pTrack=std::shared_ptr<class Track> (use count 17, weak count 1) = {...}) at ../../src/library/coverartcache.cpp:55
#13 0x00005555559f5f78 in CoverArtCache::requestTrackCover(QObject const*, std::shared_ptr<Track> const&) (pRequestor=pRequestor@entry=0x55556ee75c10, pTrack=std::shared_ptr<class Track> (use count 17, weak count 1) = {...}) at ../../src/library/coverartcache.cpp:70
#14 0x0000555555caca25 in WSpinnyBase::slotTrackCoverArtUpdated() (this=0x55556ee75c10) at ../../src/widget/wspinnybase.cpp:291
#15 WSpinnyBase::slotLoadTrack(std::shared_ptr<Track>) (this=0x55556ee75c10, pTrack=...) at ../../src/widget/wspinnybase.cpp:271
#16 0x0000555555cad24c in WSpinnyBase::WSpinnyBase(QWidget*, QString const&, QSharedPointer<ConfigObject<ConfigValue> >, VinylControlManager*, BaseTrackPlayer*) (this=0x55556ee75c10, parent=<optimized out>, group=..., pConfig=..., pVCMan=<optimized out>, pPlayer=<optimized out>) at ../../src/widget/wspinnybase.cpp:90
#17 0x0000555555f57de8 in WSpinnyGLSL::WSpinnyGLSL(QWidget*, QString const&, QSharedPointer<ConfigObject<ConfigValue> >, VinylControlManager*, BaseTrackPlayer*) (this=0x55556ee75c10, parent=<optimized out>, group=..., pConfig=..., pVCMan=<optimized out>, pPlayer=<optimized out>) at /usr/include/c++/9/bits/atomic_base.h:318
#18 0x0000555555ec8f77 in LegacySkinParser::parseSpinny(QDomElement const&) (this=0x7fffffffc680, node=...) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qsharedpointer_impl.h:330
#19 0x0000555555ecd644 in LegacySkinParser::parseNode(QDomElement const&) (this=0x7fffffffc680, node=...) at ../../src/skin/legacy/legacyskinparser.cpp:596
#20 0x0000555555ece26f in LegacySkinParser::parseChildren(QDomElement const&, WWidgetGroup*) (this=0x7fffffffc680, node=..., pGroup=0x55556eef2440) at ../../src/skin/legacy/legacyskinparser.cpp:708
#21 0x0000555555ece451 in LegacySkinParser::parseWidgetGroup(QDomElement const&) (this=0x7fffffffc680, node=...) at ../../src/skin/legacy/legacyskinparser.cpp:726
#22 0x0000555555ecd2b6 in LegacySkinParser::parseNode(QDomElement const&) (this=0x7fffffffc680, node=...) at ../../src/skin/legacy/legacyskinparser.cpp:570
#23 0x0000555555ece26f in LegacySkinParser::parseChildren(QDomElement const&, WWidgetGroup*) (this=0x7fffffffc680, node=..., pGroup=0x55556eef1d40) at ../../src/skin/legacy/legacyskinparser.cpp:708
#24 0x0000555555ece451 in LegacySkinParser::parseWidgetGroup(QDomElement const&) (this=0x7fffffffc680, node=...) at ../../src/skin/legacy/legacyskinparser.cpp:726
#25 0x0000555555ecd2b6 in LegacySkinParser::parseNode(QDomElement const&) (this=0x7fffffffc680, node=...) at ../../src/skin/legacy/legacyskinparser.cpp:570
#26 0x0000555555ece26f in LegacySkinParser::parseChildren(QDomElement const&, WWidgetGroup*) (this=0x7fffffffc680, node=..., pGroup=0x55556f03b7f0) at ../../src/skin/legacy/legacyskinparser.cpp:708
#27 0x0000555555ece451 in LegacySkinParser::parseWidgetGroup(QDomElement const&) (this=0x7fffffffc680, node=...) at ../../src/skin/legacy/legacyskinparser.cpp:726
#28 0x0000555555ecd2b6 in LegacySkinParser::parseNode(QDomElement const&) (this=0x7fffffffc680, node=...) at ../../src/skin/legacy/legacyskinparser.cpp:570
#29 0x0000555555ece26f in LegacySkinParser::parseChildren(QDomElement const&, WWidgetGroup*) (this=0x7fffffffc680, node=..., pGroup=0x55556ecbdc30) at ../../src/skin/legacy/legacyskinparser.cpp:708
#30 0x0000555555ece451 in LegacySkinParser::parseWidgetGroup(QDomElement const&) (this=0x7fffffffc680, node=...) at ../../src/skin/legacy/legacyskinparser.cpp:726
#31 0x0000555555ecd2b6 in LegacySkinParser::parseNode(QDomElement const&) (this=0x7fffffffc680, node=...) at ../../src/skin/legacy/legacyskinparser.cpp:570
#32 0x0000555555ece26f in LegacySkinParser::parseChildren(QDomElement const&, WWidgetGroup*) (this=0x7fffffffc680, node=..., pGroup=0x55556ecbd490) at ../../src/skin/legacy/legacyskinparser.cpp:708
#33 0x0000555555ece451 in LegacySkinParser::parseWidgetGroup(QDomElement const&) (this=0x7fffffffc680, node=...) at ../../src/skin/legacy/legacyskinparser.cpp:726
#34 0x0000555555ecd2b6 in LegacySkinParser::parseNode(QDomElement const&) (this=0x7fffffffc680, node=...) at ../../src/skin/legacy/legacyskinparser.cpp:570
#35 0x0000555555ece26f in LegacySkinParser::parseChildren(QDomElement const&, WWidgetGroup*) (this=0x7fffffffc680, node=..., pGroup=0x55556f624960) at ../../src/skin/legacy/legacyskinparser.cpp:708
#36 0x0000555555ece451 in LegacySkinParser::parseWidgetGroup(QDomElement const&) (this=0x7fffffffc680, node=...) at ../../src/skin/legacy/legacyskinparser.cpp:726
#37 0x0000555555ecd2b6 in LegacySkinParser::parseNode(QDomElement const&) (this=0x7fffffffc680, node=...) at ../../src/skin/legacy/legacyskinparser.cpp:570
#38 0x0000555555ece26f in LegacySkinParser::parseChildren(QDomElement const&, WWidgetGroup*) (this=0x7fffffffc680, node=..., pGroup=0x55556f3f5790) at ../../src/skin/legacy/legacyskinparser.cpp:708
#39 0x0000555555ece451 in LegacySkinParser::parseWidgetGroup(QDomElement const&) (this=0x7fffffffc680, node=...) at ../../src/skin/legacy/legacyskinparser.cpp:726
#40 0x0000555555ecd2b6 in LegacySkinParser::parseNode(QDomElement const&) (this=0x7fffffffc680, node=...) at ../../src/skin/legacy/legacyskinparser.cpp:570
#41 0x0000555555ece26f in LegacySkinParser::parseChildren(QDomElement const&, WWidgetGroup*) (this=0x7fffffffc680, node=..., pGroup=0x555571167c60) at ../../src/skin/legacy/legacyskinparser.cpp:708
#42 0x0000555555ece451 in LegacySkinParser::parseWidgetGroup(QDomElement const&) (this=0x7fffffffc680, node=...) at ../../src/skin/legacy/legacyskinparser.cpp:726
#43 0x0000555555ecd2b6 in LegacySkinParser::parseNode(QDomElement const&) (this=0x7fffffffc680, node=...) at ../../src/skin/legacy/legacyskinparser.cpp:570
#44 0x0000555555ece26f in LegacySkinParser::parseChildren(QDomElement const&, WWidgetGroup*) (this=0x7fffffffc680, node=..., pGroup=0x555572504540) at ../../src/skin/legacy/legacyskinparser.cpp:708
#45 0x0000555555ece451 in LegacySkinParser::parseWidgetGroup(QDomElement const&) (this=0x7fffffffc680, node=...) at ../../src/skin/legacy/legacyskinparser.cpp:726
#46 0x0000555555ecd2b6 in LegacySkinParser::parseNode(QDomElement const&) (this=0x7fffffffc680, node=...) at ../../src/skin/legacy/legacyskinparser.cpp:570
#47 0x0000555555ed00f5 in LegacySkinParser::parseTemplate(QDomElement const&) (this=0x7fffffffc680, node=...) at ../../src/skin/legacy/legacyskinparser.cpp:1747
#48 0x0000555555ecd905 in LegacySkinParser::parseNode(QDomElement const&) (this=0x7fffffffc680, node=...) at ../../src/skin/legacy/legacyskinparser.cpp:616
#49 0x0000555555ece26f in LegacySkinParser::parseChildren(QDomElement const&, WWidgetGroup*) (this=0x7fffffffc680, node=..., pGroup=0x555570ff85f0) at ../../src/skin/legacy/legacyskinparser.cpp:708
#50 0x0000555555ece451 in LegacySkinParser::parseWidgetGroup(QDomElement const&) (this=0x7fffffffc680, node=...) at ../../src/skin/legacy/legacyskinparser.cpp:726
#51 0x0000555555ecd2b6 in LegacySkinParser::parseNode(QDomElement const&) (this=0x7fffffffc680, node=...) at ../../src/skin/legacy/legacyskinparser.cpp:570
#52 0x0000555555ece26f in LegacySkinParser::parseChildren(QDomElement const&, WWidgetGroup*) (this=0x7fffffffc680, node=..., pGroup=0x5555707afcf0) at ../../src/skin/legacy/legacyskinparser.cpp:708
#53 0x0000555555ece451 in LegacySkinParser::parseWidgetGroup(QDomElement const&) (this=0x7fffffffc680, node=...) at ../../src/skin/legacy/legacyskinparser.cpp:726
#54 0x0000555555ecd2b6 in LegacySkinParser::parseNode(QDomElement const&) (this=0x7fffffffc680, node=...) at ../../src/skin/legacy/legacyskinparser.cpp:570
#55 0x0000555555ece26f in LegacySkinParser::parseChildren(QDomElement const&, WWidgetGroup*) (this=0x7fffffffc680, node=..., pGroup=0x555570a72af0) at ../../src/skin/legacy/legacyskinparser.cpp:708
#56 0x0000555555ece451 in LegacySkinParser::parseWidgetGroup(QDomElement const&) (this=0x7fffffffc680, node=...) at ../../src/skin/legacy/legacyskinparser.cpp:726
#57 0x0000555555ecd2b6 in LegacySkinParser::parseNode(QDomElement const&) (this=0x7fffffffc680, node=...) at ../../src/skin/legacy/legacyskinparser.cpp:570
#58 0x0000555555ece26f in LegacySkinParser::parseChildren(QDomElement const&, WWidgetGroup*) (this=0x7fffffffc680, node=..., pGroup=0x55556f7a0b60) at ../../src/skin/legacy/legacyskinparser.cpp:708
#59 0x0000555555ece451 in LegacySkinParser::parseWidgetGroup(QDomElement const&) (this=0x7fffffffc680, node=...) at ../../src/skin/legacy/legacyskinparser.cpp:726
#60 0x0000555555ecc9c3 in LegacySkinParser::parseNode(QDomElement const&) (this=0x7fffffffc680, node=...) at ../../src/skin/legacy/legacyskinparser.cpp:486
#61 0x0000555555ed2024 in LegacySkinParser::parseSkin(QString const&, QWidget*) (this=this@entry=0x7fffffffc680, skinPath="/home/daniel/workspace/mixxx2/res/skins/Shade", pParent=pParent@entry=0x7fffffffde50) at ../../src/skin/legacy/legacyskinparser.cpp:409
#62 0x0000555555ec0305 in mixxx::skin::legacy::LegacySkin::loadSkin(QWidget*, QSharedPointer<ConfigObject<ConfigValue> >, QSet<ControlObject*>*, mixxx::CoreServices*) const (this=0x55555694a680, pParent=0x7fffffffde50, pConfig=..., pSkinCreatedControls=<optimized out>, pCoreServices=<optimized out>) at ../../src/skin/legacy/legacyskin.cpp:144
#63 0x0000555555b5fd33 in mixxx::skin::SkinLoader::loadConfiguredSkin(QWidget*, QSet<ControlObject*>*, mixxx::CoreServices*) (this=0x5555569d60c0, pParent=pParent@entry=0x7fffffffde50, pSkinCreatedControls=pSkinCreatedControls@entry=0x7fffffffdef8, pCoreServices=0x555556861b30) at /usr/include/c++/9/bits/atomic_base.h:318
#64 0x000055555584afb6 in MixxxMainWindow::loadConfiguredSkin() (this=0x7fffffffde50) at /usr/include/c++/9/bits/shared_ptr_base.h:1020
#65 0x000055555584d3fc in MixxxMainWindow::rebootMixxxView() (this=0x7fffffffde50) at ../../src/mixxxmainwindow.cpp:1084
#66 0x00007ffff3b86328 in QtPrivate::QSlotObjectBase::call(QObject*, void**) (a=0x7fffffffca40, r=0x7fffffffde50, this=0x55556eb6aed0) at ../../include/QtCore/../../src/corelib/kernel/qobjectdefs_impl.h:394
#67 QMetaObject::activate(QObject*, int, int, void**) (sender=0x5555601c3e90, signalOffset=<optimized out>, local_signal_index=<optimized out>, argv=<optimized out>) at kernel/qobject.cpp:3784
#68 0x00007ffff3b86328 in QtPrivate::QSlotObjectBase::call(QObject*, void**) (a=0x7fffffffcb30, r=0x5555601c3e90, this=0x55556a09b9b0) at ../../include/QtCore/../../src/corelib/kernel/qobjectdefs_impl.h:394
#69 QMetaObject::activate(QObject*, int, int, void**) (sender=0x55556a083bb0, signalOffset=<optimized out>, local_signal_index=<optimized out>, argv=<optimized out>) at kernel/qobject.cpp:3784
#70 0x0000555555b4a1c4 in DlgPrefWaveform::reloadUserInterface() (this=0x55556a083bb0) at mixxx-lib_autogen/include/moc_dlgprefwaveform.cpp:229
#71 DlgPrefWaveform::slotSetWaveformOverviewType(int) (this=0x55556a083bb0, index=<optimized out>) at ../../src/preferences/dialog/dlgprefwaveform.cpp:257
#72 0x00007ffff3b86328 in QtPrivate::QSlotObjectBase::call(QObject*, void**) (a=0x7fffffffccf0, r=0x55556a083bb0, this=0x55556a0a6de0) at ../../include/QtCore/../../src/corelib/kernel/qobjectdefs_impl.h:394
#73 QMetaObject::activate(QObject*, int, int, void**) (sender=0x55556a092d00, signalOffset=<optimized out>, local_signal_index=<optimized out>, argv=<optimized out>) at kernel/qobject.cpp:3784
#74 0x00007ffff6d22245 in QComboBox::currentIndexChanged(int) (this=this@entry=0x55556a092d00, _t1=<optimized out>) at .moc/moc_qcombobox.cpp:509
#75 0x00007ffff6d24646 in QComboBoxPrivate::_q_emitCurrentIndexChanged(QModelIndex const&) (this=this@entry=0x55556a093100, index=...) at ../../include/QtCore/../../src/corelib/itemmodels/qabstractitemmodel.h:62
#76 0x00007ffff6d26e6d in QComboBoxPrivate::setCurrentIndex(QModelIndex const&) (this=this@entry=0x55556a093100, mi=...) at widgets/qcombobox.cpp:2188
#77 0x00007ffff6d26f8d in QComboBoxPrivate::_q_itemSelected(QModelIndex const&) (this=0x55556a093100, item=...) at widgets/qcombobox.cpp:1341
#78 0x00007ffff6d2caf5 in QComboBox::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) (_o=<optimized out>, _c=<optimized out>, _id=<optimized out>, _a=0x7fffffffcfb0) at widgets/qcombobox.h:252
#79 0x00007ffff3b861d0 in QMetaObject::activate(QObject*, int, int, void**) (sender=0x555572c28d70, signalOffset=<optimized out>, local_signal_index=<optimized out>, argv=<optimized out>) at kernel/qobject.cpp:3804
#80 0x00007ffff6d223b6 in QComboBoxPrivateContainer::itemSelected(QModelIndex const&) (this=this@entry=0x555572c28d70, _t1=...) at .moc/moc_qcombobox_p.cpp:347
#81 0x00007ffff6d22aca in QComboBoxPrivateContainer::eventFilter(QObject*, QEvent*) (this=0x555572c28d70, o=0x55556f111e40, e=0x7fffffffd520) at widgets/qcombobox.cpp:758
#82 0x00007ffff3b5a51b in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) (event=<optimized out>, receiver=<optimized out>) at kernel/qcoreapplication.cpp:1214
#83 QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) (receiver=receiver@entry=0x55556f111e40, event=event@entry=0x7fffffffd520) at kernel/qcoreapplication.cpp:1203
#84 0x00007ffff6c1ba55 in QApplicationPrivate::notify_helper(QObject*, QEvent*) (this=this@entry=0x5555566d7110, receiver=receiver@entry=0x55556f111e40, e=e@entry=0x7fffffffd520) at kernel/qapplication.cpp:3694
#85 0x00007ffff6c25343 in QApplication::notify(QObject*, QEvent*) (this=<optimized out>, receiver=0x55556f111e40, e=0x7fffffffd520) at kernel/qapplication.cpp:3160
#86 0x00007ffff3b5a80a in QCoreApplication::notifyInternal2(QObject*, QEvent*) (receiver=0x55556f111e40, event=0x7fffffffd520) at ../../include/QtCore/../../src/corelib/kernel/qobject.h:142
#87 0x00007ffff6c24457 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) (receiver=0x55556f111e40, event=event@entry=0x7fffffffd520, alienWidget=0x55556f111e40, nativeWidget=0x555572c28d70, buttonDown=buttonDown@entry=0x7ffff714b8d0 <qt_button_down>, lastMouseReceiver=..., spontaneous=true, onlyDispatchEnterLeave=false) at kernel/qapplication.cpp:2646
#88 0x00007ffff6c7ace4 in QWidgetWindow::handleMouseEvent(QMouseEvent*) (this=0x555572ccf050, event=0x7fffffffd9a0) at /usr/include/c++/9/bits/atomic_base.h:413
#89 0x00007ffff6c7d1ec in QWidgetWindow::event(QEvent*) (event=0x7fffffffd9a0, this=0x555572ccf050) at kernel/qwidgetwindow.cpp:289
#90 QWidgetWindow::event(QEvent*) (this=0x555572ccf050, event=0x7fffffffd9a0) at kernel/qwidgetwindow.cpp:232
#91 0x00007ffff6c1ba66 in QApplicationPrivate::notify_helper(QObject*, QEvent*) (this=this@entry=0x5555566d7110, receiver=receiver@entry=0x555572ccf050, e=e@entry=0x7fffffffd9a0) at kernel/qapplication.cpp:3700
#92 0x00007ffff6c250f0 in QApplication::notify(QObject*, QEvent*) (this=0x7fffffffde10, receiver=0x555572ccf050, e=0x7fffffffd9a0) at kernel/qapplication.cpp:3446
#93 0x00007ffff3b5a80a in QCoreApplication::notifyInternal2(QObject*, QEvent*) (receiver=0x555572ccf050, event=0x7fffffffd9a0) at ../../include/QtCore/../../src/corelib/kernel/qobject.h:142
#94 0x00007ffff65a17d3 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) (e=e@entry=0x55556f5c7960) at kernel/qguiapplication.cpp:2107
#95 0x00007ffff65a310b in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) (e=e@entry=0x55556f5c7960) at kernel/qguiapplication.cpp:1842
#96 0x00007ffff657d35b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) (flags=flags@entry=...) at kernel/qwindowsysteminterface.cpp:1151
#97 0x00007fffeaf4d32e in xcbSourceDispatch(GSource*, GSourceFunc, gpointer) (source=<optimized out>) at qxcbeventdispatcher.cpp:105
#98 0x00007ffff26d917d in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#99 0x00007ffff26d9400 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#100 0x00007ffff26d94a3 in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#101 0x00007ffff3bb2435 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (this=0x55555676a170, flags=...) at kernel/qeventdispatcher_glib.cpp:422
#102 0x00007ffff3b593ab in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) (this=this@entry=0x7fffffffdd40, flags=..., flags@entry=...) at ../../include/QtCore/../../src/corelib/global/qflags.h:140
#103 0x00007ffff3b61116 in QCoreApplication::exec() () at ../../include/QtCore/../../src/corelib/global/qflags.h:120
#104 0x0000555555749635 in (anonymous namespace)::runMixxx (args=..., pApp=0x7fffffffde10) at ../../src/main.cpp:82
#105 main(int, char**) (argc=<optimized out>, argv=<optimized out>) at ../../src/main.cpp:213
(gdb) Quit
(gdb) 
```
</details>

**Comment by daschuer** [comment]
> There is only an issue with the "Filtered - Qt (GL)" type. It is running slooooow with 3.5 f/s instead of the desired 60 f/s The "Simple - Qt (GL)" and "RGB - Qt (GL)" are running smooth @ 60 f/s with some dropped frames.

This issue is still pending with with QOPENGL=ON

> Even though I have doubled the same track in two decks, I see an offset between both waveforms of 20 ms (one audio Buffer Size) after the waveform type. This goes away after changing to another type and back to the original. The audio is not affected.

This can no longer be reproduced

**Comment by m0dB** [comment]
> > There is only an issue with the "Filtered - Qt (GL)" type. It is running slooooow with 3.5 f/s instead of the desired 60 f/s The "Simple - Qt (GL)" and "RGB - Qt (GL)" are running smooth @ 60 f/s with some dropped frames.
> 
> This issue is still pending with with QOPENGL=ON

As mentioned, this is because QPainter on the QOpenGLWindow is very slow, so this is inherent to the use of QOpenGLWindow. But I propose to remove all waveform types except for the ones that use the shaders, or at least hide them behind a command line option.

**Comment by m0dB** [comment]
@daschuer @ronso0 can you please try again with my latest changes to see if the spinnies look better now? I wasn't setting linear filtering on the textures used.

**Comment by m0dB** [comment]
> With QOPENGL=ON I am still able to crash Mixxx with

Thanks for the backtrace @daschuer . I see I am indirectly calling a (pure) virtual from the constructor. Surprising that doesn't crash on macOS. I will fix this tomorrow, shouldn't be too much of a problem now that I see the cause.

**Comment by uklotzde** [comment]
> > With QOPENGL=ON I am still able to crash Mixxx with
> 
> Thanks for the backtrace @daschuer . I see I am indirectly calling a (pure) virtual from the constructor. Surprising that doesn't crash on macOS. I will fix this tomorrow, shouldn't be too much of a problem now that I see the cause.

I wonder why this is not detected by any compiler using static code analysis :thinking:

**Comment by m0dB** [comment]
> > With QOPENGL=ON I am still able to crash Mixxx with
> 
> Thanks for the backtrace @daschuer . I see I am indirectly calling a (pure) virtual from the constructor. Surprising that doesn't crash on macOS. I will fix this tomorrow, shouldn't be too much of a problem now that I see the cause.

Please try again.

**Comment by ronso0** [comment]
> @daschuer @ronso0 can you please try again with my latest changes to see if the spinnies look better now? I wasn't setting linear filtering on the textures used.

Indeed, it's looking much better now. Thanks!

However, the ghost indicator is still jerky. Looks like it's making steps of ~3° or something.
Anyway, that as well as it being shown briefly at 12 o'clock also happens in 2.4, so it's probably a task for later polish / improvement, not a blocker.

**Comment by daschuer** [comment]
The jerky ghost indicator is a general issue, not related to this PR. It also happens in 2.3.5. 

grafik
grafik

The sticker anti-aliasing issue is only improved, not fixed. Not sure if this is OK, or if we want to fully fix it.

**Comment by daschuer** [comment]
Here the comparison at 800% 
grafik

**Comment by JoergAtGithub** [comment]
I just tested the latest commit on Windows11, it still works very well. But I noticed the lower frame rate of the ghost indicator in slip mode on Windows too.

**Comment by m0dB** [comment]
For clarity, the spinny position indicator and ghost indicator are drawn in the same frame (in the same function call), so it's not really the frame rate, but, as also suggested by the fact that this also occurs in 2.3.5, by the rate at which the value is updated. If we have a bug for this, I could investigate this at some point.

The difference in rendering (anti-aliasing) of rotated images between Qt and OpenGL is not surprising. I can see if I can do something to improve it a bit. But I don't think it is a reason to hold off the merge.

Which brings me to the point: is there anything else that needs to be done before this can be merged?

**Comment by m0dB** [comment]
There were two problems: 1) When the images were scaled to the widget size, the device pixel ratio was not taken into account (except for the cover art, which did do this correctly) (a bug in the original code). 2) I didn't recreate the textures after the images were scaled to the widget size (a bug in my code).

Both have been fixed and indeed it looks much better now.

(On a side note, when debugging this I noticed that the size of the spinny is 64x63. This seems a bit weird, and I assume that the intention was 64x64. Could that be the case, @ronso0 ?)

**Comment by m0dB** [comment]
https://github.com/mixxxdj/mixxx/pull/10989/commits/45c5f8a21d0fbecaae551953f592e7c331000388 fixes the jerky slip position. This was an easy fix, simply applying the same algorithm that is used to calculate the estimated visual play position at the next vsync to the slip position. @daschuer you might want to apply this fix on the 2.3 branch as well.

**Comment by ronso0** [comment]
> (On a side note, when debugging this I noticed that the size of the spinny is 64x63. This seems a bit weird, and I assume that the intention was 64x64. Could that be the case, @ronso0 ?)

For LateNight PaleMoon the spinny/cover container size is square [n * n] + some margin, see for examples https://github.com/mixxxdj/mixxx/blob/2.4/res/skins/LateNight/style_palemoon.qss#L517-L550
Are you sure you're seeing the spinny size and not that of the parent WidgetGroup?

**Comment by m0dB** [comment]
> Are you sure you're seeing the spinny size and not that of the parent WidgetGroup?

Yes, I'm sure. I am logging the size of the wspinny widget itself.

**Comment by daschuer** [comment]
> @daschuer you might want to apply this fix on the 2.3 branch as well.

Thank you for the fix of the ghost frame rate here. I don't consider this fix an important bugfix that rectifies the hassle to backport and probably resolving conflicts.

**Comment by Swiftb0y** [comment]
> Thank you for the fix of the ghost frame rate here. I don't consider this fix an important bugfix that rectifies the hassle to backport and probably resolving conflicts.

Disagree, the bug in question is purely visual and occurring only under specific circumstances (spinny active and using slip mode). Please focus on getting 2.4 out on time instead.

**Comment by ronso0** [comment]
> > Thank you for the fix of the ghost frame rate here. I don't consider this fix an important bugfix that rectifies the hassle to backport and probably resolving conflicts.
> 
> Disagree, the bug in question is purely visual and occurring only under specific circumstances (spinny active and using slip mode). Please focus on getting 2.4 out on time instead.

So you **agree** with @daschuer : )

**Comment by Swiftb0y** [comment]
Ohh, I missed the "don't" in that sentence :sweat_smile:

**Comment by m0dB** [comment]
If I remove this
```
 19         <Connection>
 20           <ConfigKey>[Skin],show_small_spinny_or_cover</ConfigKey>
 21           <BindProperty>visible</BindProperty>
 22         </Connection>
```
from the
```
 10       <WidgetGroup>
 11         <ObjectName>SpinnyCoverContainer_Small</ObjectName>
```
the issue with the WSpinny getting sized incorrectly is solved! Any idea @ronso0 ?

**Comment by m0dB** [comment]
Fixed the issue with the wrongly sized spinnies. The problem was that LateNight's SpinnyCoverContainer_Small has a binding on it's visible property. When visible gets called too soon, the style of the WWidgetGroup is not calculated correctly . By calling setupConnections a bit later the issue doesn't occur anymore.

Note that there is a comment in commonWidgetSetup which seems to be about the same or similar issue. I wonder what that means though for the widgets that are created passing false as third argument to commonWidgetSetup. I don't see how the connections are ever set up for those.

**Comment by m0dB** [comment]
> > @daschuer you might want to apply this fix on the 2.3 branch as well.
> 
> Thank you for the fix of the ghost frame rate here. I don't consider this fix an important bugfix that rectifies the hassle to backport and probably resolving conflicts.

Are you suggesting I revert this fix or only that you don't think it's worth applying to 2.3?

**Comment by m0dB** [comment]
@daschuer I believe I have addressed all conversations, but I am difficulties with the github interface which tells me there is still a change requested, so please let me know if there is anything pending. (This is a lesson learned, I will not do macro PRs like this one anymore, the conversations become unmanageable. I hope you can merge this soon and from there on I can do small PRs)

**Comment by ronso0** [comment]
> > > @daschuer you might want to apply this fix on the 2.3 branch as well.
> > 
> > 
> > Thank you for the fix of the ghost frame rate here. I don't consider this fix an important bugfix that rectifies the hassle to backport and probably resolving conflicts.
> 
> Are you suggesting I revert this fix or only that you don't think it's worth applying to 2.3?

This fix is appreciated, and since it's been agreed this PR will be part of initial 2.4-beta it doesn't make sense to separate it.

**Comment by ronso0** [comment]
> Fixed the issue with the wrongly sized spinnies. The problem was that LateNight's SpinnyCoverContainer_Small has a binding on it's visible property. When visible gets called too soon, the style of the WWidgetGroup is not calculated correctly . By calling setupConnections a bit later the issue doesn't occur anymore. ...

So you managed to fix an annoying, almost 10y old bug en passant? :grin: #7328 & #8539
Looking forward to test it. If the fix works this makes WidgetGroup nesting obsolete in quite a few places, mostly in LateNight.

**Comment by m0dB** [comment]
> > Fixed the issue with the wrongly sized spinnies. The problem was that LateNight's SpinnyCoverContainer_Small has a binding on it's visible property. When visible gets called too soon, the style of the WWidgetGroup is not calculated correctly . By calling setupConnections a bit later the issue doesn't occur anymore. ...
> 
> So you managed to fix an annoying, almost 10y old bug en passant? 😁 #7328 & #8539 Looking forward to test it. If the fix works this makes WidgetGroup nesting obsolete in quite a few places, mostly in LateNight.

Haha, nice! Yes, definitely looks like the same thing! It would be great if the amount of WidgetGroups can be reduced, when I was debugging I was surprised by the amount of WidgetGroups getting instantiated!

Btw, the fix I submitted was the most straightforward one, but I also tried another approach that also worked, so if you find there are still problems, it's something to try.

**Comment by daschuer** [comment]
I can confirm the ghost spinny is smooth now. There is only an issue that when slip-mode is enabled it is initial rendered at 12:00 and than jumps to the correct position. Dos the rendering start before the position has been calculated?

**Comment by ronso0** [comment]
> > > Fixed the issue with the wrongly sized spinnies. The problem was that LateNight's SpinnyCoverContainer_Small has a binding on it's visible property. When visible gets called too soon, the style of the WWidgetGroup is not calculated correctly . By calling setupConnections a bit later the issue doesn't occur anymore. ...
> > 
> > 
> > So you managed to fix an annoying, almost 10y old bug en passant? grin #7328 & #8539 Looking forward to test it. If the fix works this makes WidgetGroup nesting obsolete in quite a few places, mostly in LateNight.
> 
> Haha, nice! Yes, definitely looks like the same thing! It would be great if the amount of WidgetGroups can be reduced, when I was debugging I was surprised by the amount of WidgetGroups getting instantiated!

I tested that fix with a cleaned up LateNight mixer and it works beautifully! Thanks!

**Comment by daschuer** [comment]
For book keeping, I can confirm these fixes: 

> I see an offset between both waveforms of 20 ms

This is not reproducible anymore.

> "Filtered - Qt (GL)" 

Fixed via removal 

> warning [Main] QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined

Fixed

> shutown crash 

Fixed

> crash when chaning skin

Fixed

**Comment by daschuer** [comment]
With QOPENGL=OFF and 200 % HID Scaling set in preferences, the spinnies show only the cover/background and no sticker. 
With 125 % the sticker is available, but not centered: 
grafik
This does not happen with QOPENGL=ON

**Comment by daschuer** [comment]
With QOPENGL=ON, the frame rate of any widget drops to 1 Hz, and soon as one of the GL widges are completely hidden behind the Display borders (is outside the Desktop area). If the widget is hidden behind other windows the problem does not appear. This does not happen with QOPENGL=OFF

**Review by daschuer — CHANGES_REQUESTED** [review]
My pending issues have been fixed. Unfortunately I have discovered more.

**Comment by Swiftb0y** [comment]
As long as the issues aren't "party stopper"s, I'd prefer if we merge this PR without fixes for them and then track these issues separately as part of the polishing during the beta.

**Comment by Swiftb0y** [comment]
The discussion around this PR already contains a potentially record breaking 560 comments, not counting the ones on zulip...

**Comment by daschuer** [comment]
We cannot merge this if QOPENGL=OFF introduces regressions. Because the QOPENGL==OFF mode was one main argument to merge this to 2.4 and not to main. But there is no point of a discussion if this is just an easy fix as I assume.

**Comment by m0dB** [comment]
> With QOPENGL=OFF and 200 % HID Scaling set in preferences, the spinnies show only the cover/background and no sticker.
> With 125 % the sticker is available, but not centered:

I would like to debug this, but the HID scaling doesn't have any effect here. Maybe this doesn't work on macOS? Is it expected to?

In any case, I also don't expect this to be difficult to fix.  If you confirm that with 2.4 it works correctly, I can try fixing it by comparing the code.

**Comment by m0dB** [comment]
@daschuer can you try if the QOPENGL=OFF spinnies draw correctly now when scaled?

Btw, (also with 2.4) setting the scale factor from the Settings dialogs does not have any effect on macOS, but setting the environment variable does QT_SCALE_FACTOR does work.

**Comment by m0dB** [comment]
> I tested that fix with a cleaned up LateNight mixer and it works beautifully! Thanks!

Thanks for testing and confirming @ronso0 ! Are you planning to create a PR with these clean ups?

**Comment by ronso0** [comment]
> 

Yes, I have stashed the test changes and I'll issue a PR with a more complete cleanup during beta.

**Comment by m0dB** [comment]
Urgh, since I rebased on latest 2.4 the framerate has dropped significantly :-(  (From 60 fps with an occasional drop to 45). Are you seeing the same?

@daschuer I noticed the build environment has changed. Could this be related?

**Comment by JoergAtGithub** [comment]
> @daschuer I noticed the build environment has changed. Could this be related?

The buildenv is only changed, if you call `macos_buildenv.sh` after rebase.

This allows you to test your rebased PR with the old different buildenv.

**Comment by daschuer** [comment]
Rebase is evil, especially in a PR under review. Read: https://github.com/mixxxdj/mixxx/blob/7f79194df0a53987816b4e47e34067e3eb12361d/CONTRIBUTING.md?plain=1#L63

I assume you still have the original HEAD commit in `git revlog`. So there is an option to reset to it and merge instead. Does that make sense in this case, or does it put to much extra work on you?  

Does the frame rate drop happen with the build downloaded from GitHub? This will use the most recent build environment. 
Locally you can still use the old environment as @JoergAtGithub pointed out. 

I have just tested this PR in the current state and it segfaults after quitting Mixxx in the "no sound device" selection dialog. 
(With OPENGL=ON).

**Comment by daschuer** [comment]
> I would like to debug this, but the HID scaling doesn't have any effect here. Maybe this doesn't work on macOS? Is it expected to?

No, it is expected to work on macOS as well. Do we need an issue to track that?

**Comment by daschuer** [comment]
With this PR and OPENGL=ON, there is a visual issue with the CPU load and the preview deck VU-meter display in Shade: 
grafik
grafik

**Comment by daschuer** [comment]
There is another segfault on shutdown with OPENGL=ON. 
Interestingly I was on ALSA not on JACK. 

```
mixxx: src/hostapi/jack/pa_jack.c:820: Terminate: Zusicherung »err == 0« nicht erfüllt.
[Thread 0x7fffd6048700 (LWP 18586) exited]

Thread 1 "mixxx" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffeb6a4140 (LWP 18553)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: Datei oder Verzeichnis nicht gefunden.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff32f2859 in __GI_abort () at abort.c:79
#2  0x00007ffff32f2729 in __assert_fail_base
    (fmt=0x7fffe9695422 "%s%s%s:%u: %s%sZusicherung »%s« nicht erfüllt.\n%n", assertion=0x7ffff7b3be2e "err == 0", file=0x7ffff7b3bdf0 "src/hostapi/jack/pa_jack.c", line=820, function=<optimized out>) at assert.c:92
#3  0x00007ffff3303fd6 in __GI___assert_fail
    (assertion=assertion@entry=0x7ffff7b3be2e "err == 0", file=file@entry=0x7ffff7b3bdf0 "src/hostapi/jack/pa_jack.c", line=line@entry=820, function=function@entry=0x7ffff7b3d8e0 <__PRETTY_FUNCTION__.7756> "Terminate") at assert.c:101
#4  0x00007ffff7b2cb0d in Terminate (hostApi=0x5555595a88d0)
    at src/hostapi/jack/pa_jack.c:820
#5  0x00007ffff7b1deec in TerminateHostApis () at src/common/pa_front.c:186
#6  0x00007ffff7b1ef42 in Pa_Terminate () at src/common/pa_front.c:398
#7  0x00005555557d3eb1 in SoundManager::clearDeviceList(bool)
    (sleepAfterClosing=false, this=0x55555df0c450)
    at ../../src/soundio/soundmanager.cpp:213
#8  SoundManager::~SoundManager()
    (this=0x55555df0c450, __in_chrg=<optimized out>)
    at ../../src/soundio/soundmanager.cpp:90
#9  0x000055555576f2a8 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() (this=0x55555df0c440)
    at /usr/include/c++/9/bits/shared_ptr_base.h:148
--Type <RET> for more, q to quit, c to continue without paging--
#10 std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release()
    (this=0x55555df0c440) at /usr/include/c++/9/bits/shared_ptr_base.h:148
#11 0x00005555557a3ba9 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count() (this=<optimized out>, __in_chrg=<optimized out>)
    at /usr/include/c++/9/bits/shared_ptr_base.h:1169
#12 std::__shared_ptr<SoundManager, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr() (this=<optimized out>, __in_chrg=<optimized out>)
    at /usr/include/c++/9/bits/shared_ptr_base.h:1169
#13 std::__shared_ptr<SoundManager, (__gnu_cxx::_Lock_policy)2>::reset()
    (this=0x55555685b888) at /usr/include/c++/9/bits/shared_ptr_base.h:1287
#14 (anonymous namespace)::clearHelper<SoundManager>
    (name=0x5555562935a6 "m_pSoundManager", ref_ptr=std::shared_ptr<class SoundManager> (empty) = {...}) at ../../src/coreservices.cpp:69
#15 mixxx::CoreServices::finalize() (this=0x55555685b830)
    at ../../src/coreservices.cpp:575
#16 0x00005555557a4a7e in mixxx::CoreServices::~CoreServices()
    (this=0x55555685b830, __in_chrg=<optimized out>)
    at ../../src/coreservices.cpp:130
#17 0x000055555576f2a8 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() (this=0x55555685b820)
    at /usr/include/c++/9/bits/shared_ptr_base.h:148
#18 std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release()
    (this=0x55555685b820) at /usr/include/c++/9/bits/shared_ptr_base.h:148
--Type <RET> for more, q to quit, c to continue without paging--
#19 0x0000555555746328 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count() (this=<synthetischer Zeiger>, __in_chrg=<optimized out>)
    at /usr/include/c++/9/bits/shared_ptr_base.h:1169
#20 std::__shared_ptr<mixxx::CoreServices, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr() (this=<synthetischer Zeiger>, __in_chrg=<optimized out>)
    at /usr/include/c++/9/bits/shared_ptr_base.h:1169
#21 std::shared_ptr<mixxx::CoreServices>::~shared_ptr()
    (this=<synthetischer Zeiger>, __in_chrg=<optimized out>)
    at /usr/include/c++/9/bits/shared_ptr.h:103
#22 (anonymous namespace)::runMixxx (args=..., pApp=0x7fffffffde30)
    at ../../src/main.cpp:40
#23 main(int, char**) (argc=<optimized out>, argv=<optimized out>)
    at ../../src/main.cpp:213
```

**Comment by daschuer** [comment]
using --disable-vumetergl fixes the visual issue in Shade.

**Comment by daschuer** [comment]
Strange. I cannot reproduce the segfaults with OPENGL=OFF.

The Spinny scaling issue is fixed.

**Comment by daschuer** [comment]
After going back to OPENGL=OFF I can only reproduce the "no sound device" crash. 

All waveforms are at 60 FPS

**Comment by daschuer** [comment]
The commit before the rebase is 8e0b4b4935. It this not affected from the dropped famerate?

**Comment by daschuer** [comment]
Summary: 
* The both recently found crashers are unrelated. One is a Debian/Portaudio upstream issue, which has been reported. The other one is fixed here: https://github.com/mixxxdj/mixxx/pull/11593
* The pending scaling issue is minor and can be fixed after merging. I have work in progress. 
* The CPU-Meter issue is likely similar to the one we have fixed in Tango. I will take care. 
* We have here a big remaining blocker, the reported drop if frame rate to 45 FPS. 

Fortunately I cannot confirm it with Ubuntu Focal, but let's find out the point where the regression happens. 

This means when need help form Mac users. 
@m0dB did you found out more details about the regression? 
@fwcd how does it work for you? Do you have access to Intel and ARM devices? 
@foss- how is the situation on your device? 
@JoergAtGithub Do you see a difference on windows? 

The builds with the regressions are here: 
https://github.com/mixxxdj/mixxx/actions/runs/5032182114?pr=10989

A reference build before the rebase might be this: 
https://github.com/mixxxdj/mixxx/actions/runs/4983529506

This is the last run without the build environment of M1
https://github.com/mixxxdj/mixxx/actions/runs/4901310770

Please compare. 

All builds can be found here:
https://github.com/mixxxdj/mixxx/actions/workflows/build.yml?query=branch%3Aqopengl_renderers

**Comment by m0dB** [comment]
Thanks for this write up @daschuer . I didn't have the time to look into this, but I will try rebasing on some earlier 2.4 commits to see if that makes a difference, hopefully this weekend.

**Comment by daschuer** [comment]
Thank you. Do you always update the build environment after rebase/merge? 
To just sort out the build environment, it would nice if you could compile your latest HEAD with the build environment of the last known good build. Than we know if we have to fix something in the vcpkg repro or in this branch.

**Comment by m0dB** [comment]
> Thank you. Do you always update the build environment after rebase/merge?

Yes.

> To just sort out the build environment, it would nice if you could compile your latest HEAD with the build environment of the last known good build.

Yes, I will try that. Unfortunately, I am not sure which build env that was (I should have done some book keeping...)

> Than we know if we have to fix something in the vcpkg repro or in this branch.

Unless it's something else that changed in 2.4.

**Comment by m0dB** [comment]
I just did a rebase on latest 2.4 and a clean release build and everything is working as expected.

**Comment by JoergAtGithub** [comment]
I did a short test of a local build of the latest commit 63a626d on Windows11: Everything I tested works at least as good as with the 2.4 branch.

**Comment by daschuer** [comment]
Does the FPS counter in the waveform preferences show 60 FPS +-1 ?

**Comment by JoergAtGithub** [comment]
On Windows11 yes. It always worked - but note, that my Windows11 laptop has a very fast GPU.

**Comment by m0dB** [comment]
Yes, on macOS as well. It does drop when scrolling the library, but that is expected.

**Comment by daschuer** [comment]
Cool, so you can confirm that the original experienced regression after rebase is gone? 
Do you have an idea what causes the regression? Is the vcpkg environment involved?

**Comment by foss-** [comment]
This is becoming hard to navigate. Auto-collapsed comments require to `Load more…` 7 times or so until seeing the comment with test builds. So here is the directlink: https://github.com/mixxxdj/mixxx/pull/10989#issuecomment-1563943925

macOS 13.4
MacBookPro14,3 Intel

OpenGL status: 2.1 ATI-4.12.7 (AMD Radeon Pro 560 OpenGL Engine)

Builds with the regressions: 2.4-alpha-1508-gb763121761 (HEAD)
Average fram rate: ~60, briefly went down to 47 but then also went back up to 60.

Reference build before the rebase: 2.4-alpha-1505-g92e37a549f (HEAD)
Average fram rate: ~60

Last run without the build environment of M1: 2.4-alpha-1492-gbd19cf8833 (HEAD)
Average fram rate: ~60

Tested by setting frame rate to 60 fps and playing a track. Unsure what to expect. Waveform type RGB (GLSL). 🤔

**Comment by JoergAtGithub** [comment]
> macOS 13.4 MacBookPro14,3 Intel
> 
> OpenGL status: 2.1 ATI-4.12.7 (AMD Radeon Pro 560 OpenGL Engine)
> 
> Builds with the regressions: 2.4-alpha-1508-gb763121761 (HEAD) Average fram rate: ~60, briefly **went down to 47 but then also went back up** to 60.

Is this a reproduceable regression, or just a one time hick-up?

**Comment by m0dB** [comment]
> Cool, so you can confirm that the original experienced regression after rebase is gone?
> Do you have an idea what causes the regression? Is the vcpkg environment involved?

Yes, I confirm I don't have any regression with a clean local build after rebase, and neither with the github build made at the time that I experienced the regression, so I am assuming I messed something up with my build or there was something temporarily wrong with my system. So, false alarm, and sorry for that.

**Comment by foss-** [comment]
> Could you also try with the "(allshaders)" waveform types? These are the most optimised.

RGB (all-shaders) (GLSL) looking good. Drops happen when scrolling (expected and has always been the case with Mixxx on macOS. There seem to be a few issues with Qt and scrolling on macOS. This P1 Critical bug filed 2019 finally got resolved summer 2022: https://bugreports.qt.io/browse/QTBUG-73117

Very excited to see this PR land 🚀

**Comment by m0dB** [comment]
IIRC (I think @ronso0 explained this to me) it's also the querying of the sqlite database that is done in the same thread and thus can interfere with the waveform redraws.

I have a branch where I draw the waveforms from the vsync thread directly, which would solve this problem. Once this PR has been merged to 2.4 I might create an additional PR that adds a vsync render mode "render in vsync thread".

**Comment by daschuer** [comment]
The VU-Meter failure in Shade is caused by the 1 pixel height. If I use two pixel height, it works. 
A hack that limits the minimum height to two pixels works as well, but than the background is black. 
There is another issue with the VU-Meters, that they have a black border when Mixxx is scaled to 200 % 
I will file separate issues for that so we can merge this.

**Review by daschuer — APPROVED** [review]

**Review by daschuer — APPROVED** [review]
OK, so we assume that the frame rate drop is natural is some conditions ad the original report about the regression after rebase was a false positive. 

The current state of this PR is a rebase of the current 2.4. For now I ignore the issue that this may have produce not build-able commits. I have also not reviewed all the code again that can be required after such a rebase. 
Please do not rebase a PR under review in future to avoide this situation.

Thank you for all the work and patients you have put into this branch. I think it is a mayor mile stone in the history of Mixxx.

**Comment by Swiftb0y** [comment]
A huge personal thank you to @m0dB for spending this amount of time and patience on this PR. Thank you to the rest of the team that we managed to get a change this gigantic merged in a reasonable time. Good job everyone. 2.4 Full force :tada:

**Comment by uklotzde** [comment]
Kudos to @m0dB for your efforts, your perseverance, and your patience to finish this task and PR!

**Comment by m0dB** [comment]
> @m0dB you mentioned that you had PR that would allow us to use the current skin system with Qt6, right? Can you open a PR against `main` for that?

Yes, but that is on top of this PR, so I can only create the Qt6 PR once this PR has been merged from 2.4 to main. But 2.4 to main merges are done regularly, right? Otherwise, I can create a PR for 2.4 in the meantime and rebase it later on.

> Would this allow us to migrate to Qt6 fully?

It compiles (with some "deprecated" warnings, easy to fix) and runs smoothly, as far as I see, at least on macOS and only done some smoke testing.

The few issues I have seen with Qt6:

- the splitter below the waveforms doesn't work. I have done some debugging and found that the size policy of the child widgets changes somewhere between when the skin is read in the legacy skin parser and when I try to move the splitter. If I force the size policy back to it's original value it works. 
- the Latenight knobs look slightly different (more pronounced outline), but nothing major.
- I get a lot of the following warning: warning [Main] skipping QEventPoint(id=1 ts=0 pos=0,0 scn=599.994,259.461 gbl=599.994,259.461 Released ellipse=(1x1 ∡ 0) vel=0,0 press=-599.994,-259.461 last=-599.994,-259.461 Δ 599.994,259.461) : no target window

Also I would be good to have a proper Qt6 buildenv. I am now using the existing buildenv and I pass the path to the official Qt6 binary install with CMAKE_PREFIX_PATH, but I suppose that the way to go is to have Qt6 from vcpkg. I started looking into that but vcpkg is too much of a learning curve right now, so it would be great if someone with vcpkg experience (@daschuer I guess) could take care of that. Or maybe this has been done already?

We can decide to address all this before or after merging the PR. The PR will not change anything at all if you compile with Qt5 or with Qt6 with QML.

**Comment by JoergAtGithub** [comment]
grafik

**Comment by m0dB** [comment]
https://github.com/mixxxdj/mixxx/pull/11608

**Comment by Be-ing** [comment]
@m0dB I spent many months juggling weird hacks with build environments and spinning in circles looking for optimizations to keep Mixxx barely functional on macOS. Thank you for finally doing the work to fix the root problem.

**Comment by Be-ing** [comment]
https://github.com/mixxxdj/mixxx/pull/10989#issuecomment-1509884824

> Personally I would do a huge cleanup by:
>    Removing all legacy waveform widgets. There are some that I haven't ported to pure qopengl, but I can do that quickly (e.g. the simple waveform and glsl ones that read the waveform data from a texture).
>    Removing all QGL... code
>    Remove the non-GL implementations of wspinny and wvumeter.

I recommend to work on further refactoring on the main branch and leave the 2.4 beta branch with the `QOPENGL=OFF` CMake option as an emergency fallback.
