### PR TITLE
Fix key color rect when track tuning is unavailable

### LINKED ISSUE #15883: Mixxx crashes on startup: "Overflow in operator+"
### Bug Description

When starting up Mixxx it crashes with this error message:
```
fatal [Main] ASSERT failure in constexpr QtPrivate::QCheckedIntegers::QCheckedInt<int> QtPrivate::QCheckedIntegers::operator+(QCheckedInt<int>, QCheckedInt<int>): "Overflow in operator+", fi
le /usr/include/qt6/QtCore/qcheckedint_impl.h, line 69
```

I've removed the `build` directory and rebuilt Mixxx but that didn't help.

### Version

Latest git commit cb057e3a
```
QML debugging is enabled. Only use this in a safe environment.
Using preferences ScaleFactor 0.88
Default style is overwritten by command line argument -style "kvantum-dark"
Selected Qt style: "kvantum-dark"

Mixxx 2.7.0-alpha
```
### OS

Linux Gentoo ~amd64

### PR DESCRIPTION
**Pull request by danferns**
When tuning is unavailable, the cents value would be -inf, causing improper rendering of the key color rect ( https://github.com/mixxxdj/mixxx/pull/15865#issuecomment-3773412820 ).

Fixed by checking if tuning == 0, and then only using the track's own key color. 

---

This will also close #15883

### CODE REVIEW

File: src/library/basetracktablemodel.cpp [hunk 1]
```diff
@@ -940,23 +940,30 @@ QVariant BaseTrackTableModel::roleValue(
             const float tuningHz = (float)rawSiblingValue(
                     index, ColumnCache::COLUMN_LIBRARYTABLE_TUNING_FREQUENCY)
                                            .value<double>();
```
Comment (daschuer) [inline src/library/basetracktablemodel.cpp]: Unrelated by catch, we prefere C++ casts: 
```suggestion
            const float tuningHz =  static_cast<float>(rawSiblingValue(
                    index, ColumnCache::COLUMN_LIBRARYTABLE_TUNING_FREQUENCY)
                                           .value<double>());
```

File: src/library/basetracktablemodel.cpp [hunk 2]
```diff
@@ -940,23 +940,30 @@ QVariant BaseTrackTableModel::roleValue(
...
-            float cents = 0;
-            Pitch::getPitchForFrequency(tuningHz, &cents, 440.0f);
-            cents /= 100.0f; // normalize between -1 and 1
             QVariantMap colorRect;
-            if (cents < 0) {
+            if (tuningHz == 0) { // we do not have tuning information
```
Comment (daschuer) [inline src/library/basetracktablemodel.cpp]: since tuningHz is read form the database it can be any value. Maye should check for a reasonable value near 440 Hz. Not sure how strict we want to be maybe one octave around it 220 .. 880 which is already wide? 
What do you think?

File: src/library/basetracktablemodel.cpp [hunk 3]
```diff
@@ -940,23 +940,30 @@ QVariant BaseTrackTableModel::roleValue(
...
-                                s_keyColorPalette.value());
-                colorRect["bottom"] = KeyUtils::keyToColor(key, s_keyColorPalette.value());
-                colorRect["splitPoint"] = cents;
+                float cents = 0;
+                Pitch::getPitchForFrequency(tuningHz, &cents, 440.0f);
+                cents /= 100.0f; // normalize between -1 and 1
+                if (cents < 0) {
+                    colorRect["top"] = KeyUtils::keyToColor(key, s_keyColorPalette.value());
+                    colorRect["bottom"] =
+                            KeyUtils::keyToColor(KeyUtils::scaleKeySteps(key, -1),
```
Comment (daschuer) [inline src/library/basetracktablemodel.cpp]: To make it valid for wider tuning range, we need to consider also the full key offset returned by Pitch::getPitchForFrequency()

File: src/library/basetracktablemodel.cpp [hunk 4]
```diff
@@ -940,23 +940,30 @@ QVariant BaseTrackTableModel::roleValue(
...
-            cents /= 100.0f; // normalize between -1 and 1
             QVariantMap colorRect;
-            if (cents < 0) {
+            if (tuningHz == 0) { // we do not have tuning information
                 colorRect["top"] = KeyUtils::keyToColor(key, s_keyColorPalette.value());
-                colorRect["bottom"] =
-                        KeyUtils::keyToColor(KeyUtils::scaleKeySteps(key, -1),
-                                s_keyColorPalette.value());
-                colorRect["splitPoint"] = cents + 1;
+                colorRect["bottom"] = colorRect["top"];
```
Comment (daschuer) [inline src/library/basetracktablemodel.cpp]: Is this value used? Maybe we can save some CPU cycle by not writing it and no reading it in the delegate.

File: src/library/basetracktablemodel.cpp [hunk 5]
```diff
@@ -940,23 +940,30 @@ QVariant BaseTrackTableModel::roleValue(
...
+                colorRect["splitPoint"] = 1;
             } else {
-                colorRect["top"] =
-                        KeyUtils::keyToColor(KeyUtils::scaleKeySteps(key, 1),
-                                s_keyColorPalette.value());
-                colorRect["bottom"] = KeyUtils::keyToColor(key, s_keyColorPalette.value());
-                colorRect["splitPoint"] = cents;
+                float cents = 0;
+                Pitch::getPitchForFrequency(tuningHz, &cents, 440.0f);
+                cents /= 100.0f; // normalize between -1 and 1
```
Comment (daschuer) [inline src/library/basetracktablemodel.cpp]: There is a wired rounding in getPitchForFrequency() for some reasons. Maybe it can be removed? 
```suggestion
                cents /= 100.0f; // normalize for >= -0.5 and < 0.5
```

This is the code in question: 
```
    int midiPitch = int(p + 0.00001);
    float centsOffset = (p - midiPitch) * 100.0;

    if (centsOffset >= 50.0) {
        midiPitch = midiPitch + 1;
        centsOffset = -(100.0 - centsOffset);
    }
```

Can it become: 
```
    int midiPitch = static_cast<int>(p + 0.5);
    float centsOffset = (p - midiPitch) * 100.0;
```

0,49999 becomes 0 +49.999
0,5 becomes 1 -50

**Review by daschuer — CHANGES_REQUESTED** [review]
hank you fro drilling this bug down. I sorry have not found it during testing. 

Your changes are fixing the issues. I did a look left and right and found some ideas for improvements. Can you look at them. Thank you.

File: src/library/basetracktablemodel.cpp (hunk 2 above)
Comment (danferns) [reply src/library/basetracktablemodel.cpp]: Yeah an octave on both sides seems like a good idea. It is simple to understand and does not impose real restrictions on possible tuning values.

**Comment by danferns** [comment]
Thank you for the review! And don't worry about not having found the bug, we are human.

I've addressed all the review comments.

**Comment by ronso0** [comment]
Can confirm it looks kay now with now tuning info :+1:

**Review by daschuer — APPROVED** [review]
Thank you for the fix and the extra improvements. 
I still can't reproduce/explain the original backtrace. But we have confirmation that it is fixed now. So lets just mere.
