### PR TITLE
Fix assuming wrong system language on macOS, fixes #11195

### LINKED ISSUE #11195: Mixxx uses german language on macOS despite system language set to english
### Bug Description

Mixxx 2.4-alpha-1398-g9c4e2f1d1a (main)
macOS 13.1

macOS set to english as primary language with german as secondary language. Region set to germany in case that plays a role, although it shouldn't.
Mixxx set to Language: System

**Currently**

Mixxx UI is german.

**Expected**

Mixxx UI should be english since it would be expected for Mixxx to follow system language.

The simple workaround obviously is to just set Mixxx language to english. Still found this to be unexpected behavior and thus reporting.

### Version

2.4 alpha

### OS

macOS 13.1

### PR DESCRIPTION
**Pull request by daschuer**

### CODE REVIEW

File: src/util/translations.h [hunk 1]
```diff
@@ -43,6 +43,13 @@ class Translations {
             }
             QLocale::setDefault(customLocale);
         }
+#if defined(__APPLE__) && (QT_VERSION < QT_VERSION_CHECK(6, 2, 0))
+        else {
+            // Workaround https://github.com/mixxxdj/mixxx/issues/11195 and
+            // QTBUG-90971 fixed in Qt 6.2
+            QLocale::setDefault(QLocale(QLocale::system().name()));
```
Comment (Swiftb0y) [inline src/util/translations.h:50]: Slight optimization since the QString constructor of QLocale warns that its very slow, I don't fully understand the bug though so this should definitely be tested (as should this entire PR). 
```suggestion
            const auto sysLocale = QLocale::system();
            QLocale::setDefault(QLocale(sysLocale.language(), sysLocale.country()));
```

**Comment by daschuer** [comment]
@foss- Can you confirm that this still fixes your issue?

**Comment by foss-** [comment]
Looking good:

**Review by Swiftb0y — APPROVED** [review]
Thank you, LGTM.

**Comment by Swiftb0y** [comment]
CI fails, didn't we fix this issue already? 
https://github.com/mixxxdj/mixxx/actions/runs/4015053658/jobs/6896323968

**Comment by daschuer** [comment]
Original the issue was not fatal, and has been merged to main only. https://github.com/mixxxdj/mixxx/pull/4824
I think we need to backport it including the follow up fix.

**Comment by Swiftb0y** [comment]
Ah thanks, I'll try create a test branch with the backport (if its not too complicated).

**Comment by Swiftb0y** [comment]
https://github.com/mixxxdj/mixxx/actions/runs/4015973820/jobs/6898375765

**Comment by foss-** [comment]
Also verified in 2.4-alpha-1407-g80fed1d8b6 (main)

**Comment by fuesec** [comment]
still experiencing this issue with Mixxx 2.5.1 (Qt-Version 6.5.3) on macOS 15.4 (24E248)

**Comment by daschuer** [comment]
This issue has been fixed in Mixxx 2.3. Can you please file a new issue and attach the mixxx.log of starting Mixxx, verify the issue and closing it? https://github.com/mixxxdj/mixxx/wiki/Finding-the-mixxx.log-file
