### PR TITLE
GCC 14.1.1 fixes

### LINKED ISSUE #13467: Cannot build latest main (`-Werror-stringop-overflow=`)
### Bug Description

```
In file included from /home/jan/Projects/mixxx/src/util/samplebuffer.h:7,
                 from /home/jan/Projects/mixxx/src/engine/channels/enginedeck.h:8,
                 from /home/jan/Projects/mixxx/src/engine/channels/enginedeck.cpp:1:
In static member function ‘static void SampleUtil::clear(CSAMPLE*, SINT)’,
    inlined from ‘void EngineDeck::processStem(CSAMPLE*, int)’ at /home/jan/Projects/mixxx/src/engine/channels/enginedeck.cpp:62:22:
/home/jan/Projects/mixxx/src/util/sample.h:41:15: error: ‘void* memset(void*, int, size_t)’ specified bound between 18446744065119617024 and 18446744073709551612 exceeds maximum object size 9223372036854775807 [-Werror=stringop-overflow=]
   41 |         memset(pBuffer, 0, sizeof(*pBuffer) * numSamples);
      |         ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### Version

commit 1b9ebc1b6cf203768f218d9a03962b8d249fa0b8

### OS

Arch Linux (gcc 14.1.1 20240522)

### PR DESCRIPTION
**Pull request by Holzhaus**
Fixes #13467.

### CODE REVIEW

File: src/util/sample.h [hunk 1]
```diff
@@ -35,17 +35,14 @@ class SampleUtil {
     // Sets every sample in pBuffer to zero
     inline
     static void clear(CSAMPLE* pBuffer, SINT numSamples) {
-        DEBUG_ASSERT(numSamples >= 0);
-        // Special case: This works, because the binary representation
-        // of 0.0f is 0!
-        memset(pBuffer, 0, sizeof(*pBuffer) * numSamples);
-        //fill(pBuffer, CSAMPLE_ZERO, iNumSamples);
+        fill(pBuffer, CSAMPLE_ZERO, numSamples);
     }
```
Comment (Swiftb0y) [inline src/util/sample.h:39]: fyi, this is [only equally performant on `-O2` and not on `-O1` on gcc](https://quick-bench.com/q/tYpHlnq8rlRf3aNihqCQC3oetwU). I guess thats fine? idk about msvc but afaikt their optimizer is terrible...

The original bug was saying that the `memset` is operating on wayy too much memory right? Maybe thats a hint that there is actually a bug here somewhere (maybe passing some negative `numSamples` and then underflowing)?

**Comment by Holzhaus** [comment]
I guess it makes sense to backport thesr to 2.4?

File: src/util/sample.h (hunk 1 above)
Comment (Holzhaus) [reply src/util/sample.h:39]: I was also wondering if these was a reason for using memset. The original code already had the `fill` call commented out. Not sure if `fill` was the original implementation and turned out to be too slow, so that it was replaced by `memset`? Unfortunately there is no comment to explain it.

Comment (Holzhaus) [reply src/util/sample.h:39]: Fun fact on clang 17 both Implementations are equivalent even with `-O1`.

**Comment by Holzhaus** [comment]
Rebased to 2.4. One commit wasn't applicable to 2.4, moved that to #13505 instead.

File: src/util/sample.h (hunk 1 above)
Comment (JoergAtGithub) [reply src/util/sample.h]: https://travisdowns.github.io/blog/2020/01/20/zero.html

Comment (daschuer) [reply src/util/sample.h]: I can remember that fill was slow with MSVC. With GCC, memset even used AVX registers if it finds some on the target hardware. 

I have just checked with GCC and it turn out that fill also calls memset. 
In addition the fill has two extra checks that skips memset call if numSamples is zero or numSamples * sizeof(*pBuffer) is zero. They are redundant in our case. 

What is the warning you are trying to fix?  

I think we should test the current situation with MSVC before doing this change.

Comment (daschuer) [reply src/util/sample.h]: I have noticed that 
```
void EngineDeck::processStem(CSAMPLE* pOut, const int iBufferSize) {
``` 
uses int and not SINT. Does that fix the warning?

Comment (daschuer) [reply src/util/sample.h]: The diff value the compilers is complaining about is 0x1FFFFFFFC. Strange.

Comment (daschuer) [reply src/util/sample.h]: The whole clear call is redundant at that place. 
Can we just replace it and keep the clear() implementation unchanged?

Comment (JoergAtGithub) [reply src/util/sample.h]: Yes, let's the clear implementation as it is and silence this false positive. This is proven code and fast under all conditions, while fill is only fast under some conditions, when it internally calls memset.

Comment (Holzhaus) [reply src/util/sample.h]: > https://travisdowns.github.io/blog/2020/01/20/zero.html

lol, it's actually faster with GCC and `-O1`: https://quick-bench.com/q/H1hlRRCNe_t-6-iRgTplPpVMKQA

**Review by daschuer — APPROVED** [review]
LGTM, Thank you.

**Review by JoergAtGithub — APPROVED** [review]
