### PR TITLE
fix(LateNight): hide stem control if the track has no stems

### LINKED ISSUE #14242: Make it more obvious that Track has no Stems.
### Bug Description

In LateNight it Looks like that: 
Image

My expectation was that everything stem related disappears. 

If I load a preselected single Stem, it is even worse, because also the labels are displayed. 
  

### Version

_No response_

### OS

_No response_

### PR DESCRIPTION
**Pull request by acolombier**
Fixes #14242

image

Note that I initially tried to close entirely the stem control, but this leads to waveform  having offset between them so I went with a more "naive" solution.

### CODE REVIEW

**Comment by JoergAtGithub** [comment]
What Do you think about a centered label with a text like "Track has no STEMs". Otherwise we will have many users, that only see a big black box if they expand this.

**Comment by ronso0** [comment]
For me this is not working as intended: waveforms of non-stem tracks are squeezed (like 1px tall?)
image

**Comment by acolombier** [comment]
> For me this is not working as intended: waveforms of non-stem tracks are squeezed (like 1px tall?) image

Hmmm actually, it could be a feature... Currently, the non-stem waveform will not restrict the waveform container sizing... which is maybe a desired effect? This mean that a user doesn't need 2x (or 4x) stem component height used for waveform size.

Note that I could set a minimum size for the waveform to prevent this 1px height current behaviour, tho this already seems to impact `2.6 as you can see in the video.

https://github.com/user-attachments/assets/0d192e4c-95ab-4511-b19a-6fb820dbc6a1

**Comment by ronso0** [comment]
It's not a feature when a non-stem waveform is basically hidden and I have to resize the container :grimacing: 
Waveforms should always have the same height for all decks.

Currently waveforms' min height is set implicitly by the  Beat Controls toggle, so 26px for 2 decks, and 13px for 4 decks (yes, that is ridiculously small)

But let's focus on equal height.

**Comment by acolombier** [comment]
Added min size of 25px + No waveform label 

https://github.com/user-attachments/assets/8925c3e1-2a9b-4253-967c-fd2e2ce57989

> Waveforms should always have the same height for all decks.

Why thought? I mean I don't mind, but currently, if you mix with 4 decks and use stems, you are forced to waste a lost of vertical space due to the steam container, tho you rarely (not ton say never) user 4 decks with spec so why not allowing the user to get the space back? If they want equal height, they can adjust the waveform splitter to get it, but otherwise, I think it is a beneficial behaviour to be able to get this space back for the library for example.

What do you think @JoergAtGithub

**Comment by ronso0** [comment]
> Why thought?

To have a rough idea of / can compare levels.
But keeping waveform equally tall AND somehow aligned with their Stem controls is hard / not feasible with the current layout and the splitter in legacy skins. For 2 decks this _might_ work / look okayish (1: stem, 2: one stereo stream), but it'll look confusing with 4 decks (stem | non-stem on the other decks).
(would require to move the stems controls out of the single waveform to the 2/4 waveforms container, so waveform / stem controls can expand independently)

**Comment by acolombier** [comment]
> To have a rough idea of / can compare levels.

I get that but this already something you can do by resizing the splitter accordingly, as you can see on the video just above. Except that with this approach we don't force that decision to the user and instead let them chose. 

In lines with the decision around small screen optimisation in #15492, I am suggesting we keep this as the default behaviour, as otherwise, 4 deck setups suffer a massive screen space loss (440px) when using stems. 

With my latest push, there is now a skin option to constrain waveform to always render with the same height:

https://github.com/user-attachments/assets/6750e5f8-b893-4ece-a7be-cc47a4ebe76a

Otherwise, waveforms will be adjusted to fit the user requested container size, using the splitter. Hopefully this is an acceptable trade-off @ronso0 ?

File: src/skin/legacy/tooltips.cpp [hunk 1]
```diff
@@ -1005,6 +1005,12 @@ void Tooltips::addStandardTooltips() {
     add("show_intro_outro_cues")
             << tr("Show/hide intro & outro markers and associated buttons.");
 
+    add("keep_consistent_waveform_breadth") << tr(
+            "Ensure all waveforms to have the same height across all channels. "
+            "By default, when displaying the stem controls, waveform for "
+            "channel that have no stem may render with a shorter breadth in "
+            "order to honor the waveform container size you have requested..");
```
Comment (acolombier) [inline src/skin/legacy/tooltips.cpp:1012]: I'm sure the current tooltip is confusing :D 

Please suggest a better wording, if you can think of one!

**Comment by JoergAtGithub** [comment]
> What do you think @JoergAtGithub

I think this UI is self explaining with the label.
I'm not sure about the non-equal waveform height. The small screen requirement is a valid point. But somehow it feels odd to me.

Another possible optimization would be to auto-collapse the STEM control section if no track with STEMs is loaded, and auto expand it, if the first track with STEMs is loaded.

**Comment by acolombier** [comment]
> The small screen requirement is a valid point. But somehow it feels odd to me.

Are you happy with the skin option tradeoff?

> Another possible optimization would be to auto-collapse the STEM control section if no track with STEMs is loaded, and auto expand it, if the first track with STEMs is loaded.

It is not possible as it will means that waveform play position won't be aligned anymore across channels

**Comment by JoergAtGithub** [comment]
> > The small screen requirement is a valid point. But somehow it feels odd to me.
> 
> Are you happy with the skin option tradeoff?

Yes the skin option seems to be a good tradeoff to me.

> 
> > Another possible optimization would be to auto-collapse the STEM control section if no track with STEMs is loaded, and auto expand it, if the first track with STEMs is loaded.
> 
> It is not possible as it will means that waveform play position won't be aligned anymore across channels

The waveform play position issue appears only if you hide it for single tracks. But if no visible deck has a STEM track loded we could safely collapse the whole section.

**Comment by acolombier** [comment]
> The waveform play position issue appears only if you hide it for single tracks. But if no visible deck has a STEM track loded we could safely collapse the whole section.

Ah fair. It does feel like some advanced conditional `Connection` would be required, is that something skin engine support?

**Comment by ronso0** [comment]
Thank you, the extra skin setting makes sense.
Here's a fixup for the menu dd38459182
(setting are still a bit comlicated with all these nested WidgetGroups)

**Comment by acolombier** [comment]
Thanks! Added the fixup now - let me know if we are ready for squash and merge.

File: res/skins/LateNight/skin_settings.xml [hunk 2]
```diff
@@ -242,27 +242,49 @@ Description:
...
+                        <Layout>stacked</Layout>
+                        <Size>-1me,18f</Size>
+                        <Children>
+                          <!-- translucent cover when waveforms are hidden -->
+                          <Template src="skins:LateNight/helpers/skin_settings_cover_inverted.xml">
+                            <SetVariable name="Setting">[Skin],show_waveforms</SetVariable>
+                          </Template>
+                          <Template src="skins:LateNight/helpers/skin_settings_button_2state.xml">
+                            <SetVariable name="TooltipId">keep_consistent_waveform_breadth</SetVariable>
+                            <SetVariable name="Text">Maintain consistent breadth</SetVariable>
```
Comment (JoergAtGithub) [inline res/skins/LateNight/skin_settings.xml]:
```suggestion
                            <SetVariable name="Text">Enforce equal heights</SetVariable>
```
"breadth" isn't vertical

**Review by JoergAtGithub — CHANGES_REQUESTED** [review]
I tested this and it worked well, but the wording seems wrong to me.

**Comment by acolombier** [comment]
Thanks @JoergAtGithub ! Took the freedom to squash all the fixup now, so this is all ready.

**Review by JoergAtGithub — APPROVED** [review]

**Comment by ronso0** [comment]
I have a fixup ready, control order + settings tweak.
will push this evening.

**Comment by ronso0** [comment]
I just noticed that initially there's no Quick Effect preset loaded.
For other effect units I see the empty `---` preset.
image

**Comment by ronso0** [comment]
Also the stem Quick Effect chains are named `<QuickStemEffectPresetList>` (which looks like another preset list to choose from) -- (for decks this is `<QuickEffectChains>`)

Shall we rename it to `<StemsQuickEffectChains>` for consistency?
(ideally before the 2.6 release so it affects only beta testers)

**Comment by acolombier** [comment]
This bug is unrelated to this change. Please let's not block this PR with it and address this separately.

**Comment by ronso0** [comment]
Haha, I mixed this up with the or Stem PR and forgot I already gave you the fixup :laughing: 
(late night work)

All good, let's go!

**Review by ronso0 — APPROVED** [review]
